### ISSUE TITLE
CentOS 7.4 Box is Missing

### ISSUE THREAD

**Issue by naftulikay** [chef/bento#1002]
I am trying to use the `bento/centos-7.4` box:

```
==> default: Checking if box 'bento/centos-7.4' is up to date...
==> default: There was a problem while downloading the metadata for your box
==> default: to check for updates. This is not an error, since it is usually due
==> default: to temporary network problems. This is just a warning. The problem
==> default: encountered was:
==> default:
==> default: The requested URL returned error: 404 Not Found
==> default:
==> default: If you want to check for box updates, verify your network connection
==> default: is valid and try again.
```

Apparently the box has been taken down?

**Comment by smaslennikov** [comment]
Works for me:

```bash
slice@pizza ~ 0 $ vagrant init bento/centos-7.4

A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
slice@pizza ~ 0 $ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'bento/centos-7.4'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/centos-7.4' is up to date...
==> default: A newer version of the box 'bento/centos-7.4' is available! You currently
==> default: have version '201709.15.0'. The latest is version '201802.02.0'. Run
==> default: `vagrant box update` to update.
==> default: Setting the name of the VM: slava_default_1519242529772_89552
==> default: Fixed port collision for 22 => 2222. Now on port 2202.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2202 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2202
    default: SSH username: vagrant
    default: SSH auth method: private key
```

**Comment by rickard-von-essen** [comment]
Update your vagrant version?

**Comment by cheeseplus** [comment]
Also what provider are you expecting or is VAGRANT_DEFAULT_PROVIDER set to something specific? The centos-7.4 boxes are definitely available.

**Comment by naftulikay** [comment]
This may be some weird bug in Vagrant. As soon as I did `vagrant box remove bento/centos-7.4`, I was then subsequently able to get the box without warnings.

I'm on Vagrant 2.0.2 on an Ubuntu 16.04 derivative on Linux.

**Comment by cheeseplus** [comment]
Yep, it's a metadata caching problem that happens occasionally if the download is interrupted/corrupted somehow. Glad you got it sorted and closing this out.

**Comment by srinu1231** [comment]
i got this below error message please helpme how to solve this error
D:\>cd D:\Devops_Vagrant

D:\Devops_Vagrant>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'centos/7' version '1901.01' is up to date...
==> default: Clearing any previously set network interfaces...
==> default: Available bridged network interfaces:
==> default: When choosing an interface, it is usually the one that is
==> default: being used to connect to the internet.
    default: Which interface should the network bridge to?

**Comment by cheeseplus** [comment]
@srinu1231 this is an issue that has been closed for over a year so it's best not to add comments that don't have to do with the initial report. 

Issues are for bugs in the software, this particular one has nothing to do with the bento images and is a Vagrant issue you can read more about here https://www.vagrantup.com/docs/networking/public_network.html. If you require further assistance I suggest the Vagrant community channel or http://community-slack.chef.io/.
