### ISSUE TITLE
slugs/links not updated

### ISSUE THREAD

**Issue by mawatech** [chef/bento#1005]
Is there a plan to also update the "links" of boxes like debian-8?

While https://app.vagrantup.com/bento/boxes/debian-8.10 has the version v201802.02.0, https://app.vagrantup.com/bento/boxes/debian-8 is still v201801.02.0

**Comment by cheeseplus** [comment]
It appears they were upload but just not released, this has been resolved.

**Comment by mawatech** [comment]
thx, debian and ubuntu are fine. centos 6 and 7 seems to be still old/missing.

**Comment by cheeseplus** [comment]
Late close but these all got fixed as it was the same deal with the builds having been uploaded but not marked for release.

**Comment by mawatech** [comment]
Happened again with the latest release :)
Would you be so kind to update them again?
