### ISSUE TITLE
FreeBSD: Bug in open-vmware-tools fixed

### ISSUE THREAD

**Issue by Kronuz** [chef/bento#1007]
There was a rather serious bug in VMware tools for FreeBSD (and most likely other posix systems), which has been fixed in the latest FreeBSD ports tree, I’m guessing the package will be updated very soon now (to "open-vm-tools-nox11-10.2.0_4,2.txz"), due the seriousness of the problem. I suggest you upgrade the FreeBSD vagrant images to include the latest open-vmware-tools as soon as possible.

Details of the bug here:
https://github.com/vmware/open-vm-tools/issues/236

And here:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=226478

**Comment by cheeseplus** [comment]
Just pushed out 2018.03.24 which includes the latest round of updates.
