### ISSUE TITLE
ks.cfg file

### ISSUE THREAD

**Issue by githubfoam** [chef/bento#1024]
Is there a list or something else where I can see whole parameters in this file ? I am looking for centos74x particularly.

**Comment by githubfoam** [comment]
Thanks
found this as well . preseed file. https://help.ubuntu.com/lts/installation-guide/i386/apb.html

**Comment by cheeseplus** [comment]
Pressed file and kickstart files are two very different things. Kickstart is generally used in RHEL derivatives and Preseed in Debian ones but that's documentation that is part of the distros - not really something specific to bento. As it seems the question is answered and this isn't an issue or specific to bento, closing.
