### ISSUE TITLE
parallels image missing for bento/ubuntu-18.04

### ISSUE THREAD

**Issue by mcginty** [chef/bento#1028]
I noticed other versions of bentu/ubuntu-* do have a parallels image on the vagrant cloud, but 18.04 is missing one. Any chance one could get added?

**Comment by cheeseplus** [comment]
There reason there isn't an image is because it doesn't build properly. With 18.04 being a pre-release still I expect Parallels will eventually update drivers and such for this to work.

**Comment by mcginty** [comment]
Ahhhh ok, gotcha. Thanks!

**Comment by cheeseplus** [comment]
No problem, we were trying to be ahead of the curve but once parallels tooling gets an update this should be good to go.
