### ISSUE TITLE
ubuntu 14.04 201803.24.0 missing package software-properties-common

### ISSUE THREAD

**Issue by avdd** [chef/bento#1029]
package was available in previous versions.  why has it been removed?

**Comment by cheeseplus** [comment]
I don't know? I don't exactly do an entire package inventory so if something changed it's likely the distro or deps have changed somewhere.

**Comment by avdd** [comment]
I'm not presuming anything.  But I wouldn't expect a stable distro image to lose an important base package in a minor update.  The ubuntu/trusty64 image still has this package, so it seems unlikely this change came from the distro.

**Comment by avdd** [comment]
depends on python3-software-properties which in turn depends on unattended-upgrades which was removed
