### ISSUE TITLE
I am trying to run vagrant on chef and I am getting the following error:

### ISSUE THREAD

**Issue by eddamalique01** [chef/bento#1036]
edwin@edwin-Vostro-3900:~/chef-repo$ vagrant up
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.

**Comment by cheeseplus** [comment]
The answer to your question is in the error - you need to install VirtualBox, VMware Fusion/Workstation, or another hypervisor. VirtualBox is the default and if you don't have that installed then you will need to specify that with `vagrant up --provider=PROVIDER`.

Closing this issue as this is general Vagrant usage problems and unrelated to bento.
