### ISSUE TITLE
Please update openSUSE Leap 42.3 box

### ISSUE THREAD

**Issue by hwoarang** [chef/bento#1038]
Hello,

Would it be possible to build a new openSUSE Leap 42.3 box in order to take advantage of the following commit?

https://github.com/chef/bento/commit/df5cab9f3b265b4c26fe8667aeadde03aabe05eb

This is needed by some OpenStack tests which assume that the 'vagrant' group exists on the VM.

Thank you

**Comment by cheeseplus** [comment]
Closing as dupe of #1039 (because we don't need multiple issues tracking the same release)
