### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by thedrow** [chef/bento#1039]
It's been a while since the latest release.
Can we please tag a new release?

**Comment by bertvv** [comment]
There seems to be a version for Centos 7.5 at https://app.vagrantup.com/bento/boxes/centos-7.5 with two providers (VirtualBox, VMWare).
However, it doesn't seem to be released officially.

**Comment by fletchowns** [comment]
New version was released yesterday: https://github.com/chef/bento/issues/1040#issuecomment-394501215

**Comment by thedrow** [comment]
Yes but no tag yet...

**Comment by cheeseplus** [comment]
There is only so much I can do from the road and while I'm sorry I'm a SPOF here that is rather unfortunately the case. There are new builds being worked on but we've got updates for 2/4 hypervisors that need to be tested as well.

**Comment by cheeseplus** [comment]
Resolved by v201806.08.0 release
