### ISSUE TITLE
CentOS 7.4 failing to install kernel-devel

### ISSUE THREAD

**Issue by gozdal** [chef/bento#1041]
When trying to build VirtualBox Guest Additions for `bento/centos-7.4` I get an error because appropriate version of `kernel-devel` could not be found. The installed version is newer than running kernel. Not sure why.

```
# uname -a
Linux localhost.localdomain 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
No package kernel-devel-3.10.0-693.21.1.el7.x86_64 available.
```

```
# yum info kernel-devel
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.lga7.us.voxel.net
 * epel: mirror.math.princeton.edu
 * extras: mirrors.lga7.us.voxel.net
 * updates: repo1.ash.innoscale.net
Installed Packages
Name        : kernel-devel
Arch        : x86_64
Version     : 3.10.0
Release     : 862.2.3.el7
Size        : 37 M
Repo        : installed
From repo   : updates
Summary     : Development package for building kernel modules to match the kernel
URL         : http://www.kernel.org/
License     : GPLv2
Description : This package provides kernel headers and makefiles sufficient to build modules
            : against the kernel package.
```

```
# yum info kernel
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.lga7.us.voxel.net
 * epel: epel.mirror.constant.com
 * extras: mirrors.lga7.us.voxel.net
 * updates: repo1.ash.innoscale.net
Installed Packages
Name        : kernel
Arch        : x86_64
Version     : 3.10.0
Release     : 693.el7
Size        : 59 M
Repo        : installed
From repo   : anaconda
Summary     : The Linux kernel
URL         : http://www.kernel.org/
License     : GPLv2
Description : The kernel package contains the Linux kernel (vmlinuz), the core of any
            : Linux operating system.  The kernel handles the basic functions
            : of the operating system: memory allocation, process allocation, device
            : input and output, etc.

Name        : kernel
Arch        : x86_64
Version     : 3.10.0
Release     : 693.21.1.el7
Size        : 60 M
Repo        : installed
From repo   : updates
Summary     : The Linux kernel
URL         : http://www.kernel.org/
License     : GPLv2
Description : The kernel package contains the Linux kernel (vmlinuz), the core of any
            : Linux operating system.  The kernel handles the basic functions
            : of the operating system: memory allocation, process allocation, device
            : input and output, etc.

Available Packages
Name        : kernel
Arch        : x86_64
Version     : 3.10.0
Release     : 862.2.3.el7
Size        : 46 M
Repo        : updates/7/x86_64
Summary     : The Linux kernel
URL         : http://www.kernel.org/
License     : GPLv2
Description : The kernel package contains the Linux kernel (vmlinuz), the core of any
            : Linux operating system.  The kernel handles the basic functions
            : of the operating system: memory allocation, process allocation, device
            : input and output, etc.
```

**Comment by cheeseplus** [comment]
How are you trying to build the vbox extensions? they should already come as part of the image? If this is vagrant-vbguest related I'd not be surprised.

**Comment by cheeseplus** [comment]
Unfortunately the boxes are shipped in lock step with the virtualbox versions they support - if you want to change the version you're better off using older versions or creating boxes yourself. 

There isn't a great answer here because we try to minimize the footprint of the base box and so clean it from certain packages such that the user can make a more informed decision as to what to do later.  There isn't anything inherently wrong with vbguest but it's cleverness often will conflict with packaging realities in base boxes.

As for adding kernel-devel, I can look into keeping that but that probably won't solve this problem unilaterally which is why we very much "punt" because the project can only reasonably track current versions matched with the boxes for each provider (we're building 4 providers x nearly every platform so the matrix of what can be supported is already massive)

**Comment by grtjn** [comment]
Destroy the vm you have created so far, and add the following lines to your local Vagrantfile before running `vagrant up` again:

```
        if Vagrant.has_plugin?("vagrant-vbguest")
            config.vbguest.no_install = true
        end
```

It will prevent vagrant-vbguest from automatically, and unnecessarily removing mismatching Guest Additions, and skipping over attempts to install the correct ones. Older Guest Additions often work just fine, no need to have exactly matching additions in most general use..

**Comment by gozdal** [comment]
Thanks. I can work around that. I thought that maybe it'd be useful in general to have CentOS box have `kernel-devel` installed which corresponds to running kernel.

**Comment by grtjn** [comment]
The kernel-devel rpm for centos-7.4 was about 34 mb, though not sure how much it added when installed. It might be worth the effort though. The ability to override guest additions using something like vagrant-vbguest could pay off, as it adds flexibility.

However, that is specific to virtualbox. Not sure if the same applies to the other provides bento supports..

**Comment by cheeseplus** [comment]
I'm closing this one as the original issue is related to using vagrant-vbguest which causes additional issues. We are still open to adding kernel headers but would need to do so across all platforms.
