### ISSUE TITLE
New box first boot result in emergency mode

### ISSUE THREAD

**Issue by rgarrigue** [chef/bento#1043]
Hello

I've a "new" workstation, I installed chocolatey, virtualbox (5.2) vagrant (2.2.1), wrote down a quick vagrantfile with bento/centos7.4, vagrant up end up with this emergency mode

![image](https://user-images.githubusercontent.com/1872031/40121260-71b1709e-5921-11e8-8af7-4e31980a0896.png)

After hiting ctrl-D as suggested `journalctl -xb ` gives gibberish and a crashkernel=auto resulted in a zero bytes of reserved memory, dunno if that's the issue

If I try some memory tweak, like this

    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end

That's ok. This is an issue since I shouldn't need that. And the workaround is expensive, I expect to run centos server over 1024 if not 512mo.

Best regards,

**Comment by cheeseplus** [comment]
Is your system under any load or pressure? 
What operating system and box version `vagrant box list`?

I test all these with 1024MB in kitchen-vagrant on machines dedicated to the building tasks so I know that 2048 isn't required so this sounds to me like something to do with the system under test less than the base box. That said if I can reproduce this then it'd be something we would happily fix but that seems rather unlikely.

**Comment by rgarrigue** [comment]
@cheeseplus no, I've 16Go of RAM, half is unused.

Here's my Vagrantfile

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |cockpit|
  cockpit.vm.box = "bento/centos-7.4"

  # Centreon Server
  cockpit.vm.define "cockpit-centreon" do |centreon|
    centreon.vm.network "private_network", ip: "192.168.34.10"

    centreon.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
  end

  # To be monitored server
  cockpit.vm.define "cockpit-tobemonitored" do |tobemonitored|
    tobemonitored.vm.network "private_network", ip: "192.168.34.11"

    tobemonitored.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
  end
end
```

vagrant box list gives me 

    bento/centos-7.4 (virtualbox, 201803.24.0)

Yesterday I though my issue was worked around with 2Go / VM, but I launched a destroy / up before leaving and this morning it's stuck.

**Comment by cheeseplus** [comment]
Haven't been able to repro this one but feel free to re-open if a reproduction case can be provided. A new round of boxes is out and I've heard no complaints.
