### ISSUE TITLE
Amazon Linux

### ISSUE THREAD

**Issue by stfnhh** [chef/bento#1045]
It would be awesome if you created Vagrant boxes using Amazon Linux 2!

**Comment by rickard-von-essen** [comment]
Unfortunately there is no install ISO released for Amazon Linux 2. So the implement would have to be somewhat different from the current way of working using `virtualbox-ovf` instead of `virtualbox-iso`.

See https://cdn.amazonlinux.com/os-images/latest/

**Comment by cheeseplus** [comment]
At one point we were expecting them to repackage the VDIs as Vagrant Boxes but clearly this hasn't yet happened so I'm certainly open to the possibility of adding it if we can reasonably support it across the existing providers.

**Comment by tas50** [comment]
This will require us to first create a script to create the seed.iso file, spin up a virtualbox system to seed the system with our username/pw, then export the system to .ovf format. From there we can use virtualbox-ovf in a somewhat standard packer image. It's a bit more involved than a normal system image, but not horrible.

**Comment by tas50** [comment]
Working on this here: 
https://github.com/chef/bento/pull/1144

So far we have a script to get us to a OVF. It doesn't have a working nic though and that prevents the next phase. When I have some time I'll see what I can do to push this to complete.

**Comment by stfnhh** [comment]
@tas50 How is #1144 coming, I'm excited to see it!

**Comment by johnjelinek** [comment]
@stfnhh: just merged, we'll see soon.

**Comment by tas50** [comment]
This has been pushed up as bento/amazonlinux-2 on vagrantcloud. I'm currently updating kitchen-vagrant to automatically pull from bento when the user sets the boxname to amazonlinux
