### ISSUE TITLE
New release for Ubuntu 18.04

### ISSUE THREAD

**Issue by gesinn-it** [chef/bento#1058]
Since v201803.24.0 a lot of packages has been updated. Are there any plans to make a new release for VirtualBox in the near future?

I think requests like [1] are related to outdated packages.

[1] https://groups.google.com/forum/#!topic/vagrant-up/U5Ylf2Un8iw

**Comment by konstruktoid** [comment]
Hi @gesinn-it, see https://github.com/chef/bento/issues/1039

**Comment by cheeseplus** [comment]
Closing and locking for the same reason as others, only need one issue to track builds and it's #1039
