### ISSUE TITLE
Ubuntu 18.04 gets duplicate DHCP address on Parallels

### ISSUE THREAD

**Issue by NoahO** [chef/bento#1062]
Hey all, 

I'm having an issue on the latest Ubuntu image (ubuntu-18.04- 201806.08.0) where every Vagrant machine I start gets assigned the same DHCP IP address as the previous.. even vagrant destroying it and recreating it gets the same IP (even though it has a different MAC address). 

EG, 
vagrant up 
==> vm1: Waiting for machine to boot. This may take a few minutes...
    vm1: SSH address: 10.211.55.**3**:22

cd to another project, 
vagrant up 
==> vm2: Waiting for machine to boot. This may take a few minutes...
    vm2: SSH address: 10.211.55.**3**:22

I've been going crazy with this issue, have reinstalled parallels, and I'm about to log a support ticket with them, but this issue definitely doesn't happen with bento/ubuntu-16.04, and doesn't seem to happen with manually installed 18.04... so I'm wondering if anyone else can reproduce this?

**Comment by cheeseplus** [comment]
It's the first I've heard but I also have had issues prior getting 18.04 working for Parallels - we'll need some versions (Vagrant, Parallels, etc) to really dig into reproducing this one but if we can get that or a reproduction repository to try out then we can investigate.

**Comment by NoahO** [comment]
Did some testing today. It *could* be in my environment, but I don't know what's left to reinstall. I have reinstalled Vagrant and cleared ~/.vagrant.d. 

Here's my testing:
```
vagrant --version
Vagrant 2.1.1
```
prlctl --version
prlctl version 13.3.1 (43365)
``
`mkdir 1804Test1 1804Test2
cd 1804Test1
vagrant init bento/ubuntu-18.04
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
vagrant up
Bringing machine 'default' up with 'parallels' provider...
==> default: Registering VM image from the base box 'bento/ubuntu-18.04'...
==> default: Cloning new virtual machine...
==> default: Unregistering the box VM image...
==> default: Setting the default configuration for VM...
==> default: Checking if box 'bento/ubuntu-18.04' is up to date...
==> default: Setting the name of the VM: 1804Test1_default_1529479003824_94151
==> default: Preparing network interfaces based on configuration...
    default: Adapter 0: shared
==> default: Clearing any previously set network interfaces...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 10.211.55.3:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection refused. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for Parallels Tools installed on the VM...
==> default: Mounting shared folders...
    default: /vagrant => /Users/user/Resilio Sync/Sync/Work/1804Test1`

`cd 1804Test2
vagrant init bento/ubuntu-18.04
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
vagrant up
Bringing machine 'default' up with 'parallels' provider...
==> default: Registering VM image from the base box 'bento/ubuntu-18.04'...
==> default: Cloning new virtual machine...
==> default: Unregistering the box VM image...
==> default: Setting the default configuration for VM...
==> default: Checking if box 'bento/ubuntu-18.04' is up to date...
==> default: Setting the name of the VM: 1804Test2_default_1529479030093_80916
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Preparing network interfaces based on configuration...
    default: Adapter 0: shared
==> default: Clearing any previously set network interfaces...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 10.211.55.3:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Authentication failure. Retrying...
    default: Warning: Connection refused. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for Parallels Tools installed on the VM...
==> default: Mounting shared folders...
    default: /vagrant => /Users/user/Resilio Sync/Sync/Work/1804Test2`

As you can see, it assigns the same IP address to two machines.

**Comment by NoahO** [comment]
Still the same problem in Vagrant 2.1.2.

**Comment by rickard-von-essen** [comment]
Could you grep the IP from this file `/Library/Preferences/Parallels/parallels_dhcp_leases` the next time you have a duplicate and post that and which MACs your VM's NICs have.

**Comment by NoahO** [comment]
Sure, 

From 1804Test1
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.211.55.3  netmask 255.255.255.0  broadcast 10.211.55.255
        inet6 fe80::21c:42ff:fe70:696f  prefixlen 64  scopeid 0x20<link>
        ether 00:1c:42:70:69:6f  txqueuelen 1000  (Ethernet)
        RX packets 361  bytes 324707 (324.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 317  bytes 27138 (27.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 146  bytes 11964 (11.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 146  bytes 11964 (11.9 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

From 1804Test2
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.211.55.3  netmask 255.255.255.0  broadcast 10.211.55.255
        inet6 fe80::21c:42ff:fe2b:6c61  prefixlen 64  scopeid 0x20<link>
        ether 00:1c:42:2b:6c:61  txqueuelen 1000  (Ethernet)
        RX packets 1178  bytes 416985 (416.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 958  bytes 110478 (110.4 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 114  bytes 8972 (8.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 114  bytes 8972 (8.9 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

grep 10.211.55.3 /Library/Preferences/Parallels/parallels_dhcp_leases 
```
10.211.55.3="1530267299,1800,001c422b6c61,ff0824450e00020000ab114547359d7d1ed104"
10.211.55.30="1529148045,1800,001c42f44ff6,01001c42f44ff6"
10.211.55.31="1529495143,1800,001c42ab81a3,01001c42ab81a3"
10.211.55.32="1530100174,1800,001c42e7bbcc,01001c42e7bbcc"
10.211.55.33="1529175279,1800,001c4258b949,01001c4258b949"
10.211.55.34="1530252007,1800,001c42f62b09,01001c42f62b09"
10.211.55.35="1529292467,1800,001c42d2badc,01001c42d2badc"
10.211.55.36="1529292307,1800,001c423c7406,01001c423c7406"
10.211.55.37="1529292708,1800,001c421da5de,01001c421da5de"
10.211.55.38="1529292001,1800,001c42135699,01001c42135699"
10.211.55.39="1529292772,1800,001c42d57252,01001c42d57252"
```

grep 001c422b6c61 /Library/Preferences/Parallels/parallels_dhcp_leases
`10.211.55.3="1530267299,1800,001c422b6c61,ff0824450e00020000ab114547359d7d1ed104"
`
grep 001c4270696f /Library/Preferences/Parallels/parallels_dhcp_leases
`(nothing) `

**Comment by rickard-von-essen** [comment]
If you renew the lease for the VM not in the lease file, does it appear there, and does it replace the other VM's line? The dhclient passes a client id, can you find that for each VM? (it should be logged in some file used by dhclient, I don't have access to a computer at the moment so I can't tell you where)

**Comment by mgiammarco** [comment]
I have exactly the same issue in proxmox with kvm virtual machines and dhcp server on mikrotik. So it is an ubuntu problem.

**Comment by mgiammarco** [comment]
https://bugs.launchpad.net/netplan/+bug/1738998

**Comment by rickard-von-essen** [comment]
We should nuke the `/etc/machine-id` file in our provisioners. That will ensure that each VM launched from the box get a new DUID. The problem now is that they have the same and Parallels correctly hand out the same lease to both of them, even though the MAC's are different. This should probably be done for all distros that have this file.

**Comment by NoahO** [comment]
@rickard-von-essen Thank you so much for getting to the bottom of this! I don't know where I would have looked to find that answer.

**Comment by NoahO** [comment]
@rickard-von-essen I tried nuking the file in the cleanup script for ubuntu, but it doesn't get regenerated, so the systems boot up without working network. I think we need to run systemd-machine-id-setup as a provision command when each VM boots, but I'm not sure how to do that yet.

**Comment by NoahO** [comment]
I got it to work by blanking the file, instead of deleting it. Here's my pull request. https://github.com/chef/bento/pull/1073

I haven't back-tested this on earlier ubuntus, but it works on 18.04. I can't see why it wouldn't also work on earlier.

**Comment by rickard-von-essen** [comment]
https://www.freedesktop.org/software/systemd/man/systemd-machine-id-setup.html

**Comment by cheeseplus** [comment]
Closing given #1073
