### ISSUE TITLE
does these boxes come with open-vm-tools or vmware-tools installed?

### ISSUE THREAD

**Issue by rzhang-nevermore** [chef/bento#1063]
I want to launch these boxes on an ESXi server, I used this driver, which is documented here: https://github.com/josenk/vagrant-vmware-esxi#known-issues-with-vmware_esxi

It required open-vm-tools or vmware-tools. I want to know whether the bento boxes come with them installed? If not, how can I add/pack them in?

**Comment by cheeseplus** [comment]
We build with the vmware-tools in almost all cases - certain distros don't support either but for those that do we are using the VMware code itself.
