### ISSUE TITLE
Clipboard sharing service not started on 18.04

### ISSUE THREAD

**Issue by teresaejunior** [chef/bento#1090]
I just rebuilt one VM using *bento/ubuntu-18.04* instead of *bento/ubuntu-16.04-i386*, and while on 16.04 clipboard sharing worked with no problems, on 18.04 I need to run `sudo VBoxClient --clipboard` after every boot.

Could you give me any hint to what changed, or whether this is a bug?

**Comment by cheeseplus** [comment]
Honestly not sure where that would be coming from, nor do we particularly test/optimize for that kind of UI based usage. Given that 18.04 is new I'd expect it's a subtle bug in VirtualBox's client additions but would need much more detail to really dig into why: box version (`vagrant box list`, virtualbox version, and Host OS.

**Comment by teresaejunior** [comment]
I've found this is happening in other images too. Still, thanks for your attention!

**Comment by teresaejunior** [comment]
The solution is running `sudo rcvboxadd setup` manually.
