### ISSUE TITLE
Missing debian-9.5 i386 virtualbox image

### ISSUE THREAD

**Issue by kenhys** [chef/bento#1098]
# Version:

debian-9.5 i386 v201807.12.0 

# Environment:

* vagrant 2.0.2+dfsg-3

# Scenario:

Use vagrant up for debian-9.5-i386 box.

# Steps to Reproduce:

1. create Vagrantfile

```
Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-9.5-i386"
  config.vm.box_version = "201807.12.0"
end
```

2. vagrant up by using virtualbox provider

# Expected Result:

vagrant up succeeds.

# Actual Result:

Failed to launch box. This is because virtualbox provider is not published yet.

**Comment by cheeseplus** [comment]
The builders were failing at the time of build but things seem fine now - I've rebuilt and uploaded the virtualbox image.
