### ISSUE TITLE
Gentoo Linux

### ISSUE THREAD

**Issue by darkn3rd** [chef/bento#1101]
It would be awesome to have support of Gentoo linux that is Docker Ready (meaning one can install and run docker because the kernel configuration prereq).  There's currently no solution on VagrantCloud that I can find.

**Comment by cheeseplus** [comment]
The primary use case that the bento repo serves is to provide sane base boxes for consumption by kitchen-vagrant. We don't have sizable contingent of Gentoo users in the Chef community, at least if we do they aren't terribly vocal, so adding Gentoo as a platform doesn't really gain us much.

That said we're happy to accept community contributions and build them as we have with HardenedBSD. That is to say adding Gentoo isn't going to be a priority for this project given available time and resources but if someone adds a PR then we'd test and if good, merge.

**Comment by darkn3rd** [comment]
Understood.  I am looking into it, not immediately.  I would be nice to have a Docker-Ready version with all the niceties built in.

**Comment by cheeseplus** [comment]
Closing this out for pretty much the same reasons as #1110 - there are also alternative projects that make Arch boxes available like https://roboxes.org/
