### ISSUE TITLE
[ubuntu-18.04] console input required to provision with apt

### ISSUE THREAD

**Issue by fizxmike** [chef/bento#1105]
# Version:

"bento/ubuntu-18.04"`

# Environment:

running vagrant 2.1.1 from Windows 10 (1703)

# Scenario:

run a provisioning script to update/upgrade aptitude

# Steps to Reproduce:

Vagrant file
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provider "virtualbox" do |vbox|
    vbox.memory = 4092
    vbox.cpus = 2
  end

  ## SMH
  config.vm.provision "shell", inline: "apt update && apt upgrade -y", privileged: true

end
```
# Expected Result:

update and upgrade headlessly

# Actual Result:

console is expecting user input that I cannot give during provisioning script execution (asks about keyboard configuration):
![image](https://user-images.githubusercontent.com/4626398/44179036-97721f00-a0ba-11e8-8900-16a9b6e712f1.png)

**Comment by cheeseplus** [comment]
This is APT being itself, you need to set `DEBIAN_FRONTEND=noninteractive` in the environment.

```
config.vm.provision "shell", inline: "apt update && DEBIAN_FRONTEND=noninteractive apt upgrade -y", privileged: true
```
