### ISSUE TITLE
Ubuntu 18.04

### ISSUE THREAD

**Issue by zacksiri** [chef/bento#1106]
Would be lovely to support `Ubuntu 18.04` there is also now [a minimal image](https://blog.ubuntu.com/2018/07/09/minimal-ubuntu-released) which is 30 MB which would be ideal for this.

**Comment by cheeseplus** [comment]
We already support 18.04 https://app.vagrantup.com/bento/boxes/ubuntu-18.04 and the minimal is specifically targeted at clouds. I don't see it offering a tremendous amount of value for our target market which is folks using VirtualBox, Parallels, or VMware Fusion/Workstation via Vagrant.

**Comment by cheeseplus** [comment]
After doing some more reading it definitely isn't technically viable to ship Ubuntu minimal images nor would it make tremendous amount of sense as it removes so much tooling that folks would inevitably be installing a ton on top just to get it working with Vagrant and by extension test-kitchen. I'm closing this for now as we do provided 18.04 images and provide them in the most sensible manner for the target audience.

**Comment by zacksiri** [comment]
Got it! Much thanks I couldn’t find it on the vagrant site.
