### ISSUE TITLE
ArchLinux support

### ISSUE THREAD

**Issue by darkn3rd** [chef/bento#1110]
It would be awesome to have support of ArchLinux. Manjaro (based on ArchLinux) is the most popular (top top 3 most popular) Linux currently: https://distrowatch.com/

And ArchLinux is the base Linux, like Debian is the base Linux for Ubuntu.  It would be nice to get this supported, so we can test cookbooks as a possible OS.

**Comment by cheeseplus** [comment]
Same response as #1101.

**Comment by tas50** [comment]
I'm going to close this out since there are official boxes. There's not a lot of value in reinventing the wheel here only to get it into our namespace.
