### ISSUE TITLE
Oracle Linux 6.10 wrong path in ISO

### ISSUE THREAD

**Issue by xchose** [chef/bento#1111]
# Version:

bento git:(master) packer -v
1.2.5

# Environment: 
Mac OS building oracle linux 6.10 in 64bit

# Scenario:

Trying to build box in oracle linux 6.10

# Steps to Reproduce:

packer build -only=virtualbox-iso oracle-6.10-x86_64.json

# Expected Result:

building box
# Actual Result:

==> virtualbox-iso: ISO download failed. Build 'virtualbox-iso' errored: ISO download failed.

**Comment by xchose** [comment]
is-url seems to be fine anyway somewhere is one "/" more
      "iso_url": "{{user `mirror`}}/{{user `mirror_directory`}}i/{{user `iso_name`}}",

**Comment by xchose** [comment]
Found 2 errors in oracle-6.10-x86_64.json
Wrong name of ISO yourself
`-    "iso_name": "OracleLinux-R6-U10-Server-x86_64-dvd.iso",
+    "iso_name": "OracleLinux-R6-U9-Server-x86_64-dvd.iso",`

And removing one slash 
`-    "mirror": "http://mirrors.kernel.org/oracle/",
+    "mirror": "http://mirrors.kernel.org/oracle",`

**Comment by xchose** [comment]
I would like to push into branch anyway looks that I need some permition into this projekt. 

➜  oraclelinux git:(fix-#1111) git push --set-upstream origin fix-#1111
Username for 'https://github.com': xchose
Password for 'https://xchose@github.com':
remote: Permission to chef/bento.git denied to xchose.
fatal: unable to access 'https://github.com/chef/bento.git/': The requested URL returned error: 403

Please add some rights I can push into branch and ask for merging if OK. Thank you

**Comment by cheeseplus** [comment]
@xchose nobody seems to have the Oracle images publicly at this time. We download them direct from Oracle and override the mirror when building. If you want to use the old images you may but there is no reason for a PR because this is as intended until those images appear on a public mirror.
