### ISSUE TITLE
Latest centos-7.5 box has the old network interfaces eth0, eth1, etc.

### ISSUE THREAD

**Issue by bertvv** [chef/bento#1113]
# Version:

bento/centos-7.5   (virtualbox, 201805.15.0)

# Environment:

- Fedora Workstation 28
- Vagrant 2.1.2
- VirtualBox 5.2.16r123759

# Scenario:

When creating a VM from base box `bento/centos-7.5`, it gets the "old" network interface names (`eth0`, `eth1`, etc.) instead of the new ones (`enp0s3`, `enp0s8`, etc.). The previous versions of this base box, up to 201808.24.0 did not have this behaviour.

# Steps to Reproduce:

```console
$ vagrant box init bento/centos-7.5
$ vagrant up
[...]
$ vagrant ssh
```

# Expected Result:

I would expect to see the new network interface names: `enp0s3`, `enp0s8`, `enp0s9`, etc.

```console
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:54:3d:f0 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global noprefixroute dynamic enp0s3
       valid_lft 86285sec preferred_lft 86285sec
    inet6 fe80::bb30:a03:db03:2918/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

# Actual Result:

```console
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:8b:c9:3f brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global noprefixroute dynamic eth0
       valid_lft 86365sec preferred_lft 86365sec
    inet6 fe80::ab5c:5627:3c9e:daed/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

**Comment by cheeseplus** [comment]
This was intentional as all our other boxes also disable consistent interface naming which, for VMs, is most often not preferred nor useful.

**Comment by bertvv** [comment]
Fair enough. It was preferred in my case, but I'll be searching for another base box then. Thanks for explaining!

**Comment by cheeseplus** [comment]
@bertvv curious, what is the logic behind needing Consistent Interface Naming for VMS? The general consensus is that for physical systems CIN makes sense but for virtual ones, not so much.

**Comment by bertvv** [comment]
@cheeseplus  I teach Linux, I want my students to learn about systemd. ;-)
