### ISSUE TITLE
Box 'debian-8.11-i386' triggers kernel panic at boot

### ISSUE THREAD

**Issue by MagixInTheAir** [chef/bento#1114]
Pretty self-describing. Steps to reproduce :  

    vagrant init bento/debian-8.11-i386
    vagrant up

I can see the kernel panic when bringing up the VirtualBox VM window.
VB version : 5.2.18 r124319
Box version is the latest as of time of writing

**Comment by cheeseplus** [comment]
Could you screencap this supposed kernel panic? I just brought up the box without any issue and tested it via `vagrant ssh` and `kitchen test`.

**Comment by MagixInTheAir** [comment]
Here is the screencap : 
![capture_kernelpanic](https://user-images.githubusercontent.com/8146140/45349805-939ac500-b5b2-11e8-9c44-35a460a8f945.PNG)

I can't capture the whole trace as it is way too fast. Please feel free to ask any required additional data :)

**Comment by cheeseplus** [comment]
We expect hardware virtualization to be enabled and have never tested otherwise so you're a bit out of supported territory. I can at least see if I can repro but I'm not sure there is much we can do with our limited resources to go down this particular rabbit hole.

**Comment by MagixInTheAir** [comment]
I understand. I thought hardware virtualization wouldn't influence the VM, but I might be wrong as my knowledge is limited in the domain. Please keep me updated if there is anything I can do to help

**Comment by cheeseplus** [comment]
I don't think there is much that can be done at the box level unless this one is driver version specific. As we don't test or support `v.customize ["modifyvm", :id, "--hwvirtex", "off"]` I'm closing this one since it's not a box property but this should at least serve to let others know in case they run into it.
