### ISSUE TITLE
Parallels 14.0.1 - Errors with newest integration tools

### ISSUE THREAD

**Issue by NoahO** [chef/bento#1115]
# Version:
Latest bento commit (below), Vagrant 2.1.5
https://github.com/chef/bento/commit/edab45291efaeb94cabffcb9117da17fa9b57e03

# Environment: [Details about the environment such as the Operating System, cookbook details, etc...]
Parallels 14.0.1

# Scenario:
When I build Bento locally (the published boxes work fine), and I use the latest integration tools from parallels, I get the below error on some of my machines on boot. This *doesn't* happen with the current published box (v201808.24.0), that uses an old version of parallels tools. 

This issue does not happen with Parallels 13. 

```
Failed to mount folders in Linux guest. This is usually because
the "prl_fs" file system is not available. Please verify that
Parallels Tools are properly installed in the guest and
can work properly. If so, the VM reboot can solve a problem.
The command attempted was:

mount -t prl_fs -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` media_DockerData /media/DockerData
mount -t prl_fs -o uid=`id -u vagrant`,gid=`id -g vagrant` media_DockerData /media/DockerData
```

Any way I can help troubleshoot this?

**Comment by max-arnold** [comment]
There is a workaround: https://github.com/Parallels/vagrant-parallels/issues/325#issuecomment-418727113

I've made a patch for bento (adapted from vagrant-parallels, see https://github.com/Parallels/vagrant-parallels/blob/master/lib/vagrant-parallels/guest_cap/linux/mount_parallels_shared_folder.rb#L103):

```diff
diff --git a/_common/parallels.sh b/_common/parallels.sh
index 16b3644..7ce801f 100644
--- a/_common/parallels.sh
+++ b/_common/parallels.sh
@@ -20,5 +20,16 @@ parallels-iso|parallels-pvm)
     umount /tmp/parallels;
     rm -rf /tmp/parallels;
     rm -f $HOME_DIR/*.iso;
+
+    # Parallels Tools for Linux includes native auto-mount script,
+    # which causes losing some of Vagrant-relative shared folders.
+    # So, we should disable this behavior.
+    # https://github.com/chef/bento/issues/1115
+    auto_mount_script='/usr/bin/prlfsmountd'
+    if [ -f "${auto_mount_script}" ]; then
+        echo -e '#!/bin/sh\n'\
+        '# Shared folders auto-mount is disabled by Vagrant ' \
+        > "${auto_mount_script}"
+    fi
     ;;
 esac
```

I can send a PR if you are ok to accept it.

**Comment by cheeseplus** [comment]
@max-arnold please do submit the PR - I'm currently out for a family thing but I'll review and merge later this week if it's viable.

**Comment by cheeseplus** [comment]
This is fixed as per above - images will be released early next week ideally.
