### ISSUE TITLE
gurumeditation error with bento/ubuntu-16.04 201808.24.0 on virtualbox 5.1.38

### ISSUE THREAD

**Issue by hhowe29** [chef/bento#1116]
Trying to up this vagrant config 

```
# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end
end
```

With vagrant 2.1.5 and virtual box 5.1.38 produces this error

```
==> default: Importing base box 'bento/ubuntu-16.04'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/ubuntu-16.04' is up to date...
==> default: Setting the name of the VM: vagrant-test2_default_1537820631504_36460
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'gurumeditation' state. Please verify everything is configured
properly and try again.
```

**Comment by n14little** [comment]
I've seen this on a 5.2.x version of virtual box as well.

**Comment by hhowe29** [comment]
`201803.24.0` is the newest version that I can get to provision successfully. `201806.08.0`, `201807.12.0` and `201808.24.0` all produce the guru meditation error.

**Comment by cheeseplus** [comment]
We don't support old versions of virtualbox like 5.1 but I can't say I've seen this at all with 5.2.x.

**Comment by hhowe29** [comment]
@cheeseplus We have stuck with 5.1 to avoid other problems we see with 5.2. Will give 5.2 a try with the most current release and see what happens.

**Comment by cheeseplus** [comment]
Out of curiosity, are you sure you have virtualization extensions enabled on this machine? That's the most typical source of gurumediation errors.

**Comment by hhowe29** [comment]
@cheeseplus Yes. We can boot the image from March just fine, which proves virtualizaton is enabled

**Comment by cheeseplus** [comment]
Is there any more information about the host platform you can provide? Also have you tried with newer VirtualBox?

As it stands this isn't something we've been able to reproduce so hoping that by gathering more information we can narrow this down or close.

**Comment by cheeseplus** [comment]
Closing this out given lack of response and inability on our end to reproduce this failure.
