### ISSUE TITLE
Provide packages for Linux Mint

### ISSUE THREAD

**Issue by petervdb** [chef/bento#1119]
Hi,
Would it be possible to also support Linux Mint?
Thank you very much for taking this into consideration.

Regards,
Peter

**Comment by tas50** [comment]
If someone wants to provide and maintain the definitions that would be fine, but in general we support popular server operating systems + Windows / Mac desktop releases. There's a maintenance burden for the maintainers to add additional platforms and I'm not entirely sure if this is worth the level of effort involved.

**Comment by cheeseplus** [comment]
Closing this out for the same reasons as #1101, #1110 et al - we'll happily merge and even attempt to build but Mint isn't a popular target for test-kitchen (via vagrant) or even Chef so this isn't going to be something we're keen to chase ourselves.
