### ISSUE TITLE
New Platform: fedora-latest

### ISSUE THREAD

**Issue by damacus** [chef/bento#1121]
In line with dokken and making maintenance on a bunch-o-cookbooks easier, would it be possible to get a box labeled fedora-latest?

Thanks! 
Dan

# Expected Result:

kitchen.yml with fedora-latest as a platform

# Actual Result:

```text
The box 'bento/fedora-latest' could not be found or
       could not be accessed in the remote catalog. If this is a private
       box on HashiCorp's Vagrant Cloud, please verify you're logged in via
       `vagrant login`. Also, please double-check the name. The expanded
       URL and error message are shown below:

       URL: ["https://vagrantcloud.com/bento/fedora-latest"]
       Error: The requested URL returned error: 404 Not Found
```

**Comment by cheeseplus** [comment]
_IF_ we did this we would want to do it for all platforms, not just Fedora - any reason we can't stick with the major version slugs like we already do for every other platform?

**Comment by tas50** [comment]
I've added this so we can match dokken boxes, but we probably should just do it for all the boxes
