### ISSUE TITLE
Is the debian installer log data kept on purpose?

### ISSUE THREAD

**Issue by UniIsland** [chef/bento#1129]
I've been using veewee for years. New to chef/bento. It's an awesome project. I'm definitely moving over to packer and porting all my old definition files.

Just downloaded the latest Debian box, and looked around for a while. I found that `cleanup.sh` script means to "delete any logs that have built up during the install", as stated in the comment, however, `/var/log/installer/` was still there with a size of 15M (those files don't have '.log' suffix).

Is it kept on purpose?

If not, I'd like to write a patch to remove it during cleanup, which can be done by simply purging the `installation-report` package.

**Comment by cheeseplus** [comment]
It's not being kept for any reason I am aware of so we'd happily welcome anything to trim things down.
