### ISSUE TITLE
bento/freebsd-11.2-i386 boxes missing on vagrant cloud

### ISSUE THREAD

**Issue by tmm1** [chef/bento#1135]
I've been using the bento/freebsd-11.1-i386 boxes, which have been a great help in trying to build 32-bit freebsd binaries.

Since 11.1 is now EOL, I tried to switch my `Vagrantfile` to freebsd-11.2-i386. However, it looks like no boxes have been released for that version: 
https://app.vagrantup.com/bento/boxes/freebsd-11.2-i386

cc #1120 #1109

**Comment by cheeseplus** [comment]
We haven't built i386 for FreeBSD for a long time because it doesn't build reliably and statistically it's low value.
