### ISSUE TITLE
Drop the IDE controller (dvd should not be needed)

### ISSUE THREAD

**Issue by dominikzogg** [chef/bento#1140]
# Version:
ubuntu/16.04

# Steps to Reproduce:
There is a IDE Controller with DVD active, which seems to be useless to me

**Comment by cheeseplus** [comment]
Could you point to where in the code this is? The reason IDE is used for DVD is that you need media for the install process and certain hypervisors have issues if it's made SATA (ordering preferences).

**Comment by dominikzogg** [comment]
@cheeseplus when i start the box using virtualbox there is a sata disk and a ide dvd, the last one could be dropped before packaging. 

This issue is meant as a small hint, if it does more than a few minutes work or problems i suggest to close it.

**Comment by cheeseplus** [comment]
The more I think about this the less I'm inclined to remove the DVD drive as it's not uncommon for folks to want to mount ISOs to the virtual machines and keeping the option available doesn't add any weight in the form of disk space or complexity. Closing this out as removing the drive doesn't seem to bring any material benefit to the end user.
