### ISSUE TITLE
Push Fedora 29 to Vagrant Cloud

### ISSUE THREAD

**Issue by FranklinYu** [chef/bento#1154]
Fedora 29 is added since 8bbd65368e5117aefae4eb044ff3215d80019758, but I can't find it on [Vagrant Cloud](https://app.vagrantup.com/bento). I thought the boxes are pushed by Continuous Integration? Anyway please push the box.

**Comment by tas50** [comment]
We've merged it, but I'm currently fully committed to other projects so I don't have an ETA on when I'll get to build / push all the systems. Most likely this won't happen until sometime in January.

**Comment by FranklinYu** [comment]
That's fine. Shall I leave this issue open until it is actually pushed?

**Comment by cheeseplus** [comment]
Done https://app.vagrantup.com/bento/boxes/fedora-29
