### ISSUE TITLE
CentOS 7.5 version v201811.25.0 not found

### ISSUE THREAD

**Issue by FlipperPA** [chef/bento#1155]
# Version:

v201811.25.0

# Environment: [Details about the environment such as the Operating System, cookbook details, etc...]

Windows 10, MacOS, and Linux

# Scenario:

I'm attempting to upgrade from v201808.24.0 to v201811.25.0; Vagrant reports v201811.25.0 is not a valid version.

# Steps to Reproduce:

In this Vagrantfile: https://github.com/wharton/python-vagrant-centos7/blob/master/Vagrantfile Try updating `box_version` to `201811.25.0`.

# Expected Result:

For it to find the new version.

# Actual Result:

It reports that the latest version is v201808.24.0.

Thank you for all of your efforts - they are much appreciated! :)

**Comment by cheeseplus** [comment]
The 201811.25.0 release was only half done, some builds were generated but nothing was released as I was in the process of changing employers. I'm hesitant to publish a build set that is incomplete so will try to push a new set over the next few days. 

Out of curiosity there a specific impetus for upgrading to that version specifically?

**Comment by FlipperPA** [comment]
None in particular; I just try to keep up to date with a Vagrant box I made that has gotten popular for Django development. It minimizes yum update times. I very much appreciate your work, thank you!

**Comment by cheeseplus** [comment]
Closing this out as we've released https://app.vagrantup.com/bento/boxes/centos-7.6/versions/201812.27.0
