### ISSUE TITLE
ubuntu-18.04-amd64 hangs on language select in Parallels 14

### ISSUE THREAD

**Issue by svpernova09** [chef/bento#1157]
# Version:

chef/bento f253152150ee578e237ef2f69283b8c7e73e3cc8

# Environment: [Details about the environment such as the Operating System, cookbook details, etc...]

* MacOS 10.14.2 (18C54)
* Parallels Desktop 14
* Virtualbox 6.0
* Packer v1.3.4-dev
* `ubuntu/ubuntu-18.04-amd64.json`

# Scenario:

Running `packer build --only=parallels-iso ubuntu-18.04-amd64.json`

# Steps to Reproduce:

```
git clone git@github.com:chef/bento.git
cd bento/ubuntu
packer build --only=parallels-iso ubuntu-18.04-amd64.json
```

# Expected Result:

Expected Parallels to install and configure Ubuntu.

# Actual Result:

Parallels hangs at Select a language install curses window.

```
parallels-iso output will be in this color.

==> parallels-iso: Retrieving ISO
    parallels-iso: Found already downloaded, initial checksum matched, no download needed: http://cdimage.ubuntu.com/ubuntu/releases/18.04.1/release/ubuntu-18.04.1-server-amd64.iso
==> parallels-iso: Starting HTTP server on port 8542
==> parallels-iso: Creating virtual machine...
==> parallels-iso: Applying default settings...
==> parallels-iso: Creating hard drive...
==> parallels-iso: Setting the boot order...
==> parallels-iso: Attaching ISO to the default CD/DVD ROM device...
==> parallels-iso: Executing custom prlctl commands...
    parallels-iso: Executing: prlctl set ubuntu-18.04-amd64 --memsize 1024
    parallels-iso: Executing: prlctl set ubuntu-18.04-amd64 --cpus 1
==> parallels-iso: Starting the virtual machine...
==> parallels-iso: Waiting 10s for boot...
==> parallels-iso: Host IP for the Parallels machine: 192.168.1.235
==> parallels-iso: Typing the boot command...
==> parallels-iso: Waiting for SSH to become available...
```

Parallels left, Virtualbox right. Initially discovered when building Parallels & Virtualbox however I have confirmed the behavior in isolation as well.
<img width="1169" alt="screen shot 2018-12-21 at 22 15 27" src="https://user-images.githubusercontent.com/967362/50370530-0e8a5900-056e-11e9-8a3b-f73b18ee5b3e.png">

**Comment by cheeseplus** [comment]
Could you provide the specific version of Parallels? Anecdotally, we've had quite a few problems with the first few releases of Parallels 14 but 14.1.0 (45387) seems to build past that point without issue.

**Comment by svpernova09** [comment]
Parallels 14.1.0 (45387) is what I'm using and still happening just now:

<img width="1349" alt="screen shot 2018-12-28 at 13 15 19" src="https://user-images.githubusercontent.com/967362/50525733-f9985300-0aa2-11e9-9e57-e612e7474ce5.png">

**Comment by cheeseplus** [comment]
Do you have the [Parallels Virtualization SDK](http://www.parallels.com/download/pvsdk/) installed and if so what version?

**Comment by svpernova09** [comment]
I have no installed that by itself. Currently `prlctl version 14.1.0 (45387)`, Going to download the SDK and install

**Comment by svpernova09** [comment]
Version is the same after SDK install.

I thought the issue might have been with the Accessibility issues in Mojave (Having to add apps manually to the accessibility settings. I've done that, and restart apps and the computer and still hitting the same issues. I have Parallels Desktop in there:

<img width="656" alt="screen shot 2018-12-28 at 14 46 16" src="https://user-images.githubusercontent.com/967362/50527663-61ed3180-0aaf-11e9-898b-6794bdd84ba0.png">


Is there a way to debug when / which boot command is being typed? I don't see any keyboard input on the VM gui.

**Comment by svpernova09** [comment]
This seems to be resolved now, I'm past the issue I was stuck at before. The solution was to also add "Parallels Toolbox" to the Accessibility section of "Security & Privacy" in "System Preferences".

Sorry for sending you on a wild goose chase. Thanks for all your help & work on this project!

**Comment by cheeseplus** [comment]
No worries, glad it's working 🎊
