### ISSUE TITLE
Debian 9.6 point release is not published yet

### ISSUE THREAD

**Issue by kenhys** [chef/bento#1158]
# Version:

201808.24.0

# Environment:

debian/unstable, but this is not environment specific issue.

# Scenario:

I've found that Debian 9.6 point release support is [already merged](https://github.com/chef/bento/pull/1138) , but not published yet. 
Are there any release blocker?

# Steps to Reproduce:

1. open https://app.vagrantup.com/bento
2. search bento/debian-9.6, bento/debian-9.6-i386

# Expected Result:

bento/debian-9.6, bento/debian-9.6-i386 is available.

# Actual Result:

bento/debian-9.6, bento/debian-9.6-i386 is not available.

**Comment by tas50** [comment]
Releasing these boxes sits behind a lot of other work assigned to this team. I'm currently aiming to get a release sometime in Jan, but it may not happen until Feb.

**Comment by kenhys** [comment]
@tas50
thank you for sharing the current status.
