### ISSUE TITLE
18.04 - initrd removed during cleanup

### ISSUE THREAD

**Issue by GMAzrael** [chef/bento#1163]
# Version:

1.3.3

# Environment: [Details about the environment such as the Operating System, cookbook details, etc...]

# Scenario:

Building 18.04 and running through cleanup.sh script causes the initrd for the newly installed kernel to be deleted, before it is held as being the "current" kernel. 

# Steps to Reproduce:
 
packer build ubuntu-18.04-amd64.json
import with vagrant, boot, look at console
# Expected Result:

successful boot

# Actual Result:

sits at kernel panic from lack of initrd.

# Known Workaround:
insert reboot command at end of the update.sh script to switch to the new kernel before the cleanup script is ran.

**Comment by svpernova09** [comment]
This issue can be closed: https://github.com/chef/bento/blob/master/packer_templates/ubuntu/scripts/update.sh#L40

**Comment by tas50** [comment]
Closing this out per the comment above
