### ISSUE TITLE
Disable windows defender realtime protection

### ISSUE THREAD

**Issue by tas50** [chef/bento#1171]
This makes these boxes crazy slow. Let's turn it off.

**Comment by svpernova09** [comment]
Should this be done in `packer_templates/windows/scripts/base_setup.ps1`? This is an easy one liner via `Set-MpPreference -DisableRealtimeMonitoring $true` in a Powershell prompt. The `base_setup.ps1` seems logical. Unless there is a Recipe plugin for sending powershell commands?

**Comment by tas50** [comment]
We can do it via a powershell resource in Chef
