### ISSUE TITLE
bento/ubuntu-18.04 stuck at 'Powered On' using vmware_esxi provider

### ISSUE THREAD

**Issue by ynixon** [chef/bento#1174]
# Version:

bento/ubuntu-18.04

# Environment: 
Using Vagrant from Windows 10 using vmware_esxi provider 

# Scenario:

The box is stuck at 'Powered On'

# Actual Result:

```
.
.
.
Opening VI target: vi://root@10.11.1.100:443/
Deploying to VI: vi://root@10.11.1.100:443/
Transfer Completed
Completed successfully
==> remote: --- VMID            : 7
==> remote: --- Extend Boot dsk : 100GB
==> remote: --- VM has been Powered On...
==> remote: --- Waiting for state "running"
There was an error.
  Failed, timeout waiting for "running".
```

**Comment by cheeseplus** [comment]
We support the local hypervisors `vmware_fusion` or `vmware_workstation` specifically, if you have patches or fixes then we'd be happy to review them but this is out of scope for these images as we have no testing or build infra for that stack.
