### ISSUE TITLE
Incorrect disk calculation in minimize.sh

### ISSUE THREAD

**Issue by howardjones** [chef/bento#1175]
(My actual issue is that minimize.sh never completes, but I'm also modifying the vmware-iso parameters to use a remote esxi system, so there are other things in play there, but I noticed this while faultfinding...)

https://github.com/chef/bento/blob/6ab6872994b0debfd3ced0b63e4781c547b5fbbd/_common/minimize.sh#L10

This section of minimize.sh goes to some trouble to figure out how much free space there is on the root partition, in KByte blocks, and then writes 1000x that in zeroes!

Also, awk can do math.

    count=$(df --sync -kP / | tail -n1  | awk -F ' ' '{printf("%d",($4-1)/1024)}')

would get the correct number of *1MB* blocks to write.

**Comment by cheeseplus** [comment]
Do you want to just make this a PR?

**Comment by howardjones** [comment]
For annoying employment reasons, I can't, sorry!

**Comment by cheeseplus** [comment]
Ahh, totally get that and will proceed accordingly!

**Comment by arizvisa** [comment]
With regards to this, I've also had problems with minimize.sh occasionally crashing.

**Comment by kalumkalac** [comment]
https://github.com/chef/bento/pull/1277 will fix.

**Comment by tas50** [comment]
Closing this out since it was fixed.
