### ISSUE TITLE
Consider using btrfs with zstd compression

### ISSUE THREAD

**Issue by svenstaro** [chef/bento#1189]
### Describe the Enhancement:
Using btrfs' built-in zstd compression, you might be able to produce much smaller images.

### Describe the Need:
Smaller images are always better. :)

### Current Alternative
Currently, most (all?) images use ext4.

### Can We Help You Implement This?:
Should be pretty simple. Make a btrfs partition instead of ext4 for the root partition during installation.

**Comment by rickard-von-essen** [comment]
IMHO this might slim down the image a bit, _but_ the boxes will not reflect a minimal default installation anymore which is not likely what most users expect/want.

**Comment by cheeseplus** [comment]
To add some reasons:
- Not all the distros support btrfs
- Btrfs requires more resources which conflicts with a notion of minimal
- Btrfs, even among the supported distros, is still not the default

Minimal size is not the only goal, we have many other considerations in providing the most "sensible" _default_ base boxes in line with what users _expect_

**Comment by cheeseplus** [comment]
I'm going to close this out because it's not really reasonable for anyone to spend time shaving this yak for minimal benefit (if anything it would cause more confusion). Feel free to ask more questions though and I'm happy to clarify more why this isn't in the best interest of the bulk of users.
