### ISSUE TITLE
Debian 8 build is stuck, asking for user input

### ISSUE THREAD

**Issue by mgruner** [chef/bento#1190]
# Version:

https://github.com/chef/bento/commit/466553de22dce348ced4f98526dfdaf85731fe09

# Environment:

Mac OS 10.14.4 (18E226)

# Scenario:

Build the Debian 8 box. 

# Steps to Reproduce:

Trigger the Debian 8 build.

# Expected Result:

Build succeeds.

# Actual Result:

Hangs with the error message "cannot access repository" which causes a user prompt that blocks the automated processing, see screenshot.

![Bildschirmfoto 2019-04-18 um 13 26 25](https://user-images.githubusercontent.com/211281/56358087-e1794a80-61dd-11e9-8cbe-8e4b5439d941.png)

**Comment by rmoriz** [comment]
Virtualbox? Have you checked host connectivity to httpredir.debian.org? maybe a broken mirror?

**Comment by mgruner** [comment]
@rmoriz yes, VirtualBox. Happens also when I use another mirror. Debian 9 builds fine.

**Comment by cheeseplus** [comment]
Virtualbox version? This is usually vb or it's network stack being less than awesome but there can be other reasons, just requires more digging/logging.

**Comment by cmur2** [comment]
I encountered this as well, his is due to `Removal of Wheezy and Jessie (except LTS) from mirrors`: https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

**Comment by rmoriz** [comment]
> "That is, only Jessie i386, amd64, armel and armhf will continue to be hosted on the normal mirrors."

**Comment by cmur2** [comment]
@rmoriz @mgruner yes but with that step the Release files for Jessie were also expired which can be worked around on an installed system if you configure `apt` [to ignore expiry](https://unix.stackexchange.com/a/45973/105141).

**Comment by mgruner** [comment]
@rmoriz yes, amd64.

@cmur2 is there something we can change here in the files so that an automated rebuild of the debian-8 box is possible again?

**Comment by cmur2** [comment]
I'm no expert on Debian's preseed functionality, we would need to sneak in the `apt` configuration somehow into the installer and later the image.

**Comment by mgruner** [comment]
Seems to be tricky: https://stackoverflow.com/questions/25039317/is-there-any-setting-in-the-preseed-file-to-ignore-the-release-valid-until-opt

**Comment by mgruner** [comment]
The solution was finally easier than I thought. Only the "updates" repository had to be removed (keeping "security").

https://github.com/chef/bento/pull/1197

@cheeseplus I'd appreciate very much a review and merge of this PR.

Please note that there is currently another issue with Debian 9.8.0 not being available any more (there is now 9.9.0), but I decided not to fix that in this PR to keep the concerns separate.

**Comment by mgruner** [comment]
PR was merged, thanks.

**Comment by cmur2** [comment]
Thanks for your persistence in tracking this down and fixing it!
