### ISSUE TITLE
Ubuntu 19.04 support

### ISSUE THREAD

**Issue by xkrt** [chef/bento#1191]
Ubuntu 19.04 released, please support it.

**Comment by xkrt** [comment]
Hi! When `bento/ubuntu-19.04` box will be published to https://app.vagrantup.com/bento?

**Comment by cheeseplus** [comment]
There is no schedule at this time as there aren't really super active maintainers. I imagine after the chef 15 release cycle folks might have time but I honestly can't speak for them.

**Comment by tas50** [comment]
I've pushed the 19.04 image up to Vagrant.
