### ISSUE TITLE
HyperV builders has wrong params

### ISSUE THREAD

**Issue by BoGnY** [chef/bento#1194]
# Version:

Cloned on 2019/04/24 with commit 9c5a0c4

# Environment:

Windows 10 Pro build 1809
Packer v1.4.0

# Scenario:

Building ubuntu-18.04.2-amd64 image

# Steps to Reproduce:

```bash
packer validate ./ubuntu/ubuntu-18.04.2-amd64.json
```

# Expected Result:

```
Validating packer image...
Template validation succeeded, but there were some warnings.
These are ONLY WARNINGS, and Packer will attempt to build the
template despite them, but they should be paid attention to.

Warnings for build 'hyperv-iso':

* Hyper-V might fail to create a VM if there is not enough free memory in the system.
```

# Actual Result:

```
Validating packer image...
[warning] Fixable configuration found.
You may need to run `packer fix` to get your build to run
correctly. See debug log for more information.

Template validation failed. Errors are shown below.

Errors validating build 'hyperv-iso'. 2 errors occurred:
        * unknown configuration key: "cpu"
        * unknown configuration key: "ram_size"
```

I've solved the problem by changing [ubuntu-18.04-amd64.json#L240](https://github.com/chef/bento/blob/master/ubuntu/ubuntu-18.04-amd64.json#L240) from:
```json
"cpu": "{{ user `cpus` }}",
```
To:
```json
"cpus": "{{user `cpus`}}",
```

And changing [ubuntu-18.04-amd64.json#L249](https://github.com/chef/bento/blob/master/ubuntu/ubuntu-18.04-amd64.json#L249) from:
```json
"ram_size": "{{user `memory`}}",
```
To:
```json
"memory": "{{user `memory`}}",
```

I've rapidly see that all ubuntu-x64 json are misconfigured, so it's not limitated to v18.04..

For repo owner, can I make PR to fix it??

**Comment by cheeseplus** [comment]
I was the one who added and built these (they aren't regularly built) so these options definitely worked in the past. I think Packer changed this internally at some point so a PR is welcome if that's no longer valid.

**Comment by BoGnY** [comment]
Ok, but anyone can merge #1192 before???
So I can fix HyperV params in all builds, even 19.04, with a single commit/PR??

**Comment by cheeseplus** [comment]
#1192 has been merged.

**Comment by markschuh** [comment]
The HyperV params were indeed changed due to conformity with https://github.com/hashicorp/packer/pull/7447. 

The change within packer includes a fixer, so running on a linux with packer version >=1.4.0 in path a command like
```
for template in $(grep --recursive --include=\*.json --files-with-matches '"type"\s*:\s*"hyperv-iso"' .); do
  packer fix $template >$template.fixed && mv $template.fixed $template
done
```
should do the necessary template changes.
