### ISSUE TITLE
bento/centos-7 (virtualbox, 201812.27.0) (current) missing locales from glibc-common

### ISSUE THREAD

**Issue by petervandivier** [chef/bento#1195]
# Version:

* `bento/centos-7 (virtualbox, 201812.27.0)`
* https://app.vagrantup.com/bento/boxes/centos-7

# Environment:

Behavior reproduced on Macbook Pro Mojave 10.14.4 & Windows 10 Home Acer laptop with minor variances observed

# Scenario:

I am unable to access the `en_GB` locale for service configuration. Only 3 locales (en_US, C, POSIX) are available on boot. 

This appears to be a regression. `bento/centos-7 (virtualbox, 201808.24.0)` returns 789 locales.

# Steps to Reproduce:

* https://learn.chef.io/modules/learn-the-basics/rhel/virtualbox/set-up-a-machine-to-manage#/

```
$ vagrant init bento/centos-7
$ vagrant up
$ vagrant ssh

[vagrant@localhost ~]$ locale -a 
```

# Expected Result:

Expect to see common world locales, including `en_GB[.UTF-8]`. 

# Actual Result:

Only 3 locales are available.

```
C
POSIX
en_US.utf8
```

`sudo yum update glibc-common -y` resolves the issue as a workaround.

**Comment by tas50** [comment]
@petervandivier can you try updating to the latest centos image to see if you still have this problem. I've rebuilt a brand new centos image with the latest and greatest tools.

**Comment by petervandivier** [comment]
Apologies, I'm not seeing an update. Currently [vagrantup](https://app.vagrantup.com/boxes/search?order=desc&page=1&provider=virtualbox&q=bento%2Fcentos&sort=updated&utf8=%E2%9C%93) is only showing a recent update for 7.6 (init repro was based on centos-7 base image).

```sh
$ vagrant box update
==> default: Checking for updates to 'bento/centos-7'
    default: Latest installed version: 201812.27.0
    default: Version constraints: 
    default: Provider: virtualbox
==> default: Box 'bento/centos-7' (v201812.27.0) is running the latest version
```

The prior release of 7.6 does appear to have been based on the same build as though so fwiw I've `up`'d the 7.6 image and the locales appear to exist as expected

```sh
[vagrant@localhost ~]$ locale -a | wc -l
791
```

**Comment by cheeseplus** [comment]
The `centos-7` slug typically tracks the latest centos-7.x but it looks like the latest 7.6 wasn't copied/uploaded, if you change to `centos-7.6` temporarily then you can try it out.

**Comment by tas50** [comment]
Conference WiFi was making it all hard. I’ll have the teaming boxes up in the next few days

**Comment by tas50** [comment]
All new boxes have been pushed so centos-7 is now centos-7.6. I also added logic in the upload so that you can check the version description of the "slug" boxes to see what the actual version was.
