### ISSUE TITLE
Unbuntu 18.04 box fails to boot due to Kernel panic

### ISSUE THREAD

**Issue by mgruner** [chef/bento#1202]
# Version:

Current master, 032bb6c653b968a8fc05e40ec4669a310128f799

# Environment:

macOS 10.14.5 (18F132)

# Scenario:

Build the Ubuntu 18.04 box and boot it normally.

# Steps to Reproduce:

1. Build the Ubuntu 18.04 box.
2. Try to boot it.

# Expected Result:

Box boots properly.

# Actual Result:

```
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.
```

This seems to be caused by a Kernel panic:

![Bildschirmfoto 2019-06-17 um 10 22 44](https://user-images.githubusercontent.com/211281/59589287-e11c0380-90e9-11e9-9dff-8ec1ccf73c81.png)

My guess is that this is caused by a step in scripts/cleanup.sh

```
    virtualbox-iso: + xargs apt-get -y purge
    virtualbox-iso: + grep linux-image-.*-generic
    virtualbox-iso: + awk { print $2 }
    virtualbox-iso: + uname -r
    virtualbox-iso: + dpkg+ grep -v 4.15.0-45-generic
    virtualbox-iso:  --list
    virtualbox-iso: Reading package lists...
    virtualbox-iso: Building dependency tree...
    virtualbox-iso: Reading state information...
    virtualbox-iso: The following packages were automatically installed and are no longer required:
    virtualbox-iso:   amd64-microcode intel-microcode iucode-tool
    virtualbox-iso: Use 'sudo apt autoremove' to remove them.
    virtualbox-iso: The following additional packages will be installed:
    virtualbox-iso:   linux-image-unsigned-4.15.0-51-generic
    virtualbox-iso: Suggested packages:
    virtualbox-iso:   fdutils linux-tools linux-headers-4.15.0-51-generic
    virtualbox-iso: The following packages will be REMOVED:
    virtualbox-iso:   linux-image-4.15.0-51-generic* linux-image-generic*
    virtualbox-iso:   linux-modules-extra-4.15.0-51-generic*
    virtualbox-iso: The following NEW packages will be installed:
    virtualbox-iso:   linux-image-unsigned-4.15.0-51-generic
```

I'm not sure though. Any help would be most appreciated.

**Comment by dominikzogg** [comment]
Same here, tried on multiple machines

**Comment by cheeseplus** [comment]
Need Vagrant and Virtualbox versions, guessing it could be similar to https://github.com/chef/bento/issues/1198

**Comment by mgruner** [comment]
Vagrant 2.2.4
VirtualBox 6.0.8 (on macOS), also fails on 5.2.28 (on Linux)

**Comment by cheeseplus** [comment]
That round of boxes was built with Virtulbox 5.2.22 (Vagrant 2.2.0) so I'm guessing that's the culprit in this case.

**Comment by mgruner** [comment]
Today I was able to rebuild the Ubuntu 18.04 boxes and use them successfully. Perhaps the reboot change here fixed it: https://github.com/chef/bento/commit/bb55faecbda8bc61d49898de325a9848fcf5dd43#diff-bb80e9f08f53baa75ba7f87309b07a13R40
