### ISSUE TITLE
Add support for Debian 10

### ISSUE THREAD

**Issue by eheydrick** [chef/bento#1203]
### Describe the Enhancement:
Debian 10 will be out soon. Would be great to have support.

### Describe the Need:
Anyone wanting to upgrade to Debian 10 will want to test their cookbooks.

### Current Alternative
Maybe through docker but haven't tried yet.

**Comment by ifduyue** [comment]
Debian 10 released https://www.debian.org/News/2019/20190706

**Comment by tas50** [comment]
This is now up on vagrant cloud
