### ISSUE TITLE
VirtualBox shared folders broken after OS upgrade because clean up sc

### ISSUE THREAD

**Issue by DanHam** [chef/bento#1205]
# Version:

`bento/ubuntu-16.04             (virtualbox, 201906.18.0)`

Other boxes are affected as well.

# Environment:

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.5
BuildVersion:   18F132

$ VBoxManage --version
6.0.6r130049

$ vagrant --version
Vagrant 2.2.5
```

# Scenario:

I want to perform an update/upgrade of the boxes packages. However, after I upgrade and reboot, shared folder support is broken. Most likely all the other functionality enabled by installing VirtualBox Guest Additions is broken as well.

# Steps to Reproduce:

Initial set-up:
```
$ vagrant init bento/ubuntu-16.04
$ vagrant up
$ vagrant ssh
```

Once connected to the Ubuntu VM perform an upgrade of all packages (including the kernel):
```
$ sudo apt-get update
$ sudo apt-get -y dist-upgrade
$ exit
```

When the box is restarted shared folders are no longer working:
```
$ vagrant reload
...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 5.0.18_Ubuntu r106667
    default: VirtualBox Version: 6.0
==> default: Mounting shared folders...
    default: /vagrant => /Users/dan/working/vagrant/ubuntu-16-04-test
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

: No such device
```

# Expected Result:

I expect to be able to perform an upgrade/dist-upgrade without breaking support for shared folders. Didn't this used to be the case?

# Actual Result:

Support for features enabled by the Guest Additions install, such as shared folders, is broken.

# Cause:

The recent merge of #1182 added clean up scripts that remove one or more of the packages required to automatically rebuild the Guest Additions modules when the kernel is upgraded. For example, the clean up script for Ubuntu [removes the kernel headers](https://github.com/chef/bento/blob/master/packer_templates/ubuntu/scripts/cleanup.sh#L3-L7) packages. Similarly, the clean up script for [CentOS removes](https://github.com/chef/bento/blob/master/packer_templates/centos/scripts/cleanup.sh#L6-L7) the `gcc`, `cpp`, `kernel-devel` and `kernel-headers` packages.

If these packages are instead left in place then any upgrade should also upgrade the headers, devel, or source packages to match the newly upgraded kernel version. This should allow the upgraded system to automatically rebuild the required Guest Additions modules where supported e.g. via the DKMS system on Debian and Ubuntu machines. 

This issue is not specific to Ubuntu - a quick look at the other bento boxes shows that these packages are being removed by the clean up scripts for those OSes as well.

# Fix

I understand the rationale behind removing all of the packages required to build the Guest Additions as their removal decreases the resulting image size by quite a few MB. However, I believe most users would gladly accept slightly larger boxes that continue to support Guest Additions post upgrade of the boxes kernel. I also believe this used to be the case with previous versions of the box.

To fix this the clean up scripts must not remove **any** of the packages required to build the Guest Additions.

For example, for Ubuntu the clean up script could be chaged from:
```
# Delete all Linux headers
dpkg --list \
  | awk '{ print $2 }' \
  | grep 'linux-headers' \
| xargs apt-get -y purge;
```
to:
```
dpkg --list \
  | awk '{ print $2 }' \
  | grep 'linux-headers-.*-generic' \
  | grep -v `uname -r` \
  | xargs apt-get -y purge;
```

**Comment by cheeseplus** [comment]
This looks identical to #1206, closing.

**Comment by DanHam** [comment]
@cheeseplus Sorry! I don't quite know what happened there!
