### ISSUE TITLE
Guest additions broken after update of box due to removal of packages by clean up script

### ISSUE THREAD

**Issue by DanHam** [chef/bento#1206]
# Version:

`bento/ubuntu-16.04             (virtualbox, 201906.18.0)`

Other boxes are very likely affected as well.

# Environment:

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.5
BuildVersion:   18F132

$ VBoxManage --version
6.0.6r130049

$ vagrant --version
Vagrant 2.2.5
```

# Scenario:

I want to perform an update/upgrade of the boxes OS. However, after I upgrade and reboot, shared folder support is broken. Most likely all the other functionality enabled by installing VirtualBox Guest Additions is broken as well.

# Steps to Reproduce:

Initial set-up:
```
$ vagrant init bento/ubuntu-16.04
$ vagrant up
$ vagrant ssh
```

Once connected to the Ubuntu VM perform an upgrade of all packages. Crucially, the upgrade includes an update of the kernel:
```
$ sudo apt-get update
$ sudo apt-get -y dist-upgrade
$ exit
```

When the box is restarted shared folders are no longer working:
```
$ vagrant reload
...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 5.0.18_Ubuntu r106667
    default: VirtualBox Version: 6.0
==> default: Mounting shared folders...
    default: /vagrant => /Users/dan/working/vagrant/ubuntu-16-04-test
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

: No such device
```

# Expected Result:

I expect to be able to perform an upgrade/dist-upgrade (including a kernel upgrade) without breaking support for shared folders. 

Didn't this used to be the case?

# Actual Result:

Support for features enabled by the Guest Additions install, such as shared folders, is broken.

# Cause:

The recent merge of #1182 added clean up scripts that remove one or more of the packages required to automatically rebuild the Guest Additions modules when the kernel is upgraded. For example, the clean up script for Ubuntu [removes the kernel headers](https://github.com/chef/bento/blob/master/packer_templates/ubuntu/scripts/cleanup.sh#L3-L7) packages. Similarly, the clean up script for [CentOS removes](https://github.com/chef/bento/blob/master/packer_templates/centos/scripts/cleanup.sh#L6-L7) the `gcc`, `cpp`, `kernel-devel` and `kernel-headers` packages.

If these packages are instead left in place then any upgrade should also upgrade the headers, devel, or source packages to match the newly upgraded kernel version. This should allow the upgraded system to automatically rebuild the required Guest Additions modules where supported e.g. via the DKMS system on Debian and Ubuntu machines. 

This issue is not specific to Ubuntu - a quick look at the other bento boxes shows that these packages are being removed by the clean up scripts for those OSes as well.

# Fix

I understand the rationale behind removing all of the packages required to build the Guest Additions as their removal decreases the resulting image size by quite a few MB. However, I believe most users would gladly accept slightly larger boxes that continue to support Guest Additions post upgrade of the boxes kernel. I also believe this used to be the case with previous versions of the box.

To fix this the clean up scripts must not remove **any** of the packages required to build the Guest Additions.

For example, for Ubuntu the clean up script could be chaged from:
```
# Delete all Linux headers
dpkg --list \
  | awk '{ print $2 }' \
  | grep 'linux-headers' \
| xargs apt-get -y purge;
```
to:
```
dpkg --list \
  | awk '{ print $2 }' \
  | grep 'linux-headers-.*-generic' \
  | grep -v `uname -r` \
  | xargs apt-get -y purge;
```

# Work around

For the example Ubuntu box, if I install the kernel headers (virtual packaga) prior to the upgrade, then DKMS is able to rebuild the modules for the upgraded kernel. Shared folders etc then continue to work as expected after the reboot:
```
sudo apt-get update
sudo apt-get -y install linux-headers-generic
sudo apt-get -y dist-upgrade
```
Clearly, different workarounds will be required for each affected OS as each clean up script removes different packages.

**Comment by cheeseplus** [comment]
This has always been a problem with kernel upgrades even without the recent changes. The balance of minimal boxes and keeping boxes perfectly updateable with regard to virtualization has _always_ been tricky (you'll find more than a few issues in conjunction with vbox updater plugins).

The reason I mention this history is that this problem is always a "chasing" one by nature. We've chosen to release boxes that work with a snapshot of tools and preferring to engender the path of upgrading the box via external (vagrant) mechanisms as opposed to internal. We're open to PRs to make doing this easier but as an issue, this is not and will not ever likely be solvable across the board.

**Comment by DanHam** [comment]
I understand the difficulties in maintaining a balance between box size and supporting features such as shared folders following a user kernel upgrade. However, given the widespread use of bento boxes, I believe this is something they should ideally support. The current behaviour really limits the usefulness of the box as soon as a kernel update is released (or at least makes life more difficult).

Thinking about this some more, as far as I know, only Debian and Ubuntu boxes should be affected by this problem. If I'm understanding things correctly RHEL and derivatives such as CentOS, Oracle Linux etc. ([SEE HERE](https://wiki.centos.org/HowTos/Custom_Kernel#head-566abc4208fceb902d41ee82633f509dbf386a4d)), and also OpenSUSE ([SEE HERE](https://drivers.suse.com/doc/SolidDriver/SUSE_Kernel_ABI_Stability.html)), all guarantee kernel ABI compatibility for the 'lifetime of the product' or 'release'. This allows kernel modules built against an earlier kernel version to work with a later kernel version without the need to recompile.

I've run a few tests. The box size with headers is around 10M larger than the box without. That feels like a win to me. Hopefully, I'll be able to submit a PR over the next few days or so for you to take a look at.

**Comment by cheeseplus** [comment]
Part of the context is that while bento has been adopted by a bunch of projects, the boxes were specifically for use in test-kitchen like scenarios where the boxes are anything but long lived. The guarantees that you're citing unfortunately don't hold up at all with regard to to the virtualization software - they say they do but several years of building these has proved otherwise.

This isn't to discourage any effort toward making it better but speaking to why we've left that rabbit hole alone.

**Comment by DanHam** [comment]
> Heck, just getting the versions of vagrant, vbox, and OS to play nicely together has been wildly unpredictable given bugs in the other layers.

Agreed! I've often battled with this with my own builds - a working box is always cause for celebration!!

> This isn't to discourage any effort toward making it better but speaking to why we've left that rabbit hole alone.

Fair enough. Supporting the continued operation of Guest Additions/VMware tools post user upgrade of the kernel is definitely possible. However, judging from your comments above, doing so would move the builds in a direction that would likely not be of great benefit for your use case and not something that you would likely want to support moving forward. Given the differences between our use cases/needs I don't think this issue is likely solvable at the present time and so I will close the issue.

Many thanks for your time and good luck with your builds moving forward!!

**Comment by cheeseplus** [comment]
I'd still be amendable to a PR that leaves the packages/makes things easier as I think the focus of what and why we were doing things has shifted over time.
