### ISSUE TITLE
Box 201906.18.0 PHP/Composer run failures not present with 201812.27.0

### ISSUE THREAD

**Issue by cognophile** [chef/bento#1207]
# Version:
Virtualbox: `5.2.30`
Vagrant: `2.2.5`
Vagrant box `bento/ubuntu-16.04`: `201906.18.0`

# Environment:
Linux Xubuntu 16.04.

# Scenario:
Attempting to provision the VirtualBox VM managed through Vagrant and running `bento/ubuntu-16.04 201906.18.0`, with Ansible. However, this also occurs without using Ansible (i.e. occurs via `vagrant ssh` onto the box) so I think it's safe to rule that out. This produced the errors as seen in the **Actual results** section. 

This began immediately after upgrading to this box via `vagrant box update` and the `201906.18.0` version was used. No other package versions were updated/reverted, however, once the box was reverted back to `v201812.27.0` all methods of running composer and CakePHP migrations are successful again.

We tried all the usual efforts such as clearing the VM and composer caches, updating composer itself, removing and attempting to re-install packages, clearing the auto-loader cache, but the issue persisted. It wasn't until we rolled back the box version that composer/`phar`/PHP worked correctly and repeatedly. This is why I'm submitting an issue to this repo for the box itself as I feel this may be connected to the box update as we've not encountered such issues before and were able to revert back and have it be successful again. 

The `composer.json` file features: 
```
 "require": {
        "php": "~7.3",
        "admad/cakephp-jwt-auth": "^2.2",
        "box/spout": "^2.7",
        "cakephp/bake": "^1.8",
        "cakephp/cakephp": "^3.6.0",
        "cakephp/migrations": "^1.0",
        "cakephp/plugin-installer": "^1.0",
        "friendsofcake/cakepdf": "^3.2",
        "josegonzalez/dotenv": "^2.0",
        "mobiledetect/mobiledetectlib": "^2.0",
        "phpunit/phpunit": "^6",
        "setasign/fpdi-fpdf": "^2.0.0",
        "xthiago/pdf-version-converter": "dev-master"
    },
    "require-dev": {
        "alt3/cakephp-swagger": "^2.0",
        "apigen/apigen": "~4.1.2",
        "behat/behat": "@stable",
        "cakephp/bake": "^1.1",
        "cakephp/cakephp-codesniffer": "^3.0",
        "cakephp/debug_kit": "~3.0",
        "psy/psysh": "@stable"
 
    ...

    "scripts": {
            "post-autoload-dump": "Cake\\Composer\\Installer\\PluginInstaller::postAutoloadDump",
            "check": [
                "@test",
                "@cs-check"
             ],
             "cs-check": "phpcs --colors -p --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests",
             "cs-fix": "phpcbf --colors --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests",
             "test": "phpunit --colors=always"
       }
```

# Steps to Reproduce:
- Create a VM in VirtualBox via Vagrant using the `bento/ubuntu-16.04` version `201906.18.0`
- Install PHP `7.3.6` and composer `1.8.6`.
- Create a composer project and use the above `composer.json` configuration
- Run `composer install` 

# Expected Result:
Composer should run successfully and install the dependencies listed within `composer.json`. 

# Actual Result:
Composer fails and suggests that it cannot locate various classes within the `phar` extension of the `VM`. However, image B suggests this may be a PHP issue due to attempting to locate another class elsewhere. 

**A.** Via manual `composer install` on the VM.
![Screenshot from 2019-07-04 15-22-28](https://user-images.githubusercontent.com/14915130/60718502-b8cf3a00-9f1c-11e9-8bdf-71e1fab7d71f.png)

**B.** A later error produced by attempting to use one of the packages (CakePHP migrations) after copying the `vendor/` folder contents from a colleagues machine as to make the `composer install` pass
![Screenshot from 2019-07-05 10-07-53](https://user-images.githubusercontent.com/14915130/60718013-748f6a00-9f1b-11e9-82a2-e57783331520.png)

Many of these errors come from being unable to find the package's composer is meant to install I suspect, however, I think there's a connection between the PHP errors occurring as it attempts to look within the `phar` directory and the box having been upgraded and then downgraded to make this work. 

Hope this is enough information. You feel this is better directed elsewhere, please let me know, however, I felt the significance of only the box version changing and being able to reproduce this by using the latest box was relevant to this project.

**Comment by cheeseplus** [comment]
The amount of information provided is great but I'm not seeing where the box itself is being implicated - yes, the box version changed but that's also saying "everything in the os that was updated changed" which isn't terribly useful in a diagnostic sense. This seems specific to composer and it's machinations but if you find something in the box configuration that helps explain it we could attempt addressing it.

**Comment by cognophile** [comment]
> yes, the box version changed but that's also saying "everything in the os that was updated changed" which isn't terribly useful in a diagnostic sense

Yes, fair point. Sorry if it was poorly directed in the first instance. We weren't able to locate any release notes to more accurately determine whether the box was at fault, for example, if something was updated which might have led to a conflict of some sort. Thanks for taking the time to read - we'll try submitting to the composer team then. Thanks again 👍

**Comment by predakanga** [comment]
Just as a heads up for other viewers, this seems to be because of an incompatibility between VirtualBox Guest Additions >= 6.0.6 and VirtualBox < 6.

You can downgrade Guest Additions to version 6.0.4, or upgrade VirtualBox on your host.

**Comment by svpernova09** [comment]
Ran into this w/ Homestead. What we discovered via https://github.com/laravel/homestead/issues/1240 was essentially a Virtualbox *shared folders* seemed to be the culprit when built with any version of Virtualbox >6.0.0 and <= 6.0.10.
