### ISSUE TITLE
Parallels boot_command does not work.

### ISSUE THREAD

**Issue by benlumia007** [chef/bento#1211]
when trying to build box for parallels, the boot_command doesn't do anything.  any idea. has this been tested.

**Comment by cheeseplus** [comment]
Could you provide a bit more context and details as to versions of software being used? Since I've stopped building boxes personally I'm not sure if anyone has built for Parallels (licensing reasons) but that directive definitely has worked and is supported via Packer. 

Hopefully version details will make it clearer where the problem lies.

**Comment by benlumia007** [comment]
at the moment, i have

- MacOS Mojave Version 10.14.5
- Packer 1.4.2
- Vagrant 2.2.5
- Parallels 14 for Mac ( Pro Version )

I figured th boot_command should be the same as virtualbox

```
            "boot_command": [
                "<esc><wait>",
                "<esc><wait>",
                "<enter><wait>",
                "/install/vmlinuz<wait>",
                " auto<wait>",
                " console-setup/ask_detect=false<wait>",
                " console-setup/layoutcode=us<wait>",
                " console-setup/modelcode=pc105<wait>",
                " debconf/frontend=noninteractive<wait>",
                " debian-installer=en_US.UTF-8<wait>",
                " fb=false<wait>",
                " initrd=/install/initrd.gz<wait>",
                " kbd-chooser/method=us<wait>",
                " keyboard-configuration/layout=USA<wait>",
                " keyboard-configuration/variant=USA<wait>",
                " locale=en_US.UTF-8<wait>",
                " netcfg/get_domain=vm<wait>",
                " netcfg/get_hostname=sandbox<wait>",
                " grub-installer/bootdev=/dev/sda<wait>",
                " noapic<wait>",
                " preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg<wait>",
                " -- <wait>",
                "<enter><wait>"
            ]
```
but it doesn't work, meaning that when the vm gets created, and it just stays at choose language

**Comment by cheeseplus** [comment]
That all seems right enough - this is either a timing issue or a bug in Packer. Either way not a bug _we_ can address unless the directive itself changed but I'll see if I can at least confirm it later.

**Comment by benlumia007** [comment]
so in other words, it worked before right, or else you guys wouldn't add it :D  thanks for the help.

**Comment by cheeseplus** [comment]
Pretty much! 

I've confirmed that this is still a valid directive in Packer for the Parallels builder so if it's not working then it's timing or an actual bug. The timing one is nefarious to hunt down cause it depends on the speed of the host itself and any load the box is under - it's really weird behaviour to witness as the _speed_ of the keypresses can be CPU constrained and even the IO system can influence as I've seen regular hard drives (i.e. non-SSD) cause similar issues.

**Comment by benlumia007** [comment]
well that sucks, I was hoping to get parallels working without the need to do it manually.  have u tried on your end, are you getting the same thing. 

if it still doesn't work, then i guess i can't really do much about it.

**Comment by cheeseplus** [comment]
I don't have Parallels installed on my work machine so the earliest I could test is this evening (US mountain time). It could still be a bug in Packer but I don't see anything specifically matching this particular condition.

**Comment by benlumia007** [comment]
You know what is really stupid, packer.io doesn't have any documentation as to why it didn't work. so I had to figure it out. I guess googling is your friend. apparently, you need to install the parallels virtualization sdk installed so that the boot_command can work. 

can you also document this somewhere so that other users who tried to build your package can also have this information 

Parallels Virtualization SDK is a must have if want to use packer to build boxes.

**Comment by cheeseplus** [comment]
This was something I meant to ask earlier and is definitely documented on Packer's docs https://www.packer.io/docs/builders/parallels.html - it's not just so boot command works, it's so anything Packer/Vagrant related work. I understand the frustration so I've added a note to the Readme in #1214

**Comment by benlumia007** [comment]
ha, i must have skipped that requirement lol. thanks for the help. have a nice day :D

**Comment by MarcinZukowski** [comment]
Just wanted to say we hit the same thing. Would be nice if Packer detected Parallels Virtualizaton SDK missing and reported/failed when not...
