### ISSUE TITLE
Enable disk performance counters for Windows 2016+

### ISSUE THREAD

**Issue by irvingpop** [chef/bento#1223]
### Describe the Enhancement:

Currently the disk performance counters are not enabled for the C: drive, so you don't see any disk statistics in tools like Perfmon.

To enable them, run `diskperf -Y` from an elevated shell.   credit: https://tylermade.net/2017/10/16/enabling-disk-performance-counters-in-windows-server-2016-task-manager/

**Comment by tas50** [comment]
@irvingpop I know this isn't exactly your jam anymore, but any chance you could add this to the windows setup cookbook? Should be pretty easy with a execute resource.

**Comment by irvingpop** [comment]
hi @tas50 !! I don't have any Windows infra or testing setups right now, so unfortunately it would take me 10x the time to validate and test compared to someone who's box caches are warm.  I don't think I'd be able to get to this in any reasonable amount of time :(

I'm okay closing this issue, unless you want to find volunteers to adopt it?

**Comment by Stromweld** [comment]
closing this due to age. please feel free to reopen or submit a new issue/pr for this if it's still desired.
