### ISSUE TITLE
bento/debian-{9.8-10.0} vagrant default synced folder permissions error 

### ISSUE THREAD

**Issue by cstlee** [chef/bento#1225]
"Permission denied" when trying to clone a git repo into the Vagrant default synced folder (`/vagrant`) in bento/debian boxes versions 9.8, 9.9, and 10.0.  The last known working version was debian-9.6.

# Describe the problem
An error occurs when trying to `git clone` to a directory within the Vagrant default synced folder `/vagrant` from within the Debian VM.  The error produced by the steps to reproduce (below) is as follows:

```
Cloning into 'bento'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (7/7), done.
fatal: Unable to create temporary file '/vagrant/bento/.git/objects/pack/tmp_pack_XXXXXX': Permission denied
fatal: index-pack failed
```

The expected behavior is for the `git clone` to succeed  and complete (which is the case when cloning to a directory outside the synced directory or when using the older version bento/debian-9.6):

```
Cloning into 'bento'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 8845 (delta 0), reused 2 (delta 0), pack-reused 8837
Receiving objects: 100% (8845/8845), 2.10 MiB | 962.00 KiB/s, done.
Resolving deltas: 100% (5794/5794), done.
```

## Software Version
Configurations tested:
- bento/debian-9.8, 9.9, and 10.0
- macOS 10.13.6 and 10.14.6
- Vagrant 2.2.5
- VirtualBox 6.0.10

## Replication Case
Create an instance of the virtual machine:

```
vagrant init bento/debian-10 --box-version 201907.07.0
vagrant up
```

Shell into the virtual machine:

```
vagrant ssh
```

Install git:

```
sudo apt-get install -y git
```

Try to clone something into the `/vagrant` directory:

```
cd /vagrant
git clone https://github.com/chef/bento.git
```

## Stacktrace

<details><summary>  </summary>
```
```
</details>

**Comment by svpernova09** [comment]
Uninstall Virtualbox 6.0.10 (And extensions) and reinstall Virtualbox 6.0.0 and see if the problem remains.

I ran into some *really* odd issues that sound similar to this.

**Comment by cheeseplus** [comment]
This definitely feels like an upstream VirtualBox issue that we've inherited.

**Comment by svpernova09** [comment]
@cheeseplus I tried to bring this up with Virtualbox, but it went over....not great. If you have contacts that we could poke I'm up for helping debug & test.

https://www.virtualbox.org/ticket/18776

**Comment by cstlee** [comment]
Thanks for looking into this.  It does seem like it's a VirutalBox problem.  I poked around the VirtualBox bug tracker and found these issues that (after reading the comments) seem related:
https://www.virtualbox.org/ticket/18737
https://www.virtualbox.org/ticket/18569

I don't get the feeling this will be fix on the VirtualBox side soon.  Any thoughts on how us bento users should work around this problem in the mean time?  Are there versions of the bento/debian boxes built with the 6.0.0 VirtualBox guest additions?

**Comment by cheeseplus** [comment]
There aren't any great solutions outside of building yourself - a major contributing factor being the bento project has never had any dedicated infra, let alone running multiple versions of any of the hypervisors simultaneously, so having a special case for one hv version + os permutation isn't really tenable (at this time but likely ever because the matrix would always be gnarly).

Shared folders have _always_ been problematic by their very nature of using kernel modules and are endlessly plagued by edge cases - my recommendation is never using them (test-kitchen specifically avoids doing this be default) and if you _must_ then use the rsync or NFS methods.

**Comment by cstlee** [comment]
Got it; that's understandable.  I'll try some of these options and see what works best for our workflow.  Thanks for your suggestions.

Feel free to close this issue unless you'd like to keep it around to track when the VirtualBox fix makes it into bento.

@cheeseplus @svpernova09 Thanks for your help!

**Comment by cheeseplus** [comment]
I'll close this out by enumerating options for these cases (in no particular order):
- use rsync or NFS shared folders as they are far more reliable
- self-build an image with desired working VirtualBox version
- use an alternate hypervisor such as Parallels or Vmware Fusion/Workstation
- wait for VirtualBox to address issue
