### ISSUE TITLE
Ubuntu/Debian cleanup ignores dev:amd64 packages

### ISSUE THREAD

**Issue by grische** [chef/bento#1227]
# Version:
2669337e5a68a32445e1c04f7d418d1bc8e2f379

# Environment:
Debian/Ubuntu

# Scenario:
The `cleanup.sh` script is trying to remove all `-dev` packages:
https://github.com/chef/bento/blob/2669337e5a68a32445e1c04f7d418d1bc8e2f379/packer_templates/debian/scripts/cleanup.sh#L25-L28
https://github.com/chef/bento/blob/2669337e5a68a32445e1c04f7d418d1bc8e2f379/packer_templates/ubuntu/scripts/cleanup.sh#L25-L28

But in current versions of Ubuntu/Debian, `dpkg --list` will contain several packages which end in `-dev:amd64$` instead of `-dev$`.
For example: `libstdc++-8-dev:amd64`

# Proposal
If the intention of this purge is to remove all dev-packages, the regex should be expanded to something like this:
```grep -- '-dev\(:[a-z0-9]\+\)\?$'```

This regex will find both `-dev` and different arch-specific packages like `-dev:myarch32`.

**Comment by tas50** [comment]
@grische This seems like a reasonable addition to the cleanup script. Any chance you can cut a PR with this change?

**Comment by tas50** [comment]
I made this change on master and a new set of boxes are building now. Thanks @grische
