### ISSUE TITLE
`bundle install` in a recipe fails when the cookbook installs `chef_gem`s only on `bento/ubuntu-18.04`

### ISSUE THREAD

**Issue by timvisher** [chef/bento#1229]
# Version:

`ubuntu-(14|16|)18).04`

# Environment:

https://github.com/timvisher/temp_bundler_1804

# Scenario:

Run `bundle install` during a test-kitchen run when a cookbook has `chef_gem`s installed on `bento/ubuntu-18.04`.

# Steps to Reproduce:

Run `kitchen test -d never --concurrency=6` in https://github.com/timvisher/temp_bundler_1804 and you'll see that only the test cookbook with chef gems installed on 18.04 fails. All the other ones succeed.

# Expected Result:

I expect 18.04 to work like the other ones do.

# Actual Result:

18.04 fails.

**Comment by cheeseplus** [comment]
This is very likely an issue with chef itself and how it's working/sanitizing the environment. As suspected, it's very likely not an issue with the base image itself.

**Comment by timvisher** [comment]
@cheeseplus Is that a chef/chef issue then, do you think?

**Comment by cheeseplus** [comment]
Correct, that's what I was implying but should have included the repo [link](https://github.com/chef/chef) to be more complete. This has everything to do with the Ruby context that `bundle install` is being executed from which is something that the chef-client brings and isn't a part of bento's purview.

**Comment by timvisher** [comment]
Sweet. Thanks for the info!

**Comment by timvisher** [comment]
For reference opened up https://github.com/chef/chef/issues/8918
