### ISSUE TITLE
Centos 7.6 network doesn't work because of ambiguous connection type in cleanup.sh

### ISSUE THREAD

**Issue by kaibaesler** [chef/bento#1230]
# Version:

https://github.com/chef/bento/commit/2669337e5a68a32445e1c04f7d418d1bc8e2f379

# Environment:

- Ubuntu 19.04 Host
- VirtualBox 6.0.6
- packer 1.4.3

# Scenario:

(Re-)building a Centos 7.6 Vagrant box with the "virtualbox-iso" builder. The resulting box isn't accessible over the network (ie. vagrant ssh doesn't work), because the command 

    nmcli c add type eth ifname \$gwdev con-name \$gwdev 

in [line 49](https://github.com/chef/bento/blob/master/packer_templates/centos/scripts/cleanup.sh#L49) of packer_templates/centos/scripts/cleanup.sh fails.

Actually, "eth" is ambiguous since NetworkManager [1.14](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/blob/nm-1-14/NEWS), with the introduction of an additional type "ethtool". I've tried the unabbreviated type name and can confirm that the line below works 

    nmcli connection add type ethernet ifname \$gwdev con-name \$gwdev

**Comment by rhawalsh** [comment]
I was encountering this issue as well when trying to generate rhel7.7 machines (based on the rhel/centos7.6 configurations posted here).  Taking the update you suggested resolved the issues on my end.

(Not trying to sound snarky here) This is an argument for not allowing shorthand in commands being used in scripts.  I think there's less likelihood of there being a potential situation where an argument turns ambiguous.

**Comment by grassbl8d** [comment]
I'm also encountering this issue. 
no network is being generated on the guest machine. 

I'm trying the change right now.

**Comment by tas50** [comment]
This should be fixed on master and I'm building new boxes now.

**Comment by tas50** [comment]
Opening this back up since it's still an issue even after #1236

**Comment by tas50** [comment]
Ignore me this actually works now
