### ISSUE TITLE
vmware tools fails to install on Fedora 30

### ISSUE THREAD

**Issue by Sprbb** [chef/bento#1238]
# Version:

Just cloned.

# Environment:

Ubuntu 18.04

# Scenario:
[What you are trying to achieve and you can't?]

Building a VMware fedora 30 box.

# Steps to Reproduce:

Clone repo. Cd into fedora directory
packer build -only=vmware-iso fedora-30-x86_64.json

# Expected Result:

No errors.

# Actual Result:

[What actually happens after the reproduction steps?]

8006 ^[[0;32m    vmware-iso: Complete!^[[0m
  8007 ^[[1;32m==> vmware-iso: Provisioning with shell script: ../_common/motd.sh^[[0m
  8008 ^[[1;32m==> vmware-iso: Provisioning with shell script: ../_common/sshd.sh^[[0m
  8009 ^[[1;32m==> vmware-iso: Provisioning with shell script: ../_common/virtualbox.sh^[[0m
  8010 ^[[1;32m==> vmware-iso: Provisioning with shell script: ../_common/vmware.sh^[[0m
  8011 ^[[1;31m==> vmware-iso: mount: /tmp/vmware: WARNING: device write-protected, mounted read-only.^[[0m
  8012 ^[[0;32m    vmware-iso: VMware Tools Version: 10.2.5^[[0m
  8013 ^[[0;32m    vmware-iso: The installer has detected an existing installation of open-vm-tools packages^[[0m
  8014 ^[[0;32m    vmware-iso: on this system and will not attempt to remove and replace these user-space^[[0m
  8015 ^[[0;32m    vmware-iso: applications. It is recommended to use the open-vm-tools packages provided by^[[0m
  8016 ^[[0;32m    vmware-iso: the operating system. If you do not want to use the existing installation of^[[0m
  8017 ^[[0;32m    vmware-iso: open-vm-tools packages and use VMware Tools, you must uninstall the^[[0m
  8018 ^[[0;32m    vmware-iso: open-vm-tools packages and re-run this installer.^[[0m
  8019 ^[[0;32m    vmware-iso: The packages that need to be removed are:^[[0m
  8020 ^[[0;32m    vmware-iso: open-vm-tools^[[0m
  8021 ^[[0;32m    vmware-iso: The installer will next check if there are any missing kernel drivers. Type yes^[[0m
  8022 ^[[0;32m    vmware-iso: if you want to do this, otherwise type no [yes]^[[0m
  8023 ^[[0;32m    vmware-iso: INPUT: [vagrant]^[[0m
  8024 ^[[0;32m    vmware-iso:^[[0m
  8025 ^[[0;32m    vmware-iso: The answer "vagrant" is invalid. It must be one of "y" or "n".^[[0m
  8026 ^[[0;32m    vmware-iso:^[[0m
  8027 ^[[0;32m    vmware-iso: The installer will next check if there are any missing kernel drivers. Type yes^[[0m
  8028 ^[[0;32m    vmware-iso: if you want to do this, otherwise type no [yes]^[[0m
  8029 ^[[0;32m    vmware-iso: INPUT: [yes]  default^[[0m
  8030 ^[[0;32m    vmware-iso:^[[0m
  8031 ^[[0;32m    vmware-iso: Creating a new VMware Tools installer database using the tar4 format.^[[0m
  8032 ^[[0;32m    vmware-iso:^[[0m
  8033 ^[[0;32m    vmware-iso: Installing VMware Tools.^[[0m
  8034 ^[[0;32m    vmware-iso:^[[0m
  8035 ^[[0;32m    vmware-iso: In which directory do you want to install the binary files?^[[0m
  8036 ^[[0;32m    vmware-iso: [/usr/bin]^[[0m
  8037 ^[[0;32m    vmware-iso: INPUT: [/usr/bin]  default^[[0m
  8038 ^[[0;32m    vmware-iso:^[[0m
  8039 ^[[0;32m    vmware-iso: What is the directory that contains the init directories (rc0.d/ to^[[0m
  8040 ^[[0;32m    vmware-iso: rc6.d/)?^[[0m

**Comment by tas50** [comment]
This is actually a problem for all vmware builds at the moment. I'm going to take a look this upcoming work week.

**Comment by tas50** [comment]
Should be fixed by #1237

**Comment by tas50** [comment]
Still an issue for Fedora 30 actually

**Comment by tas50** [comment]
It works on 31 which is odd

**Comment by arizvisa** [comment]
I'll test-build this today (rn actually). I use vmware almost exclusively. We should probably conditionally test for `open-vm-tools` prior to installation anyways.

**Comment by tas50** [comment]
It's really odd that 29 works and 31 works, but not 30

**Comment by arizvisa** [comment]
Seems like on fedora-30 the default `/etc/rc.d` directory is not being detected. This is kind of weird as -force-install is being used. One option is to feed direct input to `vmware-tools.pl`, the other option is to not install when open-vm-tools is already installed as according to the logs it appears that everything fails anyways...

```
    vmware-iso: What is the directory that contains the init directories (rc0.d/ to
    vmware-iso: rc6.d/)?
    vmware-iso: INPUT: []  default
    vmware-iso:
    vmware-iso: The path "" is not an existing directory.
```

fedora-everything-else:
```
    vmware-iso: What is the directory that contains the init directories (rc0.d/ to rc6.d/)?
    vmware-iso: [/etc/rc.d]
    vmware-iso: INPUT: [/etc/rc.d]  default
```

**Comment by tas50** [comment]
I'm going to close this out now that we have vmware tools working on 31 and 32
