### ISSUE TITLE
Please provide RHEL 7.7 json

### ISSUE THREAD

**Issue by emo3** [chef/bento#1250]
### Describe the Enhancement:
Would like to build a RHEL 7.7 box but no supplied json.

### Describe the Need:
Use the CentOS 7.7 as template.

### Current Alternative
Modify RHEL 7.6 with new arguments.

**Comment by emo3** [comment]
"iso_checksum": "88b42e934c24af65e78e09f0993e4dded128d74ec0af30b89b3cdc02ec48f028",
"iso_name": "rhel-server-7.7-x86_64-dvd.iso"

**Comment by mariadb-JeffBachtel** [comment]
A CentOS 7.8 json is now available, should this issue be closed?
