### ISSUE TITLE
Sles template is only adding the package iso in the virtualbox-iso builder

### ISSUE THREAD

**Issue by bugbuilder** [chef/bento#1252]
Hi,

The [sles-15.json](https://github.com/chef/bento/blob/master/packer_templates/sles/sles-15.json#L31-L45) and [sles-15-sp1.json](https://github.com/chef/bento/blob/master/packer_templates/sles/sles-15-sp1.json#L31-L45) is using an additional iso package but this is only added in the virtualbox-iso.

I was working with qemu and to accomplish this I used this qemuars:

```
"qemuargs": [
  ["-drive", "file=../../builds/packer-{{user `template`}}-qemu/{{user `template`}},if=virtio,cache=writeback,discard=ignore,format=qcow2"],
  ["-drive", "file={{user `mirror`}}/{{user `packages_iso`}},format=raw,if=none,id=cdrom0,readonly=on"],
  ["-device", "virtio-scsi-pci,id=scsi0"],
  ["-device", "scsi-cd,bus=scsi0.0,scsi-id=0,lun=1,drive=cdrom0"]
 ]
```
I did this because packer had an issue with [additional drive/device](https://github.com/hashicorp/packer/issues/8379)

**Comment by cheeseplus** [comment]
Qemu support for any templates has always been community driven so I'd suggest creating a PR with these changes. Although I can't speak for the project's commitments going forward, QEMU has never been supported officially and is rarely built/tested by the maintainers.

**Comment by bugbuilder** [comment]
Thanks for the feedback @cheeseplus 

I'll send a PR because the fix was [merged](https://github.com/hashicorp/packer/pull/8380) to packer.

**Comment by tas50** [comment]
@bugbuilder Any chance you can cut a PR to fix this one?

**Comment by bugbuilder** [comment]
sure, no problem.

**Comment by tas50** [comment]
Closing since we merged a fix for this.
