### ISSUE TITLE
 backwards-breaking: Qemu builder disk size as a string

### ISSUE THREAD

**Issue by bugbuilder** [chef/bento#1253]
The next packer version, 1.5, is adding a [new disk size convention](https://github.com/hashicorp/packer/pull/7546) for qemu builder. 

**Simplest solution**

 `     "disk_size": "{{user `disk_size`}}M"` *only in the qemu builder*

**Affected template**
- [centos-5.11-i386.json](https://github.com/chef/bento/blob/master/packer_templates/centos/centos-5.11-i386.json)
- [centos-5.11-x86_64.json](https://github.com/chef/bento/blob/master/packer_templates/centos/centos-5.11-x86_64.json)
- [centos-6.10-i386.json](https://github.com/chef/bento/blob/master/packer_templates/centos/centos-6.10-i386.json)
- [centos-6.10-x86_64.json](https://github.com/chef/bento/blob/master/packer_templates/centos/centos-6.10-x86_64.json)
- [centos-7.7-x86_64.json](https://github.com/chef/bento/blob/master/packer_templates/centos/centos-7.7-x86_64.json)
- [centos-8.0-x86_64.json](https://github.com/chef/bento/blob/master/packer_templates/centos/centos-8.0-x86_64.json)
- [debian-10.1-amd64.json](https://github.com/chef/bento/blob/master/packer_templates/debian/debian-10.1-amd64.json)
- [debian-10.1-i386.json](https://github.com/chef/bento/blob/master/packer_templates/debian/debian-10.1-i386.json)
- [debian-8.11-amd64.json](https://github.com/chef/bento/blob/master/packer_templates/debian/debian-8.11-amd64.json)
- [debian-8.11-i386.json](https://github.com/chef/bento/blob/master/packer_templates/debian/debian-8.11-i386.json)
- [debian-9.11-amd64.json](https://github.com/chef/bento/blob/master/packer_templates/debian/debian-9.11-amd64.json)
- [debian-9.11-i386.json](https://github.com/chef/bento/blob/master/packer_templates/debian/debian-9.11-i386.json)
- [debian-9.11-ppc64el.json](https://github.com/chef/bento/blob/master/packer_templates/debian/debian-9.11-ppc64el.json)
- [fedora-29-x86_64.json]( https://github.com/chef/bento/blob/master/packer_templates/fedora/fedora-29-x86_64.json)
- [fedora-30-x86_64.json](https://github.com/chef/bento/blob/master/packer_templates/fedora/fedora-30-x86_64.json)
- [fedora-31-x86_64.json](https://github.com/chef/bento/blob/master/packer_templates/fedora/fedora-31-x86_64.json)
- [freebsd-11.3-amd64.json](https://github.com/chef/bento/blob/master/packer_templates/freebsd/freebsd-11.3-amd64.json)
- [freebsd-11.3-i386.json](https://github.com/chef/bento/blob/master/packer_templates/freebsd/freebsd-11.3-i386.json)
- [freebsd-12.0-amd64.json](https://github.com/chef/bento/blob/master/packer_templates/freebsd/freebsd-12.0-amd64.json)
- [freebsd-12.0-i386.json](https://github.com/chef/bento/blob/master/packer_templates/freebsd/freebsd-12.0-i386.json)
- [hardenedbsd-11-amd64.json](https://github.com/chef/bento/blob/master/packer_templates/hardenedbsd/hardenedbsd-11-amd64.json)
- [opensuse-leap-15.1-x86_64.json](https://github.com/chef/bento/blob/master/packer_templates/opensuse/opensuse-leap-15.1-x86_64.json)
- [oracle-5.11-i386.json](https://github.com/chef/bento/blob/master/packer_templates/oraclelinux/oracle-5.11-i386.json)
- [oracle-5.11-x86_64.json]( https://github.com/chef/bento/blob/master/packer_templates/oraclelinux/oracle-5.11-x86_64.json)
- [oracle-6.10-i386.json](https://github.com/chef/bento/blob/master/packer_templates/oraclelinux/oracle-6.10-i386.json)
- [oracle-6.10-x86_64.json](https://github.com/chef/bento/blob/master/packer_templates/oraclelinux/oracle-6.10-x86_64.json)
- [oracle-7.7-x86_64.json](https://github.com/chef/bento/blob/master/packer_templates/oraclelinux/oracle-7.7-x86_64.json)
- [rhel-5.11-i386.json](https://github.com/chef/bento/blob/master/packer_templates/rhel/rhel-5.11-i386.json)
- [rhel-5.11-x86_64.json](https://github.com/chef/bento/blob/master/packer_templates/rhel/rhel-5.11-x86_64.json)
- [rhel-6.10-i386.json](https://github.com/chef/bento/blob/master/packer_templates/rhel/rhel-6.10-i386.json)
- [rhel-6.10-x86_64.json](https://github.com/chef/bento/blob/master/packer_templates/rhel/rhel-6.10-x86_64.json)
- [rhel-7.6-x86_64.json](https://github.com/chef/bento/blob/master/packer_templates/rhel/rhel-7.6-x86_64.json)
- [rhel-8.0-x86_64.json](https://github.com/chef/bento/blob/master/packer_templates/rhel/rhel-8.0-x86_64.json)
- [sles-11-sp4-x86_64.json](https://github.com/chef/bento/blob/master/packer_templates/sles/sles-11-sp4-x86_64.json)
- [sles-12-sp2-x86_64.json](https://github.com/chef/bento/blob/master/packer_templates/sles/sles-12-sp2-x86_64.json)
- [sles-12-sp3-x86_64.json](https://github.com/chef/bento/blob/master/packer_templates/sles/sles-12-sp3-x86_64.json)
- [sles-15-sp1.json](https://github.com/chef/bento/blob/master/packer_templates/sles/sles-15-sp1.json)
- [sles-15.json](https://github.com/chef/bento/blob/master/packer_templates/sles/sles-15.json)
- [ubuntu-16.04-amd64.json](https://github.com/chef/bento/blob/master/packer_templates/ubuntu/ubuntu-16.04-amd64.json)
- [ubuntu-16.04-i386.json](https://github.com/chef/bento/blob/master/packer_templates/ubuntu/ubuntu-16.04-i386.json)
- [ubuntu-18.04-amd64.json](https://github.com/chef/bento/blob/master/packer_templates/ubuntu/ubuntu-18.04-amd64.json)
- [ubuntu-18.10-amd64.json](https://github.com/chef/bento/blob/master/packer_templates/ubuntu/ubuntu-18.10-amd64.json)
- [ubuntu-19.04-amd64.json](https://github.com/chef/bento/blob/master/packer_templates/ubuntu/ubuntu-19.04-amd64.json)

**Comment by tas50** [comment]
Closing this out since packer reverted the change. Let me know if you need anything else on qemu side of things. I can't test that since I'm not setup for it, but as long as we don't impact the other hypervisors I'm happy to merge in changes.
