### ISSUE TITLE
 vmtoolsd.service does not exist.  Builds finished but no artifacts were created.

### ISSUE THREAD

**Issue by vikaskedia** [chef/bento#1267]
# Version:

Vagrant 2.0.1

# Environment:

Mac Catalina

# Scenario:

Build ubuntu 18.04 for vmware

# Steps to Reproduce:

> packer build -only=vmware-iso ubuntu-18.04-amd64.json

# Expected Result:

A ubuntu 18.04 running inside vmware

# Actual Result:

==> vmware-iso: Failed to enable unit: Unit file vmtoolsd.service does not exist.
==> Builds finished but no artifacts were created.

The screenshot:

![image](https://user-images.githubusercontent.com/6703876/71778522-e6e11580-2f63-11ea-8927-5fc88aca89e4.png)

**Comment by zestysoft** [comment]
packer_templates/ubuntu/scripts/vmware.sh is attempting to start the service name that the "official" vmware tools uses, not the service name that comes with open-vmtools.

Change vmtoolsd to open-vm-tools in that script to fix.  I'll create a pr shortly.

**Comment by tas50** [comment]
Closing this since it's been fixed thanks to @zestysoft
