### ISSUE TITLE
Use ubuntu 18.04.4 images

### ISSUE THREAD

**Issue by rockdreamer** [chef/bento#1273]
### Describe the Enhancement:

Build using ubuntu 18.04.4 iso

### Describe the Need:

Current version didn't build as 18.04.3 isos are missing

### Current Alternative

- Change the iso to point to 18.04.4 isos and update sha256
- add "virtualHW.version": "13" to "vmx_data" in vmware-iso builder
- remove noapic from the boot command in vmware-iso builder

### Can We Help You Implement This?:

You can test what I've done works reasonably well with other VMWare versions. I've updated the virtualHW version to our current minimum where I work, but this might not be acceptable for wider distribution

**Comment by tas50** [comment]
I updated to 18.04.4 in 958e047b1fe830de3659e5f688abd33e8ee8e887. Thanks for the heads up. For now I'd like to keep the vwmare hardware versions as old as possible to avoid compatibility issues.
