### ISSUE TITLE
A

### ISSUE THREAD

**Issue by poxtyn1** [chef/bento#1274]
# Version:

[Version of the project installed]

# Environment:

[Details about the environment such as the Operating System, cookbook details, etc...]

# Scenario:

[What you are trying to achieve and you can't?]

# Steps to Reproduce:

[If you are filing an issue what are the things we need to do in order to repro your problem?]

# Expected Result:

[What are you expecting to happen as the consequence of above reproduction steps?]

# Actual Result:

[What actually happens after the reproduction steps?]

**Comment by tas50** [comment]
Closing this out since there's nothing in the template
