### ISSUE TITLE
"Cannot allocate memory" on vagrant up

### ISSUE THREAD

**Issue by ethanmdavidson** [chef/bento#1276]
# Version:

[bento/oracle-7 v202002.04.0](https://app.vagrantup.com/bento/boxes/oracle-7/versions/202002.04.0)

# Environment:

- Host: Windows 10, vagrant 2.2.7, virtualbox 6.1.4
- Guest: bento/oracle-7 (from vagrant cloud)

# Scenario:

When upping the box, vagrant sometimes encounters an error saying "cannot allocate memory". This seems to be an error in vagrant because it happens every time vagrant tries to insert the new public key. My host has plenty of free memory, and the guest is being configured with a much larger amount of memory than it should need. 

I recognize that this doesn't look like an issue with the box published by bento, but it has only started occurring once I switched to the bento box from a different oracle7 box. I've opened an [issue with vagrant](https://github.com/hashicorp/vagrant/issues/11420), but they seem to think it's an issue with the bento box. Could someone take a look at this issue and possibly shed some light here?

**Comment by makker-nl** [comment]
I got the same error when it mounts additional synched disks or later when doing provisioning:
```
    darwin-tf: /vagrant => D:/Projects/vagrant/ol77_tf
    darwin-tf: /media/sf_Stage => D:/Projects/vagrant/Stage
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mkdir -p /media/sf_Stage

Stdout from the command:



Stderr from the command:

mkdir: cannot create directory ‘/media/sf_Stage’: Cannot allocate memory

d:\Projects\vagrant\ol77_tf>
```

**Comment by sniedetzki-olr** [comment]
Same issue and it happens more often than not.
Happens either when inserting private key into Linux VM or when creating directory as @makker-nl has.

I have searched high and low as I can not find a solution to this.

Host: PopOS 20.04 - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, 64GB RAM
Guest: Centos 7 
Vagrant: 2.2.9
VirtualBox: 6.1.10
Ruby: ruby 2.7.0p0
Host Kernel: Linux pop-os 5.4.0-7634-generic 

Memory available: free -m
                     total        used        free      shared  buff/cache   available
Mem:          63776        6294       36269         299       21213       56543
Swap:          8191         103        8088


Failure from inserting private key:

Traceback (most recent call last):
	36: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'
	35: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/vagrant-2.2.9/plugins/communicators/ssh/communicator.rb:63:in `wait_for_ready'
	34: from /tmp/.mount_vagran11ZGAU/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
	33: from /tmp/.mount_vagran11ZGAU/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
	32: from /tmp/.mount_vagran11ZGAU/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
	31: from /tmp/.mount_vagran11ZGAU/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
	30: from /tmp/.mount_vagran11ZGAU/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
	29: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/vagrant-2.2.9/plugins/communicators/ssh/communicator.rb:88:in `block in wait_for_ready'
	28: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/vagrant-2.2.9/plugins/communicators/ssh/communicator.rb:192:in `ready?'
	27: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/guest.rb:43:in `capability'
	26: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/capability_host.rb:111:in `capability'
	25: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/capability_host.rb:111:in `call'
	24: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/vagrant-2.2.9/plugins/guests/linux/cap/public_key.rb:14:in `insert_public_key'
	23: from /tmp/.mount_vagran11ZGAU/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
	22: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/vagrant-2.2.9/plugins/guests/linux/cap/public_key.rb:19:in `block in insert_public_key'
	21: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/vagrant-2.2.9/plugins/communicators/ssh/communicator.rb:307:in `upload'
	20: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/vagrant-2.2.9/plugins/communicators/ssh/communicator.rb:740:in `scp_connect'
	19: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/vagrant-2.2.9/plugins/communicators/ssh/communicator.rb:391:in `connect'
	18: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/vagrant-2.2.9/plugins/communicators/ssh/communicator.rb:742:in `block in scp_connect'
	17: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/vagrant-2.2.9/plugins/communicators/ssh/communicator.rb:337:in `block in upload'
	16: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/vagrant-2.2.9/plugins/communicators/ssh/communicator.rb:331:in `block (2 levels) in upload'
	15: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/net-scp-1.2.1/lib/net/scp.rb:284:in `upload!'
	14: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/net-ssh-5.2.0/lib/net/ssh/connection/channel.rb:272:in `wait'
	13: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:181:in `loop'
	12: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:181:in `loop'
	11: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:181:in `block in loop'
	10: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:228:in `process'
	 9: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/net-ssh-5.2.0/lib/net/ssh/connection/event_loop.rb:29:in `process'
	 8: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/net-ssh-5.2.0/lib/net/ssh/connection/event_loop.rb:101:in `ev_preprocess'
	 7: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/net-ssh-5.2.0/lib/net/ssh/connection/event_loop.rb:101:in `each'
	 6: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:250:in `ev_preprocess'
	 5: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:540:in `each_channel'
	 4: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:540:in `each'
	 3: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:250:in `block in ev_preprocess'
	 2: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/net-ssh-5.2.0/lib/net/ssh/connection/channel.rb:323:in `process'
	 1: from /tmp/.mount_vagran11ZGAU/usr/gembundle/gems/net-scp-1.2.1/lib/net/scp.rb:369:in `block (3 levels) in start_command'
/tmp/.mount_vagran11ZGAU/usr/gembundle/gems/net-scp-1.2.1/lib/net/scp.rb:398:in `await_response_state': scp: /tmp/vagrant-insert-pubkey-1596757261: Cannot allocate memory (RuntimeError)

**Comment by makker-nl** [comment]
Hi,

I worked around it by not using the default ssh-key based sigin in, but plain username password. 
See: https://blog.darwin-it.nl/2020/05/vagrant-oracle-linux-and-vagrant-user.html.

I can't explain it just yet, but the ssh-key based logon apparently somehow influences the resource allocation.

Kind regards,
Martien

**Comment by sniedetzki-olr** [comment]
@makker-nl Unfortuneately this does not solve it for me either.

I had previously tried removing ssh-key login and using a static username/password.
This solves the issue with memory allocation during the key insertion phase, but still blows up periodically when attempting to map shared folders throwing a memory allocation issue with the 'mkdir' command.

It really appears this has something to do with the guest OS, as we use our own vagrant boxes we created internally.
The similarity I see with this issue being reported multiple times seems to have some link to Red Hat based boxes (Oracle Linux, Centos).

I really think there is something wrong with Ruby on Redhat distros, as it seems the error is being spawned from the Ruby processes running on the guest to insert the ssh keys and execute the 'mkdir' commands.

**Comment by Stromweld** [comment]
Closing this due to age. Please feel free to re-open this issue or submit a new one if the problem still exists.
