### ISSUE TITLE
ip_vs is not available in dokken images

### ISSUE THREAD

**Issue by Xorima** [chef/bento#1279]
# Version:

Latest dokken image

# Environment:

Runner: Dokken
Cookbook: https://github.com/sous-chefs/keepalived/pull/106
Operating Systemd: centos-8, ubuntu-20.04
# Scenario:

Converge on Docker and have keepalived start correctly

# Steps to Reproduce:

Converge in dokken, keepalived will fail.

# Expected Result:

`keepalived` to start, full machine images it does

# Actual Result:

Service does not start, this is due to: 

```
modprobe: FATAL: Module ip_vs not found in directory /lib/modules/5.3.0-46-generic
```
This is not an issue on centos-7 or ubuntu 18.04

It is blocking sous-chefs from being able to support the latest operating systems.

**Comment by tas50** [comment]
@Xorima dokken-images repo is where you want to file this
