### ISSUE TITLE
Add support for Ubuntu 20.04 LTS Boxes

### ISSUE THREAD

**Issue by tknerr** [chef/bento#1281]
### Describe the Enhancement:
https://app.vagrantup.com/bento/boxes/ubuntu-20.04 would be available as a basebox with the recently released Ubuntu 20.04 LTS version

### Describe the Need:
This would probably be beneficial for any user of the existing bento/ubuntu boxes, as the newly released 20.04 version is an LTS version. Also availability of vmware_desktop and parallels boxes in addition to virtualbox is a big plus for the bento boxes.

### Current Alternative
I found no other reliable / trusted basebox for Ubuntu 20.04 so far. The "official" ubuntu baseboxes are virtualbox only, thus they won't help users who need vmware_desktop or parallels boxes

### Can We Help You Implement This?:
Unfortunately I don't have the time and resources available to implement it myself right now, as it seems a bit more complicated than just updating the iso URL and checksums :-/ The issue is that with Ubuntu 20.04 the classic .iso images with the "d-i" / preseed installer are no longer available, there is only the new "subiquity" live installer. I guess this requires quite a bit more effort to adapt on packer side, if even possible at all. That's why I'm asking for your help here, as you are certainly have much more expertise in this than I do...

**Comment by svpernova09** [comment]
I'm currently trying to build a template for 20.04 and getting stuck on the installer :/

**Comment by tknerr** [comment]
@svpernova09 I can feel with you - that's what led me here... ;)

**Comment by svpernova09** [comment]
@tknerr I came across this: https://wiki.ubuntu.com/UbiquityAutomation Hoping it'll help me translate / update the options

**Comment by tknerr** [comment]
Oh, I ended up here and it looked totally different / non-preseed like:
https://wiki.ubuntu.com/FoundationsTeam/AutomatedServerInstalls

**Comment by Troym** [comment]
It seems to work by using the legacy server images at http://cdimage.ubuntu.com/ubuntu-legacy-server/releases/20.04/release/ ... although I haven't really tested the resulting machine image much yet. This is what I changed from the 19.10 json file to make it work:

     "box_basename": "ubuntu-20.04",
     "iso_checksum": "36f15879bd9dfd061cd588620a164a82972663fdd148cce1f70d57d314c21b73",
     "iso_name": "ubuntu-20.04-legacy-server-amd64.iso",
     "mirror_directory": "ubuntu-legacy-server/releases/20.04/release",
     "name": "ubuntu-20.04",
     "template": "ubuntu-20.04-amd64",

**Comment by nickcharlton** [comment]
I've been looking into this problem, and after a weekend of experiments have gotten it working using the new automated installer.

It's a bit late here in the UK as I write this, so I've run out of time to open the PR I wanted to but I'd like to come back tomorrow with one.

In the mean time, if someone wants to take a look at this, I've written up my notes which have a working configuration: https://nickcharlton.net/posts/automating-ubuntu-2004-installs-with-packer.html

**Comment by tknerr** [comment]
Thanks everyone for fixing this!! ❤️

**Comment by tas50** [comment]
This is now up at https://app.vagrantup.com/bento/boxes/ubuntu-20.04

**Comment by ahrenstein** [comment]
I'm able to pull the box and use it with kitchen 👍
