### ISSUE TITLE
vagrant key doesn't exists anymore

### ISSUE THREAD

**Issue by Tcharl** [chef/bento#1287]
# Version:

master

# Scenario:

vagrant.sh file reference `https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub`as user key.
however, this repo doesn't exist anymore.
The new address should be `https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub`

# Steps to Reproduce:

build a machine, then login using ssh with vagrant insecure key

# Expected Result:

login succeed

# Actual Result:

login failed

**Comment by tas50** [comment]
Thanks for the report @Tcharl I updated this and rebuild all the boxes.
