### ISSUE TITLE
bento/fedora-31 is not using full disk size

### ISSUE THREAD

**Issue by HolgerHees** [chef/bento#1288]
Hello,

I'm using your image bento/fedora-31 but I'm running out of space during my deployment.

Currently you box image is configured with the virtual size of 64GB with dynamic disk size. But for some reason the partition inside is limit to 15GB. Can you please expand it to use the full available dynamic size of 62GB. 

best and thanks for providing this service.

**Comment by HolgerHees** [comment]
as an example bento/opensuse-leap-15.1 has a disk size of 63,5GB and 500M SWAP

**Comment by tas50** [comment]
yeah the Fedora boxes have a less than ideal lvm setup on them that I need to destroy so we can just use a flat disk partition setup for testing.

**Comment by tas50** [comment]
I've nuked LVM in these images, removed the swap partition, and changed /tmp to not use the size capped tmpfs. If you can check out the 202010.22.0  box hopefully that works better.

**Comment by AllanJard** [comment]
Old one this one, but I'm encountering the same issue now. I'm using the 202010.22.0 version:

```
				"box": {
					"name": "bento/fedora-31",
					"provider": "virtualbox",
					"version": "202010.22.0"
				}
```

But:

```
→ df -Th
Filesystem     Type      Size  Used Avail Use% Mounted on
devtmpfs       devtmpfs  2.4G     0  2.4G   0% /dev
tmpfs          tmpfs     2.5G  8.0K  2.5G   1% /dev/shm
tmpfs          tmpfs     2.5G  604K  2.5G   1% /run
/dev/sda2      xfs        15G   15G   27M 100% /
vagrant        vboxsf    456G  191G  266G  42% /vagrant
tmpfs          tmpfs     494M     0  494M   0% /run/user/1000
```

**Comment by Stromweld** [comment]
closing this since fedora 31 is no longer supported
