### ISSUE TITLE
Windows VM templates missing `disk_size` user variable and provider option so start with very small (for Windows) 40GB disk

### ISSUE THREAD

**Issue by dragon788** [chef/bento#1294]
# Version:

Latest templates

# Environment:

Building Windows VMs with any provider

# Scenario:

Would like to pass `-var 'disk_size=100000'` to have a larger disk attached to the box rather than using experimental disk resizing via Vagrant or Vagrant plugins, but discovered that while most of the Linux images have this, the Windows ones do not.

# Steps to Reproduce:

`packer build -var 'disk_size=100000' packer_templates/windows/windows-10.json`

# Expected Result:

I get VMs with ~100GB disks.

# Actual Result:

The Packer command fails because `disk_size` isn't defined as a user variable, and isn't set/passed into any of the providers.

**Comment by dragon788** [comment]
@tas50 this should be an easy one to fix, so I'll try to get a PR up this weekend, otherwise you might be able to knock it out in a few minutes.

A nice "smoke test" might be to loop through all the templates and call `packer validate -var 'disk_size=20000' template.json` and do the same for any "global" overrides that should be consistently present as `user variables` in the template.

**Comment by tas50** [comment]
Feel free to PR this. If you want to look at adding that additional validation to the Rake task that runs for each build it would be even better.

**Comment by dragon788** [comment]
I opened an MR for this (and a couple other things) but after looking at the `rake validate` task it appears it should be catching any blatantly invalid templates.

If I get some more time I'm going to try running some negative test cases of passing an empty `disk_size` user variable or similar things to see if `packer validate` can catch those or if we'd need to try and scan for `{{ user `some_var` }}` and check if there was a default set in the `variables:` block so that actually trying to build the template succeeds if a user doesn't pass any overrides.
