### ISSUE TITLE
bento/centos-7.7 turns out to be 7.8

### ISSUE THREAD

**Issue by ian28223** [chef/bento#1303]
# Describe the problem
I spun up a box using `bento/centos-7.7` and found it spun up 7.8 instead.

```
box 'bento/centos-7.7' (v202005.12.0) for provider: virtualbox
```

```
[root@centos77 vagrant]# cat /etc/*release
CentOS Linux release 7.8.2003 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.8.2003 (Core)
CentOS Linux release 7.8.2003 (Core)
```

## Stacktrace
na
</details>

**Comment by tas50** [comment]
It's been renamed to 7.8 now. Thanks for the report

**Comment by ian28223** [comment]
I believe you missed the point. If I needed a CentOS 7.8 I would use `bento/centos-7.8`; below are working as expected:

- `bento/centos-7.8` -  spins up a Centos 7.8
- `bento/centos-7.6` -  spins up a Centos 7.6
- `bento/centos-7.5` -  spins up a Centos 7.5
- `bento/centos-7.4` - spins up a Centos 7.4
- `bento/centos-7.3` yes spins up a Centos 7.3
- and so on.

Only `bento/centos-7.7` is not spinning up the appropriate CentOS version.

**Comment by SiqingYu** [comment]
The latest CentOS 7.7 box, as of today, is actually 7.8.
https://app.vagrantup.com/bento/boxes/centos-7.7
