### ISSUE TITLE
Hyper-V Provider : Chef-solo provisioning failing for windows VM's

### ISSUE THREAD

**Issue by kishore4171** [chef/bento#1304]
Chef-solo provisioning for Windows VM's (tried Windows 10 and Windows 2012r2)

Hi, i am trying to build windows box image using "packer build windows10.json" . Also tried Windows 2012r2.json.

But the command is failing to provision the chef-solo on the target image eventually unable to create image box.

**Output below:**

PS D:\DevOps_2019\Packer_region\bento\packer_templates\windows> packer build .\windows-2012r2.json
hyperv-iso: output will be in this color.
parallels-iso: output will be in this color.
qemu: output will be in this color.
virtualbox-iso: output will be in this color.
vmware-iso: output will be in this color.

==> hyperv-iso: Trying http://download.microsoft.com/download/6/2/A/62A76ABB-9990-4EFC-A4FE-C7D698DAEB96/9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.ISO?checksum=849734f37346385dac2c101e4aacba4626bb141c
==> hyperv-iso: http://download.microsoft.com/download/6/2/A/62A76ABB-9990-4EFC-A4FE-C7D698DAEB96/9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.ISO?checksum=849734f37346385dac2c101e4aacba4626bb141c => D:\DevOps_2019\Packer_region\bento\packer_templates\windows\packer_cache\7d3af0c83aa3a016b515b190664644f7abbda784.iso
==> hyperv-iso: Creating floppy disk...
    hyperv-iso: Copying files flatly from floppy_files
    hyperv-iso: Copying file: D:\DevOps_2019\Packer_region\bento\packer_templates\windows/answer_files/2012_r2/Autounattend.xml
    hyperv-iso: Done copying files from floppy_files
    hyperv-iso: Collecting paths from floppy_dirs
    hyperv-iso: Resulting paths from floppy_dirs : []
    hyperv-iso: Done copying paths from floppy_dirs
==> hyperv-iso: Creating switch 'packer-hyperv-iso' if required...
==> hyperv-iso:     switch 'packer-hyperv-iso' already exists. Will not delete on cleanup...
==> hyperv-iso: Creating virtual machine...
==> hyperv-iso: Enabling Integration Service...
==> hyperv-iso: Setting boot drive to os dvd drive D:\DevOps_2019\Packer_region\bento\packer_templates\windows\packer_cache\7d3af0c83aa3a016b515b190664644f7abbda784.iso ...
==> hyperv-iso: Mounting os dvd drive D:\DevOps_2019\Packer_region\bento\packer_templates\windows\packer_cache\7d3af0c83aa3a016b515b190664644f7abbda784.iso ...
==> hyperv-iso: Mounting floppy drive...                                                                                                                                    ==> hyperv-iso: Skipping mounting Integration Services Setup Disk...                                                                                                        ==> hyperv-iso: Mounting secondary DVD images...                                                                                                                            ==> hyperv-iso: Configuring vlan...                                                                                                                                         ==> hyperv-iso: Determine Host IP for HyperV machine...                                                                                                                     ==> hyperv-iso: Host IP for the HyperV machine: 169.254.188.179
==> hyperv-iso: Starting the virtual machine...
==> hyperv-iso: Waiting 10s for boot...
==> hyperv-iso: Typing the boot command...
==> hyperv-iso: Waiting for WinRM to become available...
==> hyperv-iso: #< CLIXML
    hyperv-iso: WinRM connected.
==> hyperv-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">2</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> hyperv-iso: Connected to WinRM!
==> hyperv-iso: Provisioning with chef-solo
    **hyperv-iso: Installing Chef...
==> hyperv-iso: iwr : The remote name could not be resolved: 'omnitruck.chef.io'
==> hyperv-iso: At line:1 char:5
==> hyperv-iso: + . { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; Install-Project
==> hyperv-iso: +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> hyperv-iso:     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt
==> hyperv-iso:    pWebRequest) [Invoke-WebRequest], WebException
==> hyperv-iso:     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe
==> hyperv-iso:    ll.Commands.InvokeWebRequestCommand
==> hyperv-iso:
==> hyperv-iso: Install-Project : The term 'Install-Project' is not recognized as the name of
==> hyperv-iso: a cmdlet, function, script file, or operable program. Check the spelling of
==> hyperv-iso: the name, or if a path was included, verify that the path is correct and try
==> hyperv-iso: again.
==> hyperv-iso: At line:1 char:62
==> hyperv-iso: + . { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; Install-Project
==> hyperv-iso: +                                                              ~~~~~~~~~~~~~~~
==> hyperv-iso:     + CategoryInfo          : ObjectNotFound: (Install-Project:String) [], Com
==> hyperv-iso:    mandNotFoundException
==> hyperv-iso:     + FullyQualifiedErrorId : CommandNotFoundException**
==> hyperv-iso:
==> hyperv-iso: Provisioning step had errors: Running the cleanup provisioner, if present...
==> hyperv-iso: Cleanup floppy drive...
==> hyperv-iso: Clean up os dvd drive...
==> hyperv-iso: Unregistering and deleting virtual machine...
==> hyperv-iso: Deleting output directory...
==> hyperv-iso: Deleting build directory...
Build 'hyperv-iso' errored: Error installing Chef: Install script exited with non-zero exit status 1

==> Some builds didn't complete successfully and had errors:
--> parallels-iso: Failed creating Parallels driver: Parallels builder works only on "darwin" platform!
--> qemu: Failed creating Qemu driver: exec: "qemu-system-x86_64": executable file not found in %PATH%
--> vmware-iso: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
from each driver are shown below. Please fix at least one driver
to continue:
* VMware application not found:
* VMware application not found:
* VMware application not found:
* VMware application not found:

--> virtualbox-iso: Output directory exists: ../../builds/packer-windows-2012r2-standard-virtualbox

Use the force flag to delete it prior to building.
--> hyperv-iso: Error installing Chef: Install script exited with non-zero exit status 1

==> Builds finished but no artifacts were created.

**Comment by Stromweld** [comment]
Closing this issue due to age. Please feel free to re-open or submit a new issue if the problem still exists with the latest version of the bento code.
