### ISSUE TITLE
Save bandwidth by using minimal DVDs for CentOS

### ISSUE THREAD

**Issue by mkesper** [chef/bento#1308]
### Describe the Enhancement:
Use minimal DVDs (<2GB) instead of full DVDs (8GB for CentOS8) to save bandwidth and time to download

### Describe the Need:
Everybody building CentOS boxes would save space on hard drives, initial download time, and bandwidth from CentOS mirrors

### Current Alternative
Manually edit the templates

### Can We Help You Implement This?:
PR is in progress.

**Comment by tas50** [comment]
Fix merged. Thanks for the report

**Comment by mkesper** [comment]
Thank you for taking care.
