### ISSUE TITLE
CentOS 7 build fails to install VirtualBox Guest Additions

### ISSUE THREAD

**Issue by mgruner** [chef/bento#1310]
# Version:

3f7e9b56acb59130712c2f7f7497d72a36b75523

# Environment:

MacOS 10.15.7

# Scenario:

I'm trying to run the build for VirtualBox and CentOS 7. It does build, but due to missing VirtualBox Guest Additions, vagrant refuses to start the generated box.

# Steps to Reproduce:

Run the CentOS 7 build for VirtualBox.

# Expected Result:

Fully working box, with installed VirtualBox guest additions.

# Actual Result:

```
bento/packer_templates/centos/../_common/virtualbox.sh
==> virtualbox-iso: + HOME_DIR=/home/vagrant
==> virtualbox-iso: + case "$PACKER_BUILDER_TYPE" in
==> virtualbox-iso: ++ cat /home/vagrant/.vbox_version
==> virtualbox-iso: + VER=6.1.14
==> virtualbox-iso: + ISO=VBoxGuestAdditions_6.1.14.iso
==> virtualbox-iso: + mkdir -p /tmp/vbox
==> virtualbox-iso: + mount -o loop /home/vagrant/VBoxGuestAdditions_6.1.14.iso /tmp/vbox
==> virtualbox-iso: mount: /dev/loop0 is write-protected, mounting read-only
==> virtualbox-iso: + sh /tmp/vbox/VBoxLinuxAdditions.run
    virtualbox-iso: Verifying archive integrity... All good.
    virtualbox-iso: Uncompressing VirtualBox 6.1.14 Guest Additions for Linux........
==> virtualbox-iso: bzip2 not found.  Please install: bzip2 tar; and try again.
==> virtualbox-iso: + echo 'VBoxLinuxAdditions.run exited 1 and is suppressed.' 'For more read https://www.virtualbox.org/ticket/12479'
==> virtualbox-iso: + umount /tmp/vbox
    virtualbox-iso: VBoxLinuxAdditions.run exited 1 and is suppressed. For more read https://www.virtualbox.org/ticket/12479
==> virtualbox-iso: + rm -rf /tmp/vbox
==> virtualbox-iso: + rm -f /home/vagrant/VBoxGuestAdditions_6.1.14.iso
```

# Solution

As indicated by the output, it seems that `bzip2` and possibly `tar` have to be installed before running virtualbox.sh.

**Comment by mgruner** [comment]
`packer_templates/centos/http/7/ks.cfg` does list bzip2 as package to be installed, but not tar.

**Comment by mgruner** [comment]
Adding `tar` to that same list does not seem to solve the problem.

**Comment by tas50** [comment]
I ran into a similar issue today trying to build vbox images. I'll see what I can do to resolve this one. We're missing some sort of package dependency.

**Comment by tas50** [comment]
I fixed this one with a lot of hammering in master. We now install the full guest additions. I may actually switch this to just use the open vm tools since that's simpler and smaller, but this works for now.
