### ISSUE TITLE
CentOS 8 build fails early

### ISSUE THREAD

**Issue by mgruner** [chef/bento#1311]
# Version:

3f7e9b56acb59130712c2f7f7497d72a36b75523

# Environment:

MacOS 10.15.7

# Scenario:

Run the CentOS 8 build successfully. Instead, it hangs asking a question.

# Steps to Reproduce:

Run the CentOS 8 build.

# Expected Result:

Successful CentOS 8 build.

# Actual Result:

Hangs asking the question shown on the screenshot. This will trigger a packer timeout after a long time.

![Bildschirmfoto 2020-10-05 um 10 05 08](https://user-images.githubusercontent.com/211281/95054742-a0873580-06f2-11eb-96a4-61a5c665d648.png)

**Comment by davidjb** [comment]
Seeing the same issue; same environment when building only the `virtualbox-iso` and it happens each time. Choosing option 4 (Quit) sees the VM reboot and continue loading up until the login prompt.  Packer hung, waiting for the SSH server to come up, until I killed it.  

`authconfig` seems to be deprecated in el8 -- there's `authselect-compat` for backwards compatibility but I see that pykickstart still has the command as being available in EL8 (https://github.com/pykickstart/pykickstart/blob/42fec5944a46619f9197271877b68a4f0ba86594/pykickstart/handlers/rhel8.py#L31).  That's about as far as I go - I'm not familiar with what's calling what at this point.

**Comment by tas50** [comment]
I went through today and built all the images. I was able to build CentOS 8 on vbox, but not on parallels or vmware. I'm going to dig into this one to see what the issue is. Thanks for the report.

**Comment by davidjb** [comment]
@tas50 I'm still seeing the same issue with vbox; using the current `master` branch at https://github.com/chef/bento/commit/9ae6819e4669d71041f59e7728590e10c54a8c5b and vbox 6.1.14 r140239 (latest, or so the updater tells me despite 6.1.16 being out for a few days)

**Comment by tas50** [comment]
It turns out the authconfig kickstart directive is deprecated in RHEL 8 and not really necessary. I've removed that which seems to resolve the build failures here.
