### ISSUE TITLE
Update for bento/amazonlinux-2

### ISSUE THREAD

**Issue by mariadb-JeffBachtel** [chef/bento#1313]
### Describe the Enhancement:
There is a new AL2 VDI release 2020-09-17, it would be nice if there was a new bento box for it

### Current Alternative
`bento/amazonlinux-2` is available, just older (10mo old build)

### Can We Help You Implement This?:
vagrant box uploads have to be done by Chef employees

**Comment by tas50** [comment]
New box is up. Thanks for the reminder @mariadb-JeffBachtel
