### ISSUE TITLE
Errors on packer build for windows10.json

### ISSUE THREAD

**Issue by bax99** [chef/bento#1315]
# Version:

[Version of the project installed]

# Environment:

[Details about the environment such as the Operating System, cookbook details, etc...]
VirtualBox-iso

# Scenario:
[What you are trying to achieve and you can't?]
Some errors occurred  while proceeding packer build with Windows10.json

# Steps to Reproduce:

[If you are filing an issue what are the things we need to do in order to repro your problem?]
Good day,

I am using your packer_templates Windows10 that I tuned a little bit
[Windows10_631-2.json.txt](https://github.com/chef/bento/files/5384036/Windows10_631-2.json.txt)

When building I get the following errors:
[Packer_error_windows10.txt](https://github.com/chef/bento/files/5384042/Packer_error_windows10.txt)

- Error on Line 297
- Error on line 1348
- Error on line 1364
- Error on line 1366
- What does it mean no artifact created on line 1373?

As I am pretty new to Packer and chef-solo, could you help me understand those errors and help me sort them out.

Regards and thanks for the job done

# Expected Result:

[What are you expecting to happen as the consequence of above reproduction steps?]

# Actual Result:

[What actually happens after the reproduction steps?]

**Comment by tas50** [comment]
This looks like you just don't have permissions to write to the directory where it's trying to save the box.
