### ISSUE TITLE
Hyper-v with CentOS not started

### ISSUE THREAD

**Issue by Tomelin** [chef/bento#1320]
Hi,

I want to build CentOS7 in Hyper-v, but it is returning the following error:

![image](https://user-images.githubusercontent.com/7714663/97718273-8566d600-1aa4-11eb-8fc5-fa1cefb7f296.png)

![image](https://user-images.githubusercontent.com/7714663/97718299-8d267a80-1aa4-11eb-97d9-98bd6a26b9be.png)

I am using the template ' centos-7.8-x86_64.json' to create my image

**Comment by Stromweld** [comment]
Closing this issue due to age. Please feel free to re-open or submit a new issue if the problem still exists with the latest version of the bento code.
