### ISSUE TITLE
Virtualbox.sh --> missing packages

### ISSUE THREAD

**Issue by bax99** [chef/bento#1324]
### Describe the Enhancement:

In virtualbox.sh under _common there are 2 packages missing

### Describe the Need:

This line

    elif [ -f "/usr/bin/zypper" ]; then
        zypper install -y perl cpp gcc make bzip2 tar kernel-default-devel
    fi

is not enough, you should add:

    elif [ -f "/usr/bin/zypper" ]; then
        zypper install -y perl cpp gcc make bzip2 tar kernel-default-devel virtualbox-guest-tools virtualbox-guest-x11
    fi

**Comment by tas50** [comment]
In common we're assuming that the guest tools get installed from the ISO on the system so these packages shouldn't be installed.

**Comment by bax99** [comment]
They are as packages in my autoinst.xml

    <packages config:type="list">
      <package>virtualbox-guest-x11</package>
      <package>virtualbox-guest-tools</package>
     <package>virtualbox-kmp-default</package>
      <package>openssh</package>

But for an unknown reason, it does not work without changing in virtualbox.sh

**Comment by tas50** [comment]
I don't think the proposed change here is actually correct. We're trying to provide all the necessary libraries to run the official scripts from Oracle. If you install the Virtualbox packages from the OS then you already have all the tools. You can't / shouldn't do both of those things. If there's a dep missing please let me know, but we want to use the official files from the latest hypervisor vs. older distro packages.
