### ISSUE TITLE
 setting disk size doesn't change the root volume size for centos 7.8

### ISSUE THREAD

**Issue by bayeslearner** [chef/bento#1325]
# Describe the problem

I would like to create a box with larger "/" volume.   I changed the disk_size param,  somehow "autopart" creates the same 50G 
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0  100G  0 disk
├─sda1   8:1    0    1G  0 part /boot
├─sda2   8:2    0    2G  0 part [SWAP]
└─sda3   8:3    0   50G  0 part /

## Stacktrace

<details><summary>  </summary>
```
```
</details>

**Comment by b00ga** [comment]
Unfortunately this is by-design from kickstart. If you use the autopart statement and the disk is greater than 50GB, then kickstart will make root 50GB and put the remainder in home. You can specify not to create home, but that doesn’t grow root (will still be 50GB).

You either need to craft custom partition table (which you can specify to fill remaining disk space) or at $dayjob, I added a post install script. This script parses the Free PE from vgdisplay, then uses luxe tend to grow root by that much. After that, you add an xfs_growfs.

Scroll down the docs to the autopart statement for more info:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/installation_guide/sect-kickstart-syntax

**Comment by bayeslearner** [comment]
The version in master branch disabled LVM.   The change was made very recently.  I wonder why.

autopart --nohome --nolvm

I don't mind 50GB as long as it is a LV, so I can just attach another virtual disk to expand it.

**Comment by Stromweld** [comment]
Closing this issue due to age. Please feel free to re-open or submit a new issue if the problem still exists with the latest version of the bento code.
