### ISSUE TITLE
Feature Request: Produce aarch64 boxes

### ISSUE THREAD

**Issue by jakauppila** [chef/bento#1334]
### Describe the Enhancement:
It would be great if aarch64 boxes could be produced for the distros that support it.

### Describe the Need:
We are currently in the process of moving our Java workloads from Windows to Linux on AWS; we'd love to make the shift to Graviton2 instances but need a test-bed to run against.

### Can We Help You Implement This?:
What all would be needed to implement? New Packer jsons targeting the correct images?

**Comment by Stromweld** [comment]
This is currently a work in progress with the latest update to HCL2 of the packer code. Please feel free to test and submit a PR of any boxes you are able to get working. The foundation has been set and mostly tweaking around boot_commands are needed to get the aarch64 boxes to build.

**Comment by Stromweld** [comment]
currently boxes for ubuntu 20.04 and 22.04 arm64 for parallels provider have been uploaded to vagrant cloud. More to come as builds are fixed.

**Comment by Stromweld** [comment]
Work is ongoing. Any help would be greatly appreciated. Intel/arm64 builders for each provider have been created for testing builds now. Please feel free to checkout latest code and submit any PR fixes for arm64 boxes.

**Comment by damacus** [comment]
Yeah, I'm definitely going to look into this. I've got all the Ubuntu images building successfully, but CentOS doesn't seem to want to boot right now.

**Comment by claviola** [comment]
CentOS might be tricky due to kernel page sizes: see https://news.ycombinator.com/item?id=27513209 et al.
AFAIK AlmaLinux 9 should work fine. It'd be great to have at least one RPM based aarch64 OS so I could test out some stuff on an ARM Mac.

**Comment by claviola** [comment]
For what it's worth, I can confirm that AlmaLinux 9.1 aarch64 installs just fine on Parallels 18.1.1. I've used this ISO:
https://eu.edge.kernel.org/almalinux/9.1/isos/aarch64/AlmaLinux-9.1-aarch64-minimal.iso
