### ISSUE TITLE
bento/freebsd-11.x-i386 vagrant boxes for virtualbox do not successfully boot

### ISSUE THREAD

**Issue by ThomasWaldmann** [chef/bento#1338]
I tried the 11.2, 11.3 and 11.4 32bit boxes, none of them worked for me.

11.2: doesn't support the provider i requested, which is virtualbox. but the search results on vagrantup showed virtualbox support, so there is some inconsistency.

11.3 and 11.4: start booting, but vagrant times out before doing the ssh key stuff / rsync.

## Software Version

vagrant 2.2.9, virtualbox 6.1.18 on ubuntu 20.04 with all updates

## Replication Case

Just try to boot / rsync / provision it.

**Comment by ThomasWaldmann** [comment]
Side note: `bento/freebsd-11.4` (amd64) boots successfully.

**Comment by Stromweld** [comment]
closing this due to age and latest releases of the bento code we have dropped support for i386 machines.
