### ISSUE TITLE
Problem installing SLES 15 SP1

### ISSUE THREAD

**Issue by picoroma** [chef/bento#1340]
I'm having problem installing SLES 15 SP1 on virtualbox or VMware.
After the starting of installation I have an error (see attached picture) regarding the CDROM.
**ERROR**
**FAILED to ADD product "sle-module-basesystem-release" from dvd:///?devices=/dev/sr0**
![Screenshot_151](https://user-images.githubusercontent.com/23618664/109633639-99047500-7b48-11eb-9543-56c82f365279.jpg)

Is this related to something wrong in autoyast.xml file or what?
THX
P.

**Comment by Stromweld** [comment]
closing this due to age. please test with the latest release of the bento packer code and re-open or submit a new issue if the problem still exists.
