### ISSUE TITLE
CentOS Stream build failing

### ISSUE THREAD

**Issue by elreydetoda** [chef/bento#1341]
# Version:

lastest master: 6a1a2ed99928fa8bc2334ef02ab7cc75a87154c0

# Environment:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

$ vboxmanage --version
6.1.16_Ubuntur140961

$ packer --version
1.7.0

$ uname -srvmo 
Linux 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 GNU/Linux
```

# Scenario:

Trying to build the [CentOS Stream](https://github.com/chef/bento/blob/6a1a2ed99928fa8bc2334ef02ab7cc75a87154c0/packer_templates/centos/centos-stream-8-x86_64.json) packer build for virtualbox-iso.

# Steps to Reproduce:

1) clone repo
2) `cd bento/packer_templates/centos/`
3) `packer build -only=virtualbox-iso centos-stream-8-x86_64.json`

# Expected Result:
Successful build and vagrant box image created

# Actual Result:

Fails on Virtualbox Guest additions install ( specifically in the shell script [`modinfo vboxsf`](https://github.com/chef/bento/blob/6a1a2ed99928fa8bc2334ef02ab7cc75a87154c0/packer_templates/_common/virtualbox.sh#L31) ), because it fails to install the guest additions.

Here is a picture of me running the build command inside the box before it destroys the box ( I added `-on-error=ask` to the packer build command ).

![image](https://user-images.githubusercontent.com/10230166/109745729-4ce61e80-7ba2-11eb-8b63-e3ed568a533c.png)

Here is the `/var/log/vboxadd-setup.log` that I uploaded from the machine: https://pastebin.com/GGEQcGJP

Here is the full build log from packer's build: [packer_build.log](https://github.com/chef/bento/files/6073419/packer_build.log)

# Extra Info

I don't 100% know what is going on ( not really familiar with RHEL based distros ), but it seems like Vbox Guest additions doesn't like the kernel that is showing up. Which from the log file seems to be `4.18.0-277.el8.x86_64`.

Thanks you for the amazing project and let me know if there is any way I could help :grin:

**Comment by Stromweld** [comment]
Closing this issue due to age. Please feel free to re-open or submit a new issue if the problem still exists with the latest version of the bento code.
