### ISSUE TITLE
FreeBSD-13.0-RELEASE is available

### ISSUE THREAD

**Issue by myii** [chef/bento#1347]
### Describe the Enhancement:

Build box based on [freebsd/FreeBSD-13.0-RELEASE](https://app.vagrantup.com/freebsd/boxes/FreeBSD-13.0-RELEASE).

### Describe the Need:

Builds of `11.4` and `12.2` are already being provided -- continuing this series.

### Current Alternative

N/A.

### Can We Help You Implement This?:

If there's anything particular that needs to be considered when building this box (different to when the last box was introduced).  One potential issue is whether the [`freebsd-11`-based `installerconfig`](https://github.com/chef/bento/blob/51c29fb15d5b4ff2aebe5fdbdd3ba522f6ccc9ed/packer_templates/freebsd/http/freebsd-11/installerconfig) should still be used.

**Comment by tas50** [comment]
13.0 has been merged to master here
