### ISSUE TITLE
FreeBSD 13.0 builds fail on Parallels

### ISSUE THREAD

**Issue by tas50** [chef/bento#1350]
On master the FreeBSD 13 parallels builds fail with the following error:

<img width="752" alt="Screen Shot 2021-04-18 at 7 11 16 PM" src="https://user-images.githubusercontent.com/1015200/115173822-f3b44a80-a07c-11eb-897f-e47a44cb038a.png">

**Comment by Stromweld** [comment]
closing this due to age. Please feel free to test with the latest release of bento packer code and re-open or submit a new PR if the problem still persists.
