### ISSUE TITLE
Please rebuild FreeBSD 13 box to include patch for virtualbox-ose-additions-nox11

### ISSUE THREAD

**Issue by lwhsu** [chef/bento#1352]
https://app.vagrantup.com/bento/boxes/freebsd-13.0

v202104.19.0  contains virtualbox-ose-additions-nox11-6.1.18 but this patch is needed for letting shared folder work:

https://cgit.freebsd.org/ports/commit/?id=8a311de0cb804d8b135413884b4fb336d287ad5a

It is included in 6.1.18_1 and 6.1.20, the pre-built package is available in the official pkg sites so a rebuilt of image should work.

Thanks.

**Comment by Stromweld** [comment]
closing this issue due to age. Please test latest release of freebsd-13 and re-open this issue or submit a new one if the problem still exists.
