### ISSUE TITLE
openSUSE 15.3 Support

### ISSUE THREAD

**Issue by HolgerHees** [chef/bento#1362]
is there any plan to have a openSUSE 15.3 image?

**Comment by tas50** [comment]
I updated the definition, but it's currently failing to build.

**Comment by txt-file** [comment]
seems fixed to me https://app.vagrantup.com/bento/boxes/opensuse-leap-15.3

am I mistaken?

**Comment by hunleyd** [comment]
you're correct @txt-file . i was able to successfully build a leap 15.3 box myself from the repo yesterday.

**Comment by tas50** [comment]
Yep I managed to get it working
