### ISSUE TITLE
Guest additions are not running in ubuntu-20.04

### ISSUE THREAD

**Issue by isurugiu** [chef/bento#1363]
# Version:
https://app.vagrantup.com/bento/boxes/ubuntu-20.04/versions/202107.07.0

# Environment:
Windows 10, OracleVM 6.1.22

# Scenario:

I am trying to fully automate a local deployment, however vagrant up is failing at mounting vbox shared folders

# Steps to Reproduce:

run vagrant up
# Expected Result:

Vagrant is able to mount the vbox shared drives. Solution that worked can be found at https://github.com/chef/bento/issues/1185#issuecomment-611479227
# Actual Result:

Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000,_netdev vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: Invalid argument

**Comment by isurugiu** [comment]
IMAGE_NAME = "bento/ubuntu-20.04"
BOX_VERSION = "202107.07.0"
K8S_VERSION = "1.21.2"
N = 3

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vagrant.plugins = ["vagrant-disksize", "vagrant-vbguest"]
    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 4
    end

    config.vm.define "k8s-master-#{K8S_VERSION}" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.box_version = BOX_VERSION
        master.vm.network "public_network", ip: "192.168.1.200", bridge: "Realtek PCIe 2.5GbE Family Controller"
        master.vm.hostname = "k8s-master-#{K8S_VERSION}"
        master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "kubernetes-setup/master-playbook.yml"
            ansible.verbose = true
            ansible.extra_vars = {
                node_ip: "192.168.1.200",
                node_hostname: "k8s-master-#{K8S_VERSION}"
            }
        end
    end

    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 4
    end

    (1..N).each do |i|
        config.vm.define "k8s-node-#{K8S_VERSION}-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.box_version = BOX_VERSION
            node.vm.network "public_network", ip: "192.168.1.#{i + 200}", bridge: "Realtek PCIe 2.5GbE Family Controller"
            node.vm.hostname = "node-#{K8S_VERSION}-#{i}"
            node.vm.provision "ansible_local" do |ansible|
                ansible.playbook = "kubernetes-setup/node-playbook.yml"
                ansible.verbose = true
                ansible.extra_vars = {
                    node_ip: "192.168.1.#{i + 200}",
                    node_hostname: "node-#{K8S_VERSION}-#{i}"
                }
            end
        end
    end
end

**Comment by isurugiu** [comment]
Here is my error:

```
PS Z:\code\k8swincluster> vagrant up
Bringing machine 'k8s-master-1.21.2' up with 'virtualbox' provider...
Bringing machine 'k8s-node-1.21.2-1' up with 'virtualbox' provider...
Bringing machine 'k8s-node-1.21.2-2' up with 'virtualbox' provider...
Bringing machine 'k8s-node-1.21.2-3' up with 'virtualbox' provider...
==> k8s-master-1.21.2: Importing base box 'bento/ubuntu-20.04'...
==> k8s-master-1.21.2: Matching MAC address for NAT networking...
==> k8s-master-1.21.2: Checking if box 'bento/ubuntu-20.04' version '202107.07.0' is up to date...
==> k8s-master-1.21.2: Setting the name of the VM: k8swincluster_k8s-master-1212_1626017469532_73655
==> k8s-master-1.21.2: Clearing any previously set network interfaces...
==> k8s-master-1.21.2: Preparing network interfaces based on configuration...
    k8s-master-1.21.2: Adapter 2: bridged
    k8s-master-1.21.2: 22 (guest) => 2222 (host) (adapter 1)
==> k8s-master-1.21.2: Running 'pre-boot' VM customizations...
==> k8s-master-1.21.2: Booting VM...
==> k8s-master-1.21.2: Waiting for machine to boot. This may take a few minutes...
    k8s-master-1.21.2: SSH address: 127.0.0.1:2222
    k8s-master-1.21.2: SSH username: vagrant
    k8s-master-1.21.2: SSH auth method: private key
==> k8s-master-1.21.2: Machine booted and ready!
[k8s-master-1.21.2] GuestAdditions seems to be installed (6.1.22) correctly, but not running.
update-initramfs: Generating /boot/initrd.img-5.4.0-77-generic
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Kernel headers not found for target kernel
5.4.0-77-generic. Please install them and execute
  /sbin/rcvboxadd setup
VirtualBox Guest Additions: Running kernel modules will not be replaced until
the system is restarted
Restarting VM to apply changes...
==> k8s-master-1.21.2: Attempting graceful shutdown of VM...
==> k8s-master-1.21.2: Booting VM...
==> k8s-master-1.21.2: Waiting for machine to boot. This may take a few minutes...
==> k8s-master-1.21.2: Machine booted and ready!
==> k8s-master-1.21.2: Checking for guest additions in VM...
==> k8s-master-1.21.2: Setting hostname...
==> k8s-master-1.21.2: Configuring and enabling network interfaces...
==> k8s-master-1.21.2: Mounting shared folders...
    k8s-master-1.21.2: /vagrant => Z:/code/k8swincluster
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000,_netdev vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: Invalid argument
```

**Comment by tas50** [comment]
@isurugiu any chance you can confirm if this still happens on the latest boxes. I've rebuilt them several times since this initial report.

**Comment by isurugiu** [comment]
> @isurugiu any chance you can confirm if this still happens on the latest boxes. I've rebuilt them several times since this initial report.

Oh yeah, it's working for some while now, feel free to close the call
