### ISSUE TITLE
Packer/Vbox bug workaround... with guest_additions_mode attach Virtualbox can't boot Windows on macOS

### ISSUE THREAD

**Issue by dragon788** [chef/bento#1370]
# Version:

Latest `main`

# Environment:

macOS 11.5.1 host
Virtualbox 6.1.26
Packer 1.7.4

# Scenario:

Trying to create a Windows 10 VM fails with "FATAL: Could not read from the boot medium! System halted." When looking at the hardware configuration in the Virtualbox UI, it appears the VboxAdditions ISO gets added with a lower ID than the Windows ISO which results in a higher "boot priority" in the DVD category, and so Virtualbox tries to boot from a non-OS ISO and fails, hanging the build.

Switching the type to `upload` allows it to proceed but takes FOREVER and I've had it intermittently fail for no apparent reason.

I wondered if perhaps setting the tools interface to IDE could work around the issue, or enabling EFI boot instead. I tried both, and it turns out the "fix" is to set the iso_interface to ide and leave the guest_additions_interface as the default (which the docs say is ide, but actually appears to be) sata, because IDE apparently gets priority over sata in the boot order evaluation so the Windows ISO boots successfully. This fix also allows EFI to boot properly, where without it you got a slightly less scary EFI prompt instead of the FATAL error message, but if you watched closely, it did actually prompt to "press any key to boot from DVD" where for non-EFI aka BIOS mode you never get that prompt.

# Functional workaround
iso_interface = ide
guest_additions_interface = sata

# Steps to Reproduce:

packer build --only=virtualbox-iso windows-10.json

# Expected Result:

Windows installer kicks off.

# Actual Result:

Virtualbox fails to boot Windows unless the interfaces are switched around per the above workaround.

The order of adding the ISOs is a Packer issue, while the inability to order the devices within a category (DVD/disk/floppy/network) is a Virtualbox issue.

https://www.virtualbox.org/ticket/6979
https://superuser.com/a/1634735

References:

https://www.packer.io/docs/builders/virtualbox/iso#iso_interface
https://www.packer.io/docs/builders/virtualbox/iso#guest_additions_interface
https://www.packer.io/docs/builders/virtualbox/iso#creating-an-efi-enabled-vm

**Comment by tas50** [comment]
So fun story here. I went to build the Bento images today. Hit this error. Googled it. Found this issue. 🤦‍♂️

**Comment by tas50** [comment]
I added this to all the windows images. It would be great if packer resolved the bug, but we're not blocked anymore.
