### ISSUE TITLE
Debian 11 Bullseye images not found on Vagrant Cloud

### ISSUE THREAD

**Issue by wimsymons** [chef/bento#1371]
@tas50? I'd also like this to be available on Vagrant Cloud :slightly_smiling_face:

_Originally posted by @ashkulz in https://github.com/chef/bento/issues/1367#issuecomment-906162389_

https://app.vagrantup.com/bento/boxes/debian-11 does not exist ...

**Comment by ashkulz** [comment]
See the [explanation by tas50](https://github.com/chef/bento/pull/1367#issuecomment-907332327). I've already [built and pushed it to my account](https://app.vagrantup.com/ashkulz/boxes/debian-11), you can do the same...

**Comment by wimsymons** [comment]
@ashkulz thanks for your comment.

I won't close this ticket yet. I was hoping somebody could push the Debian 11 images to https://app.vagrantup.com/bento.

Can Github Actions do this on push to master?
This would remove the constraint that @tas50 laptop is required to publish new/updated images.

Cfr https://github.com/marketplace/actions/packer-github-actions

**Comment by ashkulz** [comment]
Is nested KVM enabled on GitHub Actions? Either way, I'm pretty sure only virtualbox would be easily installable there -- not so sure about parallels or vmware_desktop.

I too would love to have an "official" image :man_shrugging:

**Comment by wimsymons** [comment]
Not a clue @ashkulz ... I just pointed out that there is a such a thing a Github Actions for packer. Something to try I guess. But wouldn't it be great if you can automate a part of the image building/publication?

**Comment by ashkulz** [comment]
For sure :+1:

BTW, I just noticed that [official Debian 11 image is now available](https://app.vagrantup.com/debian/boxes/bullseye64) -- it worked as a drop-in replacement for `bento/debian-10` in my use case.

**Comment by wimsymons** [comment]
I can use the official Debian 11 image
