### ISSUE TITLE
VirtualBox box for debian-11.0-i386

### ISSUE THREAD

**Issue by tdietel** [chef/bento#1373]
### Describe the Enhancement:
The latest Debian 11 image for i386 (debian-11.0-i386) should also be available for VirtualBox, not only for Parallels.

### Describe the Need:
Debian 10/i386 was available for VirtualBox, and I used it to run an old software that I cannot recompile. I would like to upgrade, and it seems Debian 11/i386 already works on Parallels and I managed to build the image for VirtualBox on my laptop.

I also noticed that `apt` in debian-10.7-i386 (I know it's not the latest one) issues a warning that it changed from stable to oldstable since the release of Debian 11.

### Current Alternative
I can continue to use Debian 10. 

### Can We Help You Implement This?:
I guess it is only a line that you need to change in some file. If you point me to that file, I can file a PR.

**Comment by Stromweld** [comment]
closing this as we are no longer supporting i386 builds
