### ISSUE TITLE
Rocky Linux 8: Missing some man pages

### ISSUE THREAD

**Issue by fossilet** [chef/bento#1381]
# Version:

202110.25.0

# Environment:

macOS 11.6, VMware Fusion 12

# Scenario:

See man pages for some essential tools.

# Steps to Reproduce:

`man bash`, `man tar`, `man rpm`

# Expected Result:

See man pages.

# Actual Result:

No man pages for these tools, albeit there are more than four thousand man pages which are obscurer than the examples in `/usr/share/man`.

The man pages are actually missing on the disk:

```
rpm -ql tar | grep -v '/locale' | xargs stat >/dev/null
stat: cannot stat '/usr/share/doc/tar': No such file or directory
stat: cannot stat '/usr/share/doc/tar/AUTHORS': No such file or directory
stat: cannot stat '/usr/share/doc/tar/ChangeLog': No such file or directory
stat: cannot stat '/usr/share/doc/tar/NEWS': No such file or directory
stat: cannot stat '/usr/share/doc/tar/README': No such file or directory
stat: cannot stat '/usr/share/doc/tar/THANKS': No such file or directory
stat: cannot stat '/usr/share/info/tar.info-1.gz': No such file or directory
stat: cannot stat '/usr/share/info/tar.info-2.gz': No such file or directory
stat: cannot stat '/usr/share/info/tar.info.gz': No such file or directory
stat: cannot stat '/usr/share/man/man1/gtar.1.gz': No such file or directory
stat: cannot stat '/usr/share/man/man1/tar.1.gz': No such file or directory
```
I checked with these other Vagrant boxes:
1. `generic/rocky`
2. `centos/7`
3. `centos/8`

and a vanilla Rocky 8 DVD install, the man pages are all there.I even built Rocky 8 myself, and the result is the same as the box from Vagrant Cloud.

I am wondering if they are stripped on purpose, but I failed to find the code that strips them.

**Comment by Stromweld** [comment]
To help keep the size of the images down the manpages aren't installed by the bento project. Most if not all can be found with a simple google search.
