### ISSUE TITLE
iso_checksum_type fails on ubuntu 21.10 libvirt (only?)

### ISSUE THREAD

**Issue by peedy2495** [chef/bento#1386]
# Version:

as of today 2022-01-12 commit: 5f8d3dc18177b6ec372a2580770c5afc75e250db

# Environment:

Ubuntu 20.04.3 with Packer v1.3.4

# Scenario:

can't build libvirt image:

1. missing checksum method
... fixed:
2. wrong checksum method (refer mirror: https://releases.ubuntu.com/21.10/SHA256SUMS)

# Steps to Reproduce:

packer build -only=qemu ubuntu-21.10-amd64.json

# Expected Result:

==> Builds finished. The artifacts of successful builds are:
--> qemu: 'libvirt' provider box: ../../builds/ubuntu-21.10.libvirt.box

# Actual Result:

1 error(s) occurred:
* The iso_checksum_type must be specified.

# How to Fix:

file: bento/packer_templates/ubuntu/ubuntu-21.10-amd64.json

add to every image-type:  
"iso_checksum_type":  "{{user `iso_checksum_type`}}"

change checksum-type in variables to:  
"iso_checksum_type":  "sha256"

last but not least ... is this the reason for absent libvirt images in the official boxes repo?

**Comment by Stromweld** [comment]
This should be fixed in the latest version of the beno code. Closing this issue. Please feel free to re-open or submit a new issue if the problem still exists.
