### ISSUE TITLE
Adding support to bitnami stack boxes

### ISSUE THREAD

**Issue by mic345** [chef/bento#1387]
### Describe the Enhancement:
Is it possible to add bitnami wordpress stack to the supported stacks list?
https://bitnami.com/stack/wordpress/virtual-machine
https://app.vagrantup.com/bento

### Describe the Need:
AWS Lightsail uses bitnami as the standard stack and it would help greatly if it was available as a vagrant for testing.

![Create-an-instance-Lightsail](https://user-images.githubusercontent.com/36601023/149668884-1350627a-bd7e-483d-8bba-d566d43ea756.png)

### Current Alternative
Building a vagrant box manually.

### Can We Help You Implement This?:
We never worked with bento before, if you have a template script maybe we can create a pull request.

**Comment by Stromweld** [comment]
This isn't something that we are looking to support directly but are open to PR's. Closing this issue as will not do. Please feel free to reopen if you'd like to help contribute.
