### ISSUE TITLE
Apple M1 - Centos 7.5 and 8 and Windows 2019 support

### ISSUE THREAD

**Issue by ABrehm264** [chef/bento#1390]
### Describe the Enhancement:
I'd like to be able to download bento boxes for centos 7.5, centos 8, and Windows 2019 for VMWare

### Describe the Need:
This should be able to help any Apple silicon users

### Current Alternative
None, as far as I know.

### Can We Help You Implement This?:
Im working on this when I have time, I'm currently running into this issue, which I'm having a hard time fixing:
```
packer build --only=vmware-iso debian-11.2-amd64.json
vmware-iso: output will be in this color.

Build 'vmware-iso' errored after 95 milliseconds 415 microseconds: Couldn't find VMware tools for 'linux'! VMware often downloads these
tools on-demand. However, to do this, you need to create a fake VM
of the proper type then click the 'install tools' option in the
VMware GUI.

==> Wait completed after 95 milliseconds 700 microseconds

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Couldn't find VMware tools for 'linux'! VMware often downloads these
tools on-demand. However, to do this, you need to create a fake VM
of the proper type then click the 'install tools' option in the
VMware GUI.
```

**Comment by tas50** [comment]
If someone adds the config for the m1 builds we can build and push them. That will require the community to provide the change though.

**Comment by Stromweld** [comment]
This currently is a known issue with vmware packer plugin and vmware fusion 13. https://github.com/hashicorp/packer-plugin-vmware/issues/109

Closing this issue for now. Once the plugin is updated please feel free to test and re-open or submit a new issue if the problem exists.
