### ISSUE TITLE
almalinux-8(.5) image is corrupt

### ISSUE THREAD

**Issue by jdelker** [chef/bento#1393]
The images
bento/almalinux-8, or
bento/almalinux-8.5
started with Vagrant (in VirtualBox) show signs of corruption (Bus Errors; Segementation Fault, etc.)

To reproduce, start image and run "yum update". It results in a "Segementation Fault". 

An older image (bento/almalinux-8.3) ran without problems in the same setup.

**Comment by Stromweld** [comment]
current images are on 8.7 now.
