### ISSUE TITLE
ubuntu-20.04-amd64 build on qemu not building

### ISSUE THREAD

**Issue by jhalfmoon** [chef/bento#1394]
# Version: 
5f8d3dc 2021-12-23 (most recent commit on main branch)

# Environment:
Arch Linux
Linux laptop-name 5.16.5-arch1-1 #1 SMP PREEMPT Tue, 01 Feb 2022 21:42:50 +0000 x86_64 GNU/Linux
qemu 6.2.0-2
libvirt 1:8.0.0-2
vagrant 2.2.19-1

# Scenario:
Building a qemu-based image of ubuntu-20.04-amd64 hangs during install. The reason for this is that the keyboard sequence used to interrupt the ISO boot sequence is timed incorrectly. Setting "bootwait: "2s" in the qemu section of ubuntu-21.04-amd64.json and removing 3 of the 5 <wait> statements, will fix the issue. Also, the amount of waits in the typing sequence are way to high, but that is unrelated to the fix of this issue.

# Steps to Reproduce:
packer build -only=qemu ubuntu-20.04-amd64.json

# Expected Result:
The build finishes correctly, without error.

# Actual Result:
The installer will hang and time-out:

`==> qemu: Typing the boot command over VNC...
    qemu: Not using a NetBridge -- skipping StepWaitGuestAddress
==> qemu: Using SSH communicator to connect: 127.0.0.1
==> qemu: Waiting for SSH to become available...
==> qemu: Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
=`

**Comment by Stromweld** [comment]
Can you test with the latest release of the bento packer code? if the problem still persists feel free to open a PR to help fix the issue.

**Comment by Stromweld** [comment]
Looks like our latest code isn't building correctly for Ubuntu 20.04. Most likely the bootcommand may need updating. Any help troubleshooting and potential PR for fix would be greatly appreciated. I plan to get to it, but have a lot of builds to go through that need fixing and may take me a while.

**Comment by jhalfmoon** [comment]
I'll take a look and report back with a PR. My apologies for the late reply.

**Comment by Stromweld** [comment]
No worries appreciate the help.

**Comment by Stromweld** [comment]
PR #1487 merged fixing this issue.
