### ISSUE TITLE
CentOS Stream 8 default repos need updating

### ISSUE THREAD

**Issue by damacus** [chef/bento#1395]
# Version:

# Environment:

Running test kitchen in both Vagrant and Dokken. 

[Looks like it's a very recent change.](https://stackoverflow.com/questions/70963985/error-failed-to-download-metadata-for-repo-appstream-cannot-prepare-internal)

# Scenario:

`kitchen test *-centos-8` on Tomcat cookbook

# Steps to Reproduce:

- Checkout the automate/cookstyle branch on the Tomcat cookbook
- run kitchen test templated-service-centos-8

# Expected Result:

[What are you expecting to happen as the consequence of above reproduction steps?]

# Actual Result:

```shell
       
       Traceback (most recent call last):
         File "/usr/lib/python3.6/site-packages/dnf/repo.py", line 574, in load
           ret = self._repo.load()
         File "/usr/lib64/python3.6/site-packages/libdnf/repo.py", line 397, in load
           return _repo.Repo_load(self)
       libdnf._error.Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

## Fix:

```shell
dnf --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
```

**Comment by Stromweld** [comment]
Can you verify if this is still an issue with the currently release of bento packer code re-written for hcl2 please?

**Comment by Stromweld** [comment]
@damacus I know your a busy guy but if you could verify that one of the current builds that working fixes your issue then we can close this. Please find latest test builds here https://github.com/chef/bento/actions/runs/4328485365#artifacts

**Comment by Stromweld** [comment]
Updated CentOS-Stream-8 boxes have been uploaded to vagrant. Closing this issue as completed. Please feel free to reopen this issue if you find that the issue still persists.

**Comment by damacus** [comment]
Ah, completely missed this notification! 
Will test next week, thanks @Stromweld !
