### ISSUE TITLE
Ubuntu 21.10 VMWare Cannot connect ssh

### ISSUE THREAD

**Issue by suikast42** [chef/bento#1396]
# Version:
Packer version: 1.7.10
go1.17.6 windows amd64]
VMware® Workstation 15 Pro  15.5.7 build-17171714

[Version of the project installed]

master

[Details about the environment such as the Operating System, cookbook details, etc...]

Windw10 Pro

I can build ubuntu 20.04 without any issues. 
But if I want to build ubuntu 21.10 then:

1. Provisioning starts
2. VM do an inital boot until grub config
3. Then It hangs wtih the logging below:
`2022/02/15 08:57:27 packer.exe plugin: Searching for file 'C:/ProgramData/VMware/netmap.conf' 
2022/02/15 08:57:27 packer.exe plugin: Found file 'C:/ProgramData/VMware/netmap.conf'
2022/02/15 08:57:27 packer.exe plugin: Located networkmapper configuration file using Workstation: C:/ProgramData/VMware/netmap.conf
2022/02/15 08:57:27 packer.exe plugin: GuestIP discovered device matching nat: vmnet8
2022/02/15 08:57:27 packer.exe plugin: Lookup up IP information...
2022/02/15 08:57:27 packer.exe plugin: GuestAddress found MAC address in VMX: 00:0c:29:5b:ba:43
2022/02/15 08:57:27 packer.exe plugin: Trying DHCP leases path: C:/ProgramData/VMware/vmnetdhcp.leases
2022/02/15 08:57:27 packer.exe plugin: Unable to find an exact match for DHCP lease. Falling back to a loose match for hw address 00:0c:29:5b:ba:43
2022/02/15 08:57:27 packer.exe plugin: IP lookup failed: None of the found device(s) [vmnet8] has a DHCP lease for MAC 00:0c:29:5b:ba:43`

**Comment by suikast42** [comment]
I find the workaround: 

the problem occurs on an early stage. During  confiuration of grub. After typing "---" is the next wait to short. I increase this wait to 30s an then its orked as expected.  
```json
            "boot_command": [
                " <wait>",
                " <wait>",
                " <wait>",
                " <wait>",
                " <wait>",
                "c",
                "<wait>",
                "set gfxpayload=keep",
                "<enter><wait>",
                "linux /casper/vmlinuz quiet<wait>",
                " autoinstall<wait>",
                " ds=nocloud-net<wait>",
                "\\;s=http://<wait>",
                "{{.HTTPIP}}<wait>",
                ":{{.HTTPPort}}/<wait>",
                " ---",
                "<enter><wait>",  --  Replace with that  -->      "<enter><wait30>",
                "initrd /casper/initrd<wait>",
                "<enter><wait>",
                "boot<enter><wait>"
            ],
```

**Comment by Stromweld** [comment]
The current release of Bento code is currently building 22.10 for virtualbox. Currently there is an issue with packer-plugin-vmware for the latest release of vmware fusion 13 that until fixed we can't test for that provider. If you could test and let us know if it's working for vmware workstation that would be great.

**Comment by suikast42** [comment]
It try to build the 22.04.1 image but it hangs with the message 
`mtd device must be supplied (device name is empty)`


Packer version: 1.8.5
VMware® Workstation 15 Pro 15.5.7 build-17171714

I try this with the latest commit in bento_old_json_templates.

If I try with the main branch then I don't see the VM comming up in VMWare Worksation. 
furthermore there is a variable vmware_version  in  https://github.com/chef/bento/blob/main/packer_templates/pkr-variables.pkr.hcl. That is definied as 19. But the latest version is 17. 
The build is only running if I set this to 15.

**Comment by suikast42** [comment]
> The current release of Bento code is currently building 22.10 for virtualbox. Currently there is an issue with packer-plugin-vmware for the latest release of vmware fusion 13 that until fixed we can't test for that provider. If you could test and let us know if it's working for vmware workstation that would be great.

Ubuntu 22.10 Hangs at this point 
![image](https://user-images.githubusercontent.com/5046525/213800668-4854d5be-4c4e-4ad3-bfbd-14bbd21c6310.png)

**Comment by Stromweld** [comment]
if you add `-var "headless=false"` to your command you should be able to get a gui then. It's set to true by default. Or you can add that to the .pkrvars.hcl file to also override the default. In the main branch I had to update the boot_command to get past the cd load issue.

**Comment by suikast42** [comment]
`packer build -only="vmware-iso.vm" -var "headless=false"  -var="vmware_version=15"   -var-file="os_pkrvars/ubuntu/ubuntu-22.04-x86_64.pkrvars.hcl" ./packer_templates`

I testet now with the update branch. The 22.04 behaves the same as the latest old_json branch.
![image](https://user-images.githubusercontent.com/5046525/213809662-5f228e37-ef5b-4b0b-99b4-dbde361dce76.png)

**Comment by Stromweld** [comment]
ok thanks, If you able to figure out how to fix it and submit a PR that'd be great. Otherwise it'll be a while till the vmware plugin for fusion 13 issue is fixed and I'm able to get time to work on it. It is on our radar though and I'm working on getting hardware/licenses as well to get full build pipelines working for all 5 core providers.

**Comment by suikast42** [comment]
The windows firewall was the problem. 
I disable it and everything build with my setup from the main brach.

![image](https://user-images.githubusercontent.com/5046525/213820654-f47b27ec-f8b2-41b7-b997-fdb8fe35c370.png)

**Comment by Stromweld** [comment]
thanks for verifying

**Comment by suikast42** [comment]
Thanks for your tooling. I realy appreciate it.

**Comment by suikast42** [comment]
The boxes uploaded to vagrant cloud. 

[Ubuntu 22.04.01.LTS](https://app.vagrantup.com/suikast42/boxes/ubuntu-22.04_64)
[Ubuntu 22.10.Box](https://app.vagrantup.com/suikast42/boxes/ubuntu-22.10_64/versions/1.0.0)
