### ISSUE TITLE
Publish Windows boxes to Vagrant Cloud bento organization

### ISSUE THREAD

**Issue by decoyjoe** [chef/bento#1398]
### Describe the Enhancement:
This project contains Packer templates for Windows boxes at [packer_templates/windows](https://github.com/chef/bento/tree/main/packer_templates/windows). However these boxes are not published to the Vagrant Cloud [bento organization](https://app.vagrantup.com/bento) like the rest of the project's boxes are. As a user of Test Kitchen it would be great if I could use Windows "bento" boxes alongside the rest of the bento boxes I use in Test Kitchen.

### Current Alternative
Currently in Test Kitchen I use the Windows boxes under the [tas50 Vagrant org](https://app.vagrantup.com/tas50) which appear to be built from the templates in this repository.  However now that tas50 is no longer with Chef I'm unsure of the future of those boxes.

**Comment by tas50** [comment]
This was done for legal reasons and is unfortunately not going to change unless Microsoft changes their stance on Windows box distribution.

**Comment by floh96** [comment]
cc @nguyen-dows Are companies allowed to publish boxes to https://app.vagrantup.com/boxes/search?

**Comment by Stromweld** [comment]
Similar to what @tas50 had done, I started building and hosting my own windows boxes using the bento project templates. You can find them at https://app.vagrantup.com/stromweld, I'm also working on a current refresh of them that I hope to have out within the next few days.
