### ISSUE TITLE
Add support for Ubuntu 22.04 LTS (Jammy)

### ISSUE THREAD

**Issue by matuskosut** [chef/bento#1405]
### Describe the Enhancement:

https://app.vagrantup.com/bento/boxes/ubuntu-22.04 would be added as a basebox with the recently released Ubuntu 20.04 LTS Jammy version

### Describe the Need:

Review / adjust MR https://github.com/chef/bento/pull/1404

### Current Alternative

None

### Can We Help You Implement This?:

Reviews are welcome: https://github.com/chef/bento/pull/1404

**Comment by leegarrett** [comment]
I can confirm that this git branch successfully builds Ubuntu 22.04 boxes. Please merge and ship it.

**Comment by matuskosut** [comment]
Hi @vkarve-chef , do you know if there is anything else that needs to be done to get Ubuntu 22.04 image published here https://app.vagrantup.com/bento/boxes/ubuntu-22.04 ?

I noticed that in Actions (https://github.com/chef/bento/actions/runs/2281708388) there were only some unrelated (freebsd/centos/..) builds failing.

**Comment by magnetik** [comment]
From what I understand the actions are not responsible for generating the images (and pushing them to the vagrant boxes website). Something manual might be done by the bento team?

**Comment by ashiqueps** [comment]
Hi @matuskosut and @magnetik,

Sorry for the delay in getting the new builds on the vagrant cloud account. The process is manual and this was handled by Tim Smith previously. After he left the organization we are currently managing this repo. We are working on getting the organisation access so that we can release all the recently merged changes. I'll let you know once we ship the new boxes.

CC: @vkarve-chef

**Comment by BronsonQuick** [comment]
In the meantime, if any of you folks need a Jammy Jellyfish box for VirtualBox based on this Bento build then I've uploaded one [here](https://app.vagrantup.com/chassis/boxes/bento-ubuntu-22.04/versions/0.1.0) so I can start playing around with it for one of my open source projects until the official build is uploaded.

**Comment by kebugcheckex** [comment]
The box from Ubuntu Cloud Image site (https://cloud-images.ubuntu.com/jammy/current/) might be a temporary alternative.

**Comment by matuskosut** [comment]
> The box from Ubuntu Cloud Image site (https://cloud-images.ubuntu.com/jammy/current/) might be a temporary alternative.

I would just add that the official image is also available through vagrant cloud: https://app.vagrantup.com/ubuntu/boxes/jammy64

**Comment by ashiqueps** [comment]
Hey All,

Finally we got the access to the bento organization in the vagrant cloud. All the pending changes have been released to the bento account. 

@matuskosut, @jkugler, @ramereth, @kebugcheckex, @andretrevas, @vkarve-chef

**Comment by jkugler** [comment]
@matuskosut Good to know. However, it looks like the Ubuntu boxes only do Vagrant. No libvirt boxes to be seen. :(

**Comment by mmguero** [comment]
> @matuskosut Good to know. However, it looks like the Ubuntu boxes only do Vagrant. No libvirt boxes to be seen. :(

I assume you mean "[virtualbox](https://app.vagrantup.com/bento/boxes/ubuntu-22.04)" instead of "Vagrant" there? I don't think this project has *ever* published images for anything but virtualbox, but it's very easy to download and convert the image yourself with [vagrant-mutate](https://github.com/sciurus/vagrant-mutate)

**Comment by ramereth** [comment]
@ashiqueps it looks like the image isn't quite working for me unfortunately:

```
==> ubuntu-22.04: Waiting for machine to boot. This may take a few minutes...
    ubuntu-22.04: SSH address: 127.0.0.1:2201
    ubuntu-22.04: SSH username: vagrant
    ubuntu-22.04: SSH auth method: private key
    ubuntu-22.04: Warning: Connection reset. Retrying...
    ubuntu-22.04: Warning: Remote connection disconnect. Retrying...
    ubuntu-22.04: Warning: Connection reset. Retrying...
    ubuntu-22.04: Warning: Remote connection disconnect. Retrying...
    ubuntu-22.04: Warning: Authentication failure. Retrying...
    ubuntu-22.04: Warning: Authentication failure. Retrying...
    ubuntu-22.04: Warning: Authentication failure. Retrying...
    ubuntu-22.04: Warning: Authentication failure. Retrying...
    ubuntu-22.04: Warning: Authentication failure. Retrying...
```

**Comment by jkugler** [comment]
@mmguero  Ack...yes. Sorry, Virtualbox. Bento used to do other products. Take a look at https://app.vagrantup.com/bento/boxes/centos-6 and https://app.vagrantup.com/bento/boxes/debian-9 for example. They have VMWare and Parallels boxes as well. They didn't have a pipeline for it, so it was "best effort," but the person doing it (I forget their name) did have a setup to push boxes for other hypervisors.

It would be cool if they could build for libvirt too, as that would be very easy to automate.

**Comment by mmguero** [comment]
@jkugler fair enough, I didn't realize they automated builds for libvirt for all of their other boxes. FWIW the [jammy template](https://github.com/chef/bento/blob/main/packer_templates/ubuntu/ubuntu-22.04-amd64.json#L174) does have a build command for building a libvirt box and I've successfully done so (`packer build -only=qemu ubuntu-22.04-amd64.json`).

**Comment by caess** [comment]
@ramereth Ubuntu 22.04's sshd doesn't support `ssh-rsa` public keys by default. Since [Vagrant's public SSH key](https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub) is an `ssh-rsa` key, it can't log in.

To fix this, we need `PubkeyAcceptedAlgorithms +ssh-rsa` added to `/etc/ssh/sshd_config`. If you're building locally, you can change a provisioning script to do this (or add a new one).

**Comment by smammy** [comment]
See also: hashicorp/vagrant#12589

**Comment by matuskosut** [comment]
> @ashiqueps can you please rebuild the image with this fix mentioned above?

the changes you suggest to include would make this image different from standard ubuntu image, hence for those who use it for testing it would mean another thing to miss. Including weak ciphers would also make it worse option for testing.

Isn't it easier to just upgrade your vagrant? https://github.com/chef/bento/pull/1404#issuecomment-1113761673

**Comment by ahrenstein** [comment]
If you're using test-kitchen I'm using this workaround until new keys are added to Vagrant:

```yaml
platforms:
  - name: ubuntu-18.04
  - name: ubuntu-20.04
  - name: ubuntu-22.04
    transport: # Dealing with 22.04 deprecating ssh-rsa prior to tooling being ready for it
      name: ssh
      username: vagrant
      password: vagrant

```

**Comment by jkugler** [comment]
@matuskosut Considering https://github.com/hashicorp/vagrant/issues/12589 is still open, I don't think vagrant has a ecdsa nor ed25519 in place yet. So upgrading vagrant wouldn't help.

**Comment by jkugler** [comment]
https://github.com/hashicorp/vagrant/blob/main/keys/vagrant is still and RSA private key. As to the referenced comment, https://github.com/chef/bento/pull/1404#issuecomment-1113761673, I don't know what about the upgrade fixed it. I'm not sure how, as it's still using the RSA key.

**Comment by matuskosut** [comment]
@jkugler I have a hunch that it doesn't necessarily need ecdsa/ed25519 then. Looking at changelog there are some potentially related changes, e.g. changing signature algorithm:
- https://github.com/hashicorp/vagrant/pull/12298/files

I manage to login straight away and I get this record in auth.log:
```
Jun  8 05:43:37 vagrant sshd[1348]: Accepted publickey for vagrant from 10.0.2.2 port 65476 ssh2: RSA SHA256:Agu2LyLvAGbjvpcUnWHB2HnN2rEYtaq3RC0MLbvTzM8
```

btw any chance you upgraded openssh, for example if upgrading packages using either apt (linux) or brew (macOS)?

**Comment by meermanr** [comment]
@jkugler: Regarding a parallels box: I came here looking for one, and saw your comment:

> Bento used to do other products. Take a look at https://app.vagrantup.com/bento/boxes/centos-6 and https://app.vagrantup.com/bento/boxes/debian-9 for example. They have VMWare and Parallels boxes as well. They didn't have a pipeline for it, so it was "best effort," but the person doing it (I forget their name) did have a setup to push boxes for other hypervisors.

So I installed packer and the Parallels SDK and built ubuntu-22.04.parallels.box (for AMD64) and uploaded it to https://app.vagrantup.com/meermanr/boxes/bento-ubuntu-22.04

Is there a way I can contribute it to `bentu/ubuntu-22.04`?

**Comment by smammy** [comment]
> @jkugler: Is there a way I can contribute it to `bentu/ubuntu-22.04`?

Please let's not have boxes built by third parties "contributed" to Vagrant under the bento org. It's a supply chain attack waiting to happen.

**Comment by ashiqueps** [comment]
Hi All,

The Ubuntu 22.04 boxes for Parallels, VirtualBox and VMware have been uploaded to the vagrant cloud account. The libvirt box is pending and I am facing #1412 while building the box in Mac as well as in Ubuntu.
