### ISSUE TITLE
Ubuntu 20.04 Unexpected mirror change

### ISSUE THREAD

**Issue by BryanQuigley** [chef/bento#1411]
# Version:

https://app.vagrantup.com/bento/boxes/ubuntu-20.04/versions/202206.03.0

# Environment:

Tests run on Fedora 37 with Vagrant 2.2.19 and Virtualbox

# Scenario:

Noticed a lot of new errors on connecting to apt repos, investigated and the previous image was us.archive.ubuntu.com (77 ms away) and now it's trying to reach in.archive.ubuntu.com (350ms away)

# Steps to Reproduce:

```
vagrant init bento/ubuntu-20.04 --box-version 202206.03.0
vagrant up

$ vagrant ssh -c 'grep archive.ubuntu.com /etc/apt/sources.list | head -n 1'
deb http://in.archive.ubuntu.com/ubuntu focal main restricted
```

# Expected Result:

Should be using at least my country mirror. For example, the previous image did it:

```
vagrant init bento/ubuntu-20.04 --box-version 202112.19.0
vagrant up

$ vagrant ssh -c 'grep archive.ubuntu.com /etc/apt/sources.list | head -n 1'
deb http://us.archive.ubuntu.com/ubuntu focal main restricted
```

Another option would be to use the mirror protocol described [here](https://linuxconfig.org/ubuntu-mirrors).

**Comment by tas50** [comment]
@BryanQuigley can you try this one again with the new release? We don't actually touch the mirrors at all so I'm not sure where this is coming from.

**Comment by BryanQuigley** [comment]
Confirmed it's no longer an issue with the latest image.  Thanks!
