### ISSUE TITLE
Ubuntu 22.04 build for arm64 not found

### ISSUE THREAD

**Issue by omidontop** [chef/bento#1427]
# Describe the problem

Could you kindly provide an arm64 build of the Ubuntu 22.04?

```
The box 'bento/ubuntu-22.04-arm64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/bento/ubuntu-22.04-arm64"]
Error: The requested URL returned error: 404
```

## Software Version

```bento/ubuntu-22.04```

**Comment by Stromweld** [comment]
This is currently a work in progress. Current release of the code has all the parts in place to build arm machines but still requires testing and tweaks mostly to the boot_command to get them building correctly. Please feel free to test the latest release of the code and submit any findings or PR's for fixes. Once builds are working for aarch64 machines we will publish to vagrant cloud.

**Comment by Stromweld** [comment]
a new box has been created `bento/ubuntu-22.04-arm64` with parallels provider
