### ISSUE TITLE
CentOS Stream 9 not found on Vagrant Cloud

### ISSUE THREAD

**Issue by vancanhuit** [chef/bento#1432]
# Problem

I can't find the CentOS Stream 9 box on Vagrant Cloud: [https://app.vagrantup.com/bento](https://app.vagrantup.com/bento).

# Expected Result:

CentOS Stream 9 box is available on Vagrant Cloud.

**Comment by elreydetoda** [comment]
Duplicate of #1391

**Comment by Stromweld** [comment]
box released at https://app.vagrantup.com/bento/boxes/centos-stream-9/versions/202301.20.0
