### ISSUE TITLE
Ubuntu arm64 VirtualBox provider (since the macOS M1/M2 developer preview is available)

### ISSUE THREAD

**Issue by LordParsley** [chef/bento#1460]
### Describe the Enhancement:

Would it please be possible to add a VirtualBox provider to the Ubuntu 20.04/22.04 arm64 templates since the [developer preview for macOS M1/M2 hosts is now available for VirtualBox](https://www.virtualbox.org/wiki/Downloads)?

### Describe the Need:

Boxes built using the Ubuntu arm64 image only use the `parallels` provider at the moment. This means there's no open alternative for running Ubuntu vagrant boxes.

```
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

[...]
Requested provider: [:virtualbox]
```

### Current Alternative

Purchasing & running Parallels instead.

### Can We Help You Implement This?:

🙏

**Comment by Stromweld** [comment]
This is being worked on and will be released with the hcl2 rewrite. https://github.com/chef/bento/pull/1455

**Comment by Stromweld** [comment]
hcl2 code has been released and aarch64 is supported for all providers. Aarch64 boxes still need testing and tweaking mostly of the boot_command to work. Please give it a spin and open an issue or PR for any problems/fixes you may find. Closing this as complete since the provider is now available.

**Comment by jeromecovington** [comment]
I'll be trying these as well. I have been looking on Hashicorp Cloud website for Ubuntu/ARM64/Virtualbox but didn't check yet for Ubuntu/Aarch64/Virtualbox.
