### ISSUE TITLE
Today (2023-01-14) README.md typo?

### ISSUE THREAD

**Issue by rubisher** [chef/bento#1464]
# Version

[rudy@rl8-vgr2 bento]$ git log -n 1
commit 3dca3da7f9bbe41a75e505b155422902c6ae96a7 (HEAD -> main, origin/main, origin/HEAD)
Author: Corey Hemminger <hemminger@hotmail.com>
Date:   Mon Jan 9 18:04:35 2023 -0600

## Environment

VirualBox-7.0 Rockylinux 8.7 guest 

## Scenario

Create my custom vagrant box image based on bento templates.

## Steps to Reproduce

the github Readme.md mentioned:
*NOTE: Virutalbox 7.x requires extra config to allow nat network to connect to the host. To use uncomment lines #79 and #80 in bento/packer_templates/pkr-sources.pkr.hcl

While it seems to be better bento/packer_templates/pkr-variables.pkr.hcl file which would required to uncomment line #154 & #155?

## Expected Result

Reading note:
*NOTE: Virutalbox 7.x requires extra config to allow nat network to connect to the host. To use uncomment lines #154 and #155 in bento/packer_templates/pkr-variables.pkr.hcl

## Additional comment:
Couldn't we merge this 2 lines ?

**Comment by Stromweld** [comment]
Thanks for the catch fixing this in latest PR #1465
