### ISSUE TITLE
VM_Data missing default settings

### ISSUE THREAD

**Issue by suikast42** [chef/bento#1467]
The old_json repo contains the vmware json settings 
```json
        "vmx_data": {
                "cpuid.coresPerSocket": "1",
                "ethernet0.pciSlotNumber": "32"
            },
 ```
which missing in the defaults for vmware 

```hcl
variable "vmware_vmx_data" {
  type    = map(string)
  default = {
    "cpuid.coresPerSocket" = "1"
    "ethernet0.pciSlotNumber"  = "32"
  }
}
 ```

**Comment by Stromweld** [comment]
is this causing any issues? when I look around at various templates like windows doesn't have anything for vmx_data, ubuntu has what you posted, rockylinux 9.1, only has cpuid for vmx_data. I didn't set default and eventually want to test vmware builds to see if that is needed or not.

**Comment by suikast42** [comment]
Yes it does. If the VM boots up over vagrant up then the network initialisation phase takes over two minutes. 

I am privioning more then one vms within same Vagrant file. The first machine configuretion works ( with that long init phase )
but the rest of the proviosning goes wrong with ssh timeout.

**Comment by Stromweld** [comment]
gotcha thanks, I'll add that to my next release.

**Comment by Stromweld** [comment]
Can you verify this is now working as expected for you?
