### ISSUE TITLE
For Ubuntu 22.10 giving error for packer build . authentication error when trying to connect via SSH.

### ISSUE THREAD

**Issue by adityashewale** [chef/bento#1468]
after running
#packer build --only=qemu ubuntu-22.10-amd64.json
Error :  Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

**Comment by Stromweld** [comment]
please update your repo and test with the latest code

**Comment by Stromweld** [comment]
if you are on the latest build of packer since we updated to hcl2 code from the json templates you'll need to use the command from bento root `packer build -only=qemu.vm -var-file=os_pkrvars/ubuntu/ubuntu-22.10-x86_64.pkrvars.hcl packer_templates`

**Comment by Stromweld** [comment]
qemu build of ubuntu-22.10-x86_64 look to be working with latest code closing this issue. https://github.com/chef/bento/actions/runs/4328485365#artifacts
