### ISSUE TITLE
issue with corp network and loopback routing over vpn

### ISSUE THREAD

**Issue by devmuppet** [chef/bento#1476]
Hi there,

Not sure if anyone can help with this but i hope so! 

My corp laptops force loopback traffic over the vpn client (and they are not willing to change this) so i cant ever get builds working on my laptop due to this (forced over the vpn and into a proxy). 

MY question is.... can we update the communicator/something to allow specific networks to be used. So I can setup a host only network on my virtual box and then get the communicators to use that? 

Any and all help massively appreciated... been bashing my head off a wall to get this far.

**Comment by Stromweld** [comment]
The communicator would work either way with a host only network, the issue I see coming in is the scripts being able to install patches etc... with data from the internet.

**Comment by devmuppet** [comment]
I've gone with using azure devbox to get around it... Thanks for the input ☺️

**Comment by Stromweld** [comment]
Sounds good. I’ll close this issue then. Please feel free to open a new one if needed.
