### ISSUE TITLE
freebsd i386 boxes no longer support virtualbox?

### ISSUE THREAD

**Issue by tmm1** [chef/bento#1486]
# Describe the problem
freebsd-12.2-i386 is available for virtualbox: https://app.vagrantup.com/bento/boxes/freebsd-12.2-i386

but newer boxes like 12.3-i386 and 12.4-i386 are only available for vmware_desktop

## Possible Solution

what would it take to generate virtualbox vms for the newer freebsd i386 builds?

**Comment by Stromweld** [comment]
We currently aren't actively building and supporting 32bit machines anymore. If you look at the old json template branch here https://github.com/chef/bento/tree/bento_old_json_templates you can find the i386 templates and update them to build boxes for yourself.
