### ISSUE TITLE
centos-stream-9 build failed on cleaning ifcfg

### ISSUE THREAD

**Issue by matihost** [chef/bento#1488]
# Version

main branch

## Environment

Windows 10, Vagrant 2.3.4, VirtualBox 7.0.6, packer 1.8.6

## Scenario

Error duirng building centos-stream-9 vagrant image

## Steps to Reproduce

```bash
  OS_NAME=centos
  IMAGE_BASENAME=centos-stream-9
  packer init -upgrade ./packer_templates && \
  packer build -only=virtualbox-iso.vm -var-file=os_pkrvars/${OS_NAME}/${IMAGE_BASENAME}-x86_64.pkrvars.hcl ./packer_templates
```

## Expected Result

Successfuly build centos-stream-9 image

## Actual Result

Build failed on:

```txt
==> virtualbox-iso.vm: + mkdir -p /etc/udev/rules.d/70-persistent-net.rules
==> virtualbox-iso.vm: + rm -f /lib/udev/rules.d/75-persistent-net-generator.rules
==> virtualbox-iso.vm: + rm -rf /dev/.udev/
==> virtualbox-iso.vm: + for ndev in /etc/sysconfig/network-scripts/ifcfg-*
==> virtualbox-iso.vm: ++ basename '/etc/sysconfig/network-scripts/ifcfg-*'
==> virtualbox-iso.vm: + '[' 'ifcfg-*' '!=' ifcfg-lo ']'
==> virtualbox-iso.vm: + sed -i '/^HWADDR/d' '/etc/sysconfig/network-scripts/ifcfg-*'
==> virtualbox-iso.vm: sed: can't read /etc/sysconfig/network-scripts/ifcfg-*: No such file or directory
==> virtualbox-iso.vm: Provisioning step had errors: Running the cleanup provisioner, if present...
==> virtualbox-iso.vm: Cleaning up floppy disk...
```

Workaround/fix proposal:
https://github.com/chef/bento/blob/main/packer_templates/scripts/rhel/cleanup_yum.sh#L34
and
https://github.com/chef/bento/blob/main/packer_templates/scripts/rhel/cleanup_dnf.sh#L34
replace with:
```bash
for ndev in `ls /etc/sysconfig/network-scripts/ifcfg-*`; do
```

**Comment by Stromweld** [comment]
Can you test this again as I am not seeing the same behavior?

**Comment by Stromweld** [comment]
There is a new version of centos-stream-9 published to vagrant. Marking this as closed as the box is currently building for virtualbox.
