### ISSUE TITLE
new build cmd updated?

### ISSUE THREAD

**Issue by rubisher** [chef/bento#1493]
# Describe the Enhancement

In a recent git update, I noticed the comment related to bento cmd:

`To build a Debian vagrant box using the bento tool with the template available in the **_os_pkrvars_** dir, `

if I well understand, wouldn't it means that the actual cmd would be :

`bento build --cpus 2 os_pkrvars/debian/debian-11-x86_64.pkrvars.hcl`

## Describe the Need

Just update the doc to align comment & command ;)

## Current Alternative

May be useful for newbies?

**Comment by Stromweld** [comment]
This has been fixed in latest commit.
