### ISSUE TITLE
Boot command not working on ARM64/Silicon VMWare 13.0.x

### ISSUE THREAD

**Issue by combatpoodle** [chef/bento#1499]
# Describe the Enhancement

On ARM64/Silicon boot commands only come through if USB is attached with...
```
usb_xhci.present = "TRUE"
```
In the VMX file.

## Describe the Need

The above enhancement is needed to get nocloud/etc to initialize the headless install process.

## Current Alternative

Nothing currently; even VNC seems to be non-functional

## Can We Help You Implement This

Am done for the night - dropping a reminder for myself/the project in case I don't get back to it this weekend or someone comes around before I remember ;)

**Comment by Stromweld** [comment]
this should be fixed in the latest merge
