### ISSUE TITLE
E1000 Driver issue on Ubuntu/VMware Fusion 13.0.x, ARM64

### ISSUE THREAD

**Issue by combatpoodle** [chef/bento#1500]
# Version

Currently running into a driver issue on VMware's e1000 driver in combination with Ubuntu 20.04, 22.04, and 22.10 and VMWare Fusion 13.0.1 and 13.0.2 on ARM64/OS X.

## Environment

ARM64/Silicon Mac.

## Scenario

So, *strictly hypothetically* I'd like to not be stuck in a sneakernet.  I meannnn...  I know that's a lot, BUT...  I still remember those dark days...

## Steps to Reproduce

Here are my build lines...
```
israel@HOST ~/_/bento> git rev-parse HEAD
5b98131aef24eb3923cfaec623ed7f110ead4fed
israel@HOST ~/_/bento> PACKER_LOG=DEBUG packer build -debug -timestamp-ui -only=vmware-iso.vm -var-file=os_pkrvars/ubuntu/ubuntu-20.04-aarch64.pkrvars.hcl ./packer_templates
israel@HOST ~/_/bento> PACKER_LOG=DEBUG packer build -debug -timestamp-ui -only=vmware-iso.vm -var-file=os_pkrvars/ubuntu/ubuntu-22.04-aarch64.pkrvars.hcl ./packer_templates
israel@HOST ~/_/bento> PACKER_LOG=DEBUG packer build -debug -timestamp-ui -only=vmware-iso.vm -var-file=os_pkrvars/ubuntu/ubuntu-22.10-aarch64.pkrvars.hcl ./packer_templates
```

My VMX is modded at the pause of:
```
==> vmware-iso.vm: Pausing after run of step 'StepRegister'. Press enter to continue. 
```
with the following line:
```
usb_xhci.present = "TRUE"
```

Which allows you to get through the boot process by adding a USB host; drop to a terminal via the help menu.  Get to `dmesg | less` (that's dmesg pipe less).  Search for `e1000`

## Expected Result

Should probably just not crash out; working network would be *greattttt*.  Is it a VMWare issue?  Is it something we can work around for the moment?  IDK.  Reporting to VMWare.

### Ubuntu 22.xx

<img width="1022" alt="Screenshot 2023-04-29 at 12 53 21 AM" src="https://user-images.githubusercontent.com/1100234/235289631-9583c7a8-b457-4288-bdb9-34423fcc9688.png">
<img width="1024" alt="Screenshot 2023-04-29 at 12 53 29 AM" src="https://user-images.githubusercontent.com/1100234/235289642-c7973c96-7a74-40ef-bd8d-9042ff213870.png">

### Ubuntu 20.xx

<img width="1022" alt="Screenshot 2023-04-29 at 1 13 04 AM" src="https://user-images.githubusercontent.com/1100234/235289671-a1dd937b-9f6f-41bc-a37c-9106b8f8efd1.png">
<img width="1020" alt="Screenshot 2023-04-29 at 1 13 19 AM" src="https://user-images.githubusercontent.com/1100234/235289675-162b1db0-3d75-4ac5-91e2-e009eed73797.png">

**Comment by Stromweld** [comment]
This should be fixed in the latest merge.
