### ISSUE TITLE
Request for latest LTS releases of Ubuntu on ARM64 for vmware_desktop or virtualbox (ubuntu-20.04-arm64 and ubuntu-22.04-arm64)

### ISSUE THREAD

**Issue by martenlehmann** [chef/bento#1505]
# Describe the Enhancement

LTS releases of Ubuntu are supported longterm, so they are even in use years after the release of Apple's M1 und M2 processors. Unfortunately the first vagrant box for ARM64 and the vmware_desktop provider is Ubuntu 22.10 (a too recent non-LTS release).

## Describe the Need

I'm not sure how much work is involved in building a box, yet rather than working on a custom box for myself, it would be more helpful to others if an official box from bento was provided.

## Current Alternative

Currently, everyone using VMware Fusion would need to switch to Parallels Desktop Pro and purchase another license for the same functionality he already got.

## Can We Help You Implement This

I guess many things could be backported using the vmware_desktop box of 22.10 for 20.04 and 22.04.

**Comment by Stromweld** [comment]
I just uploaded a new 20.04-arm64 version with both parallels and vmware box. Unfortunately 22.04-arm64 only has a parallels build that working and uploaded now. Are you ok with me closing this for now or would you like me to keep it open till there is a 22.04-arm64 for vmware build working.

**Comment by martenlehmann** [comment]
Thanks for creating the 20.04-arm64 VMware version! I guess I'll be migrating to Docker containers for the 22.04 version, so closing is ok to me.

**Comment by Stromweld** [comment]
I just released new version of all except 18.04 for arm64 and vmware_desktop provider.

**Comment by jeromecovington** [comment]
I see this is closed. I am very much looking forward to Ubuntu ARM64 builds that will run with Virtualbox as the provider. Would it help to have a new issue?
