### ISSUE TITLE
Fix broken url to chef.github.io/bento

### ISSUE THREAD

**Issue by manjufy** [chef/bento#1514]
## Steps to Reproduce

The link to [chef.github.io/bento](http://chef.github.io/bento) in the About section is broken

## Expected Result

Change [chef.github.io/bento](http://chef.github.io/bento) => [chef.github.io/bento](https://github.com/chef/bento)

**Comment by manjufy** [comment]
![Screenshot 2023-06-29 at 21 00 54](https://github.com/chef/bento/assets/5035624/685d4d18-8245-4567-9df9-103eed8918b1)

As shown in the screen, that link leads to 404

**Comment by Stromweld** [comment]
thanks, I removed it since there isn't any actual website for bento. Doesn't make sense to add a link to itself. At one time in the past that must of linked to a website within this repo.
