### ISSUE TITLE
Installation of Parallels Tools in (particular) Ubuntu VMs fails

### ISSUE THREAD

**Issue by mpdude** [chef/bento#1524]
Hey there 👋🏼,

I am using [this Ubuntu Vagrant box](https://app.vagrantup.com/bento/boxes/ubuntu-22.04/versions/202303.13.0) with Parallels Desktop.

Upon boot, the `vagrant-parallels` plugin detects that the version of Parallels Tools installed in the box is outdated and tries to update it. 

The problem is that, to my understanding, installation of Parallels Tools needs the `linux-headers-5.15.0-67-generic` package to be installed. Or, more generally, the version of that package matching the currently running kernel version. However, when the Kernel version included in the box image has since then replaced with a newer version (in the upstream Ubuntu repositories), it seems the matching header files can no longer be installed. They probably came from an Ubuntu security update release channel where the package has been replaced with a newer version since the box was built.

Full details can be found in the issue at https://github.com/Parallels/vagrant-parallels/issues/458.

## Suggested enhancement

I _think_ when the Parallels versions of the Ubuntu boxes (and maybe the same is true for other distros as well?) come with a suitable version of `linux-headers-...` installed, the automatic update of Parallels Tools upon first boot should work.

Maybe installation of the `linux-headers-generic` meta package would be the best way to approach this.

This needs to happen at box build time, so that we get a snapshot of the header files matching the kernel version used at that time.

## Current Alternative

Disable Parallels Tools update in the `Vagrantfile` for the first boot. Update kernel to the latest version, reboot. Enable Parallels Tools update again, reboot to make the update happen.

## Can We Help You Implement This

Sure! If you agree the suggested change makes sense, I'd probably need to update some build script for the Parallels provider?

**Comment by Stromweld** [comment]
I'm open to reviewing PR's that would help enhance and fix this issue. You'll probably want to start by looking at https://github.com/chef/bento/blob/main/packer_templates/scripts/_common/parallels.sh.

**Comment by mpdude** [comment]
To my knowledge, the installation as in

https://github.com/chef/bento/blob/d56f2198a32c1a8110c0a1596336e6844c56e014/packer_templates/scripts/_common/parallels.sh#L18

should install the necessary header files package.

So how come that’s not present in the resulting box? Or how may it happen that the box ships with another (updated) kernel version?

**Comment by Stromweld** [comment]
to reduce image size this is probably what is removing those https://github.com/chef/bento/blob/d56f2198a32c1a8110c0a1596336e6844c56e014/packer_templates/scripts/ubuntu/cleanup_ubuntu.sh.

**Comment by mpdude** [comment]
#1526 is my attempt to fix it, by running an extra script for Parallels on Ubuntu/Debian to re-install the necessary package after `cleanup_ubuntu.sh` has run.

Looking forward to your review!

**Comment by Stromweld** [comment]
completed via #1526
