### ISSUE TITLE
bento/ubuntu-22.10 cannot update because apt URLs are wrong

### ISSUE THREAD

**Issue by ploveridge-caci** [chef/bento#1528]
Due to a change in the host of apt repositories apt-get update command fails on bento/ubuntu-22.10 

# Describe the problem
After creating the vagrant box any run of "sudo apt-get update" fails with the error "The repository no longer has a Release file"

## Software Version
bento/ubuntu-22.10

## Replication Case
1. Provision VM
2. Log in 
3. Run "sudo apt-get updatge"

## Possible Solution
The repository URLS need to be updated to the new host 

https://azdigi.com/blog/en/linux-server-en/fix-the-the-repository-no-longer-has-a-release-file-error-on-ubuntu/

This command will update them:

sudo sed -i -re 's/([a-z]{2}.)?archive.ubuntu.com|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list

**Comment by Stromweld** [comment]
Ubuntu 22.10 was an interim release and only officially is supported for 9 months. Only the LTS releases are supported long term. With that we strive to support and build Officially Supported releases. With this many OS's and builds for multiple providers and cpu architectures we don't have the resources to support them for longer terms.

**Comment by Stromweld** [comment]
You are free to use the templates and build your own boxes as well.
