### ISSUE TITLE
OracleLinux 7: No IP for NAT network after 1st boot

### ISSUE THREAD

**Issue by Rendanic** [chef/bento#1533]
# Version

current master

## Environment

Windows 10 with Packer, Vagrant and VirtualBox as build host.

## Scenario

Building a Oracle Linux 7 VM with packer.

## Steps to Reproduce

`packer build -only=virtualbox-iso.vm -var-file=os_pkrvars/oracle/oracle-7-x86_64.pkrvars.hcl packer_templates/`

The build for CentOS7 works fine:
`packer build -only=virtualbox-iso.vm -var-file=os_pkrvars/centos/centos-7-x86_64.pkrvars.hcl packer_templates/`

## Expected Result

VM should get an IP from DHCP network on NAT network after 1st boot.
I can workarround the problem by manually starting the dhclient in the machine.

## Actual Result

SSH connect from `packer build` run in a timeout, because the VM does not have an IP and SSH is not reachable via the port forwarding on NAT Device in VirtaulBox.

**Comment by Stromweld** [comment]
OL-7 is EOL and isn't supported anymore.
