### ISSUE TITLE
What does Bento do differently than official Rocky Images?

### ISSUE THREAD

**Issue by jeffmacdonald** [chef/bento#1537]
So this is going to be ... poorly phrased.

Any time I try rockylinux/8 images on either MacOS or Linux it gets frozen, usually at the grub screen I think.

Bento Images always just work. 

Do you guys do any special sauce to work with modern virtual box? Something I could perhaps suggest to the Rocky folks? :)

**Comment by Stromweld** [comment]
Nothing too special. The install happens and then we run scripts to remove things like machine ID, install guest tools for the specific virtualization provider, and zero out the empty space on disk so it compresses better when made into a vagrant image.

**Comment by jeffmacdonald** [comment]
Hhrmm. Conversely then, I wonder what Rocky folks are doing wrong, but that's not your problem :)
