### ISSUE TITLE
Some ARM64 boxes are missing on Vagrant Cloud

### ISSUE THREAD

**Issue by luangong** [chef/bento#1545]
# Enhancement

Some ARM64 boxes are missing on Vagrant Cloud.

## The Need

Here are some ARM64 boxes (among the most popular distros) that are missing under the [bento](https://app.vagrantup.com/bento) org on Vagrant Cloud.

- Debian 10 for ARM64
- [Debian 11 for ARM64](https://app.vagrantup.com/bento/boxes/debian-11-arm64) (there is a box for parallels, but none for vmware_desktop)
- Rocky Linux 8 for ARM64
- Alma Linux 8 for ARM64
- Arch Linux for ARM64

## Current Alternative

- [rockylinux/8](https://app.vagrantup.com/rockylinux/boxes/8)

**Comment by Stromweld** [comment]
These are still a work in progress. We don't support Arch Linux for either CPU architecture though. Any help on testing and updating the configs to get them working is greatly appreciated. Otherwise this is a side project for me and will take some time to get them all tested and working.

**Comment by luangong** [comment]
I have a MacBook Pro with M1 Pro and VMware Fusion installed. Please let me know what I can do.

**Comment by Stromweld** [comment]
you can clone repo and run tests with `packer build -only=vmware-iso.vm -on-error=ask -var-file=./os_pkrvars/almalinux/ualmalinux-8-aarch64.pkrvars.hcl packer_templates` and connect to VM to see the issue. Most likely the in vars file the boot_command may need to be updated or the boot wait might need to be adjusted. Typically if 1 provider worked then the boot_command is good, just the timing of the boot_wait needs to be adjusted.

**Comment by luangong** [comment]
It seems that RHEL 8 and and most of its clones (AlmaLinux 8, Rocky Linux 8, etc.) don’t support Apple silicon with VMware Fusion because of CPU page size difference. The only exceptions are Oracle Linux 8.7 and 8.8.

Here are some links:

- [RHEL 8.8 Cant install in VMware Fusion on macOS Ventura](https://access.redhat.com/discussions/7023386)
- [Fusion 13 Support](https://communities.vmware.com/t5/VMware-Fusion-Discussions/Fusion-13-Support/td-p/2963238)
- [RHEL 8.7/8.8 on Fusion 13.0.2](https://communities.vmware.com/t5/VMware-Fusion-Discussions/RHEL-8-7-8-8-on-Fusion-13-0-2/td-p/2982597)

**Comment by Stromweld** [comment]
that makes sense then. we try to stay on the latest so we'd be focused on 8.9 versions. Thanks for the info nice find.

**Comment by luangong** [comment]
I think it may still be worth it to dig deeper to see if we can patch/recompile the kernel like what Oracle Linux 8.7—8.9 are doing, not only for Apple silicon Macs with VMware Fusion, but also for other ARM-based PCs/OSes with other hypervisors.

@Stromweld What do you think?

**Comment by Stromweld** [comment]
I think that is probably way beyond the scope of this project as it's meant more for as close to stock install as possible for testing tools like chef. The only real modifications we are doing is running patches to keep them up to date and removing unneeded things for a VM like linux-firmware to shrink the image size to make it faster and easier to download.

**Comment by luangong** [comment]
Agreed.

**Comment by luangong** [comment]
Can you please build Oracle Linux 8.7–8.9 arm64 boxes for the vmware_desktop provider and publish them to Vagrant Cloud? Thanks! That’ll be the only way we can run RHEL 8–like boxes on an Apple silicon Mac with VMware Fusion installed.

**Comment by Stromweld** [comment]
I just tried building them and ran into errors during the build phase that will take some time to look at and fix. My Vmware build failed to upload tools iso and the parallels build failed to compile the guest tools.
