### ISSUE TITLE
Make centos-stream-9-arm64 box available for the vmware_desktop provider

### ISSUE THREAD

**Issue by patrickbooth** [chef/bento#1555]
# Describe the Enhancement

I'd like to have the centos-stream-9-arm64 vagrant box available for the vmware_desktop provider.  

## Describe the Need

Currently the image only supports parallels, https://app.vagrantup.com/bento/boxes/centos-stream-9-arm64, It would be great to have an image available for us using VMware Fusion. 

## Current Alternative

Other enterprise linux variants are available from bento, i.e  the recently fixed rockylinux-9 and the fedora-39 images.

**Comment by Stromweld** [comment]
this is completed for bento/centos-stream-9 box. Vagrant 2.4.0+ is required for the new cpu architecture detection and flags. https://app.vagrantup.com/bento/boxes/centos-stream-9
