### ISSUE TITLE
'Error downloading kickstart file' within Oracle VM VirtualBox

### ISSUE THREAD

**Issue by francisalfanta** [chef/bento#172]
I'm new to CentOS and learning how to go around like in kickstarter file. I can't pass this error when running packer build centos-6.5-x86_64.json

Unable to download the kickstart file. Please modify the kickstart parameter below or press Cancel to proceed as an interactive installation.

http://10.0.2.2:8300//centos-6.5-x86_64/ks.cfg

Any guide is really appreciated.

**Comment by bridiver** [comment]
what did you change?

**Comment by konradb90** [comment]
How exactly did you solve this problem?

**Comment by cheeseplus** [comment]
@konradb90 this is more a general packer question and resurrecting 3 year old close threads is less than ideal way to get this properly answered. Typically this problem results from mis-configuration of the hypervisor or host networking.

I'd suggest checking out the #packer-tool channel on Freenode IRC or the Chef Community Slack's #packer channel if you have any "How To Packer" questions.
