### ISSUE TITLE
fix OmniOS build under VMWare

### ISSUE THREAD

**Issue by juliandunn** [chef/bento#178]
The installation of VMWare tools will kernel-panic the OmniOS box on shutdown for packaging, which is no good. This can be fixed by having the tools installed with only the options as detailed here:

http://lists.omniti.com/pipermail/omnios-discuss/2013-December/001958.html

Unfortunately I wasn't able to quickly find a way to do this noninteractively, so we probably need to patch the vmware-tools-install.pl script.

**Comment by fnichol** [comment]
@juliandunn Taking a quick look with VMware Fusion 7.1.1 as things may have resolved themselves…

**Comment by fnichol** [comment]
Looks like this is no longer happening. If I'm wrong, we can re-open.
