### ISSUE TITLE
rename box prefixes to bento- instead of opscode-

### ISSUE THREAD

**Issue by juliandunn** [chef/bento#208]
* Opscode is now Chef Software
* Since these boxes are used by and for other purposes than Chef, rather than putting the company name in there, we should change the prefix to 'bento-'
* Rebuild and publish all boxes
* Coordinate with Fletcher Nichol to update test-kitchen URLs
* Stretch goal: Get Chef Ops to put Cloudfront in front of the S3 bucket, to speed up downloads

**Comment by flaccid** [comment]
For me the main one outstanding that will really help now is cloudfront support for the boxes (which currently is just S3 bucket opscode-vm-bento.s3.amazonaws.com in us-west-1 afaik).
Down here in Australia some of the routes overseas plain suck even when on cable or better - box download can literally be 1 or more hours.

**Comment by cheeseplus** [comment]
Closing this issue as we're moving everything to Atlas which takes care of namespacing https://atlas.hashicorp.com/bento @8a424e2900148bb8d732604844b4e18bce064d07
