### ISSUE TITLE
Puppet support in bento?

### ISSUE THREAD

**Issue by schrepfler** [chef/bento#251]
Hi, I think it's possible to provide a second set of box definitions which would have puppet rather that chef as provider (I essentially fiddled a bit by forking bento, removing the chef provider and then importing the puppet-bootstrap as external module and loading that during install).
If you guys care for it I can polish a bit my work and push it back to you. Interested?

**Comment by cheeseplus** [comment]
Closing this issue as the Bento boxes are built without any CM as stated earlier and these boxes can be bootstrapped with CM by other mechanisms.
