### ISSUE TITLE
Vagrant public key file could be empty

### ISSUE THREAD

**Issue by indigo423** [chef/bento#258]
It could be possible the `wget` command runs in an error and creates an empty `authorized_keys` file. The exit code is 0 and doesn't stop the build process. See example below by having issues resolving the raw.githubusercontent.com address:

    Provisioning with shell script: scripts/common/vagrant.sh
    virtualbox-iso: --2014-08-25 10:18:06--  https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub
    virtualbox-iso:   Resolving raw.githubusercontent.com... failed: Name or service not known.
    virtualbox-iso: wget: unable to resolve host address "raw.githubusercontent.com"
    virtualbox-iso: Provisioning with shell script: scripts/common/vmtools.sh
    virtualbox-iso: Verifying archive integrity... All good.

Suggestion to solve this issue: https://github.com/opscode/bento/pull/257

**Comment by juliandunn** [comment]
@indigo423 are you still working on this or shall I close it?

**Comment by cheeseplus** [comment]
Resolved by 51b76435e8bdb4ad21da3e9dfc49cbea4ebaeb2a
