### ISSUE TITLE
Single disk configuration for VMware

### ISSUE THREAD

**Issue by thasmo** [chef/bento#307]
Noticed that the default VMware configuration uses multiple disks á 2 GB. Would it be an option to use a single disk configuration using disk type 0?

```
0 – create a growable virtual disk contained in a single file (monolithic sparse).
```

Packer docs mention it [here](https://packer.io/docs/builders/vmware-iso.html#disk_type_id).

**Comment by juliandunn** [comment]
I don't think there's a significant benefit to this, and in this day and age, if you're still running FAT32 and this is a problem... well I'm very sorry for you :grin:
