### ISSUE TITLE
Create Fedora 21 box

### ISSUE THREAD

**Issue by dfarrell07** [chef/bento#312]
First: I really appreciate your work to create wonderful Vagrant boxes for the community. Thank you!

It'd be great to create a `chef/fedora-21` box, especially since there [aren't any official-ish ones on Vagrantcloud at the moment](https://vagrantcloud.com/boxes/search?utf8=%E2%9C%93&sort=&provider=&q=fedora+21). I'm up for contributing, but I've never used Packer or Bento. One of you super-cool Chef folks might be able to knock it out before I can loop back to getting spun up on building Vagrant base boxes. Either way, let's use this issue to track progress.

**Comment by juliandunn** [comment]
psst there already is one published, just not on vagrantcloud/atlas.

http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-21-i386_chef-provisionerless.box
http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-21_chef-provisionerless.box

(substitute 'vmware' for 'virtualbox' if that's your poison)

Can you test it out and let me know if it works?

**Comment by dfarrell07** [comment]
> psst there already is one published, just not on vagrantcloud/atlas.

Huzzah!

> Can you test it out and let me know if it works?

Very quick initial test looks good.

```
wget http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-21_chef-provisionerless.box
vagrant box add chef/fedora-21 opscode_fedora-21_chef-provisionerless.box
mkdir f21; cd f21
vagrant init -m chef/fedora-21
vagrant up
<screw around, confirm stuff behaves as expected>
```

I'll consume it in the project I'm working on ASAP, which should put it through enough stress to give some non-trivial confidence that it works properly.

**Comment by dfarrell07** [comment]
> (substitute 'vmware' for 'virtualbox' if that's your poison)

It doesn't look like the VMware ones are at that URL.

```
[~]$ wget http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_fedora-21-i386_chef-provisionerless.box                                  17:21:20
--2015-01-16 17:22:28--  http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_fedora-21-i386_chef-provisionerless.box
Resolving opscode-vm-bento.s3.amazonaws.com (opscode-vm-bento.s3.amazonaws.com)... 54.231.9.225
Connecting to opscode-vm-bento.s3.amazonaws.com (opscode-vm-bento.s3.amazonaws.com)|54.231.9.225|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-01-16 17:22:28 ERROR 404: Not Found.

[~]$ wget http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_fedora-21_chef-provisionerless.box                                       17:22:28
--2015-01-16 17:22:47--  http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_fedora-21_chef-provisionerless.box
Resolving opscode-vm-bento.s3.amazonaws.com (opscode-vm-bento.s3.amazonaws.com)... 54.231.9.225
Connecting to opscode-vm-bento.s3.amazonaws.com (opscode-vm-bento.s3.amazonaws.com)|54.231.9.225|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-01-16 17:22:47 ERROR 404: Not Found.
```

**Comment by juliandunn** [comment]
Ah yes. As it turns out I remembered why I didn't put vmware boxes up there; because the kernel was too new for the tools from VMWare Fusion 6.x to work. Now that I've upgraded to 7 and plan to rebuild all VMWare boxes, I will soon fix this.

**Comment by juliandunn** [comment]
All Fedora 21 boxes are on S3 now.

**Comment by Tcharl** [comment]
Hi, 
chef/fedora-21 vagrant box gave me an error while starting:
==> default: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

ARPCHECK=no /sbin/ifup eth1 2> /dev/null

Stdout from the command:
Stderr from the command:

Looks like a packaging issue: https://github.com/mitchellh/vagrant/issues/1777

Regards
