### ISSUE TITLE
Fedora kickstart script downloads CA cert bundle over HTTP

### ISSUE THREAD

**Issue by elehack** [chef/bento#318]
The kickstart scripts for Fedora (at least) download a new CA certificate bundle over unsecured HTTP from curl.haxx.se.

It seems to me that this should be done in some more secure fashion, if it is needed at all. Why does the CA cert bundle need to be updated, rather than using the one shipped by Fedora?

I have not reviewed the other build definitions to see if they also do this.

**Comment by juliandunn** [comment]
Indeed. It's probably just copypasta legacy from a CentOS 5 definition so that the `wget` of https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub works in `vagrant.sh` without SSL warnings.

I'm happy to take a PR to remove this, as long as that `wget` still works.
