### ISSUE TITLE
Error building debian7.8-amd-64

### ISSUE THREAD

**Issue by billinux** [chef/bento#319]
Hi bento,

I forked your repo, clone it and created a new branch to change en_US and us in fr_FR and fr, $> cd packer, $> packer build -only=virtualbox-iso debian-7.8-amd64.json

Every thing work fine until this error :

![capture d ecran 2015-02-07 a 00 40 26](https://cloud.githubusercontent.com/assets/737479/6090869/d46f3f08-ae62-11e4-9b6b-a35ea728ab55.png)

Can you help me please

**Comment by billinux** [comment]
I forgot, i used virtualbox on mac yosemite v4.3.20 r96996

**Comment by rickard-von-essen** [comment]
This is a packer issue. There are some old issues matching VBOX_E_INVALID_OBJECT_STATE, see https://github.com/mitchellh/packer/issues.

Check that you have the latest version of packer and report an issue there, see 
[Reporting an Issue](https://github.com/mitchellh/packer/blob/master/CONTRIBUTING.md#issues).

**Comment by billinux** [comment]
I rebuild the vm doing $> cd packer, $> packer build -only=virtualbox-iso debian-7.8-amd64.json.
Result: i have the same error like my first post.

someone can help me please ?

**Comment by billinux** [comment]
Thank You so much rickard-von-essen

==> Builds finished. The artifacts of successful builds are:
--> virtualbox-iso: 'virtualbox' provider box: ../builds/virtualbox/opscode_debian-7.8_chef-provisionerless.box

I had this error lastly because i didn't delete the last build packer vm in ~/Virtualbox VMs

Thank You
