### ISSUE TITLE
Use the SATA HDD controller for faster disk IO speeds

### ISSUE THREAD

**Issue by irvingpop** [chef/bento#324]
According to the [virtualbox documentation](https://www.virtualbox.org/manual/ch05.html#harddiskcontrollers): 
*Like a real SATA controller, VirtualBox's virtual SATA controller operates faster and also consumes fewer CPU resources than the virtual IDE controller. Also, this allows you to connect up to 30 virtual hard disks to one machine instead of just three, as with the VirtualBox IDE controller (with the DVD drive already attached).*

This has been an option in Packer for a while now: https://github.com/mitchellh/packer/pull/391
like so:
```json
"hard_drive_interface": "sata",
```

If there's general agreement that this is a good idea, I'll submit a PR.

**Comment by juliandunn** [comment]
That's cool. I'd take a PR.
