### ISSUE TITLE
centos 7.1 image request

### ISSUE THREAD

**Issue by kramvan1** [chef/bento#334]
With rhel decision to not make 7.0 a EUS/LTS, need to switch to 7.1.

Would like to see a 7.1 image like the one for 7.0 here:

'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.0_chef-provisionerless.box'

Doc of rhel EUS/LTS: https://access.redhat.com/support/policy/updates/errata

**Comment by juliandunn** [comment]
Sure, you can go ahead and submit a PR for the Packer definition -- we'll build it.

**Comment by kramvan1** [comment]
ok, will get started on that definition, thx.

**Comment by kramvan1** [comment]
https://github.com/chef/bento/pull/336
