### ISSUE TITLE
Why are definitions removed (RHEL 7.0 was just removed)

### ISSUE THREAD

**Issue by jeffdeville** [chef/bento#344]
Is there a prescribed way to keep using old definitions?  Checking out a random old SHA doesn't seem like a good plan, but neither does manually restoring the old files with git surgery.

**Comment by juliandunn** [comment]
That's just how the philosophy of this project works - we only keep the latest, as we don't want to maintain older versions of OSes. You can always go back in Git history to pull them out.

If you want a project with a different philosophy, check out [box-cutter](github.com/box-cutter).
