### ISSUE TITLE
Add support for Ubuntu 15.04

### ISSUE THREAD

**Issue by eheydrick** [chef/bento#345]
Ubuntu 15.04 is out, would be nice to have bento boxes for test-kitchen.

**Comment by juliandunn** [comment]
@fnichol ping

**Comment by fnichol** [comment]
Confirmed! I took a spike at this earlier this week and now that the ISO bits are in GA I will circle back on this.

**Comment by thasmo** [comment]
Would be awesome to also have a base box available for Vagrant on Atlas.

**Comment by arosenhagen** [comment]
@thasmo FYI: just pushed an update to https://github.com/ffuenf/vagrant-boxes

**Comment by andrewhood125** [comment]
:+1:

**Comment by fnichol** [comment]
Work is ongoing in #349 which will close this issue once merged.

Sadly it seems as the VMware Fusion and Parallels can't yet compile their tools against the 3.19.x Linux kernel. There are links in #349 for tracking.

**Comment by thasmo** [comment]
@fnichol, thanks for the update! :)

**Comment by fnichol** [comment]
I'll drop an update here, although the tl;dr is: no new news. Still pending software updates from VMware and Parallels, but I'm still checking almost every day.

**Comment by thasmo** [comment]
@fnichol, there was an update for VMware Workstation 11 some days ago, but not sure if the fixed the related issue.

**Comment by fnichol** [comment]
@thasmo Yes, that Workstation update is very likely required to make these templates work. On the Mac side, I could not get the file sharing (hgfs) kernel bits working without running VMware Fusion 7.1.2. There's a really good chance you'll find the same issue with the newer Debian 8.0 templates as well. Hope this helps :smile:
