### ISSUE TITLE
centos-7.1 vmware box got uploaded as virtualbox

### ISSUE THREAD

**Issue by phinze** [chef/bento#351]
First of all, you have a wonderful project. Thanks for all the work you do! :grinning: 

![chefboxerror](https://cloud.githubusercontent.com/assets/37534/7356219/4892ab00-ecec-11e4-9548-c6c3ee0030a2.png)

Looks like the VMware box for `chef/centos-7.1` uploaded yesterday was actually a duplicate of the VirtualBox one. I'd imagine it was just a simple typo and is easily fixable.

Let me know if there's anything I can do to help out! :+1:

**Comment by juliandunn** [comment]
Can you try it now? Make sure to delete the old box from Vagrant first.

**Comment by phinze** [comment]
Looks good now - thanks!
