### ISSUE TITLE
Chef on Centos boxes seems not be installed

### ISSUE THREAD

**Issue by kikitux** [chef/bento#352]
on  packer file, chef.sh script is called without arguments

checking the boxes on vagrantcloud/atlas, they don't have chef installed

when I run the script manually, this is what happen:

sh chef.sh 
downloading https://www.getchef.com/chef/install.sh
  to file /tmp/install-chef.sh
trying wget...
/tmp/install-chef.sh: option requires an argument -- v
usage: /tmp/install-chef.sh [-p] [-v version] [-f filename | -d download_dir]

**Comment by juliandunn** [comment]
The boxes don't have Chef or Puppet or anything installed by default.

Don't use the `chef.sh` here to install Chef; just `wget https://www.chef.io/chef/install.sh` and run that.
