### ISSUE TITLE
Parallels boxes?

### ISSUE THREAD

**Issue by rmoriz** [chef/bento#371]
Can chef build and provide boxes for parallels, too? https://github.com/chef/bento/blob/master/README.md

At least on osx parallels has the best performance and the best feature set, Fusion still can't deliver the features of VMware Workstation and also requires a paid vagrant plugin. Also paralles provides and supports a free vagrant plugin, see https://github.com/Parallels/vagrant-parallels

**Comment by rickard-von-essen** [comment]
This is a interesting topic that I'm interested in driving forward.
As I see it there three options:

1. Chef start maintain builds also for PD. Best for users of Bento with PD.
2. Chef/Bento push metadata to Atlas (vagrant-cloud) referencing boxes built and uploaded by some community members (i.e. me). This requires some synchronisation but similar to one 1) for the users.
3. Bento's documentation instructs everybody to override PD's box to something else maintained by the community. This requires nearly zero work for Chef and clearly separate "official" boxes from community maintained, but requires most "configuration" for users. Example config:
```ruby
config.vm.provider "parallels" do |p|
  p.vm.box = "rickard-von-essen/opscode_centos-7.1"
end
```

Do _Chef Inc_ have any input on this?

**Comment by rmoriz** [comment]
Option 1. would be the best. However maybe _Parallels, Inc._ can be motivated to provide/build boxes and integrated as you describe in your Option 2. Since they are already activily maintaining their own Vagrant plugin (that's why it is free and not payware, like the one for Fusion), maybe they will see a benefit in supporting bento, too. (=> hint for Chef-Partners?)

Technically Packer is be able to build PD boxes, so it's just about pre-building+distiribution of the boxes.

**Comment by cheeseplus** [comment]
Adding this here for cross-reference purposes: https://github.com/chef/ohai/pull/557/files

**Comment by rmoriz** [comment]
`In Parallels we build our official boxes using templates based on Bento project.`

see http://parallels.github.io/vagrant-parallels/docs/boxes/packer.html

**Comment by legal90** [comment]
Yep. I'm from Parallels and we are open for communication and collaboration :)

Chefs, seems like community really want to see Vagrant boxes for `parallels` provider as part of your `chef/*` boxes on Atlas. 
If you are interested on it and ready to build Parallels boxes on your side, Parallels can provide you a pack of licenses for Parallels Desktop for Mac. 
If it is needed, we can also provide you an option to store result box files on our CDN.

And, of course, we are ready to support and maintain Parallels-related part of bento templates for Packer.

cc:\ @juliandunn

**Comment by cheeseplus** [comment]
@legal90 this is great to hear!

I'll see if I can poke some folks internally to get this moving forward. Fwiw @juliandunn isn't shepherding Bento any longer even though I'm sure he is happy with this development.

Feel free to contact me at the GH listed e-mail regarding licenses and I'll start the conversation. I think the only tricky bit is us getting the boxes to our S3 as that is where test-kitchen pulls them from as opposed to Atlas but I believe we push to both - just an implementation detail that I'm sure we can figure out.

**Comment by juliandunn** [comment]
That's great to hear, and yes @cheeseplus is right that I have relinquished my stewardship of Bento due to ENOTIME. You can look in [MAINTAINERS.md](https://github.com/chef/bento/blob/master/MAINTAINERS.md) to see who is now responsible.

**Comment by thasmo** [comment]
Nice to see progress on this! :+1:

**Comment by cheeseplus** [comment]
Done @8a424e2900148bb8d732604844b4e18bce064d07

**Comment by legal90** [comment]
@cheeseplus Thank you! :trophy:

**Comment by rickard-von-essen** [comment]
Awesome! :+1:
