### ISSUE TITLE
Upload Ubuntu 15.04 to S3 Bucket

### ISSUE THREAD

**Issue by fnichol** [chef/bento#376]
Activities to complete this issue:

- [x] Upload vmware/opscode_ubuntu-15.04_chef-provisionerless.box
- [x] Upload virtualbox/opscode_ubuntu-15.04_chef-provisionerless.box
- [x] Upload vmware/opscode_ubuntu-15.04-i386_chef-provisionerless.box
- [x] Upload virtualbox/opscode_ubuntu-15.04-i386_chef-provisionerless.box
- [x] Create Atlas box for ubuntu-15.04
- [x] Create Atlas box for ubuntu-15.04-i386
- [ ] Update README.md with new URL links

**Comment by lamont-granquist** [comment]
:+1:

**Comment by fnichol** [comment]
Ready to rock on this, pending S3 credentials which I clearly don't have yet :crying_cat_face:

**Comment by thasmo** [comment]
:+1:

**Comment by fnichol** [comment]
Update: got me some credentials, and uploads in progress :smile:

**Comment by thasmo** [comment]
Awesome! :)

**Comment by fnichol** [comment]
Done and done!
