### ISSUE TITLE
Debian 8.1

### ISSUE THREAD

**Issue by fnichol** [chef/bento#379]
Once 8.0 has flowed through, we should be able to get this one done quickly.

**Comment by rmoriz** [comment]
Just a bit confused as the 8.0 image already reports to be 8.1?!

```
vagrant@default-debian-80:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.1 (jessie)
Release:	8.1
Codename:	jessie
```

**Comment by fnichol** [comment]
@rmoriz Woah, that is odd! I'm pretty suspect of [this now](https://github.com/chef/bento/blob/master/scripts/debian/update.sh#L4) and think that's not quite correct. What do you think?

**Comment by rmoriz** [comment]
yes, good catch!

**Comment by fnichol** [comment]
I'm doubling checking the man page now, but I'm fairly sure this *could* upgrade to the latest point release? I'm a bit more familiar with `apt-get dist-upgrade` from Ubuntu, so just want to make sure I understand.

**Comment by rmoriz** [comment]
not sure, problem is that the 8.0.0 images are already gone…

**Comment by cheeseplus** [comment]
Done  @ 00798d975dd6e28475925932acc34d234deb4d57

**Comment by rfc1459** [comment]
@fnichol: from apt's POV there is no such thing as a point release, so an `upgrade` or a `dist-upgrade` will inevitably pull in the latest available packages from the archive.

That's _intended behaviour_, point releases are part of the normal update track of a Debian (major) release. This also means that if you want to differentiate (say) 8.0 and 8.1 you will end up with an image lacking potentially critical security updates.

**Comment by cheeseplus** [comment]
With 617d007dae96ee52872ca194d28b8eb252083e08 this is complete: 8.0 definitions removed, 8.1 templates built/uploaded, and links updated.
