### ISSUE TITLE
debian-7.8 box broken by VMWare Fusion 7.1.1 to 7.1.2 update

### ISSUE THREAD

**Issue by RobbKistler** [chef/bento#397]
Short story:

The debian-7.8 1.0.0  vagrant box uses has Linux kernel 3.2.65.  Later distro updates of Debian 7.8 pull in kernel 3.2.68.  This kernel has a change that breaks VMWareFusion’s hgfs host file system drivers on a few Linux distros, see this thread  at [communities.vmware.com](https://communities.vmware.com/thread/502554).  

This is fine as long as you don't update Debian, but...

VMWare “fixed” the hgfs problem in Fusion 7.1.2 with vmware tools 9.0.3.  After updating Fusion, the vmware-tools automatically update.  At this point, the *updated* hgfs driver fails to compile because it only works with kernel 3.2.68.  This also breaks the vmware-tools automatic capability, which uses hgfs to get the new tools from the host.

The fix seems to be to update the chef/debian-7.8 box 
1.  Update Fusion to 7.1.2
2.  Update the box vm to the latest version of debian 7.8 (new kernel): apt-get update; apt-get upgrade
3.  Manually reinstall vmware-tools in the Box.

Once these updates are applied, the box seems to work fine if I downgrade to VMWare 7.1.1.

This issue probably applies to distros downstream from Debian, too.

**Comment by RobbKistler** [comment]
Maybe this is a dup of [Issue 377](https://github.com/chef/bento/issues/377)

**Comment by cheeseplus** [comment]
We've rebuilt the boxes with the latest version @8a424e2900148bb8d732604844b4e18bce064d07

**Comment by RobbKistler** [comment]
Still doesn't work with VMWare Fusion 7.1.2 or Fusion 8.

**Comment by cheeseplus** [comment]
@RobbKistler just to confirm - this is the new box hosted out of the bento namespace https://atlas.hashicorp.com/bento/boxes/debian-7.8?

**Comment by RobbKistler** [comment]
Yes, bento/debian7.8 version v2.2.0
The symptom is the same -- stuck waiting for the HGFS driver to come up.

```==> client: Waiting for HGFS kernel module to load...```

**Comment by RobbKistler** [comment]
Root cause is still the same -- bad behavior in the vmware-tools updater.  A newer version of Fusion triggers the vwware-tools to self-update, which then break against the kernel version in the Debian 7.8 image.

**Comment by RobbKistler** [comment]
The problem might be from 250efaa58ad8ff239afabdc7a44a14564d530116.  The cleanup script removes the linux kernel headers and the compiler.  This seems like a great thing to do, but the, but the vmware-tools need the headers and compiler to rebuild the hgfs module.  The vmware-tools automatically update when there is a new version available.  

I see this error in /var/log/vmware-tools-upgrader.log with a timestamp of the time I do "vagrant up":

>WARNING: This program cannot compile any modules for the following reason(s)...
>
>- This program could not find a valid path to the kernel headers of the running
>kernel.  Please ensure that the header files for the running kernel are
>installed on this sytem.'

One option would be to leave the packages required by vmware tools (kernel headers, gcc, make, binutils).  Another might be to configure vmware-tools to not auto-update.

**Comment by dilas** [comment]
@RobbKistler you can use: https://github.com/rasa/vmware-tools-patches

Works nice on VMWare Fusion 7.1.2 and Debian 8.2.

**Comment by cmluciano** [comment]
I'm seeing the same thing on Ubuntu-14.04 boxes at box patch 2.2.1

**Comment by cheeseplus** [comment]
2.2.2 was just recently released and should not have the issue.

**Comment by cmluciano** [comment]
👍 works well for me now :)
