### ISSUE TITLE
Inconsistent builds of freebsd-10.1-i386 and freebsd-9.3-i386

### ISSUE THREAD

**Issue by fnichol** [chef/bento#402]
I'm guessing that this is related to ZFS being used on a 32-bit release with a small amount of RAM (currently 512MB). The FreeBSD wiki has a section on [i386/ZFS tuning](https://wiki.freebsd.org/ZFSTuningGuide#i386) and seems to hint at dragons ahead.

What I'm seeing is a stall somewhere around `cleanup.sh` and `minimize.sh` like so:

```
    virtualbox-iso: + rm -rf /usr/src/COPYRIGHT /usr/src/LOCKS /usr/src/MAINTAINERS /usr/src/Makefile /usr/src/Makefile.inc1 /usr/src/ObsoleteFiles.inc /usr/src/README /usr/src/UPDATING /usr/src/bin /usr/src/cddl /usr/src/contrib /usr/src/crypto /usr/src/etc /usr/src/games /usr/src/gnu /usr/src/include /usr/src/kerberos5 /usr/src/lib /usr/src/libexec /usr/src/release /usr/src/rescue /usr/src/sbin /usr/src/secure /usr/src/share /usr/src/sys /usr/src/tests /usr/src/tools /usr/src/usr.bin /usr/src/usr.sbin
```

When I inspect the processes on the VM I see that the SSH client session is no longer present. My guess is that the process of filling (or cleaning) the filesystem is causing system instability and eating the SSH client connection. For the moment, I'm no much closer to figuring out a reasonable way forward. Perhaps we don't *really* need the 32-bit templates?

\cc @cheeseplus

**Comment by cheeseplus** [comment]
So I've seen similar behaviour in recent testing although didn't run it down this far. I'm all for dropping i386 for FreeBSD unless anyone has stern objections. We don't have an i386 for CentOS7 and I'm fairly sure nobody will be kicking down the door for i386 FreeBSD builds.

**Comment by yzl** [comment]
@cheeseplus I wouldn't describe it as "kicking down the door", but Chef does supports i386 FreeBSD builds for the client, so in some abstract sense, I'd like to have the box if it isn't too much of a Thing.  If it is, we can definitely accommodate doing development/maintenance on that code in ec2, but it's one more difference that someone needs to remember/track.

(The irony that I am the one saying this is just awful.)

CentOS 7 does not provide an i386 iso, which is why we don't build the corresponding box.

**Comment by cheeseplus** [comment]
@yzl well with a response like that I can hardly disagree ;)

Hooray for irony and FreeBSD i386 support

**Comment by yzl** [comment]
@cheeseplus If it turns out to be awful, I am fine with dropping FreeBSD i386 support.  Or...do we have statistics for box downloads?  We probably use that box only _very_ occasionally, and if no one else is depending on it...

**Comment by cheeseplus** [comment]
My thinking is such that for i386 we can totally maintain FreeBSD builds, just not with ZFS. I think that is a fine middle ground, thoughts?

**Comment by fd1e4020** [comment]
By the way, I'm able to successfully build FreeBSD 10.2 i386 using default options with VirtualBox and Parallels; for VMware Fusion Pro RAM needs to be bumped up to 1024MB.

**Comment by cheeseplus** [comment]
@fd1e4020 good to know - for us the issue has been consistently building the boxes, especially with ZFS as the filesystem. ZFS doesn't like 32bit at all so it seems like if we publish the boxes we might want to choose an alternate FS for reliability sake.

**Comment by cheeseplus** [comment]
Closing this one for now as it's mostly informational.
