### ISSUE TITLE
vagrant box `chef/freebsd-10.0`: Unable to install packages

### ISSUE THREAD

**Issue by fd0** [chef/bento#407]
First: Thanks for providing the boxes for easy use with vagrant!

I was trying to use the box `chef/freebsd-10.0` with a shared folder of type `rsync`. On `vagrant up`, vagrant installs rsync, which failed with the following error message:

    ==> freebsd: Installing rsync to the VM...
    The following SSH command responded with a non-zero exit status.
    Vagrant assumes that this means the command failed!

    pkg install -y rsync

    Stdout from the command:

    Updating repository catalogue
    Incremental update completed, 24348 packages processed:
    21196 packages updated, 1774 removed and 3152 added.

    Stderr from the command:

    pkg: package field incomplete: comment
    pkg: Unable to find catalogs

Upon manual inspection I found that `pkg install rsync` indeed fails because the package version could not be found. This is caused by an error in the file `/etc/pkg/FreeBSD.conf`, which references the `latest` release. It may have worked when the box was released, but in the meantime FreeBSD 10.1 was published, so `latest` points to `release_1` instead of `release_0`.

The original content of the file is:

    # $FreeBSD: release/10.0.0/etc/pkg/FreeBSD.conf 258710 2013-11-28 14:24:26Z gjb $
    FreeBSD: {
      url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest",
      mirror_type: "srv",
      signature_type: "fingerprints",
      fingerprints: "/usr/share/keys/pkg",
      enabled: yes
    }

For the FreeBSD 10.0 box, the third line should be changed to reference `release_0`, like this:

    # $FreeBSD: release/10.0.0/etc/pkg/FreeBSD.conf 258710 2013-11-28 14:24:26Z gjb $
    FreeBSD: {
      url: "pkg+http://pkg.FreeBSD.org/${ABI}/release_0",
      mirror_type: "srv",
      signature_type: "fingerprints",
      fingerprints: "/usr/share/keys/pkg",
      enabled: yes
    }

Could you please either publish a new version of the `freebsd-10.0` box or publish `freebsd-10.1`?

**Comment by cheeseplus** [comment]
Published @8a424e2900148bb8d732604844b4e18bce064d07 FreeBSD 10.2

**Comment by fd0** [comment]
Cool, thanks!
