### ISSUE TITLE
chef.github.io/bento is outdated

### ISSUE THREAD

**Issue by moonglum** [chef/bento#409]
I wanted to check, which versions of Ubuntu are available as Bentos. Did not find 15.04 there, thought that it didn't exist. I was sad :cry: Then I checked the README.md and found that it indeed exists – so I was happy :joy_cat: Please update the [Homepage](http://chef.github.io/bento) to show the recent version of the README.

Thanks for this awesome project :heart:

**Comment by cheeseplus** [comment]
Fixed!
