### ISSUE TITLE
Using bento boxes with Vagrant

### ISSUE THREAD

**Issue by moonglum** [chef/bento#410]
Are the [vagrant base boxes on Atlas](https://atlas.hashicorp.com/chef) the up to date boxes of this project? If so, we could add some information about that to the README.

**Comment by chris-rock** [comment]
+1 would be great to discover the boxes via atlas

**Comment by cheeseplus** [comment]
Not but they will be very soon!

Stay Tuned

**Comment by cheeseplus** [comment]
@8a424e2900148bb8d732604844b4e18bce064d07 and https://atlas.hashicorp.com/bento

:tada:

**Comment by moonglum** [comment]
Awesome!!! Thanks ☺️

**Comment by chris-rock** [comment]
awesome work. thanks @cheeseplus
