### ISSUE TITLE
rhel/centos 6 and 7, virtualbox guest additions

### ISSUE THREAD

**Issue by charlesyan** [chef/bento#412]
It does not look like virtualbox guest additions are properly installed. Looking through the code, vmtools,sh, it is not likely kernel modules are properly built and installed. The following code snippet should make things work better, only tested with 6.6 and 7.1, new code in ```code```

virtualbox-iso|virtualbox-ovf)
```
    OS_VER=`cat /etc/redhat-release | grep -o '[0-9]\.[0-9]'`;
    echo $OS_VER;

    case $OS_VER in
        '6.6') rpm -Uvh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm;;
        '7.1') rpm -Uvh http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm;;
        *) echo "only 6.6, and 7.1 are supported currently";;
    esac

    yum -y install gcc dkms make bzip2 perl wget curl;    
    yum -y install gcc kernel-devel-`uname -r` kernel-headers-`uname -r`;  
    export KERN_DIR=/usr/src/kernels/`uname -r`
```
    mkdir -p /tmp/vbox;
    ver="`cat /home/vagrant/.vbox_version`";
    mount -o loop $HOME_DIR/VBoxGuestAdditions_${ver}.iso /tmp/vbox;
    sh /tmp/vbox/VBoxLinuxAdditions.run \
        || echo "VBoxLinuxAdditions.run exited $? and is suppressed." \
            "For more read https://www.virtualbox.org/ticket/12479";
    
    lsmod |grep -i vbox;

    umount /tmp/vbox;
    rm -rf /tmp/vbox;
    rm -f $HOME_DIR/*.iso;
    ;;

**Comment by cheeseplus** [comment]
So we've just rebuilt these boxes at the latest definitions and my test seem to indicate that the guest additions are installed properly in 6.7 and 7.1

How are you determining that the modules are not installed?

**Comment by cheeseplus** [comment]
Thus far I've no evidence this condition exists. Feel free to re-open with repro steps and software versions.
