### ISSUE TITLE
We need fedora-22 for DNF testing

### ISSUE THREAD

**Issue by lamont-granquist** [chef/bento#419]
title sez it all.  blocked on DNF testing.

**Comment by rickard-von-essen** [comment]
See #418 

Note: these boxes include also includes the ```dnf-yum``` package.

**Comment by cheeseplus** [comment]
Added both definitions but given some weird issues with i386 builds detailed here https://github.com/chef/bento/pull/431 we've only published the x86_64 build for the time being.
