### ISSUE TITLE
minimize.sh fails with no swap partition

### ISSUE THREAD

**Issue by beddari** [chef/bento#420]
With set -e this line will exit minimize.sh if we got no swap partition, seems like that wasn't the intention ...

https://github.com/chef/bento/blob/master/scripts/common/minimize.sh#L3

**Comment by fnichol** [comment]
@beddari  Oh yes, a great point. I was trying to skirt around the platforms that didn't have swap (or even the `/sbin/blkid` command) to preserve the previous behavior. While I don't normally like doing this, do you think a `swapuuid="`/sbin/blkid -o value -l -s UUID -t TYPE=swap`" || true;` would be an okay-ish fix?

**Comment by beddari** [comment]
Yes,
```
swapuuid="`/sbin/blkid -o value -l -s UUID -t TYPE=swap || true`";
```
... the closest well-tested portable shell code to grab from is probably https://github.com/chef/opscode-omnitruck/blob/master/views/install.sh.erb ;-)

**Comment by sheldonh** [comment]
#469 applies a more conservative approach than a blanket ignore. It's not as nice to read, but it does deal with just the special case of swapless builders.
