### ISSUE TITLE
Missing 13 Boxes

### ISSUE THREAD

**Issue by radepal** [chef/bento#427]
I can't download  centos-6.7 virtualbox box
I parsed READM.md and can't find 13 of boxes:

tail -n 88 README.md |awk 'NF' |cut -d" " -f2 |parallel --gnu --keep-order 'curl -s --head {}|head -n1;echo {};echo;' |grep 404 -A1
HTTP/1.1 404 Not Found
http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.7-i386_chef-provisionerless.box
--
HTTP/1.1 404 Not Found
http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.7_chef-provisionerless.box
--
HTTP/1.1 404 Not Found
http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_centos-6.7-i386_chef-provisionerless.box
--
HTTP/1.1 404 Not Found
http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_centos-6.7_chef-provisionerless.box
--
HTTP/1.1 404 Not Found
http://opscode-vm-bento.s3.amazonaws.com/vagrant/parallels/opscode_centos-6.7-i386_chef-provisionerless.box
--
HTTP/1.1 404 Not Found
http://opscode-vm-bento.s3.amazonaws.com/vagrant/parallels/opscode_centos-6.7_chef-provisionerless.box
--
HTTP/1.1 404 Not Found
http://opscode-vm-bento.s3.amazonaws.com/vagrant/parallels/opscode_freebsd-9.3-i386_chef-provisionerless.box
--
HTTP/1.1 404 Not Found
http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_freebsd-10.2-i386_chef-provisionerless.box
--
HTTP/1.1 404 Not Found
http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_freebsd-10.2-i386_chef-provisionerless.box
--
HTTP/1.1 404 Not Found
http://opscode-vm-bento.s3.amazonaws.com/vagrant/parallels/opscode_freebsd-10.2-i386_chef-provisionerless.box
--
HTTP/1.1 404 Not Found
http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_opensuse-13.2-x86_64_chef-provisionerless.box
--
HTTP/1.1 404 Not Found
http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_opensuse-13.2-x86_64_chef-provisionerless.box
--
HTTP/1.1 404 Not Found
http://opscode-vm-bento.s3.amazonaws.com/vagrant/parallels/opscode_opensuse-13.2-x86_64_chef-provisionerless.box

**Comment by cheeseplus** [comment]
Thanks for reporting this!

For the CentOS 6.7 boxes, that was a configuration issue that has been corrected and they should be uploaded to S3 properly now.

For the Freebsd i386 boxes, I've removed those from the supported matrix for the time being due to https://github.com/chef/bento/issues/402 but I left the link placeholders for if/when we resolve the issue.I guess I could remove the anchors or you can modify the script, whichever is easiest.

**Comment by cheeseplus** [comment]
As for the OpenSuSE 13.2 boxes those were missed because these boxes diverged from the naming scheme we use elsewhere. I've uploaded the box under both names to deal with both cases.

**Comment by radepal** [comment]
Thanks !!

Centos-6.7 is where is expected now.

I made a script only for check so.
