### ISSUE TITLE
fedora-22 Bento Box Corruption?

### ISSUE THREAD

**Issue by st-isidore-de-seville** [chef/bento#432]
Hey gang,

I am trying to use the fedora-22 bento box with test-kitchen/kitchen-vagrant/virtualbox.  Everytime I try to run a test against fedora-22, i get the following error message:

```
STDERR: The box failed to unpackage properly.  Please verify that the box file you're trying to add is not corrupted and try again.  The output from attempting to unpackage (if any):

x Vagrantfile
x box.ovf
x metadata.json
x package-fedora-22-x86_64-disk1.vmdk: truncated gzip input
bsdtar.EXE Error exit delayed from previous errors.
```

I just wanted to get your take on the issue.  I tried clearing out my vagrant.d folder multiple times in case the download itself failed.

Thanks in advance!

**Comment by kelcecil** [comment]
I'm running into the same issue trying to use the Fedora 22 box.

**Comment by cheeseplus** [comment]
Are these both Windows hosts? 
What version of vagrant?

I see bsdtar.exe in there and there were several issues with the pacakged BSDtar in past versions of vagrant. These boxes currently unpack without issue on OS X and Linux.

**Comment by st-isidore-de-seville** [comment]
I was running on Windows in the GitHub bash environment.  That being said, I had used the Fedora boxes previously without incident.

**Comment by cheeseplus** [comment]
This vagrant issue has some more detail https://github.com/mitchellh/vagrant/issues/3674

**Comment by kelcecil** [comment]
It's failing for me on Ubuntu 15.04 using Vagrant 1.7.4 with the following message:
```
==> master: Adding box 'kube-fedora22' (v0) for provider: virtualbox
    master: Downloading: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-22_chef-provisionerless.box
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

x Vagrantfile
x box.ovf
x metadata.json
x packer-fedora-22-x86_64-disk1.vmdk: truncated gzip input
bsdtar: Error exit delayed from previous errors.
```

**Comment by st-isidore-de-seville** [comment]
The Fedora 21 box unpackages for me as well using my aforementioned Windows/GitHub Bash setup.

**Comment by cheeseplus** [comment]
It appears that the box copy from Atlas to S3 broke this release which is why the tests didn't catch it as they run against the bento org in Atlas. I've forced a re-upload and it appears to be working correctly now.

**Comment by kelcecil** [comment]
Thanks @cheeseplus! I'll test shortly and report back.

**Comment by st-isidore-de-seville** [comment]
Thanks @cheeseplus.  I will test when I get home and will report back as well!

**Comment by kelcecil** [comment]
It's working for me now @cheeseplus. Thanks again!

**Comment by cheeseplus** [comment]
Seem like we're good now so I'm closing the issue - thanks for the catching this @st-isidore-de-seville!

**Comment by st-isidore-de-seville** [comment]
Thank you @cheeseplus for seeing this through!
