### ISSUE TITLE
Building boxes results in files with unhelpful names

### ISSUE THREAD

**Issue by davidjb** [chef/bento#433]
I'm using the latest version of Bento from git and finding that if I build a box like so, following the instructions:

```
packer build -only=virtualbox-iso -var 'mirror=...' centos-7.1-x86_64.json
```

the result is that the box is named ``builds/__unset_box_basename__.virtualbox.box``.  This isn't very helpful, especially when I was building two boxes from different OSes at the same time.

I note that the string ``__unset_box_basename__`` is hard-coded into most, but not all, provided JSON files in Bento and that the comment at https://github.com/chef/bento/issues/430#issuecomment-135843675 mentions how to configure the box basename.

If that comment is the prescribed the way to avoid the above problem, then may I suggest documenting this process in the README?  Otherwise, can a more useful name be set in each JSON file?

**Comment by cheeseplus** [comment]
Yes to both questions - PR #434 is addressing the first part and I'm planning on reverting to friendlier and more generally useful names.

That was initially something that was done to serve our needs for the `bin/bento` tool but has proven a bit more confusing than helpful.

**Comment by grtjn** [comment]
You might find these comments useful too: https://github.com/grtjn/centos-packer-templates#building-yourself
