### ISSUE TITLE
Vagrant Up Boxes

### ISSUE THREAD

**Issue by Dev-Dipesh** [chef/bento#435]
I've build ubuntu box with name starting from `__unset_box_basename__`, which I can fix by simply changing the base_box variable in packer file. However my concern is after building the box 

1. how can I use it in virtualbox. On vagrant up it gives me:

```
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.
```
I don't know whether creating a separate vagrantfile is a good idea, 

2. I wan't to provision it with my Ansible scripts but don't know where I can actually define them. As running from windows I can't run ansible locally and have to use a shell script to locate in generated box, which I wan't to achieve at the time of building it.

**Comment by cheeseplus** [comment]
We've addressed the box naming issue in https://github.com/chef/bento/commit/fa8b33d1ba294417555cd938fa625fc17049d05f

The boxes have embedded vagrantfiles so `vagrant init` is the command you'd want to use to get a base Vagrantfile and then you can customize it from there. These boxes are built without CM provisioners, they are meant to be base boxes and you can use tools like `test-kitchen` to provision as part of testing or customize the definitions if you want pre-baked CM.

**Comment by Dev-Dipesh** [comment]
Thanks!
Could you tell me the purpose of files in `vagrantfile_templates` and how they are connected?

**Comment by cheeseplus** [comment]
vagrantfile_template is a key for the Packer post-processor to allow you to override the default Vagrantfile - we only do this for some boxes as illustrated here: https://github.com/chef/bento/blob/fa8b33d1ba294417555cd938fa625fc17049d05f/freebsd-10.2-i386.json#L154

**Comment by Dev-Dipesh** [comment]
I've looked in packer document but can't find such a key, is it custom or default?
Do you know where I can find all packer different keys?

Also it might be a good idea to have a [Gitter](https://gitter.im/) account for the repo, that will prevent from opening issues for simple queries.

**Comment by cheeseplus** [comment]
The only documentation is here: https://www.packer.io/docs/post-processors/vagrant.html

That said it's just overriding the default Vagrantfile so the documentation is really part of Vagrant more than Packer. 

This is a fairly low traffic repo in terms of issues and development so a Gittr channel is a bit overkill - especially given that 99% of the questions overlap with Packer.
