### ISSUE TITLE
Ubuntu 14.10 boxes missing on Atlas

### ISSUE THREAD

**Issue by thasmo** [chef/bento#443]
Is it on purpose that the Ubuntu 14.10 boxes haven't been migrated to the new [Bento account on Atlas](https://atlas.hashicorp.com/bento/)?

**Comment by cheeseplus** [comment]
Somewhat - Ubuntu 14.10 was EOL'd July 13 2015. Normally we remove the template as as well which I haven't done just yet.

**Comment by thasmo** [comment]
Ah, alright - legit. Thanks!
