### ISSUE TITLE
Debian 8.2 vagrant box doesn't have HGFS kernel module

### ISSUE THREAD

**Issue by TeroPihlaja** [chef/bento#463]
Looks like the 8.2 version of Debian for VMware is missing the HGFS kernel module (VMware tools).

This means that shared folders don't work and provisioning with chef_solo fails.

Here's the exact box version:
==> default: Adding box 'bento/debian-8.2' (v2.2.1) for provider: vmware_desktop
    default: Downloading: https://atlas.hashicorp.com/bento/boxes/debian-8.2/ver
sions/2.2.1/providers/vmware_desktop.box

And the actual error message reported by Vagrant:
"The HGFS kernel module was not found on the running virtual machine.
This must be installed for shared folders to work properly. Please
install the VMware tools within the guest and try again. Note that
the VMware tools installation will succeed even if HGFS fails
to properly install. Carefully read the output of the VMware tools
installation to verify the HGFS kernel modules were installed properly."

**Comment by cheeseplus** [comment]
@TeroPihlaja this is actually a known issue across ALL boxes that is being resolved (at least for the latest tools) in the next build

**Comment by cheeseplus** [comment]
Should be resolved @efeb14a810551b06d7c5718639034cd9d3b45219

**Comment by cheeseplus** [comment]
If you still see issues please open a new issue with specific versions of the box, vmware fusion or workstation version, and host operating system.
