### ISSUE TITLE
The download link to fedora 21 vmware 64 is broken

### ISSUE THREAD

**Issue by kopwei** [chef/bento#472]
The download [link](http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_fedora-21_chef-provisionerless.box) for fedora 21 vmware box is not working and this result in kubernetes cluster booting failed

**Comment by cheeseplus** [comment]
Not sure what broke (there were no build errors) but investigating and pushing a new build through to ensure it's not a process problem.

**Comment by cheeseplus** [comment]
The box is up now and this can be closed.
