### ISSUE TITLE
Organize Templates into Folders

### ISSUE THREAD

**Issue by cheeseplus** [chef/bento#478]
Given that all the templates are in the root directory it's visually messy.

- Organize for sanity
- Organize old/EOL templates accordingly.

Still thinking how best to do this but dropping this as a place holder for discussion.

**Comment by atomic-penguin** [comment]
do it :+1:

**Comment by cheeseplus** [comment]
Thinking for now just current and EOL - would need to modify all the templates though given the path changes. Not sure where to put the common stuff like HTTP but kind of want to leave it alone for simplicity and de-dupe.
