### ISSUE TITLE
/dev/sr0 is readonly

### ISSUE THREAD

**Issue by LudwigHoff** [chef/bento#480]
Hi Guys, sorry to bother you but I am having issues building using Packer v0.8.6 on Yosemite with (paid) fusion standard (not pro).

My google-fu is clearly not up to this, so in desperation I am asking you.  Sorry for this. 

Maybe you might have seen this:

dracut-initqueue[xxx]: mount: /dev/sr0 is write-protected, mounting read-only
dracut-initqueue[xxx]: RTNETLINK answers: File exists
<waits for quite a few seconds>....
dracut-initqueue[xxx]: Warning: Could not boot.
              Starting Dracut Emergency Shell...

Please close straight away if this question is not appropriate.

**Comment by rickard-von-essen** [comment]
```mount: /dev/sr0 is write-protected``` is just noice. There is nearly no info in your report, run packer with debug logging and gist the log, see http://packer.io/docs/other/debugging.html. You probably get a quicker answer if you send the question to the Packer Google group, see http://packer.io/community.

**Comment by LudwigHoff** [comment]
Cheers!

**Comment by rickard-von-essen** [comment]
Close?

**Comment by cheeseplus** [comment]
Closing!

**Comment by LudwigHoff** [comment]
Sorry Cheeseplus

so sorry.  Only just noticed this.

An upgrade to 8.0.2 of VMWare and it all worked fine.  :-/

(And a revert and it didn't work again).

Sorry to have bothered.

**Comment by cheeseplus** [comment]
Oh no worries at all @LudwigHoff - I was only closing as it seemed like the issue was just a warning and the question was answered. Always feel free to open issues even if it's just a question.
