### ISSUE TITLE
Proposal: Fedora 22 for libvirt provider

### ISSUE THREAD

**Issue by aanm** [chef/bento#481]
Can you create boxes for `libvirt` provider?

**Comment by cheeseplus** [comment]
We could but we've not really got the infra for it at this time since the build hosts are OSX at the moment. This isn't to say we can't use Atlas or a Linux build node to do so though but it's just not at the top of the priority queue.

**Comment by cheeseplus** [comment]
Closing this as Fedora 22 is EOL
