### ISSUE TITLE
Ubuntu 15.10

### ISSUE THREAD

**Issue by rickard-von-essen** [chef/bento#482]
Add [Ubuntu 15.10](http://releases.ubuntu.com/15.10/) boxes.

**Comment by rickard-von-essen** [comment]
Blocked by [Launchpad Ubuntu - Debian installer #1505839](https://bugs.launchpad.net/ubuntu/+source/debian-installer/+bug/1505839), also see boxcutter/ubuntu#22.

**Comment by cheeseplus** [comment]
Merged https://github.com/chef/bento/pull/483 with hack
