### ISSUE TITLE
ARM builds

### ISSUE THREAD

**Issue by jmthackett** [chef/bento#486]
It'd be really great if there were builds for ARM for use on boxes like Scaleway C1s, Cubiebox etc.

**Comment by cheeseplus** [comment]
Not sure how we'd accommodate these as those are baremetal services - I know they use images but we'd need the boxes themselves to build or test the images.

**Comment by tethra** [comment]
To be a bit more specific, it'd be nice if this worked on ARM in general. I'm not sure how portable between flavours of ARM an image like this can be, though.

There are *some* things that can be done using qemu for emulation - it has various types of ARM available for emulation, which if you install QEMU (I'm on debian 8.2) you can see by doing `qemu-system-arm -machines list`

I've tried this - so far unsuccessfully - and the result is here:
https://github.com/tethra/bento/blob/debian-armhf-build/debian-8.2-armhf.json

The issue I'm having is that packer isn't being helpful in logging the output of its commands, or very clear on what it is doing. I'm watching netstat while the VM boots and the VNC console comes up and see it getting to opening up VNC, but I've not succeeded in getting any output from the VM and packer hangs forever. I'm a bit new to packer, so I've not managed to pry any useful information out of it about whether it uses extra qemu flags I'm not supplying etc. 

Scaleway have their own images (eg https://github.com/scaleway/image-debian ) which appear to be based on docker images (eg https://hub.docker.com/r/armbuild/debian/ ), which might be useful to look at.

Alternatively, I'd be happy to provide access to a box to build / test on :)

**Comment by cheeseplus** [comment]
I feel like the idiosyncracies of ARM and the services/emulators that support it may prevent this from being broadly useful but I'd be happy to accept PRs. That said I can't see it being a viable artifact to maintain in our CI/CD at this time although I am definitely open to the possibility.

**Comment by cheeseplus** [comment]
It also looks like the VNC and networking blockers have been hit by others as well https://github.com/annonymouse/rpi-qemu-up#why-not-packerio

**Comment by cheeseplus** [comment]
Closing this for now but still open to idea and PRs - just don't think it's viable as part of a stable build pipeline for us but we could add definitions if we had easy (free) ways to test them.
