### ISSUE TITLE
Fedora 22 & 23 i386 box not possible to build

### ISSUE THREAD

**Issue by rickard-von-essen** [chef/bento#488]
Kickstart of Fedora 22 & 23 i386 boxes fails Kickstart due to https://bugzilla.redhat.com/show_bug.cgi?id=1264571 
I'll close this when the upstream bug is resolved.

**Comment by rickard-von-essen** [comment]
PR #418 is affected by this issue.

**Comment by cheeseplus** [comment]
Yep I think that even 21 has an issue too for i386 when I try to build as well.

**Comment by cheeseplus** [comment]
This shows closed so closing here too as Fedora 22 is EOL - we can open a separate issue if 23 is still affected. https://bugzilla.redhat.com/show_bug.cgi?id=1264571
