### ISSUE TITLE
Any support (or planned support) for building Amazon AMIs?

### ISSUE THREAD

**Issue by Joseph-R** [chef/bento#490]
Hey guys!

So I'm evaluating Packer for building Amazin AMIs, but then I found the Bento project.  I know this is mainly a project for re-using Packer templates to crank out boxes for the local providers (VirtualBox, VMWare, etc).  

But is there any plan to extend support to the cloud providers?

Regards,
Joe Reid

**Comment by cheeseplus** [comment]
Closing for lack of comment - feel free to re-open in the future with any thoughts.

**Comment by Joseph-R** [comment]
If the goal of Bento is to build minimal base OS images, then I would probably agree that there isn't much point in supporting AMI builds.  As you have stated, others are already doing that.  

I am interested in moving towards an immutable model, where I build AMIs with Chef and Packer prior to deploy time.   Spooling up pre-built images and tying everything together with abstracted network services (for user management, databases, network addressing, etc) could save me a lot of headaches at deploy time.

This move is largely sparked by a series of issues we've had at deploy time with Chef provisioning or chef code.  Even tested code.  I don't want to scrabble to figure out or debug a configuration issue at deployment time.  Especially if it appears to be something weird with Chef itself.  

So we want to move configuration management earlier into the process and pre-bake images to reduce the number of surprises we see during deployments.  It's hard to get much simpler than "spool up this AMI and check out this app container".

If that is not a use case the Bento project is interested in supporting, I can understand that.

**Comment by cheeseplus** [comment]
So moving to a hybrid or fully immutable model is something we see lots of folks doing. Packer is often a component of this process but the templates themselves are usually far too specific to be generally useful (in the case of Bento template) as they'd apply your specific configuration (cookbooks for example).

It's not that we aren't interested, it's that we aren't exactly capable of addressing that particular concern - your templates are AMI artifacts are yours. It sounds like you might want to create your own templates and build your own Packer pipeline or check out [Atlas](https://atlas.hashicorp.com/help/packer/artifacts/creating-amis) which offers this kind of service already. Happy to offer any assistance from how we've build our pipelines as well.
