### ISSUE TITLE
Fedora 23 x86_64 and virtualbox: no vboxsf

### ISSUE THREAD

**Issue by Tcharl** [chef/bento#500]
Hi,

I don't know if its a real bug, but if it can help...
I used packer to build the F23-x86_64 iso with the latest VirtualBox (5.0.0.r101573), but it looks like something wrong appends during vbguest additions.

Running this image in vagrant (vbguest plugin installed):

Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant

Regards,

**Comment by cheeseplus** [comment]
I'll give this a look but just so you know the latest VirtualBox is 5.0.10 (r104061)

**Comment by rickard-von-essen** [comment]
Do upgrade VirtualBox, they have fixed several things for running with Linux 4.2. See https://www.virtualbox.org/wiki/Changelog

**Comment by Tcharl** [comment]
I really thought I installed the latest virtualbox, maybe in my dreams (I really should stop IAC by night).
Thank you and sorry for the inconvenience.

Charlie
