### ISSUE TITLE
RHEL 6.7 image has wrong guest

### ISSUE THREAD

**Issue by wyaeld** [chef/bento#501]
https://github.com/chef/bento/blob/master/rhel-6.7-x86_64.json#L47 should be `"rhel6-64"` as it is in https://github.com/chef/bento/blob/master/rhel-6.6-x86_64.json#L47 not `"oraclelinux"`

**Comment by wyaeld** [comment]
thankyou

**Comment by cheeseplus** [comment]
Fixed @d8a8de7
