### ISSUE TITLE
OpenSUSE Leap (and Tumbleweed)

### ISSUE THREAD

**Issue by rickard-von-essen** [chef/bento#504]
There are two new types of OpenSUSE, Leap and Tumbleweed.

- Leap is OpenSUSE's new release which is the upstream of SLES, much like Fedora is for RHEL.
- Tumbleweed Is a rolling release with all package that passed OpenSUSE's QA. This might prove a challenge to implement Ina good way coping with the constant updates.

Is Chef interested in adding Leap and possible Tumbleweed? If so I can start working on two PR's.

**Comment by juliandunn** [comment]
@rickard-von-essen I think we'd be interested in Leap, but probably not something like Tumbleweed, 'cause rolling releases are... rolling :-) and change too much for building a static image in Bento to be worth it.

**Comment by rickard-von-essen** [comment]
I'll open a PR in a few days when I'm back home with Leap.
