### ISSUE TITLE
Uncompressed boxes for VMware and Parallels are to large 

### ISSUE THREAD

**Issue by rickard-von-essen** [chef/bento#505]
I have been digging a bit in the effectiveness of [minimize.sh](https://github.com/chef/bento/blob/master/scripts/common/minimize.sh). My conclusion is that everything is good with VirtualBox.

E.g. CentOS 7.1 x86_64 produces a box that is 343 MB and uncompresses to 358 MB with minimisation, without it would be 485 MB and 505 MB.

But comparing that with VMware where a minimised box is 444 MB, but uncompresses to **1.1 GB**! Without minimisation it is slightly worse with 606 MB and 1.5 GB. ~~It even gets worse~~ with Parallels where a minimised box is 407 MB and uncompressed **~~1.6 GB~~ 1.0 GB**.

----

_Why is VMware and Parallels x3 worse than VirtualBox on space efficiency?_ I think we need to find out and see if there is anything we can do about it.

----

All numbers I found out can be [viewed in my spread sheet](https://docs.google.com/spreadsheets/d/1jSrwB-WhxQBAjn6G6rnRl6VuPvtRsUYG-nWSB7vp2Rs/edit?usp=sharing).

UPDATED: Updated numbers for Parallels after taking into account https://github.com/chef/bento/issues/505#issuecomment-163539506

**Comment by rickard-von-essen** [comment]
CC: @legal90

**Comment by legal90** [comment]
About Parallels Desktop - I guess that the situation will be much better with the next Packer version (0.9.0), due to `CompactDisk` step for `parallels-iso` builder: https://github.com/mitchellh/packer/pull/2731

**Comment by rickard-von-essen** [comment]
@legal90 that improves Parallels boxes to be in parity with VMware, but it is still strange that VirtualBox is about 1/3 the size. Also the improvement isn't that significant on file systems other that ext3. For example btrfs and the BSD file systems.

**Comment by cheeseplus** [comment]
Now that 0.9.0 is out, how are we looking and is this still a concern?

**Comment by rickard-von-essen** [comment]
I think this is better since v0.9.0 but still VMware and Parallels boxes are x3 VirtualBox but that is probably something only VMware and Parallels them self can improve on. Closing for now.
