### ISSUE TITLE
Publish Ubuntu 15.10 boxes on Atlas

### ISSUE THREAD

**Issue by thasmo** [chef/bento#506]
Noticed they've already been added to the Bento project but are still missing on Atlas.

Any chance they'll be published on Atlas too?

**Comment by cheeseplus** [comment]
So I'm currently at an impasse with these boxes cause of this issue: https://gist.github.com/brbsix/b70413dec907906ef659

They will build just fine but won't pass the TK test which, in my mind, is basic enough that it should work without issue.

I'm going to try to solve this soon with one of the recommended workarounds

**Comment by thasmo** [comment]
@cheeseplus, did you have time to look at this already?

**Comment by cheeseplus** [comment]
I've not had time unfortunately but it's high on the bento priority list which is part of a larger test-kitchen related list.

**Comment by cheeseplus** [comment]
Revisited this one and the only thing preventing a publish is that installing the virtualbox tools seems to fail for what seems like kernel or header related reasons so our test which sets up a shared folder fails. It builds fine for Parallels and Vmware Fusion. I can publish now and have the shared folder broken while I investigate further - not sure if that helps or not.

**Comment by rmoriz** [comment]
@cheeseplus maybe you can increase the prio on this, given the imminent release of Ubuntu 16.04 LTS we probably will have the same issues with 15.10…

**Comment by cheeseplus** [comment]
See https://github.com/chef/bento/pull/551

**Comment by cheeseplus** [comment]
Done https://github.com/chef/bento/releases/tag/2.2.5

**Comment by Maks3w** [comment]
This box still pending of to be published on Atlas

**Comment by cheeseplus** [comment]
@Maks3w it is https://atlas.hashicorp.com/bento/boxes/ubuntu-15.10

How are you determining it's not being published out of curiosity?

**Comment by cheeseplus** [comment]
@Maks3w actually see what it is - Atlas API doesn't seem to ever make a box public even if you tell it to so I had to manually make it public.

Sorry about that, it was published but just private - will add an extra check as part of validation to re-apply this change as it seems to never work at the outset.
