### ISSUE TITLE
Ubuntu 12.04 HGFS module failing in VMWare

### ISSUE THREAD

**Issue by zxaos** [chef/bento#512]
Possibly related to #496 and #283, the Ubuntu 12.04 box fails to start up properly with bento/ubuntu-12.04   (vmware_desktop, 2.2.2).

Like usual, manually installing build-essentials, the appropriate kernel headers, and running `vmware-config-tools.pl` resolves the issue, but it definitely doesn't work out of the box.

**Comment by cheeseplus** [comment]
What version of vmware?

**Comment by zxaos** [comment]
8.0.2

**Comment by cheeseplus** [comment]
Fixed in 2.2.3
