### ISSUE TITLE
error when building boxes with packer 

### ISSUE THREAD

**Issue by babatundebusari** [chef/bento#514]
I get the following errors when  building MacOS boxes with packer. Had no issues building other boxes like CentOS but the issue is with MacOS

```
$ packer build -only=virtualbox-iso macosx-10.11.json
virtualbox-iso output will be in this color.

Build 'virtualbox-iso' errored: Error parsing checksum: encoding/hex: invalid byte: U+005F '_'

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error parsing checksum: encoding/hex: invalid byte: U+005F '_'

==> Builds finished but no artifacts were created.
```

This is ran on a Windows 10 machine with git, vagrant, virtualbox and packer installed

**Comment by cheeseplus** [comment]
Please see: https://github.com/chef/bento#mac-os-x

You have to provide the DMG and checksum yourself due to Apple licensing restrictions.
