### ISSUE TITLE
VirtualBox: bento/centos-7.1 fails building VBGA due to missing kernel-devel package

### ISSUE THREAD

**Issue by andy-maier** [chef/bento#517]
Hi, the current version of the `bento/centos-7.1` box for VirtualBox has an outdated kernel (relative to the latest available in CentOS 7.1), and does not have the `kernel-devel` package installed. Combined with the fact that a binary `kernel-devel` package for CentOS 7.1 is only available in its latest version, this leaves users with no good choices:
- Installing the missing `kernel-devel` package causes its latest version to be used, causing the build process of the VBGA to fail with the widely discussed Make error that the include directory for the Linux kernel headers was not found.
- Updating `kernel` and installing `kernel-devel` gets them in sync but this requires a reboot before actually building the VBGA, which the `vbguest` plugin does not do. As a result, the VBGA update process has broken the VBGA installation, causing the box to be broken because it now fails when it attempts to establish shared folder access, plus it cannot fix that by rebuilding VBGA.
- Re-building `kernel-devel` from its sources in the CentOS Vault repo for a version that matches the kernel version.
- The `vbguest` plugin could do something about it, but that is not easily implemented. See [vbguest issue 161](https://github.com/dotless-de/vagrant-vbguest/issues/161).

This is a major issue for VirtualBox-based boxes of CentOS 6.7, 7.1, or 7.2, because for those versions, the older binary versions of `kernel-devel` are not provided anymore. But it is also an (admittedly smaller) issue for any older versions of CentOS.

I suggest that in any Bento boxes based on CentOS, a `kernel-devel` package gets installed that matches their kernel version. This is even more important than having the VBGA installed at the latest version, because the VBGA update can be done using the `vbguest` plugin (if the `kernel` and `kernel-devel` versions match).

**Comment by martin-langhoff** [comment]
+1 on this. I have filed a bug against vbguest suggesting enabling the Vault repos (see https://github.com/dotless-de/vagrant-vbguest/issues/223 ) . This improves chances of success, but isn't bulletproof -- for example CentOS 6.8 bento box contains a kernel from CentOS 6.7 -- the 'vault' repos are not up to date (probably an upstream CentOS problem). 

Including kernel-devel for the matching kernel would be a definite improvement.

**Comment by cheeseplus** [comment]
What is the present state of things? Still a problem?

**Comment by alanthing** [comment]
For what it's worth, you can still get previous versions of `kernel-devel` from http://vault.centos.org. The following is crude and only tested on 7.2 URLs, but perhaps this could be the foundation to help someone: https://gist.github.com/alanthing/efd909473988a43aca686a1f785cf8bb

Sadly, `/etc/yum.repos.d/CentOS-Vault.repo` on a fully-updated 7.3 system doesn't contain sources for 7.2.1511. If it did, you would be able to `rpm -q kernel --queryformat '%{VERSION}-%{RELEASE}\n' | xargs -I{} --no-run-if-empty yum --enablerepo="C7.?.????-base" --enablerepo="C7.?.????-updates" -y install "kernel-devel-{}"` and get `kernel-devel` for any installed `kernel`.

**Comment by cheeseplus** [comment]
Given the lack of traction here and the moving target, not sure what we could do more here. Going to close this one since we generally only track against latest for sanity and time sake.
