### ISSUE TITLE
sles 12 mirror no more exist

### ISSUE THREAD

**Issue by gimler** [chef/bento#520]
the mirror http://cdn.novell.com/prot/1RBC-NrdggI~ no more exist

https://github.com/chef/bento/blob/master/sles-12-x86_64.json#L188

**Comment by juliandunn** [comment]
As documented in the [readme](https://github.com/chef/bento/blob/master/README.md#proprietary-boxes), the SLES URLs are generally bogus and you should supply your own ISO if you are building a proprietary box.
