### ISSUE TITLE
Ubuntu: 12.04 / 14.04 baseboxes do not work with VMWare Workstation 12

### ISSUE THREAD

**Issue by tknerr** [chef/bento#522]
I tried the latest version (2.2.3) of the vmware baseboxes for ubuntu-14.04 and ubuntu-12.04

For both the box does not come up, as there is an error mounting the shared folders inside the guest.

Minimal repro case Vagrantfile:
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-12.04"
end
```

Output with error message:
```
W:\repo\tmp\vmwaretest>vagrant up --provider vmware_workstation
Bringing machine 'default' up with 'vmware_workstation' provider...
==> default: Cloning VMware VM: 'bento/ubuntu-12.04'. This can take some time...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 192.168.67.138:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Forwarding ports...
    default: -- 22 => 2222
==> default: Configuring network adapters within the VM...
==> default: Waiting for HGFS kernel module to load...
==> default: Enabling and configuring shared folders...
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["enableSharedFolders", "W:/repo/tmp/vmwaretest/.vagrant/machines/default/vmware_workstation/35fc6724-032c-4d7c-b81b-7312a194dd99/ubuntu-12.04-amd64.vmx", {:notify=>[:stdout, :stderr]}]

Stdout: Error: There was an error mounting the Shared Folders file system inside the guest operating system

Stderr:
```

I tried with "hashicorp/precise64" and it works, so I assume it must be something specific with the bento boxes. Also, disabling the shared folders brings up the box without errors, so it must be specific to the shared folder support.

I'm new to the VMWare provider, so if there is anything else I can provide for analysis (e.g. specific commands to run in the guest VM) please let me know.

Environment:

 * Windows 7
 * VMWare Workstation 12 Pro (12.1.0 build-3272444)
 * Vagrant 1.7.4
 * vagrant-vmware-workstation (4.0.5)
 * bento/ubuntu-12.04 and bento/ubuntu-14.04 (2.2.3)

**Comment by cheeseplus** [comment]
This is the same ol' VMware breaks every release everytime - we haven't updated our builders because fusion 8.1 is fundamentally broken (port forwarding bug)

**Comment by josegonzalez** [comment]
The fix for that bug is here: https://blogs.vmware.com/teamfusion/2016/01/workaround-of-nat-port-forwarding-issue-in-fusion-8-1.html

In the meantime, what do you suggest users on VMWare Fusion 8.1.x do?

**Comment by cheeseplus** [comment]
This is tricky:
I've not upgraded any pipelines or my own stuff so the best I can say is yell at Vmware because I don't want to break all the folks who heeded the warning from HashiCorp.

That said, Vmware has cut their entire Fusion team so we're all left in the lurch. Given that change I'm not expecting any more builds from them, at least anytime soon so I'll look at upgrading the pipelines and putting big warnings out around fixing the bug.

*hard side eye* @ vmware

**Comment by josegonzalez** [comment]
So parallels, amirite?

**Comment by cheeseplus** [comment]
That is exactly how I'm feeling <3 - also they (at least @legal90) have been super helpful in a way that VMware never has so I'm moving my local dev that way.

**Comment by ayanich** [comment]
I see a v2.2.4 build of the ubuntu-14.04 box on atlas, but I can't seem to pull it down because its not "released".  Whats the current holdup?

**Comment by cheeseplus** [comment]
No real holdup - there are still some issues with a few of the 2.2.4 builds (with regard to shared folders we're already working on a 2.2.5 release) and we just haven't merged the readme/changelog changes yet.

**Comment by cheeseplus** [comment]
Closing this one as we moved on and there even though 14.04 is still wonky it's got it's own issue.
