### ISSUE TITLE
Ubuntu: Don't use LTS Hardware Enablement Stack

### ISSUE THREAD

**Issue by legal90** [chef/bento#529]
Was originally reported by @byronclark here: https://github.com/Parallels/vagrant-parallels/issues/247

> The current Parallels Ubuntu 14.04 boxes use the LTS Hardware Enablement Stack (https://wiki.ubuntu.com/Kernel/LTSEnablementStack).
Usually this wouldn't be a big issue, but there's a fairly nasty bug that affects NFS and the install(1) command: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1445664.
I'd love to see these boxes built without the LTS Hardware Enablement Stack as recommended by Ubuntu for cloud and virtual images.

To Bento maintainers: What do you think about it? Is it reasonable to disable "LTS Hardware Enablement Stack" in bento templates for Ubuntu?

**Comment by yzl** [comment]
I am :+1: with not using the LTS Hardware Enablement Stack going forward.

**Comment by tas50** [comment]
We should probably disable it since the AWS AMIs don't use it. You'd be testing on a significantly different host than what you'd be using in prod if you were on AWS.

**Comment by cheeseplus** [comment]
I'm down with the change

**Comment by sethvargo** [comment]
This seems reasonable to me

**Comment by cheeseplus** [comment]
Seems we're now being bit by this with specifically VMware tools and it appears the only way to disable this is to start from an older image and upgrade. It's less than ideal but it may be the only solution.

**Comment by cheeseplus** [comment]
It seems that the only way to get non-HWE kernels is to start with older releases and upgrade all the way through - this is pretty lame on Canonical's part but I think that is how we best address this unfortunately.
