### ISSUE TITLE
/tmp directory is cleaned upon restart?

### ISSUE THREAD

**Issue by tknerr** [chef/bento#535]
I'm using the stock "bento/ubuntu-14.04" box, wondering why the `/tmp` directory is wiped out everytime I reload the VM.

Is this a feature of the bento boxes, or a plain Vagrant thing I just never realized until now?

**Comment by cheeseplus** [comment]
When you say reload, do you mean restart?

**Comment by tknerr** [comment]
Yes, I did a 'vagrant reload' which means restart. Trying to reproduce with
a minimal Vagrantfile and 'VAGRANT_NO_PLUGINS=1' env var...
Am 16.02.2016 6:12 nachm. schrieb "Seth Thomas" <notifications@github.com>:

**Comment by tknerr** [comment]
Minimal repro case:

```
$ vagrant init bento/ubuntu-14.04 --minimal
$ vagrant up
$ vagrant ssh -c "echo bla > /tmp/bla.txt"
$ vagrant ssh -c "ls -la /tmp"
$ vagrant reload
$ vagrant ssh -c "ls -la /tmp"         # <--- it's empty now
```

**Comment by tknerr** [comment]
happens with "hashicorp/precise64" too -- so must be a vagrant feature
