### ISSUE TITLE
CALL FOR MAINTAINERS

### ISSUE THREAD

**Issue by cheeseplus** [chef/bento#537]
In all caps cause I'd love to let more people in to help on this project cause I know we all love it. Sound off in comments if you'd like to be a maintainer and I'll be adding commit bits in the comings days.

Related to #536

**Comment by rickard-von-essen** [comment]
I would like to join.

**Comment by legal90** [comment]
Would like to join as well :)

**Comment by bflad** [comment]
As a long time user/lurker, I would love to assist!

**Comment by tas50** [comment]
As a huge consumer of this work count me in

**Comment by sethvargo** [comment]
Oh me me me

**Comment by tiwilliam** [comment]
I would love to help

**Comment by itmustbejj** [comment]
I'll gladly help as well, if you need it.

**Comment by cheeseplus** [comment]
Ok, everybody in this thread is now a maintainer. We're going by the general Chef RFC rules which is two +1s from maintainers to merge to master assuming no lieutenant vetoes the PR. As of right now I'm really the only lieutenant but we can sort that out depending on who has the most time and/or willpower

**Comment by chasebolt** [comment]
Count me in if you need more

**Comment by rickard-von-essen** [comment]
I think we need some sort of guideline on what boxes should contain, which OS/flavors we care about, the general goal of the project etc. So we have something to base decisions on. Otherwise I think there will be some sprawl between boxes and versions and harder to reject issues/PR's.

**Comment by cheeseplus** [comment]
@rickard-von-essen going to write a vision/roadmap on that front before closing this issue.

**Comment by therootcause** [comment]
count me in also if you need more.  
I maintain a fork, with daily validated .box builds. Among other things, my "interest" are around RHEL7 subscription & vmware tools.
Thank you for this incredibly useful project.

**Comment by cheeseplus** [comment]
@therootcause we can always use more eyes on PRs and the repo for sure - what is your fork taking care of that we aren't? May be easier to incorporate changes and do some sharing ;)

**Comment by cheeseplus** [comment]
Closing this now that the MAINTAINERS.md is updated.
