### ISSUE TITLE
Publish Debian GNU/Linux 8.3

### ISSUE THREAD

**Issue by kenhys** [chef/bento#546]
Debian GNU/Linux 8.3 support is merged https://github.com/chef/bento/pull/526 at Jan, 26 2016, but it seems that 8.3 boxes are not published yet.

Are there any blockers?
I'm happy those boxes are published before next Debian GNU/Linux point release comming.

**Comment by cheeseplus** [comment]
Done with https://github.com/chef/bento/releases/tag/2.2.5

**Comment by kenhys** [comment]
Thanks!
