### ISSUE TITLE
Box version documentation inconsistent

### ISSUE THREAD

**Issue by sktaylor** [chef/bento#549]
Altas show's a centos-7.1 and a centos-7.2. The readme only shows the 7.2 box, and http://chef.github.io/bento/ only shows the 7.1 box. I'd fix it myself, but I don't know if you plan to retire 7.1 or keep them both on atlas. I'd vote for the latter because having the base box go away is a pain, but either way the docs should be consistent. I can fix it if you let me know the plan.

Great boxes, thanks for providing these.

Best,

Kendrick

**Comment by cheeseplus** [comment]
There are a few things going on here:

1. In the Readme we only track latest of any distro like CentOS where the minor version supplants the former (7.2 being latest)
2. The doc site needs to get updated and I can fix that
3. We don't retire old boxes from Atlas but we don't necessarily update them when new tooling versions are released - when we get a nicer pipeline we'll automate this and try to build old definitions if people want them.

**Comment by cheeseplus** [comment]
I've updated the doc site and with the explanation given I'm closing this one.
