### ISSUE TITLE
Stripping man/docs removes audit rules

### ISSUE THREAD

**Issue by abriel** [chef/bento#564]
Hello,

with `yum info audit` I can confirm that the package audit is installed.
with `rpm -ql audit` I can see a list of files, including /usr/share/doc/audit-2.3.7/*
But those files are missing
`ls: cannot access /usr/share/doc/audit-2.3.7: No such file or directory`

CentOS 6.7
Can you help with that?
Thanks.

**Comment by abriel** [comment]
I think you strip all docs and mans, but sometimes some docs contains default behavior rules like audit package.
Thanks.

**Comment by tas50** [comment]
I removed the line on Fedora where we removed these. I think I had already added them back elsewhere. Let me know if you're still using Bento boxes and running into this problem.
