### ISSUE TITLE
Add the headless option for QEMU builders.

### ISSUE THREAD

**Issue by jmatt** [chef/bento#567]
I recently ran into a problem because the qemu builder doesn't use the headless option. It wasn't immediately obvious since other builders in the packer configuration were using the existing headless option: ``"{{user `headless`}}"``. So initially I just changed the variable to true and expected it to work. In the end I had to add it (or pass it in) manually.

I believe my use case is common and that the qemu builder should support the headless option. I am willing to implement the PR if there is interest.

**Comment by cheeseplus** [comment]
Feel free to add a PR - in the bento world, as we don't publish QEMU images to Atlas, I can't say it's a common use case to the degree of all the other builders but it's certainly something that would be fine to add in a PR.

This is to say, if it fixes your issue and others we'll happily merge it but aren't building or testing QEMU images at this time.

**Comment by cheeseplus** [comment]
Fixed by #570 and #572
