### ISSUE TITLE
bento/centos-7.2 hangs on during "vagrant up" if NIC Type is Am79C973

### ISSUE THREAD

**Issue by kjtanaka** [chef/bento#573]
If I change Network Adapter Type to Am79C973, `bento/centos-7.2` hangs on at "default: SSH auth method: private key" as shown below. The issue doesn't happen to `bento/centos-6.7`

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'bento/centos-7.2'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/centos-7.2' is up to date...
==> default: Setting the name of the VM: vagrant-centos7_default_1461613083801_37679
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
<======  Hangs on here  ======>
```

Here's my Vagrantfile

```ruby
Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.2"

  config.vm.provider "virtualbox" do |v|
    # change network adapter type and promiscuous mode
    v.customize ['modifyvm', :id, '--nictype1', 'Am79C973']
    v.customize ['modifyvm', :id, '--nicpromisc1', 'allow-all']
  end

end
```

Here're the versions of `bento/centos-7.2`, vagrant and virtualbox.
```
$ vagrant box list|grep bento/centos-7.2
bento/centos-7.2   (virtualbox, 2.2.5)

$ vagrant --version
Vagrant 1.8.1

$ VBoxManage --version
5.0.18r106667
```

Does anyone see the same problem?

**Comment by rmoriz** [comment]
May I ask why do change the nictype? I'm pretty sure this will change the MAC address and all udev/systemd/whatever-naming rules CentOS 7.2 uses to number ethernet devices.

**Comment by kjtanaka** [comment]
With default (Intel PRO/1000), Network Bridge doesn't work properly, so the change is needed when I test some network stuff with Docker or LXC. But I found the answer on the following link, it says `pcnet` is not supported by CentOS 7.
--> https://github.com/jpetazzo/pipework#virtualbox

So the right Vagrantfile looks like this:

```ruby
Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.2"

  config.vm.provider "virtualbox" do |v|
    # change network adapter type and promiscuous mode
    v.customize ['modifyvm', :id, '--nictype1', 'virtio']
    v.customize ['modifyvm', :id, '--nicpromisc1', 'allow-all']
  end

end
```

I  tested a few things, and confirmed network bridge worked fine with this one. Thanks!

**Comment by teugeny** [comment]
It does not work. The same problem.
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'bento/centos-7.2'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/centos-7.2' is up to date...
==> default: Setting the name of the VM: test_default_1475834694399_91907
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key

Here my vagrant settings

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.2"

  config.vm.provider "virtualbox" do |v|
    # change network adapter type and promiscuous mode
    v.customize ['modifyvm', :id, '--nictype1', 'virtio']
    v.customize ['modifyvm', :id, '--nicpromisc1', 'allow-all']
  end

end

**Comment by krasoffski** [comment]
This solution does not work with any VBox nic card.

**Comment by cheeseplus** [comment]
Hey folks, just to be clear bento doesn't support alternate nic cards as that's way out of scope and too many idiosyncrasies between various platforms. /cc @teugeny @krasoffski 

That said, the issues being seen here may be related purely to the permutation of bento version, virtualbox, and vagrant - so chasing the NIC issue may be a red herring (not the actual problem even though it looks like it)

<3 your friendly bento maintainer @cheeseplus

**Comment by krasoffski** [comment]
Thank you for your answer :-)

But what does mean `alternate nic cards`. I checked all possible variants of NIC for virtualbox 4.0.24 (from Ubuntu repos) and as a result no one is working on the latest release of bento/CentOS 7.2. There is no any problem with CentOS 7.2 version `v2.2.7`.
It would be great if share info what type of NICs are supported?

Sorry for barging but I need find a workaround for this problem.

**Comment by cheeseplus** [comment]
The biggest problem there is that virtualbox 4.0.24 is incredibly outdated - 5.1.8 is the latest and the current bento boxes were built against 5.1.6.

**Comment by krasoffski** [comment]
I also has checked with `VirtualBox 5.0.28` which is still actively maintained from VBox repos. The problem still exists.  
Anyway I'll check against `VirtualBox 5.1.6`.

Many thanks!

**Comment by cheeseplus** [comment]
5.0.28 is still maintained definitely but unfortunately vbox made breaking changes in a minor release (which in my book is real bad) and so supporting both 5.0 and 5.1 wasn't possible. 5.0.28 should work with bento boxes at version 2.2.9 but 2.3.0 requires 5.1. I don't expect either version would work against 2.2.7 given the age.

**Comment by krasoffski** [comment]
Thank you cheeseplus for you time,

The latest VirtualBox solved problem. :-)
But yep, this breaking changes of virtualbox look ugly.
