### ISSUE TITLE
VMware: use correct script flags based on version

### ISSUE THREAD

**Issue by dbirchak** [chef/bento#590]
I see that vmtools.sh has been updated to use --force-install over --default.
https://github.com/chef/bento/commit/a8f5ab4b90abac9371810d4050d1e957b61ba5d6

Is the --force-install tied to a specific version of vmware-install.pl?  I'm running VM Workstation 11.1 (VMware Tools 9.9.4 build-3193940) 
builds fail with 
/tmp/vmfusion-archive/vmware-tools-distrib/vmware-install.pl --force-install;

Error
vmware-iso: + /tmp/vmfusion-archive/vmware-tools-distrib/vmware-install.pl --force-install
    vmware-iso: VMware Tools 9.9.4 build-3193940 for Linux installer
    vmware-iso: Usage: /tmp/vmfusion-archive/vmware-tools-distrib/vmware-install.pl
    vmware-iso: [[-][-]d[efault]]
    vmware-iso: default: Automatically answer questions with the proposed answer.

Successful with 
/tmp/vmfusion-archive/vmware-tools-distrib/vmware-install.pl --default;

**Comment by rickard-von-essen** [comment]
Yes I think this changed in Workstation 12/Fusion 8, if you use an earlier version you have to revert to `--default`.

**Comment by davidmnoriega** [comment]
It's the new flag in VMware Tools 10.0+

**Comment by nickma** [comment]
It brakes compatibility with older pre 10.0.x VMWare Tools just FYI. Had the same issue until edited vmtools

**Comment by cheeseplus** [comment]
We can and should fix this one.

**Comment by cheeseplus** [comment]
Working on a fix now, should have a PR this evening.
