### ISSUE TITLE
Ubuntu 16.04: 70-persistent-net.rules "hack" messes with update-initramfs triggers

### ISSUE THREAD

**Issue by franklouwers** [chef/bento#592]
In all (?) Ubuntu bento boxes, a hack is used to fix ethx persistency (see https://github.com/chef/bento/blob/master/scripts/ubuntu/networking.sh). 

In Ubuntu 16.04, this breaks update-initramfs related tasks. You can trigger this by spinning up a new box, and installing a package that forces an update to initramfs. Eg:

root@default-ubuntu-1604:~# apt-get install xfsprogs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  xfsdump acl attr quota
The following NEW packages will be installed:
  xfsprogs
0 upgraded, 1 newly installed, 0 to remove and 20 not upgraded.
Need to get 596 kB of archives.
After this operation, 3,412 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 xfsprogs amd64 4.3.0+nmu1ubuntu1 [596 kB]
Fetched 596 kB in 0s (646 kB/s)   
Selecting previously unselected package xfsprogs.
(Reading database ... 34840 files and directories currently installed.)
Preparing to unpack .../xfsprogs_4.3.0+nmu1ubuntu1_amd64.deb ...
Unpacking xfsprogs (4.3.0+nmu1ubuntu1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up xfsprogs (4.3.0+nmu1ubuntu1) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Processing triggers for initramfs-tools (0.122ubuntu8) ...
update-initramfs: Generating /boot/initrd.img-4.4.0-21-generic
W: plymouth: The plugin label.so is missing, the selected theme might not work as expected.
W: plymouth: You might want to install the plymouth-themes and plymouth-label package to fix this.
cp: omitting directory '/etc/udev/rules.d/70-persistent-net.rules'
E: /usr/share/initramfs-tools/hooks/udev failed with return 1.
update-initramfs: failed for /boot/initrd.img-4.4.0-21-generic with 1.
dpkg: error processing package initramfs-tools (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 initramfs-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by rmoriz** [comment]
Ubuntu 15.10, 16.04+ uses Predictable Network Interface Names https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/ so we should be able to get rid of the hack with those versions (but keep it for the pre-systemd releases)
