### ISSUE TITLE
Virtualbox 5.0.8: builds for Ubuntu 16.04 fail

### ISSUE THREAD

**Issue by tizzo** [chef/bento#593]
When running builds my build always hangs on:

````
virtualbox-iso: Uncompressing VirtualBox 5.0.8 Guest Additions for Linux............
````

Entering the VM I see it was successfully uncompressed in the `/opt` folder.

**Comment by cheeseplus** [comment]
Have you tried with 5.0.16? - currently the latest, 5.0.20 introduces a regression/bug but I have only validated that 16.04 builds with 5.0.16.

**Comment by tizzo** [comment]
I can confirm that this works with 5.0.16. Thanks!

**Comment by cheeseplus** [comment]
Awesome, the tools at 5.0.20 are still sketchy and seem to introduce a regression but once that a new version is out I'll update the 16.04 boxes. Closing.
