### ISSUE TITLE
ubuntu 16.04 virtualbox box 2.2.7 isn't available

### ISSUE THREAD

**Issue by artem-sidorenko** [chef/bento#604]
https://atlas.hashicorp.com/bento/boxes/ubuntu-16.04

There is no box version 2.2.7 for virtualbox provider
(this version includes the fix for #592)

**Comment by cheeseplus** [comment]
Indeed, this is because the latest virtualbox tools (5.0.20) fail when building 16.04. I'm reverting a builder and will be pushing a build with 5.0.16 which is known working.

**Comment by cheeseplus** [comment]
Looks like I was able to get 5.0.20 installed and tested from a linux builder and not sure if this was resolved by packer or the vbox + linux combination. I've uploaded the box to Atlas so we should be good to go.
