### ISSUE TITLE
FreeBSD: Root password not set!

### ISSUE THREAD

**Issue by rickard-von-essen** [chef/bento#610]
The FreeBSD 9.3 and 10.3 boxes don't have any root password set allowing any user to become root with `su` without a password.

This is because the install scripts ([9.3](https://github.com/chef/bento/blob/master/http/freebsd-9.3/install.sh#L98) and [10](https://github.com/chef/bento/blob/master/http/freebsd-10/install.sh#L98)) are missing `-h 0`.
E.g.
`echo "vagrant" | pw -V /mnt/zroot/etc usermod root`
should be
`echo "vagrant" | pw -V /mnt/zroot/etc usermod root -h 0`

But fixing this causes the script execution to fail since no root password is given.
```json
      "execute_command": "{{.Vars}} su -m root -c 'sh -eux {{.Path}}'",
```

**Comment by rickard-von-essen** [comment]
One solution would be to install `sudo` in the install script and use `sudo` in the _shell_ provisioner. Another would be to allow `root` to ssh and use
```json
  "ssh_username": "root",
```

**Comment by cheeseplus** [comment]
Fantastic catch - I seem to recall us trying to avoid sudo on FreeBSD as it's not strictly required for the platform but it's probably sensible for these boxes.

**Comment by rickard-von-essen** [comment]
We install it anyway in [scripts/freebsd/sudoers.sh](https://github.com/chef/bento/blob/master/scripts/freebsd/sudoers.sh).
