### ISSUE TITLE
Push CentOS 6.8 to Atlas

### ISSUE THREAD

**Issue by alindeman** [chef/bento#613]
Hi folks,

I see the CentOS 6.8 build in the repository, but it's not available on Hashicorp's Atlas. Could it be pushed up there at some point?

Cheers,

**Comment by StephenKing** [comment]
Same for Debian 8.5. Anything wrong with automated uploads?

**Comment by tas50** [comment]
We currently lack a fully automated pipeline for bento so automated uploads aren't yet possible. It's definitely something we'd like to get done though.

**Comment by cheeseplus** [comment]
Closed by #626 and https://github.com/chef/bento/issues/627
