### ISSUE TITLE
apt.systemd.daily creates conflict in xenial64 box

### ISSUE THREAD

**Issue by foxx** [chef/bento#616]
```
==> default: + sudo apt-get update
==> default: E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
==> default: E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
```

To get around this, I've used `sleep 30` but this is hacky at best. It would be nice if cron paused was delayed whilst provisioning takes place, as executing `apt-get` during provisioning is a very common task.

**Comment by rmoriz** [comment]
is that maybe related to https://github.com/chef/bento/issues/609 ?

**Comment by foxx** [comment]
Ah yes, this is a duplicate of #609, ty
