### ISSUE TITLE
Possible to add docker box versions?

### ISSUE THREAD

**Issue by gsdevme** [chef/bento#624]
Im using these boxes for Kitchen CI, when trying to use the docker provider within Vagrant it fails due to no .box for Vagrant with the provider docker

Although kitchen-docker exists it doesn't really allow you to cache resources, any chance a docker provider could be added?

**Comment by cheeseplus** [comment]
Possible yes but between kitchen-docker and kitchen-dokken I'm not sure I entirely see the point. It's also adding another layer of build infra that for the same reasons seems unnecessary. This is much for the same reasons we don't do AMIs, there are better mechanisms that exists and while Vagrant can wrap them it offers little in the way of advantages to the more direct methods.

**Comment by gsdevme** [comment]
The main advantage I want it for is to allow the use of `vagrant-cachier`, we are currently using Vagrant on our machines when developing but our CI uses docker and they can be very slow as they continue to download packages each time when running a big suite.

Ref: 
https://github.com/fgrehm/vagrant-cachier

**Comment by cheeseplus** [comment]
Very familiar with vagrant-cachier (both good and bad) but making Vagrant the center of a docker workflow just feels slightly mismatched to me. That said I'd happily review a PR but as the sole person maintaining the build pipelines I'm weary to add more things to our already sprawling matrix.

**Comment by cheeseplus** [comment]
Closing this one out given the age and discussion above - we can revisit docker templates but if we do it will be with a PR.
