### ISSUE TITLE
2.2.8 virtualbox on Atlas missing?

### ISSUE THREAD

**Issue by gesinn-it** [chef/bento#630]
It seems, that 2.2.8 for _virtualbox_ (and _parallels_) is missing on https://atlas.hashicorp.com/bento/boxes/ubuntu-16.04.

**Comment by cheeseplus** [comment]
While these do build, neither is working with shared folders at the moment.

**Comment by gesinn-it** [comment]
I was using _ubuntu/xenial64_ with vagrant plugin _vagrant-vbguest_ and the following Vagrantfile snippet on a Win7 machine:

`config.vm.synced_folder ".", "/vagrant", :create => "true", type: "virtualbox"`

Beside other issues with _ubuntu/xenial64_, the shared folders was working for me then. Mmhhh.

My hope was, that _bento/ubuntu-16.04_ 2.2.8 could solve my `vagrant up` gets stuck with "Processing triggers for libc-bin (2.23-0ubuntu3) ..." issue.

**Comment by cheeseplus** [comment]
The 2.2.8 box will fix that part and I'll push them without a confirmed shared folder fix for the time being. vagrant-vbguest sidesteps the root problem here but a 2.2.9 should be incoming for the 16.04.1 update anyway.

**Comment by gesinn-it** [comment]
great! Many thanks @cheeseplus. If helpful, I can share my experience with 2.2.8 here and report, if the shared folder is working in my setup.

**Comment by gesinn-it** [comment]
How is it going with this one? Any updates? :-)

**Comment by cheeseplus** [comment]
https://atlas.hashicorp.com/bento/boxes/ubuntu-16.04/versions/2.2.8
