### ISSUE TITLE
Add box for openSUSE Leap 42.1 with virtualbox provider to Atlas

### ISSUE THREAD

**Issue by MrWong99** [chef/bento#631]
I wasn't able to any find openSUSE Leap 42.1 boxes build for the virtualbox provider. If it can be build please upload it to Atlas.

When I try to build the box by hand it fails during the OS autoinstallation...

**Comment by cheeseplus** [comment]
Last I tried it was failing on all providers but if it's working I am happy to push it.

**Comment by MrWong99** [comment]
The vmware_desktop box is already [available on Atlas](https://atlas.hashicorp.com/bento/boxes/opensuse-leap-42.1/) which is why I thought the box can be build in general.

**Comment by cheeseplus** [comment]
Right, that is the only platform we can get it to build properly on at present.

**Comment by cheeseplus** [comment]
Done - https://atlas.hashicorp.com/bento/boxes/opensuse-leap-42.1
