### ISSUE TITLE
Incorrect authorized_keys permissions set by scripts/common/vagrant.sh

### ISSUE THREAD

**Issue by inarush0** [chef/bento#636]
The last line in the script: chmod -R go-rwsx $HOME_DIR/.ssh; sets the authorized_keys permissions to 660. For ssh keys to work properly the permission level must be 600 for that file.

**Comment by cheeseplus** [comment]
While that sounds correct how are you verifying this is "broken"? Also if it's with Vagrant 1.8.5 / Vbox 5.1.2 there is a key permissions issue in the Vagnrat release https://github.com/mitchellh/vagrant/issues/7610

**Comment by inarush0** [comment]
Ah, that was the issue. Thanks!

**Comment by cheeseplus** [comment]
No problem, we got bit by it in our pipelines so I'm happy that helped you figure it out quickly 🎊
