### ISSUE TITLE
Execute "update" on Centos images

### ISSUE THREAD

**Issue by svpace** [chef/bento#639]
It seems like Ubuntu images already do that but I couldn't find it on Centos images.

**Comment by cheeseplus** [comment]
Indeed - the reason we didn't at the time was because if you upgrade a point release, say 7.1 then you will get 7.2. Now for the latest version, you definitely want to do it and it's something I'll get to fixing but we need to add some logic in there to allow one to not update.

**Comment by svpace** [comment]
I've "fixed" it locally by adding a remote repository on the kickstart file (therefore it is updated on install). But I don't know a way to make it optional using that strategy.
