### ISSUE TITLE
VirtulBox Guest Additions Installation Error in Fedora-23

### ISSUE THREAD

**Issue by hkarakose** [chef/bento#645]
I am using OSX El-Capitan and VirtualBox 5.1.10.

I have received following error during provision step of Fedora-23: 

```
An error occurred during installation of VirtualBox Guest Additions 5.0.10. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /Users/halil/Vagrant/bento_fedora-23
```

And after that I received following error during vagrant ssh: 

```
Halils-MacBook-Pro:bento_fedora-23 halil$ vagrant ssh
-bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
```

What is the impact of these errors?

**Comment by rickard-von-essen** [comment]
"Window System drivers" means you don't get any guest addition support for X (as in X11) but that is probably nothing you need. 

"setlocale: LC_CTYPE: cannot change locale (UTF-8)" is just showing a idiosyncrasy of OS X, it sets `LC_CTYPE` to `UTF-8` but on Linux it should prefixed with your language, e.g. `en_US.UTF-8`. If you set it in OS X before you ssh the warning will disappear.

**Comment by rickard-von-essen** [comment]
Closing since this is as expected.
