### ISSUE TITLE
centos vs. ubuntu kitchen converge issue

### ISSUE THREAD

**Issue by TemporarilyOffline** [chef/bento#646]
Not sure if this is the right place for this... not sure where to put it.

Given the .kitchen.yml file below, I can't get a successful `kitchen converge`.  If I switch to `ubuntu-14.04` it will work just fine.  Any suggestions?

The error message is just a repeated "Waiting for SSH service on 127.0.0.1:2222, retrying in 3 seconds" and eventually that will timeout and give "[SSH] connection failed, terminating..."

I've tried 4 different versions of Centos bento boxes from Atlas.

```---
driver:
  name: vagrant
  
provisioner:
  name: chef_zero
  environments_path: test/integration/environments
  client_rb:
    environment: kitchen
  require_chef_omnibus: true
  
platforms:
  - name: centos-7.2

suites:
  - name: web
    driver:
      network:
        - [ 'private_network', { ip: '192.168.33.70' } ]
      customize:
        memory: 2048
    run_list:
    - recipe[chef-base]
```

**Comment by cheeseplus** [comment]
Vagrant 1.8.5? If so it's busted for CentOS/RHEL platforms - see https://github.com/mitchellh/vagrant/issues/7610

**Comment by TemporarilyOffline** [comment]
That was it, thanks!
