### ISSUE TITLE
Speed up booting process for FreeBSD saving 10 seconds in boot time

### ISSUE THREAD

**Issue by amontalban** [chef/bento#649]
Fixed in #648

**Comment by amontalban** [comment]
@cheeseplus thank you for merging, just a quick question when can I expect this change going to image? Do you have any release cycle available so I can monitor it?

Thanks!

**Comment by cheeseplus** [comment]
There is no real official release cycle as such but once I've merged a batch of changes I typically build the images and upgrade the build pipelines within a week or so. Currently I'm checking out all the latest version of virtualization tools (parallels released a major release) but it shouldn't be too long.
