### ISSUE TITLE
Upgrade Ubuntu 14.04.1 to 14.04.5

### ISSUE THREAD

**Issue by fowlslegs** [chef/bento#652]
You're currently 4 point releases behind the latest for the Ubuntu trusty images.

**Comment by cheeseplus** [comment]
Actually we aren't ;)

The reason we do this is because of HWE which is not recommended for virtualized stacks - https://wiki.ubuntu.com/Kernel/LTSEnablementStack#Ubuntu_14.04_LTS_-_Trusty_Tahr

We start at 14.04.1 but upgrade the system to latest so that we aren't forced onto the HWE kernel.
