### ISSUE TITLE
Select the server task instead of the ubuntu-server task in the Ubuntu 14.04 preseed config

### ISSUE THREAD

**Issue by fowlslegs** [chef/bento#653]
In https://github.com/freedomofpress/securedrop/issues/1375#issuecomment-242696534 my colleague points out that in Ubuntu 14.04, the `ubuntu-server` task does not exist. In the comment below I suggest that it has been renamed as the `server` task, which I do think is the case. You probably want to confirm this, but I think what you want to be doing is selecting the `server` task in the preseed config instead of the `ubuntu-server` task.

**Comment by cheeseplus** [comment]
This seems legit but surprised nothing has blown up because of it - will open a PR if you don't get to it first.

**Comment by conorsch** [comment]
> surprised nothing has blown up because of it 

I'd assumed that the bento builds were intentionally extremely minimal, but omission of the `server` task is probably more minimal than intended.

**Comment by conorsch** [comment]
Updated the PR with changes to all Ubuntu builds with a Packer JSON config file in the top-level repo directory. Holler if there's an additional testing you'd like a hand with to help get this resolved.
