### ISSUE TITLE
Set UTF-8 locale by default

### ISSUE THREAD

**Issue by hauleth** [chef/bento#658]
Currently locale for Ubuntu 16.04 is `en_US` which forces PostgreSQL to use `LATIN1` charset instead of `UTF8`. It would be nice to have UTF-8 locale enabled by default.

**Comment by cheeseplus** [comment]
Would `en_us.utf8` be good enough?

**Comment by hauleth** [comment]
It would be perfect.

**Comment by fumiyas** [comment]
FYI.

* #531721 - bash: glob pattern "[A-Z]" matches "b", "c" .. and "z" on LC_ALL=en_US.UTF-8 - Debian Bug report logs  
  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=531721

I love C.UTF-8 that is available on Ubuntu 16.04, but I don't know PostgreSQL supports it or not.

**Comment by cheeseplus** [comment]
Fixed by #702 - if we need to make anymore changes here we can raise a new issue.

**Comment by scottjacobsen** [comment]
Will a new version of this box be released soon? It would be great to have this so I can get postgres going.

**Comment by cheeseplus** [comment]
For some value of soon - I am currently on the road for work without access to to quality bandwidth that is required to build these in a timely fashion. All the hypervisors dropped new versions quite recently so these have to be accounted for as some of the fixes, especially VirtualBox 5.1.10 which was released 2 days ago, are needed for some platforms to even build.
