### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by kevinburke** [chef/bento#663]
Hi,
I use the ubuntu boxes with VMWare, but get stuck on the "Waiting for HGFS..." screen when I boot a box. It looks like a fix was added here: 4591252939fc6cdb24dc80df05b2835ff84546d6

However this patch is not in the v2.2.9 release. Any chance of deploying a new Ubuntu box that contains this change?

**Comment by cheeseplus** [comment]
That commit doesn't necessarily fix the issue as this is also related to the version of vmware fusion. That commit was largely a re-organization and depending on the version of Ubuntu may or may not have anything to do with the issue.

I'm working on a release this week but we'd need more detail to determine if this actually fixes it.

**Comment by kevinburke** [comment]
> That commit doesn't necessarily fix the issue as this is also related to the version of vmware fusion. 

That may be - I observe that 'vagrant up' hangs on the "Waiting for HGFS..." dialog and I have to ctrl+c it. I can then run 'vagrant provision'. If I install open-vm-tools and create /mnt/hgfs, "vagrant up" does not hang.

**Comment by cheeseplus** [comment]
I take it this is 16.04 then?

**Comment by kevinburke** [comment]
Yep!


--
Kevin Burke
925.271.7005 | kev.inburke.com

**Comment by cheeseplus** [comment]
Rolled out 2.3.0 - this should be resolved for Fusion 8.5/Workstation 12.5

**Comment by kevinburke** [comment]
Thanks!
