### ISSUE TITLE
Centos 7.2 HGFS (Partially revert #638)

### ISSUE THREAD

**Issue by pmorton** [chef/bento#667]
Hi - I have been working with the Centos7.2 bento. The image that is currently published works perfectly. However if you use the current packer json in this repository, your vagrant box will never succeed because vagrant thinks that HGFS was never loaded. I spent a significant amount of time trying to figure out what was going on. It turns out that there was a refactor in June of the way that VM tools were installed. In that refactor the, centos was changed to a provider specific installer which only installed open-vm-tool. After spending hours troubleshooting the issue with the bento box that I built using this template... I found this http://partnerweb.vmware.com/GOSIG/CentOS_7.html. The long and short is that HGFS is _not_ distributed with open-vm-tools and that you _also_ need to install the commercial guest additions if you want shared folders to work. 

The fix should be easy, add `"scripts/common/vmware.sh"` somewhere around https://github.com/BIAINC/bento/blob/master/centos-7.2-x86_64.json#L151

**Comment by cheeseplus** [comment]
@pmorton what versions are in play? Fusion/Workstation, Vagrant, etc

**Comment by pmorton** [comment]
vmware fusion 8.5, MacOS Sierra, vagrant-share (1.1.5, system), vagrant-vmware-fusion (4.0.12), Vagrant 1.8.5.

I am very confident that this is a not a vagrant, vmware issue. You can repro this behavior in a couple of ways but the most basic is to Create a centos 7.2 VM (Mine has the latests updates installed). Install open-vm-tools. Share out a folder. Try to mount that folder with the mount command. The result is that mount fails because the vmhgfs file system is unknown.

If I am reading the packer definition properly, only open-vm-tools are installed which is what I have done in my repro case above. I can resolve this issue by following the directions in the vmware article. (Installing the VMWare guest additions).

**Comment by cheeseplus** [comment]
Confirmed this building latest, will be reverting the behaviour.
