### ISSUE TITLE
Ubuntu Desktop does not show vagrant user in LightDM greeter

### ISSUE THREAD

**Issue by courtarro** [chef/bento#668]
I'm working on a desktop-based project, so I installed the `ubuntu-desktop` package on the Bento base box `ubuntu-16.04`. Because the `vagrant` user is set to UID 900, the Ubuntu Desktop login screen doesn't show it. Instead, only the Guest account is listed. To fix this issue, I had to edit `/etc/login.defs` to change the following two lines:

    UID_MIN			 1000
    GID_MIN			 1000

to:

    UID_MIN			  900
    GID_MIN			  900

At that point, both `vagrant` and `vboxadd` appear on the login screen. Is there any particular reason why the `vagrant` user is set to a UID of 900 instead of 1000 or higher? 1000 seems to be the de-facto minimum for interactive users on modern Ubuntu installs.

**Comment by cheeseplus** [comment]
Likely because these boxes are specifically targetted to be lightweight base boxes so we use server packages and generally assume there is no desktop.

**Comment by rickard-von-essen** [comment]
Please PR this. Since we allow login for the vagrant user it should be an interactive (normal) user.

**Comment by courtarro** [comment]
It seems like a cleaner solution is to update the UID of the `vagrant` user to be 1000 or higher (and the GID of the `vagrant` group), rather than drop the minimum UID. The `vboxadd` user, for instance, is UID 999, so it will show up with my workaround, which is not ideal.

I also don't know how my workaround will affect future updates (via Apt) to `login.defs`.

The change to the `vagrant` UID (perhaps to 1000) would be pretty simple to make. Each Debian and Ubuntu config has a `preseed.cfg` file that specifies:

    d-i passwd/user-uid string 900

Unfortunately, this kind of change seems likely to cause problems with backward compatibility for everyone's provisioning scripts. I'm happy to submit a PR to make this change and continue discussions based on that.
