### ISSUE TITLE
CentOS 6.8 v 2.3.0 freeze at SSH

### ISSUE THREAD

**Issue by MarcFletcher** [chef/bento#681]
I've just tried upgrading my vagrantfile from (provider is virtualbox 5.1.2):

`config.vm.box = "bento/centos-6.7"`

to

`config.vm.box = "bento/centos-6.8"`

(everything else is the same) and when I do:

```
vagrant destroy
vagrant up
```

the VM just hangs on the first SSH connect:

```
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key

```

Switching back to the bento/centos-6.7 box resolves the problem. Any idea why the 6.8 version won't create?

**Comment by rickard-von-essen** [comment]
@cheeseplus Which VirtualBox version did you build with? There is a regression in VB resulting in that packer creates VM's with the nic disconnected. See https://github.com/mitchellh/packer/issues/3757

**Comment by MarcFletcher** [comment]
VirtualBox Version 5.1.2 r108956

**Comment by MarcFletcher** [comment]
I can confirm that upgrading to VB Version 5.1.6 r110634 resolved the problem for me.

**Comment by chris-fa** [comment]
@MarcFletcher did you have to delete some cache or global config or anything at all?  I also have 5.1.6 but it still hangs.

**Comment by MarcFletcher** [comment]
@chris-fa Nope, just a straight up install of the latest VB.
