### ISSUE TITLE
Build of CentOS 6.8 and 7.2 no longer working / hash mismatch

### ISSUE THREAD

**Issue by smithgcovert** [chef/bento#685]
I am not sure what is going on in CentOS land, but it seems that both the 6.8 and 7.2 DVD images' hashes have been changed.

The URLs are still there, at the same location, but when I try to run a build of either one of these, the build fails with a hash mismatch.

I happened to have a saved copy of those DVDs -- I was able to edit the iso_url to my own copy of the iso, and it was resolved.  

Unfortunately, just updating the hash value in the appropriate .json did not fix the problem for me.  When I did this, the packer build then failed at a later stage.

I did several checks - pulling the .iso from several mirrors, and they all had a different (and consistent) hash than that in the packer .json files.

**Comment by cheeseplus** [comment]
Could we get some more detail here?

- hashes that worked for you
- mirrors used
- packer versions

**Comment by smithgcovert** [comment]
I'm not sure what was going on -- I tried this for a full day, and kept having problems.  But I think my real problem was that I updated to Sierra Mac 10.12, and my Sophos AV reported problems under Sierra, and somehow the AV was messing up all of my downloads.  I'll close this issue.
