### ISSUE TITLE
vbox: Ubuntu-16.04 v2.3.0 fails to boot with network on vbox 5.0.x

### ISSUE THREAD

**Issue by jaraco** [chef/bento#686]
Using a late Virtualbox 5.0.26, bento/ubuntu-16.04 fails to boot after installing and instead encounters [this error reported here](https://ubuntuforums.org/showthread.php?t=2323253), reporting the error message:

```
A start job is running for raise network interfaces (2 minutes of 5 mins 1 sec)
```

After waiting for the full five minutes, the machine does boot, but the network interface doesn't get an IP address. Following the workaround in that article doesn't seem to correct for the condition.

I saw in another ticket that 2.3.0 was targeted to Virtualbox 5.1, which I see has been released for months and is later, even though Virtualbox 5.0 reports it's the latest when asked. I'll update and I suspect that will address the issue.

Should box version 2.3.0 be expected to work on Virtualbox 5.0?

**Comment by rickard-von-essen** [comment]
See my comment on https://github.com/chef/bento/issues/681#issuecomment-251881978 and follow the link to packer.

**Comment by jaraco** [comment]
Thanks @rickard-von-essen - now that you point it out, it seems obvious. Also, I confirmed updating to VirtualBox 5.1 also works around the issue. I don't think there's anything more to be done than what you've presented here. Thanks.

**Comment by markhorrocks** [comment]
I had the same issue on a Mac but the problem was that I had recently changed from using wifi to ethernet and just had the change the Bridged adapter setting to ethernet in the network settings.
