### ISSUE TITLE
CentOS 7.2 (and possibly 6.8) builds on Atlas are broken

### ISSUE THREAD

**Issue by ramereth** [chef/bento#690]
I'm not sure what happened, but the latest builds of CentOS on Atlas are broken. After the machine boots up, vagrant is never able to ssh into the VM. If I use the previous version of the box, it works fine.

**Comment by montge** [comment]
having similar issue, was using with Kitchen, I'm unable to ssh into the box.  This occurs with 2.3.0.  I reverted back to 2.2.9 and things seem to work fine.

**Comment by legal90** [comment]
It looks like a duplicate of https://github.com/chef/bento/issues/688
Please, try the solution mentioned here: https://github.com/chef/bento/issues/688#issuecomment-252404560

**Comment by cheeseplus** [comment]
The builds are not broken, they have just been built with newer versions of the hypervisors so you'll need to upgrade Virtualbox to 5.1.6. Closing as dupe.
