### ISSUE TITLE
Please publish Debian 8.6 vbox images

### ISSUE THREAD

**Issue by kenhys** [chef/bento#708]
After Debian 8.6 point release was released, it seems that Debian 8.6 support is already merged ( https://github.com/chef/bento/pull/671 ) about a month ago, but not yet published here ( https://github.com/chef/bento ).

I'm happy if Debian 8.6 vbox images are published.

**Comment by tersmitten** [comment]
+1

**Comment by cheeseplus** [comment]
They were already published - https://atlas.hashicorp.com/bento/boxes/debian-8.6

The readme just needs an update.

**Comment by kenhys** [comment]
Thanks. I confirmed that boxes are published on atlas.
By the way, It seems that boxes on s3 are not found yet. they are already marked as obsolete and will not be updated anymore?

**Comment by cheeseplus** [comment]
There isn't much good reason in maintaining S3 anymore, Atlas (which is CDNed by fastly)

**Comment by tersmitten** [comment]
@cheeseplus Thanks for the explanation

**Comment by kenhys** [comment]
Thanks, @cheeseplus !

**Comment by cheeseplus** [comment]
Closing this as it's answered - I'll be updating the readme and probably just removing the links in favor of pointing at Atlas (so I don't have to update things in two places).

Feel free to open another issue or ask further questions!
