### ISSUE TITLE
bento/ubuntu-16.04  virtualbox 2.3.0 hangs on boot

### ISSUE THREAD

**Issue by itsuugo** [chef/bento#713]
Vagrants time outs while booting, downgrading to 2.2.9 works fine

**Comment by rickard-von-essen** [comment]
Updated VirtualBox to 5.1.6

This duplicates #688

**Comment by itsuugo** [comment]
Apologize for the inconvenience , next time will  check first

**Comment by rickard-von-essen** [comment]
No worries.
