### ISSUE TITLE
Windows: timeout when starting ubuntu-16.04

### ISSUE THREAD

**Issue by ferrarimarco** [chef/bento#719]
Hi everyone.

I get a timeout when starting an ubuntu 16.04 box.

Specs:

- OS: Windows 7 x64
- Vagrant: 1.8.6
- Virtualbox: 5.1.8

I deleted all the boxes I had in my Vagrant setup just to be sure to start fresh.

Here is a log of the command line: [Vagrant cmd](https://github.com/chef/bento/files/594945/vagrant.bento.log.txt)

After enabling the GUI, I see that the box starts in Emergency mode, see my screenshot:

![image](https://cloud.githubusercontent.com/assets/621939/20354126/6ff56600-ac1d-11e6-8088-b9b7e756c104.png)

At first it seemed related to #688 but it's not the case (the cable set as "connected" in Virtualbox).

Thanks

**Comment by ferrarimarco** [comment]
Pressing CTRL-D boots into default mode. If you do this while Vagrant is trying to connect, it works.

**Comment by cheeseplus** [comment]
Has this been resolved by Vagrant 1.9.x? I seem to remember a linkage between these builds and this issue.

**Comment by ferrarimarco** [comment]
@cheeseplus I'll try and let you know.

**Comment by ferrarimarco** [comment]
@cheeseplus I tried with the latest Vagrant and I am not able to reproduce the issue anymore. Is there anything in the Vagrant changelog that makes you think this is solved? If so maybe this can be closed.

**Comment by cheeseplus** [comment]
There are several fixes regarding network as well as Windows (some subprocess fixes among other things) so pretty confident this was ironed out between 1.8.7-1.9.1.
