### ISSUE TITLE
Downloads don't resume

### ISSUE THREAD

**Issue by abumalick** [chef/bento#726]
Hello,
I tried to download `https://atlas.hashicorp.com/bento/boxes/ubuntu-16.04/versions/2.2.9/providers/virtualbox.box` without success because the download won't resume and I have very slow connexion. So after some times it eventually crashes and I have to start over again. I tested with `wget -c` and jdownloader without success.
Now I am downloading it on my server with ssh so I can download it while resuming the download ...

**Comment by cheeseplus** [comment]
Vagrant itself should resume the download if you are doing this via `vagrant up` or any other commands that cause the box to be downloaded. Closing this because it nothing to do with bento itself and is purely an Atlas/Vagrant issue.
