### ISSUE TITLE
SSH handshake failed with qemu and virtualbox

### ISSUE THREAD

**Issue by cvandome** [chef/bento#741]
Hello all !

I'm having troubles in running packer on ubuntu16.04 host.
I'm running packer in headless mode ans have this error once the VM have rebooted:
SSH handshake fail with qemu and virtualbox

The same setup work properly on makeOS Sierra.

For this test I'm using bento files without modifying anything except headless mode.

Thanks for help

**Comment by cheeseplus** [comment]
What version of VirtualBox - we don't really support the qemu builders as we have no infrastructure for VirtualBox that sounds like a version issue.

**Comment by cvandome** [comment]
virtualbox 5.0.24

**Comment by cheeseplus** [comment]
Latest bento boxes (2.3.x) will not work with anything below 5.1.6 and there are known issues there on the VirtualBox side.
