### ISSUE TITLE
CentOs 7 on vmware has non existent VMWareTools

### ISSUE THREAD

**Issue by spuder** [chef/bento#747]
```
 packer build --only=vmware-iso centos-7.3-x86_64.json
vmware-iso output will be in this color.

1 error(s) occurred:

* Bad source 'VMwareTools-10.1.0-4449150.tar.gz': stat VMwareTools-10.1.0-4449150.tar.gz: no such file or directory
```

This is caused by the following lines

https://github.com/chef/bento/blob/master/centos-7.3-x86_64.json#L138-L142

This was introduced here:

https://github.com/chef/bento/commit/292a39f432702a857e86121a0ebfdd8292f0f21b

The work around is to pre-download VMwareTools-10.1.0-4449150.tar.gz to your drive before running packer build. That is inconsistent with all other bento images, and is confusing if you aren't familiar with packer. 

Furthermore you must have a vmware account to download specific versions of vmware tools. Even if you have an account, vmware does not make it easy to download previous versions. The current download revision is `VMware-Tools-10.0.0-3000743.tar.gz` and there is no link I can find to download `VMwareTools-10.1.0-4449150.tar.gz`

![screenshot 2016-12-28 10 07 07](https://cloud.githubusercontent.com/assets/242382/21527009/89149a64-cce5-11e6-8992-ae0ea15630c8.png)

**Comment by rickard-von-essen** [comment]
I think you should complain to _VMware_ 😉

**Comment by spuder** [comment]
I think the centos 7 template should be consistent with others and not require specific files in specific directories. Go ahead and try and build it yourself, see how far you get.

**Comment by cheeseplus** [comment]
It's inconsistent because it's literally the only way to get it to build currently on 7.3 - please review the PR and commit for why this is - once vmware fixes it, I'll update but currently this is a problem on the VMware side.

**Comment by bdwyertech** [comment]
You can just download from vmware and replace `linux.iso` and `linux.iso.sig` with those in the archive.

For VMware Fusion, that's at `/Applications/VMware Fusion.app/Contents/Library/isoimages`

**Comment by cheeseplus** [comment]
The reason I didn't do that is that asking folks to modify their application files out of band felt slightly worse than having them sideloaded via Packer. The common vmware.sh script should work for this so when vmware updates things we'll go back to using it.

**Comment by bdwyertech** [comment]
Oh for sure, the real fix here is probably to get the [open-vm-tools package](https://git.centos.org/summary/rpms!open-vm-tools) updated to 10.1.0 

This line fixed it. https://github.com/vmware/open-vm-tools/blob/e0a7b4e98bd6d6af06d31212dfdc82610d37e4d3/open-vm-tools/modules/linux/vmhgfs/page.c#L1648

**Comment by mvermaes** [comment]
@bdwyertech I think CentOS will only receive an updated open-vm-tools when Red Hat releases one. It looks like [10.1.0 is in the works, at least for CentOS 6](https://bugzilla.redhat.com/show_bug.cgi?id=1408959) - I've added a request for RHEL/CentOS 7 to their Bugzilla as well now.

I'll be interested to try it out when available, as I had thought that the FUSE version of vmhgfs was not going to be supported with the older RHEL/CentOS kernels. The open-vm-tools release notes previously referred to a [4.0.0 kernel requirement](https://github.com/vmware/open-vm-tools/commit/41c0f0812fd02bf9db2c276c675549ce9685af8b#diff-5e601b5070ec55264211202a7cf0dacdL18), but that reference was removed when the docs were updated for 10.1, so maybe the requirement has changed.

The [VMware docs](http://partnerweb.vmware.com/GOSIG/CentOS_7.html) still refer to the need to install vmhgfs from the proprietary tools package though.

**Comment by skyzyx** [comment]
@bdwyertech: Wait, I'm confused. I'm able to build a working CentOS 7.3.1611 Vagrant box with Packer and the `open-vm-tools-10.0.5-2.el7.x86_64` package from the CentOS "os" repository.

Is there a hard dependency on the newer release that I'm missing? I had read (I can't remember where at the moment) that with CentOS 7, the classic VMware Tools package is deprecated in favor of OpenVM Tools.

> @cheeseplus: It's inconsistent because it's literally the only way to get it to build currently on 7.3 […]

Am I missing context?

----
**Update:** Ah, the HGFS problem.

I generally get around it by [using NFS](https://github.com/lru-packages/lru-buildbox-centos7/blob/feaf008e1f74f2a61d079b22bbc244d4841933e9/Vagrantfile#L40-L42) and [explicitly disabling HGFS](https://github.com/lru-packages/lru-buildbox-centos7/blob/master/Vagrantfile#L59) in my `Vagrantfile`.

But I can see why you'd want to fix that.

**Comment by cheeseplus** [comment]
Yep, HGFS despite all the "everything works with open-vm-tools" statement we still need proprietary. I'm also going to side for more compatible vs more "free as in beer" because of how these are consumed by users and the expectations therein.
