### ISSUE TITLE
Any plan to support Hyper-v boxes?

### ISSUE THREAD

**Issue by glasslion** [chef/bento#748]
Hi,
The new [Docker for Windows](https://docs.docker.com/engine/installation/windows/#docker-for-windows) is based on Hyper-V virtualization, which can not co-exist with other virtualization tech like Virtualbox amd VMware. Given Docker's huge popularity among the developer community, I guess more and more people will abandon Virtualbox in favor of Hyper-V.  There's only a few vagrant hyperv boxes. Is there any plans to support the Hyper-v boxes?

**Comment by rickard-von-essen** [comment]
I guess this could be interesting but there are some obstacles that need to be tackled. 

- The Hyper-V builder in Packer was just introduced in the latest Packer release (v0.12.1 - 15 dec) and probably have a lot of rough edges (v0.12.1 (December 15, 2016).
- This requires Windows to develop. The current three supported providers can run on macOS/Linux/Windows expect Parallels which is macOS only. But most/many contributors have Macs.
- The current build infrastructure runs macOS and Windows must be added to it.

If this is not added to the bento project I think it would be interesting to create a downstream project which supplies Hyper-V boxes based on the bento code base.

**Comment by cheeseplus** [comment]
We've thought about this in the past by converting virtual box images to Hyper-V but with the new Packer builds this potentially becomes much easier. However, from a build box standpoint HyperV is a bit of a pain since it precludes ANY other hypervisor's from running which effectively means a dedicated box which is less than ideal.

I wouldn't go so far as to say folks will abandon Virtual box wholesale as Docker brings its own set of "-isms" that often preclude it from being a choice. That said once we would certainly be open to accepting PRs for Hyper-V builder sections for templates but setting up the build infrastructure (which only works on MacOS and Linux, save Parallels) is a separate issue that depends on potential resources that I am unable to speculate on or guarantee at this time.

**Comment by wickedviking** [comment]
Would the Hyper-V builders be better suited as there own templates? The main issue I seem to be having with the hyperv builder is getting MS LIS (Linux Integration Services) installed and running correctly. LIS is bound to kernel versions and thus requires a reboot during the install process to switch to the new kernel prior to installing LIS. This means the kickstart file ends up with hyperv specific instructions as the LIS has to be enabled before Packer/Vagrant will be able to interact with the box (and run additional provisioners). 

I have managed a work around in my own projects by implementing a runonce solutions similar to http://serverfault.com/questions/148341/linux-schedule-command-to-run-once-after-reboot-runonce-equivalent

Probably not a good one size fits all solution for something like bento, but it illustrates the biggest pain point in getting packer to build linux vms for vagrant on hyperv. And this solution could easily be removed once the LIS is installed correctly and functioning.

**Comment by wickedviking** [comment]
Actually, I just figure out how to do away with the runonce thing all together.  So, my ks.cfg now installs the hyperv_daemons and enables them, which allows the ip reporting to work and the packer build script to connect via ssh and continue with provisioners. However, this still results in hyperv specific instructions in the `%post` section.

**Comment by rickard-von-essen** [comment]
You can use [`virt-what`](https://linux.die.net/man/1/virt-what) in the kickstart/preseed file to run code only depending on which virtualisation it is running on.

**Comment by wickedviking** [comment]
oooo, neato, I give that a go

**Comment by wickedviking** [comment]
I've only done this on CentOS 7.3, but here's what got LIS working and the box building, add the following to your ks.cfg:

```
#hyperv support
if [ $(virt-what) == "hyperv" ]; then
    yum -y install hyperv-daemons
    systemctl enable hypervvssd
    systemctl enable hypervkvpd
fi
```

**Comment by wickedviking** [comment]
Question, if I make a pull request for this and add the hyperv builder block, can i just do that on CentOS 7.3, or do I need to do all the builders?  I ask, cause 7.3 was all I needed personally, but I would prefer to use the bento repo to satisfy my suites.

**Comment by cheeseplus** [comment]
Hey @wickedviking, this is great to hear. It also happens that I ended up going down the hyper-v rabbit hole last weekend and was able to get some templates building (no testing just yet but it's a start). So far it's only ubuntu 14.04, ubuntu 16.04, and centos 7.3. I'd happily take pull requests adding the builders to the templates but not sure if I can guarantee build infra for them but that's another issue.

In my case I created separate ks.cfg and presseed.cfg files but if we can use some intelligent logic inside those I am cool with that as well.

**Comment by wickedviking** [comment]
So I dropped my changes into my fork, but ended up having some issues. I am currently chasing a deadline at work so I have limited availability. I will however get you a pull request for Cent 7.3 and maybe a separate PR for Windows Server 2016. I have both of these building in my own project but there are some differences I need to look into before migrating them to bento.

**Comment by cheeseplus** [comment]
@wickedviking have you picked this back up or at put the work in a spot I can look at it? I checked your fork of this repo and didn't see anything but am happy to do some legwork.

**Comment by lavahot** [comment]
I'm definitely interested in this. I'm going to try to roll a box or two this weekend.

**Comment by cheeseplus** [comment]
@lavahot any particular distros? I can fairly easily add the changes required for ubuntu but CentOS et al get more complicated.

**Comment by lavahot** [comment]
I was trying to get CentOS working the other day, but you're right it's
complicated. I just need something to run Chef Server with, so Ubuntu 16.04
looks like a good bet.

**Comment by cheeseplus** [comment]
@lavahot the trick with CentOS is to get LIS (Linux Integrated Services) installed from an ISO during the post-script of the kickstart

Will probably add the ubuntu sections this week

**Comment by lavahot** [comment]
Yeah, I ran into that. Not sure I can figure that out.

**Comment by wickedviking** [comment]
Sorry for the delay, I am preparing a PR for CentOS 7.3 now.

**Comment by wickedviking** [comment]
#822 

Fails Travis due to lack of Hyper-V test infra

**Comment by wickedviking** [comment]
#823 

Let me know if I screwed that PR up in any way...

**Comment by wickedviking** [comment]
@cheeseplus Was working on CentOS 5.11. The current build is broken as the ISO has been moved to the vault. CentOS 5.x is officially end of support. Should I bother making it work or do you guys plan to deprecate as well?

**Comment by cheeseplus** [comment]
We've got CentOS 6.9 and 7.3 (gen1) and Ubuntu 14-04->17.04 (gen2) supported in the templates and I'll be pushing these as part of the next release. Going to close this issue and we can open specific ones instead of using this as a catch all.
