### ISSUE TITLE
Is there a way to find currently supported Vagrant/VirtualBox combination?

### ISSUE THREAD

**Issue by mrmark** [chef/bento#750]
Hello, this is a question only.  Every time I upgrade my Bento box, I search around in the issues to see if I can find a working Vagrant and VirtualBox combination.  Is there an easier way to do this?  Maybe the versions are locked down somewhere in the testing code?  I think I can derive the VirtualBox version via the version of guest additions installed.

Thanks for any insights and feel free to close this issue whenever it suites you.

Cheers!

**Comment by cheeseplus** [comment]
Great question!

We now include this as part of a JSON blob we attach to the box on Atlas, example here https://atlas.hashicorp.com/bento/boxes/centos-7.3

**Comment by mrmark** [comment]
Great answer! Thank you very much, just what I needed!
