### ISSUE TITLE
CentOS 7.3 cable not connected (Virtualbox)

### ISSUE THREAD

**Issue by neikei** [chef/bento#751]
The "vagrant up" stuck on the first ssh connection, because the cable of the nic is not connected. I checked the box.ovf file and there is no parameter for the cable defined. The box is working fine if I add cable="true" to the adapter configuration manually.

Current setting without connected cable:
`<Adapter slot="0" enabled="true" MACAddress="0800278FEF23" type="82540EM">`

Working solution:
`<Adapter slot="0" enabled="true" MACAddress="0800278FEF23" cable="true" type="82540EM">`

Is it possible to fix it in this project or is it a virtualbox problem?

**Comment by rickard-von-essen** [comment]
Duplicates #701. You need to upgrade your VirtualBox version, see #701 for version that you should expect to work.
