### ISSUE TITLE
Debian 8.7 image

### ISSUE THREAD

**Issue by mariszin** [chef/bento#758]
Is there a timeline on when the image could be published?

**Comment by cheeseplus** [comment]
The timeline is me having both the literal and personal bandwidth. I'm currently on the road and w/o a decent connection which is required to build these in any reasonable time frame. Also new versions of tools have been released so I need to build all the templates to make sure it hasn't broken.

**Comment by cheeseplus** [comment]
https://atlas.hashicorp.com/bento/boxes/debian-8.7
