### ISSUE TITLE
We should remove old distros from git instead of archiving them

### ISSUE THREAD

**Issue by tas50** [chef/bento#771]
When we archive box confis we're not actually doing people a favor. The configs don't have their paths updated and the various other scripts like vagrant.sh continue to get updates that most likely don't work with the old box configs. For someone that wants to build an EOL distro they'd be much better off checking out the repo at the time that script existed in a working state. Instead during each release we should state the distros we added and removed. That would allow someone to checkout the previous tag if they wanted a version. This can be documented in the readme somewhere also.

**Comment by cheeseplus** [comment]
Closed by #772
