### ISSUE TITLE
bento/centos-7.3 vs chefdk test kitchen

### ISSUE THREAD

**Issue by Paladin** [chef/bento#774]
Given:

OSX Sierra
chefDK 1.2.22 (kitchen 1.15.0)
bento/centos-7.3 (virtualbox 2.3.2)
Virtual Box 5.1.10
vagrant 1.9.2

The command "kitchen test" will build a system fine, but slow way down when running the tests, to the tune of 30+minutes to run a set of tests that take a few seconds on centos-7.2

This delay also occurs if you I build the box with kitchen converge and then run the tests via kitchen verify.

This same software combination works fine with the 7.2 version, and with the other distros I've tried, so it appears to be something concerned with this particular image.

**Comment by cheeseplus** [comment]
Will need the detail here from the logs as it's going to be hard to tell which part of the stack is actually at fault.

**Comment by Paladin** [comment]
OK, so I went back and made several runs, trying to whittle it down to the least amount of log data for you to swim through, and it appears to come from adding the openssh cookbook from chef to a completely default chef build.

Along the way, I discovered a config option difference for sshd_config:

The only difference between the 7.3 box that hangs on verification and the one that passes is the value for useDNS in the sshd_config file. Did the default value for useDNS in the version of openSSH you're using to build this box? I never had to set that to "off" in previous systems, but for this one I do. Adding that setting to my current set of cookbooks has no noticeable effect on the older ones (based on 7.2) and also stops the 7.3 box from hanging.

**Comment by cheeseplus** [comment]
If the default changed it wasn't on account of any of the bento scripts in that they haven't really changed for a bit for RHEL platforms. I would recommend the latest release of the boxes which is 2.3.4 (you have to update via vagrant unfortunately, test-kitchen doesn't do this for you)

**Comment by cheeseplus** [comment]
Looks like we added the option to disable this ages ago [1] and that should be part of the base build. If anything else is stepping on that change, then that would explain the behaviour but also is somewhat out of "our" control wrt to bento.

[1] :https://github.com/chef/bento/pull/45/files

**Comment by Paladin** [comment]
Interesting, according to "vagrant box list" I've had 2.3.4 in place for a while now...probably updated it while trying to work through this issue, not sure why chef has been pulling 2.3.2 to build from, but that could explain it...but no, it doesn't.

Testing that, I leave chef out of the picture, 'git pull origin' to make sure my copy of bento is current (yeah, I know, but I'm grasping at straws here, folks) and do

vagrant init bento/centos-7.3
vagrant up

It comes up with the version 31 ssh as noted above. *But* at the very end of the sshd_config is UseDNS no

There still remains a mystery. (There's no mystery about why it's not there after the chef build; that's in the nature of the ssh cookbook itself -- see below. The mystery is the version of OpenSSH.)

 So I repeat the process sans chef for the 7.2 box. It comes up with build 22el7 in Vagrant alone.

After the chef build of 7.2, OpenSSH is on build 33. Somehow, the same recipes that build the 7.2 boxes (and apparently update openssh to build 33el7_3 along the way) are *not* updating the 7.3 box. Bingo. It had been done so transparently I hadn't noticed the ssh update happening.

Because of that it ends up using an older build of openssh in the 7.3 box than is used in the 7.2 box.

The problem with 'UseDNS no' in the config file, rather than the updated OpenSSH, is the chef-cookbooks/ssh cookbook rewrites the config file when run, and if UseDNS isn't specified, it gets the default. Resulting in the behavior I've seen; two different behaviors based on the OpenSSH build's differing default behaviors.

So you can address it on your end by building with a later version, and in any case I'll address it on my end by figuring out why chef is not updating OpenSSH when building with 7.3 like it does with 7.2. If the reason for that tracks back to the box, I'll be back, but I think we've hit Truth on this now, so there's no more to do here.

**Comment by cheeseplus** [comment]
Cool thanks for the follow up - will close this one out.
