### ISSUE TITLE
Upcoming changes to vmware vagrant plugin: vmx whitelisting

### ISSUE THREAD

**Issue by davidmnoriega** [chef/bento#775]
Writing this to let you know of an upcoming change to vagrant's vmware plugin

mitchellh/vagrant/pull/8368

**Comment by cheeseplus** [comment]
Thanks, this is definitely going to come up.

**Comment by cheeseplus** [comment]
Addressed this by removing the vmx interface at end of build.

**Comment by davidmnoriega** [comment]
I have a vagrant project that uses the vagrant-reload plugin as part of it's provisioning and while at first boot the vmx message doesn't happen, it does on the reload. Not sure if this is an issue with the box or vagrant. Using the latest build of centos-7.3

```
vagrant box list
bento/centos-7.3    (vmware_desktop, 201708.22.0)
```
