### ISSUE TITLE
Debian 8.7 VMware 2.3.4 build not available on Atlas

### ISSUE THREAD

**Issue by RobertDeRose** [chef/bento#782]
The version currently available on Atlas is 2.3.3 which is not working with VMware 8.5.5, at least I have to make this assumption because I can't get a successful vagrant up any more, I get an error that SharedFolders were unable to mount, which is normally an out of sync vmware tools to version of VMware Fusion.

**Comment by RobertDeRose** [comment]
Built this box and manually added it, it now works as expected.  Hopefully one of the maintainers can push these missing build up soon.

**Comment by cheeseplus** [comment]
There were some build problems with specifically this one, additionally VMware released a very quick hotfix in the form of Fusion 8.5.6 so we're going to build a new batch against that given it was a CVE related patch.

**Comment by rmoriz** [comment]
any updates on this?

**Comment by RobertDeRose** [comment]
Please, with sugar on top?

**Comment by rmoriz** [comment]
I'm happy to help to automate building of bento boxes, if that is still a problem…

**Comment by cheeseplus** [comment]
I've unfortunately been busy with the release of Chef 13 and some personal travel - it also happens that all the virtualization providers updated so need to build latest across the board.

**Comment by RobertDeRose** [comment]
@cheeseplus I completely understand that you're busy, but any chance a new release could be had? Been over a month with broken boxes.  Not common for this repo, we've come to rely on the dependably of the boxes in this repo. Honestly, wish HashiCorp just provided boxes as good as yours so we could relieve some of the burden on you.

**Comment by RobertDeRose** [comment]
It appears version 2.3.5 got pushed out the door, so I am going to close this.  Thanks @cheeseplus!
