### ISSUE TITLE
boot_command and preseed config house-keeping

### ISSUE THREAD

**Issue by cheeseplus** [chef/bento#786]
In exploring some alternate builders I realized we're a bit all over with regard to options being in the `boot_command` or `preseed.cfg`. Given that most preseeds are the result of multi-generational cargo culting and I've already noticed some duplication or defunct options, we should clean these up a bit. This is a reminder to do some maintenance there and collect some pristine/distro recommended preseed files. Also we should totally leave comments in those because of this very issue.

Debian 8
https://www.debian.org/releases/jessie/example-preseed.txt

**Comment by tas50** [comment]
I've opened a PR to move Ubuntu to a single preseed file since the 2 files were actually the same. https://github.com/chef/bento/pull/828

**Comment by EugenMayer** [comment]
Be sure to notice, that preseed settings which are done in the preseed file explicitly, cannot not be overridden using boot-commands. This said, to use the preseed file more widely, you want to remove or comment out some in the preseed and make it set in the boot-commabd, be it make-user and other related user tasks or other variations

**Comment by cheeseplus** [comment]
For our purposes, I think shoving _as much_ into the preseed as is reasonably possible without making it painful for end users is the ideal.
