### ISSUE TITLE
Centos 7.3 remote connection consistently fails

### ISSUE THREAD

**Issue by davidcpell** [chef/bento#789]
**Platforms:** Windows 7 Enterprise and Mac OSX 10.12.3

I keep running into the same problem with the Centos 7.3 image when using Test Kitchen. TK seems to work otherwise (including with e.g. the Ubuntu 16.04 image from Bento) so I am assuming the issue is with the image but can open the image elsewhere if appropriate.

Basically the remote connection fails endlessly:

```
➜  playground git:(master) ✗ cekcr 73
-----> Starting Kitchen (v1.16.0)
-----> Creating <default-centos-73>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Checking if box 'bento/centos-7.3' is up to date...
       ==> default: Clearing any previously set forwarded ports...
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 22 (guest) => 2222 (host) (adapter 1)
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 127.0.0.1:2222
           default: SSH username: vagrant
           default: SSH auth method: private key
           default: Warning: Remote connection disconnect. Retrying...
           default: Warning: Remote connection disconnect. Retrying...
           default: Warning: Remote connection disconnect. Retrying...
           default: Warning: Remote connection disconnect. Retrying...
           default: Warning: Remote connection disconnect. Retrying...
           default: Warning: Remote connection disconnect. Retrying...
           default: Warning: Remote connection disconnect. Retrying...
           default: Warning: Remote connection disconnect. Retrying...
           default: Warning: Remote connection disconnect. Retrying...
           default: Warning: Remote connection disconnect. Retrying...
           default: Warning: Remote connection disconnect. Retrying...
           default: Warning: Remote connection disconnect. Retrying...
```

**Comment by davidcpell** [comment]
closing b/c this appears to be a known issue with outdated VirtualBox and Vagrant

**Comment by grtjn** [comment]
@davidcpell Could you provide some more detail on this? I enabled vb.gui, and it only shows a login. I am indeed running older Vagrant and VirtualBox. I could upgrade, but it would be useful to know what would be the least versions you need. Is there some particular feature I'd need to look for?

**Comment by rickard-von-essen** [comment]
See #701

**Comment by grtjn** [comment]
Not sure that is the same. I have seen timeouts like that in the past because of unconnected cables (see also #751), but vbox gui tells me they are connected, and I also enforce that by using:

    # Customize the virtual machine environments
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
        vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
        # to make sure ssh won't timeout because of a regression in VBox
        vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
        vb.customize ["modifyvm", :id, "--cableconnected2", "on"]
        #vb.gui = true # for debugging
    end

PS: not using TK, but running the bento/centos-7.3 basebox directly with Vagrant using a Vagrantfile of my own..

**Comment by grtjn** [comment]
This comment looks key: https://github.com/geerlingguy/drupal-vm/issues/953#issuecomment-257477515. I suspect Bento is using latest guest additions, and they don't operate well with the VBox version I have. It was still working so far though. I'll ask someone to confirm 7.3 runs fine with recent VBox..
