### ISSUE TITLE
ubuntu 16.04 network timeout on virtualbox

### ISSUE THREAD

**Issue by tedivm** [chef/bento#790]
This is the exact same issue as #682 with the exact same solution- for some reason you are shipping boxes which have the network connection disabled because the cable is not "plugged in".

**Comment by rickard-von-essen** [comment]
See https://github.com/chef/bento/issues/688#issuecomment-252404560

**Comment by tedivm** [comment]
Yes, I read that. I have an updated version of virtualbox. Adding in the customization line did work, but I thought changing that one single configuration on your end (since you're literally the only box I've downloaded that doesn't set it) would have been a cleaner solution.
