### ISSUE TITLE
Add Debian 9 (strech)

### ISSUE THREAD

**Issue by andir** [chef/bento#791]
In the upcoming months strech will be released. Providing early (still testing) builds of strech would allow people to test their stuff on strech.

I'm in the process of re-writing some salt and puppet deployments which I would rather want to base on strech then on jessie at this point in time.

**Comment by andir** [comment]
ISOs can be found at: http://cdimage.debian.org/cdimage/daily-builds/daily/current/amd64/iso-cd/
The pre-seed should not be that different from strech.

**Comment by rmoriz** [comment]
Can you test and provide a PR? If we are lucky, only the variables need to be adjusted, see:
 https://github.com/chef/bento/blob/master/debian-8.7-amd64.json#L223-L244

**Comment by andir** [comment]
Trying :-)

I can only test the virtualbox based builds since I do not have parallels and vmaware.

**Comment by rmoriz** [comment]
Maybe the maintainers can also say something regarding pre/test releases. I've had trouble with debian 7->debian 8 so I very much like the idea of having some kind of pre-release images available on atlas upfront.

Regarding VMWare: I've just tried your file on vmware but having issues:

```shell

 vmware-iso: is going to create it, including needed parent directories. Is this what you
    vmware-iso: want? [yes]
    vmware-iso: The installation of VMware Tools 10.1.6 build-5214329 for Linux completed
    vmware-iso: successfully. You can decide to remove this software from your system at any
    vmware-iso: time by invoking the following command: "/usr/bin/vmware-uninstall-tools.pl".
    vmware-iso:
    vmware-iso: Before running VMware Tools for the first time, you need to configure it by
    vmware-iso: invoking the following command: "/usr/bin/vmware-config-tools.pl". Do you want
    vmware-iso: this program to invoke the command for you now? [yes]
    vmware-iso: Setup is unable to find the "ifconfig" program on your machine.  Please make
    vmware-iso: sure it is installed.  Do you want to specify the location of this program by
    vmware-iso: hand? [yes]
    vmware-iso: What is the location of the "ifconfig" program on your
    vmware-iso: machine?
    vmware-iso: The answer "" is invalid.  It must be the complete name of a binary file.
    vmware-iso:
    vmware-iso: What is the location of the "ifconfig" program on your
    vmware-iso: machine?
    vmware-iso: The answer "" is invalid.  It must be the complete name of a binary file.
    vmware-iso:
    vmware-iso: What is the location of the "ifconfig" program on your
    vmware-iso: machine?
    vmware-iso: The answer "" is invalid.  It must be the complete name of a binary file.
    vmware-iso:
```

I guess they finally made the switch to `ip` and remove `ifconfig`…

**Comment by cheeseplus** [comment]
For our part adding a pre-release platform doesn't present a problem assuming it actually works somewhat reliably across all providers - the catch here is that such platforms, if they are still in flux and finicky, will backlog the pipeline which is already a bit of a pain at the moment.

As noted already, the hypervisor providers have varying levels of support/fixes for these new platforms so it's bit of a gamble.
