### ISSUE TITLE
Ubuntu-16.04 failing on SSH with "vagrant up"

### ISSUE THREAD

**Issue by mrwillis** [chef/bento#793]
Hi all,

Running into this issue when using bento/ubuntu-16.04 with VirtualBox 5.0.16 and Vagrant 1.9.1. It seems to hang after 

default: SSH auth method: private key...

> The primary issue for this error is that the provider you're using
> is not properly configured. This is very rarely a Vagrant issue.
> 
> C:\Users\jwilso37\PycharmProjects\basezero>vagrant destroy
>     default: Are you sure you want to destroy the 'default' VM? [y/N] y
> ==> default: Forcing shutdown of VM...
> ==> default: Destroying VM and associated drives...
> 
> C:\Users\jwilso37\PycharmProjects\basezero>vagrant up
> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Importing base box 'bento/ubuntu-16.04'...
> ==> default: Matching MAC address for NAT networking...
> ==> default: Checking if box 'bento/ubuntu-16.04' is up to date...
> ==> default: Setting the name of the VM: basezero_default_1493137633499_35414
> ==> default: Clearing any previously set network interfaces...
> ==> default: Preparing network interfaces based on configuration...
>     default: Adapter 1: nat
>     default: Adapter 2: intnet
> ==> default: You are trying to forward to privileged ports (ports <= 1024). Most
> ==> default: operating systems restrict this to only privileged process (typically
> ==> default: processes running as an administrative user). This is a warning in case
> ==> default: the port forwarding doesn't work. If any problems occur, please try a
> ==> default: port higher than 1024.
> ==> default: Forwarding ports...
>     default: 8881 (guest) => 8881 (host) (adapter 1)
>     default: 80 (guest) => 80 (host) (adapter 1)
>     default: 22 (guest) => 2222 (host) (adapter 1)
> ==> default: Booting VM...
> ==> default: Waiting for machine to boot. This may take a few minutes...
>     default: SSH address: 127.0.0.1:2222
>     default: SSH username: vagrant
>     default: SSH auth method: private key
> Timed out while waiting for the machine to boot. This means that
> Vagrant was unable to communicate with the guest machine within
> the configured ("config.vm.boot_timeout" value) time period.
> 
> If you look above, you should be able to see the error(s) that
> Vagrant had when attempting to connect to the machine. These errors
> are usually good hints as to what may be wrong.
> 
> If you're using a custom box, make sure that networking is properly
> working and you're able to connect to the machine. It is a common
> problem that networking isn't setup properly in these boxes.
> Verify that authentication configurations are also setup properly,
> as well.

And my Vagrantfile:

`Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "basezero"
  config.vm.network "forwarded_port", guest: 8881, host: 8881
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "private_network", ip: "10.30.3.4", netmask: "255.255.255.0", virtualbox__intnet: "my-network", drop_nat_interface_default_route: true`

It seems like if I go into VB it gets stuck on this 

![image](https://cloud.githubusercontent.com/assets/2652683/25396957/83836130-29b4-11e7-990c-305a53e5c25b.png)

Thanks

**Comment by mrwillis** [comment]
Just saw a bunch of other issues relating to the same thing. Sorry.

**Comment by queglay** [comment]
can I ask what the solution was? I'm getting a similar issue and just start to use bento/ubuntu-16.04
