### ISSUE TITLE
Ubuntu 17.04 box

### ISSUE THREAD

**Issue by NoahO** [chef/bento#803]
Hi, Ubuntu 17.04 is out, 

Any plans for a new box? I think it should just be a quick tweak of 16.10... Let me know if there's any way I can help.

**Comment by rmoriz** [comment]
you could provide PRs with the appropriate .json files to help

**Comment by NoahO** [comment]
ok... I am trying to do this now. But just in case anyone else has more of a clue than me.. 

I have downloaded packer, cloned the repo, and created a new file ubuntu-17.04-amd64.json which is a copy of the 16.10 one, with find and replace 16.10/17.04, and the new file hashes inserted.

It seems to work, the VM builds, runs the ansible steps, shuts down. I'm just getting stuck on the last step:

==> parallels-iso: Compacting the disk image
==> parallels-iso: Unregistering virtual machine...
Build 'parallels-iso' errored: open /Users/Noah/bento/packer-ubuntu-17.04-amd64-parallels/ubuntu-17.04-amd64.pvm/ubuntu-17.04-amd64.app: no such file or directory

Anyone know where to go from here?

**Comment by NoahO** [comment]
I worked it out. Pull request coming soon.

**Comment by NoahO** [comment]
Pull request here: https://github.com/chef/bento/pull/808

**Comment by akarasulu** [comment]
@NoahO What actually fixed the parallels problem for you? I keep getting the following and have no idea why this is happening:

> Build 'parallels-iso' errored: open /Users/...-parallels-iso.pvm/packer-parallels-iso.app: no such file or directory

Thanks!

**Comment by rickard-von-essen** [comment]
See https://github.com/hashicorp/packer/issues/5056

**Comment by NoahO** [comment]
@rickard-von-essen @akarasulu ahhh that clears the mystery for me too. The problem just went away, and I wasn't sure how I fixed it.

**Comment by cheeseplus** [comment]
https://app.vagrantup.com/bento/boxes/ubuntu-17.04

**Comment by akarasulu** [comment]
Thanks for the heads up @rickard-von-essen  @NoahO !
