### ISSUE TITLE
Memory and CPU values not being respected from template

### ISSUE THREAD

**Issue by Moncky** [chef/bento#813]
Whenever I try to build a box I always get 1 cpu and 1024 memory, no matter what I put into my template.

Take for example the default template in the repo for centos-6.9.  The memory value there is 512 but if you run:

`λ callum [work/git/bento] at  master !?
→ bundle exec bento build -n -H -o virtualbox-ios centos-6.9-x86_64.json                                                                                                                          [c903a53]
==> Starting build for templates: ["centos-6.9-x86_64"]
==> [centos-6.9-x86_64] Building: 'echo packer build -var headless=true -only=virtualbox-ios -var-file=/var/folders/g0/l44rqb7n3zx3yh2xxlkcyklh0000gn/T/centos-6.9-x86_64-metadata.json20170613-55528-ejs69o centos-6.9-x86_64.json'
packer build -var headless=true -only=virtualbox-ios -var-file=/var/folders/g0/l44rqb7n3zx3yh2xxlkcyklh0000gn/T/centos-6.9-x86_64-metadata.json20170613-55528-ejs69o centos-6.9-x86_64.json
==> (Dry run) Metadata file contents would be something similar to:
{
  "name": "centos-6.9",
  "version": "2.1.20170613094550",
  "build_timestamp": "20170613094550",
  "git_revision": "c903a532b3cc14571c1f19ec8945ce6a89dee0ea",
  "box_basename": "centos-6.9-2.1.20170613094550",
  "template": "centos-6.9-x86_64",
  "cpus": "1",
  "memory": "1024",
  "providers": [

  ],
  "tool_versions": {
    "packer": "1.0.0",
    "vagrant": "1.9.5",
    "parallels": "None",
    "virtualbox": "5.1.22",
    "vmware_fusion": "file"
  },
  "build_times": {
    "virtualbox-ios": 1
  }
}
==> [centos-6.9-x86_64] Finished building in 0m0.00s.
==> Build finished in 0m0.22s.`

The value for memory and cpu appears to be hard coded in the bulidmetadata.rb of the bento-ya gem. 

`  def cpus
    1
  end

  def memory
    1024
end`

It entiery breaks the ability to build boxes for me using the bento tool.

Bulding using the same template using the packer tool directly works fine

**Comment by cheeseplus** [comment]
I can fix the bento-ya gem and add some notes but I would like to be incredibly clear that the gem in it's current state is for _me_ and the Bento pipeline primarily.

**Comment by cheeseplus** [comment]
Closing this here as this works fine with the packer documentation.
