### ISSUE TITLE
Cannot install packages via apt

### ISSUE THREAD

**Issue by james50428** [chef/bento#835]
When I was going to compile vim from source
I was using following command:
```
sudo apt-get install -y libncurses5-dev libgnome2-dev libgnomeui-dev \
    libgtk2.0-dev libatk1.0-dev libbonoboui2-dev \
    libcairo2-dev libx11-dev libxpm-dev libxt-dev python-dev \
    python3-dev ruby-dev lua5.1 lua5.1-dev libperl-dev git
```
And It will return some error msgs: 
```
1.Hash Sum Mismatch
2.Bad header line Bad header data [IP: 91.189.91.23 80]
3.0  OK [IP: 91.189.91.26 80]
4.Writing more data than expected (1077529 > 1076198) [IP: 91.189.91.26 80]
```

Is it serverside's problem or bento's?

Here is my apt-get upgrade log: [Gist](https://gist.github.com/james50428/cbc0671e8f8fef81d77b4a469e2c890e)

* Using bento/ubuntu-16.04

**Comment by cheeseplus** [comment]
That's an apt-mirror issue and nothing really to do with the box itself.

**Comment by james50428** [comment]
@cheeseplus 
Thanks
