### ISSUE TITLE
Debian: Could you ship debian-8.8 and debian-9 i386 box images?

### ISSUE THREAD

**Issue by kenhys** [chef/bento#841]
## Problem

Debian 8.8 and Debian 9 recipes are merged into master but not shipped yet.

## Expected result

Debian 8.8 **i386** and Debian 9 **i386** box are provided.

## Actual result

Debian 8.8 and Debian 9 box are provided only amd64 box images.

**Comment by cheeseplus** [comment]
So I've actually been debating whether or not we're killing these as the download numbers for 32bit are fractional at best. I'll push i386 with 2.3.8 which will be released once I've smoothed out some pipeline issues.

**Comment by cheeseplus** [comment]
Published as part of 2.3.8

**Comment by kenhys** [comment]
Debian 8.8 i386 box is confirmed on https://app.vagrantup.com/bento/boxes/debian-8.8-i386.
But what about Debian 9 i386 box?
