### ISSUE TITLE
debian-9.0 update-initramfs is broken due to /etc/udev/rules.d/70-persistent-net.rule being a folder

### ISSUE THREAD

**Issue by EugenMayer** [chef/bento#851]
due to https://github.com/chef/bento/blob/master/scripts/debian/networking.sh#L6

`/etc/udev/rules.d/70-persistent-net.rule` is a folder, which seem to confuse update-initramfs:

```
update-initramfs: Generating /boot/initrd.img-4.9.0-3-amd64
       cp: -r not specified; omitting directory '/etc/udev/rules.d/70-persistent-net.rules'
```

Seems to be a known limitation https://bugs.launchpad.net/ubuntu/+source/initramfs-tools/+bug/1636922

either use `ln -s /dev/null /etc/udev/rules.d/70-persistent-net.rules or` whatever it is tried here.

**Comment by EugenMayer** [comment]
@cheeseplus any way to move this forward somehow? i cannot really undestand why the folder has been created in the first place, most probably to force udev to not create network udev rules ( MAC mappings ) since this would do harm for bento boxes.

I think, as you know, this becomes a issue with stretch, since we use the old preseed file here, and not opting out using strict nic namings, thus initramfs wants to establish those -and thus want to remove this file.

a) I am not sure if the proper solution here is switching to strict named interfaces and remove this hack allthogther
b) or opting out from the strict naming and symlink /dev/null to /etc/udev/rules.d/70-persistent-net.rules' instead of creating a folder there.

A different smell tells me, that this folder has been wrong for debian since past days, it was just right for ubuntu and has been reused here.

**Comment by EugenMayer** [comment]
talked to the debian ops, yes debian stretch does use predictable nic names for fresh installations, so its very different from debian jessie here

That said, by default, no udev rules would be generated, since its no longer MAC based.

@cheeseplus could you decide, what you want to stick with, using ethX but avoiding udev rules, so having nic0 on eth0, or do you want to go with the new predictable names?

the ops in debian suggest, opt out from the predictable names, so we need to add

`net.ifname=0` to /etc/default/grub `cmdline_linux='net.ifname=0'`

and then use `ln -s /dev/null /etc/udev/rules.d/70-persistent-net.rule` to avoid persisting the rules.

I am happy to provide a PR here, just need some decisions/guidance

**Comment by jakob223** [comment]
For ubuntu, there seems to be a switch disabling this folder hack on 15.10+ (https://github.com/chef/bento/commit/a3a19348ca622772017d98b1c2641b993e1a07e4) - can we set an equivalent switch in https://github.com/chef/bento/blob/master/scripts/debian/networking.sh for debian 8.0+ or 9.0+?

**Comment by rmoriz** [comment]
Looks like this issues is present in Debian 8 as well:

```
      Installing new version of config file /etc/init.d/networking ...
       Setting up libpam-systemd:amd64 (230-7~bpo8+2) ...
       Processing triggers for systemd (230-7~bpo8+2) ...
       Processing triggers for initramfs-tools (0.120+deb8u3) ...
       update-initramfs: Generating /boot/initrd.img-3.16.0-4-amd64
       cp: omitting directory ‘/etc/udev/rules.d/70-persistent-net.rules’
       E: /usr/share/initramfs-tools/hooks/udev failed with return 1.
       update-initramfs: failed for /boot/initrd.img-3.16.0-4-amd64 with 1.
       dpkg: error processing package initramfs-tools (--configure):
        subprocess installed post-installation script returned error exit status 1
       Errors were encountered while processing:
        initramfs-tools
```
