### ISSUE TITLE
Update to Debian 8.9

### ISSUE THREAD

**Issue by rickard-von-essen** [chef/bento#854]

**Comment by tas50** [comment]
I’ll grab this one

**Comment by cheeseplus** [comment]
Images aren't even available yet as I just tried to do so.

**Comment by kenhys** [comment]
@cheeseplus It seems that images are uploaded!
http://cdimage.debian.org/cdimage/archive/8.9.0/amd64/iso-cd/

**Comment by cheeseplus** [comment]
Will get these in the next release.

**Comment by tas50** [comment]
Fixed by https://github.com/chef/bento/pull/860
