### ISSUE TITLE
debian-9 repo sources need to be updated

### ISSUE THREAD

**Issue by kplimack** [chef/bento#858]
currently by default apt is pointed at httpredir.deb.debian.org which forwards to fastly.  this is broken and deprecated according to the ops in irc.debian.org.  this should be updated to point to "deb.debian.org"

**Comment by EugenMayer** [comment]
this is related to the debian build uses the debian jessie preseed file, and that means https://github.com/chef/bento/blob/master/http/debian-8/preseed.cfg#L12 is used. we need a debian-9 preseed file and need to fix the mirror there

**Comment by cheeseplus** [comment]
Does this need to be fixed for all Debians or just 9? I recall we used that redir as that was advised at the time.

**Comment by kplimack** [comment]
@cheeseplus according to the operators in the debian channel on irc, the redirs are deprecated and they advised to use deb.debian.org.

as you can see in this gist, the redirects are omitting the trailing `/` and the servers hosting the repos are not rewriting to the working one, so it 404s.
https://gist.github.com/kplimack/39fb8ed90cbca80da54021f9f0442d24
