### ISSUE TITLE
Debian 9 VMWare Fusion not mounting shared folders

### ISSUE THREAD

**Issue by RobertDeRose** [chef/bento#873]
I did a local build because there Vagrant can't find a provider with only `vmware` as the listed provider on Vagrant Cloud. But I am still getting the following error with a local build.  I have to assume the VMWare tools are not working properly with Debian 9?

```bash
==> debian9: Waiting for HGFS to become available...
==> debian9: Enabling and configuring shared folders...
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["enableSharedFolders", "/.vagrant/machines/debian/vmware_fusion/2de8d4c2-59ab-4f1b-b036-bfebf1251cb4/debian-9.1-amd64.vmx", {:notify=>[:stdout, :stderr]}]

Stdout: Error: There was an error mounting the Shared Folders file system inside the guest operating system

Stderr:
```

**Comment by RobertDeRose** [comment]
Ah... I figured it out... VMWare is requiring the FUSE packages to be installed and they are not installed by the pressed.  I'm going to make a PR once I get it correctly working locally.

**Comment by RobertDeRose** [comment]
Also need to upgrade the vm to use an e1000e nic or vmxnet3 nic.  VMWare no longer supports the driver with the new kernel. Not sure that's a blocker at the moment, but going to see and include in PR if it is.

**Comment by cheeseplus** [comment]
The vmware tools are not working properly with Debian 9, we published the boxes anyway this go round cause not everyone strictly needs them but normally we'd not publish.

**Comment by cheeseplus** [comment]
I've confirmed that something is wonky with the uploads and I have to change the provider to `vmware_desktop` to get the expected behaviour - I'm cleaning this up for existing boxes today. My theory is the HashiCorp is trying to improve something here for the future but not all the tooling is on the same page yet so I'll see if we can patch/fix/force this in our upload code

**Comment by RobertDeRose** [comment]
@cheeseplus Thanks, did you add the FUSE package to the debian-8 pressed, that fixed the tool building for me on Debian 9.  I was in the middle of writing up a PR, but something just started flaking on the Debian side complaining about no supported architecture found, even though I switched to the `deb.debian.org` redirect server.

**Comment by cheeseplus** [comment]
Unfortunately building vmware boxes has been stymied by the classic vagrant/vagrant-vmware plugin race issues with ports which has slowed things down a bit.
