### ISSUE TITLE
Virtualbox: Multiple Networks issue on centos-7.3

### ISSUE THREAD

**Issue by diLLec** [chef/bento#875]
Hi,

there is a problem with bento/centos-7.3 and multiple network interfaces (on vagrant version 1.9.7). Vagrant creates the following interfaces via virtualbox:

```
NIC 1:           MAC: 080027CBE37F, Attachment: NAT, Cable connected: on
NIC 2:           MAC: 0100278B733F, Attachment: Internal Network 'net1', Cable connected: on
NIC 3:           MAC: 080027194E08, Attachment: Internal Network 'net2, Cable connected: on,
NIC 4:           MAC: 08002729E3FA, Attachment: Internal Network 'net3', Cable connected: on
```

Inside of the VM those interfaces are created with the interface names 
- NIC 1 == enp0s3
- NIC 2 == enp0s8
- NIC 3 == enp0s9
- NIC 4 == enp0s10

For some reason the Network Manager only creates a network-script for the last NIC (NIC4 = enp0s10) and configures it with DHCP:

![grafik](https://user-images.githubusercontent.com/10614533/29434733-91327ace-83a4-11e7-8c8e-31f23c79f522.png)

This in turn is bad for vagrant, since the DHCP and the NAT and the forwarded ports are on NIC1 and so vagrant is never able to connect to the box for initial provisioning.

I'd say that the problem may be lying inside of /scripts/centos/cleanup.sh because it clears all the `ifcfg configs` and network manager configuration. 

Help would be much appreciated :-).

Greetings,
Michael

**Comment by rickard-von-essen** [comment]
What's your Vagrant version?

**Comment by diLLec** [comment]
$ vagrant -v
Vagrant 1.9.7

**Comment by diLLec** [comment]
Hi,

I think the problem is in `/scripts/centos/cleanup.sh:46`, which creates exactly one interface (head of the list) and thats it. Replacing it with the following should resolve the issue I think:

```
# add gateway interface connection.
for network_device in `nmcli dev | grep ethernet | egrep -v 'unmanaged' | head -n 1 | awk '{print \$1}'\`; do 
    if [ "\$network_device" != "" ]; then
        nmcli c add type eth ifname \$network_device con-name \$network_device
    fi
done
```
I'm a bit confused, since /etc/rc.d/rc.local is empty on my system. Is there anything that replaces it after the first start?

Greetings,
Michael

**Comment by cheeseplus** [comment]
I am somewhat confused because it'll never have multiple interfaces as part of the build process so I'm not sure how we could possibly enumerate things that don't exist in the context of the Packer run.

**Comment by cheeseplus** [comment]
Closing this one due to lack of response and that it doesn't seem to be related to the image itself at all - this falls under additional configuration that the user needs to do for adding more network interfaces.
