### ISSUE TITLE
Error in Solaris 11 build (No module named six)

### ISSUE THREAD

**Issue by sharktamer** [chef/bento#879]
I'm playing around with the solaris-11 packer template right now. All seems good apart from the error seen below:

> ==> virtualbox-iso: Provisioning with shell script: scripts/solaris/update.sh
>     virtualbox-iso: Traceback (most recent call last):
>     virtualbox-iso: File "/usr/bin/pkg", line 66, in <module>
>     virtualbox-iso: import pkg.actions as actions
>     virtualbox-iso: File "/usr/lib/python2.7/vendor-packages/pkg/actions/__init__.py", line 68, in <module>
>     virtualbox-iso: globals(), locals(), [modname])
>     virtualbox-iso: File "/usr/lib/python2.7/vendor-packages/pkg/actions/license.py", line 38, in <module>
>     virtualbox-iso: import generic
>     virtualbox-iso: File "/usr/lib/python2.7/vendor-packages/pkg/actions/generic.py", line 48, in <module>
>     virtualbox-iso: import pkg.variant as variant
>     virtualbox-iso: File "/usr/lib/python2.7/vendor-packages/pkg/variant.py", line 35, in <module>
>     virtualbox-iso: from pkg.misc import EmptyI
>     virtualbox-iso: File "/usr/lib/python2.7/vendor-packages/pkg/misc.py", line 29, in <module>
>     virtualbox-iso: import OpenSSL.crypto as osc
>     virtualbox-iso: File "/usr/lib/python2.7/vendor-packages/OpenSSL/__init__.py", line 8, in <module>
>     virtualbox-iso: from OpenSSL import rand, crypto, SSL
>     virtualbox-iso: File "/usr/lib/python2.7/vendor-packages/OpenSSL/rand.py", line 10, in <module>
>     virtualbox-iso: from six import integer_types as _integer_types
>     virtualbox-iso: ImportError: No module named six
>     virtualbox-iso: Traceback (most recent call last):
>     virtualbox-iso: File "/usr/bin/pkg", line 66, in <module>
>     virtualbox-iso: import pkg.actions as actions
>     virtualbox-iso: File "/usr/lib/python2.7/vendor-packages/pkg/actions/__init__.py", line 68, in <module>
>     virtualbox-iso: globals(), locals(), [modname])
>     virtualbox-iso: File "/usr/lib/python2.7/vendor-packages/pkg/actions/license.py", line 38, in <module>
>     virtualbox-iso: import generic
>     virtualbox-iso: File "/usr/lib/python2.7/vendor-packages/pkg/actions/generic.py", line 48, in <module>
>     virtualbox-iso: import pkg.variant as variant
>     virtualbox-iso: File "/usr/lib/python2.7/vendor-packages/pkg/variant.py", line 35, in <module>
>     virtualbox-iso: from pkg.misc import EmptyI
>     virtualbox-iso: File "/usr/lib/python2.7/vendor-packages/pkg/misc.py", line 29, in <module>
>     virtualbox-iso: import OpenSSL.crypto as osc
>     virtualbox-iso: File "/usr/lib/python2.7/vendor-packages/OpenSSL/__init__.py", line 8, in <module>
>     virtualbox-iso: from OpenSSL import rand, crypto, SSL
>     virtualbox-iso: File "/usr/lib/python2.7/vendor-packages/OpenSSL/rand.py", line 10, in <module>
>     virtualbox-iso: from six import integer_types as _integer_types
>     virtualbox-iso: ImportError: No module named six

Not sure what the effect is just yet, just raising the error for now.

**Comment by cheeseplus** [comment]
This largely comes back to the fact we don't build those images (at least at present) due to lack of licenses so we somewhat rely on community contributions for those at present. Happy to help shepherd a fix through if you figure out what is preventing that from working.

**Comment by LandonThomas** [comment]
This works for me:

```
[~/chef/bento/solaris (master *)]$ git diff
diff --git a/solaris/http/default.xml b/solaris/http/default.xml
index 077d8de..09f5087 100644
--- a/solaris/http/default.xml
+++ b/solaris/http/default.xml
@@ -50,6 +50,8 @@
       -->
       <software_data action="install">
         <name>pkg:/server_install</name>
+        <name>pkg:/library/python/six</name>
+        <name>pkg:/library/python/cryptography</name>
       </software_data>
       <!--
            babel_install and slim_install are group packages used to
diff --git a/solaris/solaris-11-x86.json b/solaris/solaris-11-x86.json
index c2ca788..0a2691f 100644
--- a/solaris/solaris-11-x86.json
+++ b/solaris/solaris-11-x86.json
@@ -142,7 +140,7 @@
     "box_basename": "solaris-11.3",
     "build_timestamp": "{{isotime \"20060102150405\"}}",
     "cpus": "1",
-    "disk_size": "10360",
+    "disk_size": "11000",
     "git_revision": "__unknown_git_revision__",
     "headless": "",
     "memory": "2048",
```

I got that hint from https://blogs.oracle.com/scottdickson/installing-ansible-on-solaris-113

In the Solaris LiveCD environment, `/usr/bin/pkg` works fine but the 'six' Python module still isn't available. I don't know why pkg in the bento script's OS environment suddenly requires six. The service `svc:/system/ca-certificates:default` has the same Python error and it doesn't start. That makes wget no longer trust the certificate at `https://omnitruck.chef.io/install.sh`, which breaks `kitchen converge`.

After installing 'six', I then get this error: `ImportError: No module named cryptography.hazmat.bindings.openssl.binding`. That's why I added the cryptography package installation as well. Installing cryptography through pip requires CC/gcc, so the OS packages are better.

I'm not a Solaris expert, so I haven't analyzed what `bento/solaris/http/default.xml` does versus the ISO's `/system/volatile/ai.xml`, but my guess is something in that change breaks Python.
