### ISSUE TITLE
OpenSUSE 42.3 shared folders broken for all providers

### ISSUE THREAD

**Issue by cheeseplus** [chef/bento#885]
Shared folders don't work with any of the providers for OpenSUSE 42.3 - normally at _least_ one of the providers (typically VirtualBox) at least works with shared folders.

Related we could make kitchen-vagrant default opensuse to disabling shared folders given the unreliability.

**Comment by glookie1** [comment]
I think this issue (with virtualbox) is related to a virtualbox/sles compatibility issue:

https://forums.suse.com/showthread.php?9923-sles12-sp3-virtualbox-tools-build-problem

I found multiple solutions. Solution 1 (untested):
https://forums.opensuse.org/showthread.php/525768-Cannot-install-oracle-virtualbox-5-1-5-1-22_115216/page4

Solution 2:
You need to install the VBoxGuestAdditions_5.2.0_BETA2.iso to get the guest additions to work. 

In the end you will probably need updated VBoxGuestAdditions to fix this issue. The same issue also applies to SLES12 SP3. Therefore you will probably need to wait for an update of virtualbox. The use of the BETA2 guest additions feels super hacky and I dont know how stable this is.

**Comment by tas50** [comment]
It looks like this may be fixed with the new vbox. We should try that out.

**Comment by cheeseplus** [comment]
VirtualBox is building again so closing this one out.
