### ISSUE TITLE
bento/centos-5.11-i386

### ISSUE THREAD

**Issue by mkoennecke** [chef/bento#890]
Hi,

first, sorry to bother you with such old stuff. I need it however in order to run some old cross 
compilation toolchain for a MEN-A12 VME CPU board. 

Well, the box is not working: it fails to install its latest kernel and other software on vagrant up. I tracked it down: the URL's in /etc/yum.repos.d are all wrong. CENTOS 5 is EOL and is not on mirror.centos.org anymore but in vault.centos.org. I changed that in Centos-Base.repo and then it provisioned OK.

I attach my version of that file. (Had to append a .txt though for it to be digested by github)

Best Regards,

      Mark Koennecke

[CentOS-Base.repo.txt](https://github.com/chef/bento/files/1266203/CentOS-Base.repo.txt)

**Comment by rickard-von-essen** [comment]
This is how it should be CentOS 5 is EOL and thus should not be used.

**Comment by mkoennecke** [comment]
I am happy to drop Centos-5 if you send me a million CHF to replace our data acquisition electronics by a new one and some gunmen who make sure that the electronics guys who can do that project give us priority one :-) No, hiring a new electronics person will do not do the trick: she will need years of training to have the knowledge to build electronics for neutron detectors.  Do not take this comment too seriously, just a reminder that people may have valid reasons for running old stuff. Due to a vendor lock in I am even running (and installing) MS-DOS in my place!

**Comment by kwakwaversal** [comment]
If you still need it, clone the repo and find and checkout the commit before it was removed.

I like projects like this that stop me from hurting myself by removing things that I really shouldn't be using. Now, if only I could get rid of Debian Etch from a few machines. :P

**Comment by tas50** [comment]
@mkoennecke The sed lines you'll want to add to one of the scripts are here:

https://github.com/someara/dokken-images/blob/master/centos-5/Dockerfile

That being said we remove distros from Bento once they go EOL. The existing boxes are there and the git history is there for anyone who wants to maintain them on their own. It's just too much work to maintain EOL distros while also maintaining all the new releases that come out.
