### ISSUE TITLE
Please publish bento/debian-9.1-i386 images

### ISSUE THREAD

**Issue by okkez** [chef/bento#892]
There is https://github.com/chef/bento/blob/master/debian/debian-9.1-i386.json but https://app.vagrantup.com/bento does not have bento/debian-9.1-i386 images.

Could you publish them?

**Comment by cheeseplus** [comment]
It looks like this never got built so I'll need to run it through the pipelines but this should go out soon.

**Comment by cheeseplus** [comment]
https://app.vagrantup.com/bento/boxes/debian-9.1-i386

**Comment by okkez** [comment]
Thank you!
