### ISSUE TITLE
Vagrant up Timeout

### ISSUE THREAD

**Issue by contactavishek** [chef/bento#901]
My OS is Windows 7 Service Pack 1 and I have installed Oracle VM VirtualBox Manager 5.1.26 and vagrant 1.8.5
Even I am getting this with 'vagrant up' in Git bash:

```
Timed out while waiting for the machine to boot. This means that Vagrant was unable to communicate with the guest machine within the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that Vagrant had when attempting to connect to the machine. These errors are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly working and you're able to connect to the machine. It is a common problem that networking isn't setup properly in these boxes. Verify that authentication configurations are also setup properly, as well.

If the box appears to be booting properly, you may want to increase the timeout ("config.vm.boot_timeout") value.
```

I even tried adding the following to the Vagrantfile
config.vm.boot_timeout = 600
And also "cable connected" checkbox is selected in Network settings.

But still getting the same timeout error. Please suggest.

**Comment by cheeseplus** [comment]
Upgrade your vagrant - 2.0.0 is out now.

**Comment by contactavishek** [comment]
![vm_installed](https://user-images.githubusercontent.com/29422191/30509981-95042994-9ad9-11e7-92ba-4a9860bb9bf2.jpg)

It finally worked, Virtual machine got installed successfully. But after rebooting system and trying to start it with vagrant up, its giving the same messeage:

"Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value. "

It should not show this after the VM is properly installed right??

![vagrant_timeout](https://user-images.githubusercontent.com/29422191/30509984-a0b75590-9ad9-11e7-96e6-5a256e2ec0b6.jpg)

**Comment by cheeseplus** [comment]
That condition is usually a combination of factors involving Vagrant, VirtualBox, and bento box version. From that image it looks like it had problems even acquiring the box. I'd also recommend upgrading VirtualBox to  5.1.28 as it's a hotfix release. Some folks have reported problems with Vagrant 2.0 and have found 1.9.8 a better experience but that seems to be on specific platforms only.
