### ISSUE TITLE
Support LXC builder

### ISSUE THREAD

**Issue by mjanser** [chef/bento#907]
Since [version 1.1.0](https://github.com/hashicorp/packer/blob/master/CHANGELOG.md#110-september-12-2017) of packer it supports LXC and LXD builders. Do you plan to add them to your templates as well?

**Comment by rmoriz** [comment]
The goal of `Bento` is to provide VMWare, VirtualBox and Parallels images for use with vagrant and test-kitchen. LXC is not officially supported by vagrant and there are other tools to combine `test-kitchen` with cgroup-containers, e.g. https://github.com/test-kitchen/kitchen-docker

**Comment by cheeseplus** [comment]
@rmoriz hits the nail on the head there - we may offer libvirt and Hyper-V images in the future but the abstraction is specifically targeted at providers offered via Vagrant.

**Comment by cheeseplus** [comment]
Closing this one out as we're not likely do do this since there is not much value/utility in doing so at present.
