### ISSUE TITLE
Vagrant bento centos 7.3 have issue in windows platform

### ISSUE THREAD

**Issue by dvenrao** [chef/bento#908]
vagrant bento 7.3 latest version have issue when running in windows platform. It is not mounting any folder with c.vm.synced_folder.  Other bento images don't have this issue in windows platform.

Vagrant was unable to mount VirtualBox shared folders. This is usually
       because the filesystem "vboxsf" is not available. This filesystem is
       made available via the VirtualBox Guest Additions and kernel module.
       Please verify that these guest additions are properly installed in the
       guest. This is not a bug in Vagrant and is usually caused by a faulty
       Vagrant box. For context, the command attempted was:

       mount -t vboxsf -o uid=1000,gid=1000 tmp_omnibus_cache /tmp/omnibus/cache

       The error output from the command was:

       /sbin/mount.vboxsf: mounting failed with the error: No such device

Vagrant file:
Vagrant.configure("2") do |c|
  c.vm.box = "bento/centos-7.3"
  c.vm.hostname = "default-centos-73.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", create: true
  c.vm.synced_folder "C:/Users/venkatesh/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
  end
end

**Comment by cheeseplus** [comment]
What version of bento/centos-73 box is this?

**Comment by cheeseplus** [comment]
Closing for non-response. Hopefully this was fixed by version upgrades but feel free to open a new issue with current versions if not.
