### ISSUE TITLE
opscode_centos-7.4_chef-provisionerless box not found

### ISSUE THREAD

**Issue by dev31000** [chef/bento#929]
I'm trying to run the kitchen tests using centos 7.4 but seems there is no box available for 7.4
Insisting on centos 7.4 because this release fixes few issues while migrating from centos 6.8.

Can we know when shall we expect the centos 7.4 chef provisionerless box?

Error Log:

```
 Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Box 'opscode-centos-7.4' could not be found. Attempting to find and install...
           default: Box Provider: virtualbox
           default: Box Version: >= 0
       ==> default: Box file was not detected as metadata. Adding it directly...
       ==> default: Adding box 'opscode-centos-7.4' (v0) for provider: virtualbox
           default: Downloading: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.4_chef-provisionerless.box
An error occurred while downloading the remote file. The error
       message, if any, is reproduced below. Please fix this error and try
       again.
       
       The requested URL returned error: 404 Not Found
```

**Comment by cheeseplus** [comment]
We deprecated the S3 builds a very long time ago and you shouldn't be looking for boxes there. Everything has been moved to Vagrant Cloud which gives us versions. See https://app.vagrantup.com/bento/boxes/centos-7.4 and use the Readme to update your configs accordingly.
