### ISSUE TITLE
packer 1.1.1, centos 7, packer hangs after reboot

### ISSUE THREAD

**Issue by mmarseglia** [chef/bento#930]
Packer hangs after executing the update script.  The VM reboots but packer doesn't detect this and just waits.  There was a change to scripts that causes the ssh session to be disconnected, see thread https://github.com/hashicorp/packer/issues/4684

Changing the update script as @secbitchris suggested worked.

**Comment by cheeseplus** [comment]
We've updated our scripts accordingly so this shouldn't be an issue.
