### ISSUE TITLE
VMware Failed to fetch kickstarter dracut-initqueue timeout

### ISSUE THREAD

**Issue by staticfrost** [chef/bento#933]
Hi,

I'm getting the following error whilst trying to build centos 7.4 vmware-iso.

![image](https://user-images.githubusercontent.com/1342176/32420416-ac330fa8-c2d5-11e7-842c-fe8f5cff9ec1.png)

![image](https://user-images.githubusercontent.com/1342176/32420428-cca388ee-c2d5-11e7-9a25-430e2faf976c.png)

**Comment by staticfrost** [comment]
![image](https://user-images.githubusercontent.com/1342176/32420451-33393efa-c2d6-11e7-9a7e-c8d74fc528b1.png)

**Comment by rickard-von-essen** [comment]
Firewall?

**Comment by staticfrost** [comment]
yup firewall issue.
