### ISSUE TITLE
16.04 apt package lock still possible

### ISSUE THREAD

**Issue by aeimer** [chef/bento#942]
It would be good to disable [`unattended-upgrades`](https://wiki.debian.org/UnattendedUpgrades). This can cause apt-locks directly after startup. This way a `ansible-local`-provisioner errors, if I wait a few minutes the ansible-provisioner won't fail.

I would suggest to disable the `unattended-upgrades`-service and add the file `/etc/apt/apt.conf.d/90-disable-automatic-update` with the content:
```
APT::Periodic::Update-Package-Lists "0";
APT::Periodic::Download-Upgradeable-Packages "0";
APT::Periodic::Unattended-Upgrade "0";
APT::Periodic::AutocleanInterval "0";
```

Alternatively you could change these values in the several files in `/etc/apt/apt.conf.d/`.

This Issue specially applies to Ubuntu-16.04, but it may be a good idea for all the linux machines.

**Comment by aeimer** [comment]
Apparently you are disabling it!
https://github.com/chef/bento/blob/master/ubuntu/scripts/update.sh#L22

But this setting does not seems to work...

**Comment by tersmitten** [comment]
Indeed, with have issues with that too

**Comment by aeimer** [comment]
In addition you simply could uninstall the `unattended-uprades` package...

**Comment by cheeseplus** [comment]
It's possible it was a setting cargo culted from past ubuntu that is no longer applicable. Would be good to get some more details of how this looks and what we might be able to do to force a repro.

**Comment by aeimer** [comment]
We use the `bento/ubuntu-16.04` box as base-box to build our own base-box. (Currently version 2.3.7, 2.3.8 didn't work for us)
This base-box installs apache, php, nodejs, ... with the `ansible_local`-provisioner of vagrant.
After that we pack the vm and then it's "our base-box".

After disabling the `unattended-upgrades`-service the build-time decreased from ~ 45 to ~ 37 minutes.
This means to me, the service was working in the background and as a conlusion added apt-locks.

My idea was that the `/var/lib/dpkg/lock`-file is the problem, because it got set by unattended-upgrades?!, it then upgrades software.
While this happens we deaactivate and remove the service, so the lock stays there and blocks the provisioner apt calls.

If you run `vagrant up --no-provision` with the `Vagrantfile` down there, then `vagrant ssh` and there call ` sudo service unattended-upgrades status` I get:
```bash
vagrant@vagrant:~$ sudo service unattended-upgrades status
● unattended-upgrades.service - Unattended Upgrades Shutdown
   Loaded: loaded (/lib/systemd/system/unattended-upgrades.service; enabled; vendor preset: enabled)
   Active: active (exited) since Thu 2017-11-30 23:33:23 UTC; 37s ago
     Docs: man:unattended-upgrade(8)
    Tasks: 0
   Memory: 0B
      CPU: 0

Nov 30 23:33:23 vagrant systemd[1]: Started Unattended Upgrades Shutdown.
```

-----

The following command can NOT reproduce the problem, but it these calls fail with our base-box:
```bash
# Copy the files down there to an empty folder
vagrant up --provision-with=apt
# Now I get an error that says it couldn't install with apt
vagrant package -out base-box.box
# The package normally gets called if everything is installed correctly
```

`Vagrantfile`
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder ".", "/vagrant"

  if Vagrant.has_plugin? 'vagrant-vbguest'
    config.vbguest.auto_update = false
  end

  config.vm.provision "apt", type: "ansible_local" do |ansible|
    ansible.playbook = "apt.yaml"
  end
end
```

`apt.yaml`
```yaml
---
- hosts: all
  remote_user: vagrant
  become: true

  tasks:
  - name: simple apt install
    apt:
      name: "{{ item }}"
      state: installed
      update_cache: yes
    with_items:
      - tree
      - git
      - watch
```

**Comment by cheeseplus** [comment]
So are we sure that it's actually `unattended-upgrades` causing the lock issue? I ask because we've followed all the documented steps and if that is the case then `/var/log/unattended-upgrades` should have details confirming this as the cause. It could be us calling apt here on boot or something else in cron we're not accounting for yet.

https://github.com/chef/bento/blob/master/ubuntu/scripts/update.sh#L18

I'll see if I can repro this myself on a fresh build.
