### ISSUE TITLE
Support for macOS High Sierra ? 

### ISSUE THREAD

**Issue by Shashikant86** [chef/bento#945]
Just wondering if you have plans to add support to macOS High Sierra. ?

**Comment by Artistan** [comment]
maybe try this...
https://github.com/Artistan/homestead-builder
I have not upgraded my box to try it. to busy...

**Comment by rmoriz** [comment]
From what I know: The macos packer scripts used by bento are based on https://github.com/timsutton/osx-vm-templates - sadly a macOS 10.12.x change a couple of months ago rendered the existing solution unusable (https://github.com/timsutton/osx-vm-templates/issues/81) this also affects 10.13 (https://github.com/timsutton/osx-vm-templates/issues/87) - good news is that a workaround was just merged https://github.com/timsutton/osx-vm-templates/pull/82 but there are still issues with HighSierra (https://github.com/timsutton/osx-vm-templates/issues/87)

**Comment by cheeseplus** [comment]
We will support in so far as we'll add a template but can't host the boxes for the same reasons as always.

**Comment by atikhono** [comment]
Hi, you should be able to build a High Sierra image. Do not use iso builders.
Apple have put sleepimage under SIP in either 10.13.1 or 10.13.2, so running macos/scripts/update.sh provisioner will fail packer build. Disable it. I built an image for Parallels Desktop with no trouble: https://github.com/timsutton/osx-vm-templates/pull/95

**Comment by cheeseplus** [comment]
We generally try to support building from scratch and I've yet to find any set of packer templates that do this well for 10.13. For my own purposes I did a manual install with VMware Fusion and then use the `vmware-vmx` builder to apply Vagrant customizations.

**Comment by tas50** [comment]
I'm going to close this out since we're no longer building macos images here. MacOS images are super tricky and the macinbox project does a great job of building around apple's latest security constraints.
