### ISSUE TITLE
Changelog / Releases / Tags not created for new Version-SCheme

### ISSUE THREAD

**Issue by aeimer** [chef/bento#946]
Changelog, Releases and Tags are not created since you're using the new versioning-scheme.

Could you add all these parts for the past and in future?

Best regards

**Comment by tisba** [comment]
It looks like `CHANGELOG.md` was also not updated (latest `201708.22.0`). https://app.vagrantup.com/bento/boxes/ubuntu-16.04 e.g. states `v201710.25.0` as the current version.
