### ISSUE TITLE
Larger disk_size value

### ISSUE THREAD

**Issue by joliver** [chef/bento#951]
Any chance the default value of the `disk_size` user parameter could be increased from `40960` to `65536`?

There's no negative consequence to having a larger value by default. VirtualBox and other hypervisors (VMWare, Parallels, etc.) don't allocate the full size on the host machine. But having a larger value does allow the specific virtual machine to increase in size up to the max size:

Here's the specific box we're hoping to increase:
https://github.com/chef/bento/blob/master/ubuntu/ubuntu-16.04-amd64.json

**Comment by cheeseplus** [comment]
We can probably increase this we just felt 40GB was enough for general purposes but if it's not then we can  bump it higher.

**Comment by joliver** [comment]
@cheeseplus 64 GB would be great. I have a few Vagrants that work with large amounts of data.

**Comment by richard-scott** [comment]
Why not just increase it to your needs once downloaded? Saves everyone else having to download an oversized disk that takes longer?

**Comment by joliver** [comment]
@richard-scott It actually doesn't increase the download or host machine size at all. For example, I can allocate a 1 TB disk attached to a VM and it will *grow* as it is used up to a capacity of 1 TB (or whatever configured value). The creation of a large disk doesn't actually use any extra space. It just makes it capable of growing to that size.

**Comment by cheeseplus** [comment]
I'll go ahead and bump this for some testing, I don't expect any anomalies but just want to be safe.

**Comment by cheeseplus** [comment]
Closed by #959
