### ISSUE TITLE
Centos 7 builds using hyperv builder require cifs-utils package for cifs mounts

### ISSUE THREAD

**Issue by BruceRobertson** [chef/bento#953]
Using the centos-7.4 packer file with the hyperv builder results in a box that can't mount SMB synced folders using the default Vagrant options for SMB mounts. During the vagrant up I get the "wrong fs type" error noted at the bottom of [this page](https://www.vagrantup.com/docs/synced-folders/smb.html) in the Vagrant docs.

The solution is to install the cifs-utils package which then allows Centos to correctly use the secure credential file that Vagrant 1.8 and later requires for SMB mounts. It'd be great to get cifs-utils installed by default for those of us using hyperv. Rather than make the box bigger for everyone can I suggest that cifs-utils is just added to the existing hyperv conditional section that's in the %post section of the Centos 7 kickstart file?

**ks.cfg before**
```bash
%post
#Enable hyper-v daemons only if using hyper-v virtualization

if [ $(virt-what) == "hyperv" ]; then
    yum -y install hyperv-daemons
    systemctl enable hypervvssd
    systemctl enable hypervkvpd
fi
```

**ks.cfg after**
```bash
%post
#Enable hyper-v daemons and install cifs-utils only if using hyper-v virtualization
if [ $(virt-what) == "hyperv" ]; then
    yum -y install hyperv-daemons cifs-utils
    systemctl enable hypervvssd
    systemctl enable hypervkvpd
fi
```

Environment
Packer v1.1.3
Vagrant v2.0.1
Windows 10 build 1709

**Comment by cheeseplus** [comment]
Closed by #960
