### ISSUE TITLE
Debian 9.3 and 8.10 point release is not published yet

### ISSUE THREAD

**Issue by kenhys** [chef/bento#956]
## Problem

Debian 9.3 and 8.10 point release boxes are not published yet.

## Actual

Debian 9.3 and 8.10 point release is supported by https://github.com/chef/bento/pull/947 https://github.com/chef/bento/pull/948.
They are already merged, but not published yet.

## Expected

Vagrant boxes are available via https://app.vagrantup.com/bento on Vagrant Could.

**Comment by kenhys** [comment]
any progress about this issue?

**Comment by TomyLobo** [comment]
Thanks @kenhys for updating these.
I downloaded the boxes manually by modifying the 9.2 links and so far they seem to be working as expected.
Having them downloadable via bento/debian-9.3 would be nice, so I'm looking forward to seeing these released :)

**Comment by cheeseplus** [comment]
https://app.vagrantup.com/bento/boxes/debian-9.3/versions/201801.02.0
https://app.vagrantup.com/bento/boxes/debian-8.10/versions/201801.02.0
