### ISSUE TITLE
Any plans to adopt Amazon Linux 2?

### ISSUE THREAD

**Issue by skyzyx** [chef/bento#963]
More info: https://aws.amazon.com/amazon-linux-2/

**Comment by cheeseplus** [comment]
Why would we when they are making images available directly?

**Comment by skyzyx** [comment]
Mostly to Vagrant-ize them. But if not, that’s fine. I can do it myself. Just wanted to know the plan before I started writing code. :)

**Comment by cheeseplus** [comment]
Word is that they will be Vagrantizing them, I don't have concrete confirmation but this seems to be something AWS is aware of.

**Comment by et304383** [comment]
I was about to create an issue to ask about this.  @skyzyx can you detail what has to be done against the images available at https://cdn.amazonlinux.com/os-images/2017.12.0.20171212.2/ to use them in Vagrant?

More specifically, I'd like to run Chef kitchen tests so a full guide on how to use one of these images in Kitchen would be awesome.
