### ISSUE TITLE
Can't download bento/ubuntu-16.04 version 201801.02.0

### ISSUE THREAD

**Issue by arturmartins** [chef/bento#970]
This version is published online: https://app.vagrantup.com/bento/boxes/ubuntu-16.04/versions/201801.02.0

Unfortunately, that version is not published to the list
https://app.vagrantup.com/bento, therefore `vagrant up` pulls the version `v201710.25.0`:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bento/ubuntu-16.04' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'bento/ubuntu-16.04'
    default: URL: https://vagrantcloud.com/bento/ubuntu-16.04
==> default: Adding box 'bento/ubuntu-16.04' (v201710.25.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/bento/boxes/ubuntu-16.04/versions/201710.25.0/providers/virtualbox.box
```

Proofs:
`vagrant box add -cf  --box-version 20180102 --provider virtualbox bento/ubuntu-16.04`

```==> box: Loading metadata for box 'bento/ubuntu-16.04'
    box: URL: https://vagrantcloud.com/bento/ubuntu-16.04
The box you're attempting to add has no available version that
matches the constraints you requested. Please double-check your
settings. Also verify that if you specified version constraints,
that the provider you wish to use is available for these constraints.

Box: bento/ubuntu-16.04
Address: https://vagrantcloud.com/bento/ubuntu-16.04
Constraints: 20180102
Available versions: 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.3.0, 2.3.1, 2.3.4, 2.3.5, 2.3.7, 2.3.8, 201708.22.0, 201710.25.0
```

Currently, the version `v201710.25.0` does not allow shared folders to work with VirtualBox 5.2.4-119785. 

Workaround:
Download file:
```
wget https://app.vagrantup.com/bento/boxes/ubuntu-16.04/versions/201801.02.0/providers/virtualbox.box
```

Add box:
```
vagrant box add virtualbox.box --name bento/ubuntu-16.04
```

**Comment by jarshwah** [comment]
Wondering if this version has updated kernel patches with mitigations for meltdown et al?

**Comment by cheeseplus** [comment]
Uploaded != published or what the Vagrant Cloud API calls "Released". While working on a release we do this because as soon as you flip the switch it does so for all providers of the box so I hold the "release" until it's actually complete which will be after I finish writing the notes.

@jarshwah these include the latest updates as per the time they were built so this really depends on when each OS released patches. I don't have the time to run down each OS's set of patches itself on top of getting the release out so would appreciate spot checks - I imagine I'll need to cut another release fairly shortly.

**Comment by cheeseplus** [comment]
I'm closing this as a non-issue, the box will be available when it is released.

**Comment by arturmartins** [comment]
@cheeseplus: Thanks for the info. If there is anything I can help with the release process (testing, etc), I would be glad to help.

**Comment by George1wanis** [comment]
where should i write "wget https://app.vagrantup.com/bento/boxes/ubuntu-16.04/versions/201801.02.0/providers/virtualbox.box" ?
