### ISSUE TITLE
Issues mounting synced_folders - VirtualBox 5.2.4

### ISSUE THREAD

**Issue by joshphp** [chef/bento#974]
I have had lots of issues with bento images mounting synced folders via vagrant (by way of test-kitchen) with Virtualbox 5.2.4 on OSX 10.13.2.

Has anyone else seen this? Lots of device not found and other related errors. I can supply more info if it helps, otherwise I may have some other issue going on but it has plagued me for a while. Keeping my virtualbox locked at 5.1.2(x) (running 5.1.28 now) seems to be okay.

**Comment by cheeseplus** [comment]
You're going to need to be a lot more specific but what I expect happening is that you're using newer VirtualBox with _older_ images. Vagrant and be extension kitchen-vagrant don't auto-update images so the most recent release which was built against 5.2.4 is probably not being used.

**Comment by joshphp** [comment]
For example, bento/centos-7.3 running on
Vagrant 2.0.1
kitchen version: 1.19.2
Virtualbox 5.1.28

`
Installing additional modules ...
       vboxadd.sh: Starting the VirtualBox Guest Additions.

       Could not find the X.Org or XFree86 Window System, skipping.
       An error occurred during installation of VirtualBox Guest Additions 5.1.28. Some functionality may not work as intended.
       In most cases it is OK that the "Window System drivers" installation failed.
       Redirecting to /bin/systemctl start  vboxadd.service
       Redirecting to /bin/systemctl start  vboxadd-service.service
       Job for vboxadd-service.service failed because the control process exited with error code. See "systemctl status vboxadd-service.service" and "journalctl -xe" for details.
       Unmounting Virtualbox Guest Additions ISO from: /mnt
       ==> default: Checking for guest additions in VM...
       ==> default: Setting hostname...
       ==> default: Configuring and enabling network interfaces...
           default: SSH address: 127.0.0.1:2205
           default: SSH username: vagrant
           default: SSH auth method: private key
       ==> default: Mounting shared folders...
           default: /root/.aws => /Users/username/.aws
       Vagrant was unable to mount VirtualBox shared folders. This is usually
       because the filesystem "vboxsf" is not available. This filesystem is
       made available via the VirtualBox Guest Additions and kernel module.
       Please verify that these guest additions are properly installed in the
       guest. This is not a bug in Vagrant and is usually caused by a faulty
       Vagrant box. For context, the command attempted was:

       mount -t vboxsf -o uid=1000,gid=1000 root_.aws /root/.aws

       The error output from the command was:

       /sbin/mount.vboxsf: mounting failed with the error: No such device
`

**Comment by cheeseplus** [comment]
Things we need to continue troubleshooting this:

- Host OS information
- `.kitchen.yml`  
- `vagrant box list` (for the version of box being used)
- the complete output, to rule out something like vb-guest-updater

**Comment by joshphp** [comment]
`---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

platforms:
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: salsify-basics
    driver:
      synced_folders:
        - ["~/.aws", "/home/vagrant/.aws"]
        - ["~/.aws", "/root/.aws"]
      network:
        - ["private_network", {type: "dhcp"}]
    run_list:
        - recipe[salsify-basics-cookbook::duo+ldap.rb]
    attributes:`

`bento/centos-6           (virtualbox, 201710.25.0)
bento/centos-6.7         (virtualbox, 2.2.7)
bento/centos-6.9         (virtualbox, 201801.02.0)
bento/centos-7           (virtualbox, 201801.02.0)
bento/centos-7.2         (virtualbox, 2.3.1)
bento/centos-7.3         (virtualbox, 201708.22.0)
bento/ubuntu-14.04       (virtualbox, 2.3.8)
bento/ubuntu-16.04       (virtualbox, 201708.22.0)
bento/ubuntu-17.04       (virtualbox, 201710.25.0)
centos/7                 (virtualbox, 1708.01)
debian/jessie64          (virtualbox, 8.10.0)
debian/wheezy64          (virtualbox, 7.11.2)
generic/centos6          (virtualbox, 1.3.30)
generic/rhel7            (virtualbox, 1.3.30)
iamseth/rhel-7.3         (virtualbox, 1.0.0)
realreadme/amazon2016.09 (virtualbox, 1.0.0)
ubuntu/xenial64          (virtualbox, 20171221.0.0)`

`-----> Starting Kitchen (v1.19.2)
-----> Creating <salsify-basics-centos-72>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'bento/centos-7.2'...
==> default: Matching MAC address for NAT networking...
       ==> default: Checking if box 'bento/centos-7.2' is up to date...
       ==> default: Setting the name of the VM: salsify-basics-centos-72_default_1515688766937_38561
       ==> default: Fixed port collision for 22 => 2222. Now on port 2201.
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
           default: Adapter 2: hostonly
       ==> default: Forwarding ports...
           default: 22 (guest) => 2201 (host) (adapter 1)
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 127.0.0.1:2201
           default: SSH username: vagrant
           default: SSH auth method: private key
           default: Warning: Connection reset. Retrying...
           default: Warning: Remote connection disconnect. Retrying...
           default: Warning: Connection reset. Retrying...
           default: Warning: Remote connection disconnect. Retrying...
           default: Warning: Connection reset. Retrying...
           default:
           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.
           default:
           default: Inserting generated public key within guest...
           default: Removing insecure key from the guest if it's present...
           default: Key inserted! Disconnecting and reconnecting using new SSH key...
       ==> default: Machine booted and ready!
       [default] GuestAdditions versions on your host (5.1.28) and guest (5.1.10) do not match.
       Loaded plugins: fastestmirror
       Determining fastest mirrors
        * base: mirror.cc.columbia.edu
        * extras: centos.aol.com
        * updates: mirrors.centos.webair.com
       No package kernel-devel-3.10.0-327.el7.x86_64 available.
       Package bzip2-1.0.6-13.el7.x86_64 already installed and latest version
       Resolving Dependencies
       --> Running transaction check
       ---> Package binutils.x86_64 0:2.23.52.0.1-55.el7 will be updated
       ---> Package binutils.x86_64 0:2.25.1-32.base.el7_4.1 will be an update
       ---> Package gcc.x86_64 0:4.8.5-16.el7_4.1 will be installed
       --> Processing Dependency: libgomp = 4.8.5-16.el7_4.1 for package: gcc-4.8.5-16.el7_4.1.x86_64
       --> Processing Dependency: cpp = 4.8.5-16.el7_4.1 for package: gcc-4.8.5-16.el7_4.1.x86_64
       --> Processing Dependency: libgcc >= 4.8.5-16.el7_4.1 for package: gcc-4.8.5-16.el7_4.1.x86_64
       --> Processing Dependency: glibc-devel >= 2.2.90-12 for package: gcc-4.8.5-16.el7_4.1.x86_64
       ---> Package make.x86_64 1:3.82-21.el7 will be updated
       ---> Package make.x86_64 1:3.82-23.el7 will be an update
       ---> Package perl.x86_64 4:5.16.3-286.el7 will be updated
       ---> Package perl.x86_64 4:5.16.3-292.el7 will be an update
       --> Processing Dependency: perl-libs = 4:5.16.3-292.el7 for package: 4:perl-5.16.3-292.el7.x86_64
       --> Running transaction check
       ---> Package cpp.x86_64 0:4.8.5-16.el7_4.1 will be installed
       ---> Package glibc-devel.x86_64 0:2.17-196.el7_4.2 will be installed
       --> Processing Dependency: glibc-headers = 2.17-196.el7_4.2 for package: glibc-devel-2.17-196.el7_4.2.x86_64
       --> Processing Dependency: glibc = 2.17-196.el7_4.2 for package: glibc-devel-2.17-196.el7_4.2.x86_64
       --> Processing Dependency: glibc-headers for package: glibc-devel-2.17-196.el7_4.2.x86_64
       ---> Package libgcc.x86_64 0:4.8.5-4.el7 will be updated
       ---> Package libgcc.x86_64 0:4.8.5-16.el7_4.1 will be an update
       ---> Package libgomp.x86_64 0:4.8.5-4.el7 will be updated
       ---> Package libgomp.x86_64 0:4.8.5-16.el7_4.1 will be an update
       ---> Package perl-libs.x86_64 4:5.16.3-286.el7 will be updated
       ---> Package perl-libs.x86_64 4:5.16.3-292.el7 will be an update
       --> Running transaction check
       ---> Package glibc.x86_64 0:2.17-105.el7 will be updated
       --> Processing Dependency: glibc = 2.17-105.el7 for package: glibc-common-2.17-105.el7.x86_64
       ---> Package glibc.x86_64 0:2.17-196.el7_4.2 will be an update
       ---> Package glibc-headers.x86_64 0:2.17-196.el7_4.2 will be installed
       --> Processing Dependency: kernel-headers >= 2.2.1 for package: glibc-headers-2.17-196.el7_4.2.x86_64
       --> Processing Dependency: kernel-headers for package: glibc-headers-2.17-196.el7_4.2.x86_64
       --> Running transaction check
       ---> Package glibc-common.x86_64 0:2.17-105.el7 will be updated
       ---> Package glibc-common.x86_64 0:2.17-196.el7_4.2 will be an update
       ---> Package kernel-headers.x86_64 0:3.10.0-693.11.6.el7 will be installed
       --> Finished Dependency Resolution

       Dependencies Resolved

       ================================================================================
        Package             Arch        Version                     Repository    Size
       ================================================================================
       Installing:
        gcc                 x86_64      4.8.5-16.el7_4.1            updates       16 M
       Updating:
        binutils            x86_64      2.25.1-32.base.el7_4.1      updates      5.4 M
        make                x86_64      1:3.82-23.el7               base         420 k
        perl                x86_64      4:5.16.3-292.el7            base         8.0 M
       Installing for dependencies:
        cpp                 x86_64      4.8.5-16.el7_4.1            updates      5.9 M
        glibc-devel         x86_64      2.17-196.el7_4.2            updates      1.1 M
        glibc-headers       x86_64      2.17-196.el7_4.2            updates      676 k
        kernel-headers      x86_64      3.10.0-693.11.6.el7         updates      6.0 M
       Updating for dependencies:
        glibc               x86_64      2.17-196.el7_4.2            updates      3.6 M
        glibc-common        x86_64      2.17-196.el7_4.2            updates       11 M
        libgcc              x86_64      4.8.5-16.el7_4.1            updates       98 k
        libgomp             x86_64      4.8.5-16.el7_4.1            updates      154 k
        perl-libs           x86_64      4:5.16.3-292.el7            base         688 k

       Transaction Summary
       ================================================================================
       Install  1 Package  (+4 Dependent packages)
       Upgrade  3 Packages (+5 Dependent packages)

       Total download size: 60 M
       Downloading packages:
       Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
       Public key for glibc-2.17-196.el7_4.2.x86_64.rpm is not installed
       warning: /var/cache/yum/x86_64/7/updates/packages/glibc-2.17-196.el7_4.2.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
       Public key for make-3.82-23.el7.x86_64.rpm is not installed
       --------------------------------------------------------------------------------
       Total                                              4.7 MB/s |  60 MB  00:12
       Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
       Importing GPG key 0xF4A80EB5:
        Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
        Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
        Package    : centos-release-7-2.1511.el7.centos.2.10.x86_64 (@anaconda)
        From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
       Running transaction check
       Running transaction test
       Transaction test succeeded
       Running transaction
       Warning: RPMDB altered outside of yum.
         Updating   : libgcc-4.8.5-16.el7_4.1.x86_64                              1/21
         Updating   : glibc-2.17-196.el7_4.2.x86_64                               2/21
       warning: /etc/nsswitch.conf created as /etc/nsswitch.conf.rpmnew
         Updating   : glibc-common-2.17-196.el7_4.2.x86_64                        3/21
         Installing : cpp-4.8.5-16.el7_4.1.x86_64                                 4/21
         Updating   : 4:perl-libs-5.16.3-292.el7.x86_64                           5/21
         Updating   : 4:perl-5.16.3-292.el7.x86_64                                6/21
         Updating   : libgomp-4.8.5-16.el7_4.1.x86_64                             7/21
         Updating   : binutils-2.25.1-32.base.el7_4.1.x86_64                      8/21
         Installing : kernel-headers-3.10.0-693.11.6.el7.x86_64                   9/21
         Installing : glibc-headers-2.17-196.el7_4.2.x86_64                      10/21
         Installing : glibc-devel-2.17-196.el7_4.2.x86_64                        11/21
         Installing : gcc-4.8.5-16.el7_4.1.x86_64                                12/21
         Updating   : 1:make-3.82-23.el7.x86_64                                  13/21
         Cleanup    : 4:perl-libs-5.16.3-286.el7.x86_64                          14/21
         Cleanup    : 4:perl-5.16.3-286.el7.x86_64                               15/21
         Cleanup    : binutils-2.23.52.0.1-55.el7.x86_64                         16/21
         Cleanup    : 1:make-3.82-21.el7.x86_64                                  17/21
         Cleanup    : libgomp-4.8.5-4.el7.x86_64                                 18/21
         Cleanup    : glibc-2.17-105.el7.x86_64                                  19/21
         Cleanup    : glibc-common-2.17-105.el7.x86_64                           20/21
         Cleanup    : libgcc-4.8.5-4.el7.x86_64                                  21/21
         Verifying  : cpp-4.8.5-16.el7_4.1.x86_64                                 1/21
         Verifying  : glibc-devel-2.17-196.el7_4.2.x86_64                         2/21
         Verifying  : glibc-common-2.17-196.el7_4.2.x86_64                        3/21
         Verifying  : 4:perl-5.16.3-292.el7.x86_64                                4/21
         Verifying  : libgcc-4.8.5-16.el7_4.1.x86_64                              5/21
         Verifying  : libgomp-4.8.5-16.el7_4.1.x86_64                             6/21
         Verifying  : 1:make-3.82-23.el7.x86_64                                   7/21
         Verifying  : glibc-2.17-196.el7_4.2.x86_64                               8/21
         Verifying  : 4:perl-libs-5.16.3-292.el7.x86_64                           9/21
         Verifying  : binutils-2.25.1-32.base.el7_4.1.x86_64                     10/21
         Verifying  : kernel-headers-3.10.0-693.11.6.el7.x86_64                  11/21
         Verifying  : glibc-headers-2.17-196.el7_4.2.x86_64                      12/21
         Verifying  : gcc-4.8.5-16.el7_4.1.x86_64                                13/21
         Verifying  : 4:perl-5.16.3-286.el7.x86_64                               14/21
         Verifying  : libgomp-4.8.5-4.el7.x86_64                                 15/21
         Verifying  : libgcc-4.8.5-4.el7.x86_64                                  16/21
         Verifying  : 1:make-3.82-21.el7.x86_64                                  17/21
         Verifying  : glibc-2.17-105.el7.x86_64                                  18/21
         Verifying  : binutils-2.23.52.0.1-55.el7.x86_64                         19/21
         Verifying  : 4:perl-libs-5.16.3-286.el7.x86_64                          20/21
         Verifying  : glibc-common-2.17-105.el7.x86_64                           21/21

       Installed:
         gcc.x86_64 0:4.8.5-16.el7_4.1

       Dependency Installed:
         cpp.x86_64 0:4.8.5-16.el7_4.1
         glibc-devel.x86_64 0:2.17-196.el7_4.2
         glibc-headers.x86_64 0:2.17-196.el7_4.2
         kernel-headers.x86_64 0:3.10.0-693.11.6.el7

       Updated:
         binutils.x86_64 0:2.25.1-32.base.el7_4.1       make.x86_64 1:3.82-23.el7
         perl.x86_64 4:5.16.3-292.el7

       Dependency Updated:
         glibc.x86_64 0:2.17-196.el7_4.2      glibc-common.x86_64 0:2.17-196.el7_4.2
         libgcc.x86_64 0:4.8.5-16.el7_4.1     libgomp.x86_64 0:4.8.5-16.el7_4.1
         perl-libs.x86_64 4:5.16.3-292.el7

       Complete!
       Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
       Mounting Virtualbox Guest Additions ISO to: /mnt
       mount: /dev/loop0 is write-protected, mounting read-only
       Installing Virtualbox Guest Additions 5.1.28 - guest version is 5.1.10
       Verifying archive integrity... All good.
       Uncompressing VirtualBox 5.1.28 Guest Additions for Linux...........
       VirtualBox Guest Additions installer
       Removing installed version 5.1.10 of VirtualBox Guest Additions...
       Copying additional installer modules ...
       Installing additional modules ...
       vboxadd.sh: Starting the VirtualBox Guest Additions.

       Could not find the X.Org or XFree86 Window System, skipping.
       An error occurred during installation of VirtualBox Guest Additions 5.1.28. Some functionality may not work as intended.
       In most cases it is OK that the "Window System drivers" installation failed.
       Redirecting to /bin/systemctl start  vboxadd.service
       Redirecting to /bin/systemctl start  vboxadd-service.service
       Job for vboxadd-service.service failed because the control process exited with error code. See "systemctl status vboxadd-service.service" and "journalctl -xe" for details.
       Unmounting Virtualbox Guest Additions ISO from: /mnt
       ==> default: Checking for guest additions in VM...
       ==> default: Setting hostname...
       ==> default: Configuring and enabling network interfaces...
           default: SSH address: 127.0.0.1:2201
           default: SSH username: vagrant
           default: SSH auth method: private key
       ==> default: Mounting shared folders...
           default: /root/.aws => /Users/joshuabranham/.aws
       Vagrant was unable to mount VirtualBox shared folders. This is usually
       because the filesystem "vboxsf" is not available. This filesystem is
       made available via the VirtualBox Guest Additions and kernel module.
       Please verify that these guest additions are properly installed in the
       guest. This is not a bug in Vagrant and is usually caused by a faulty
       Vagrant box. For context, the command attempted was:

       mount -t vboxsf -o uid=1000,gid=1000 root_.aws /root/.aws

       The error output from the command was:

       /sbin/mount.vboxsf: mounting failed with the error: No such device
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'bento/centos-7.2'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/centos-7.2' is up to date...
==> default: Setting the name of the VM: salsify-basics-centos-72_default_1515688766937_38561
==> default: Fixed port collision for 22 => 2222. Now on port 2201.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2201 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2201
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
[default] GuestAdditions versions on your host (5.1.28) and guest (5.1.10) do not match.
Loaded plugins: fastestmirror
Determining fastest mirrors
 * base: mirror.cc.columbia.edu
 * extras: centos.aol.com
 * updates: mirrors.centos.webair.com
No package kernel-devel-3.10.0-327.el7.x86_64 available.
Package bzip2-1.0.6-13.el7.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package binutils.x86_64 0:2.23.52.0.1-55.el7 will be updated
---> Package binutils.x86_64 0:2.25.1-32.base.el7_4.1 will be an update
---> Package gcc.x86_64 0:4.8.5-16.el7_4.1 will be installed
--> Processing Dependency: libgomp = 4.8.5-16.el7_4.1 for package: gcc-4.8.5-16.el7_4.1.x86_64
--> Processing Dependency: cpp = 4.8.5-16.el7_4.1 for package: gcc-4.8.5-16.el7_4.1.x86_64
--> Processing Dependency: libgcc >= 4.8.5-16.el7_4.1 for package: gcc-4.8.5-16.el7_4.1.x86_64
--> Processing Dependency: glibc-devel >= 2.2.90-12 for package: gcc-4.8.5-16.el7_4.1.x86_64
---> Package make.x86_64 1:3.82-21.el7 will be updated
---> Package make.x86_64 1:3.82-23.el7 will be an update
---> Package perl.x86_64 4:5.16.3-286.el7 will be updated
---> Package perl.x86_64 4:5.16.3-292.el7 will be an update
--> Processing Dependency: perl-libs = 4:5.16.3-292.el7 for package: 4:perl-5.16.3-292.el7.x86_64
--> Running transaction check
---> Package cpp.x86_64 0:4.8.5-16.el7_4.1 will be installed
---> Package glibc-devel.x86_64 0:2.17-196.el7_4.2 will be installed
--> Processing Dependency: glibc-headers = 2.17-196.el7_4.2 for package: glibc-devel-2.17-196.el7_4.2.x86_64
--> Processing Dependency: glibc = 2.17-196.el7_4.2 for package: glibc-devel-2.17-196.el7_4.2.x86_64
--> Processing Dependency: glibc-headers for package: glibc-devel-2.17-196.el7_4.2.x86_64
---> Package libgcc.x86_64 0:4.8.5-4.el7 will be updated
---> Package libgcc.x86_64 0:4.8.5-16.el7_4.1 will be an update
---> Package libgomp.x86_64 0:4.8.5-4.el7 will be updated
---> Package libgomp.x86_64 0:4.8.5-16.el7_4.1 will be an update
---> Package perl-libs.x86_64 4:5.16.3-286.el7 will be updated
---> Package perl-libs.x86_64 4:5.16.3-292.el7 will be an update
--> Running transaction check
---> Package glibc.x86_64 0:2.17-105.el7 will be updated
--> Processing Dependency: glibc = 2.17-105.el7 for package: glibc-common-2.17-105.el7.x86_64
---> Package glibc.x86_64 0:2.17-196.el7_4.2 will be an update
---> Package glibc-headers.x86_64 0:2.17-196.el7_4.2 will be installed
--> Processing Dependency: kernel-headers >= 2.2.1 for package: glibc-headers-2.17-196.el7_4.2.x86_64
--> Processing Dependency: kernel-headers for package: glibc-headers-2.17-196.el7_4.2.x86_64
--> Running transaction check
---> Package glibc-common.x86_64 0:2.17-105.el7 will be updated
---> Package glibc-common.x86_64 0:2.17-196.el7_4.2 will be an update
---> Package kernel-headers.x86_64 0:3.10.0-693.11.6.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package             Arch        Version                     Repository    Size
================================================================================
Installing:
 gcc                 x86_64      4.8.5-16.el7_4.1            updates       16 M
Updating:
 binutils            x86_64      2.25.1-32.base.el7_4.1      updates      5.4 M
 make                x86_64      1:3.82-23.el7               base         420 k
 perl                x86_64      4:5.16.3-292.el7            base         8.0 M
Installing for dependencies:
 cpp                 x86_64      4.8.5-16.el7_4.1            updates      5.9 M
 glibc-devel         x86_64      2.17-196.el7_4.2            updates      1.1 M
 glibc-headers       x86_64      2.17-196.el7_4.2            updates      676 k
 kernel-headers      x86_64      3.10.0-693.11.6.el7         updates      6.0 M
Updating for dependencies:
 glibc               x86_64      2.17-196.el7_4.2            updates      3.6 M
 glibc-common        x86_64      2.17-196.el7_4.2            updates       11 M
 libgcc              x86_64      4.8.5-16.el7_4.1            updates       98 k
 libgomp             x86_64      4.8.5-16.el7_4.1            updates      154 k
 perl-libs           x86_64      4:5.16.3-292.el7            base         688 k

Transaction Summary
================================================================================
Install  1 Package  (+4 Dependent packages)
Upgrade  3 Packages (+5 Dependent packages)

Total download size: 60 M
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
Public key for glibc-2.17-196.el7_4.2.x86_64.rpm is not installed
warning: /var/cache/yum/x86_64/7/updates/packages/glibc-2.17-196.el7_4.2.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Public key for make-3.82-23.el7.x86_64.rpm is not installed
--------------------------------------------------------------------------------
Total                                              4.7 MB/s |  60 MB  00:12
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-2.1511.el7.centos.2.10.x86_64 (@anaconda)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Warning: RPMDB altered outside of yum.
  Updating   : libgcc-4.8.5-16.el7_4.1.x86_64                              1/21
  Updating   : glibc-2.17-196.el7_4.2.x86_64                               2/21
warning: /etc/nsswitch.conf created as /etc/nsswitch.conf.rpmnew
  Updating   : glibc-common-2.17-196.el7_4.2.x86_64                        3/21
  Installing : cpp-4.8.5-16.el7_4.1.x86_64                                 4/21
  Updating   : 4:perl-libs-5.16.3-292.el7.x86_64                           5/21
  Updating   : 4:perl-5.16.3-292.el7.x86_64                                6/21
  Updating   : libgomp-4.8.5-16.el7_4.1.x86_64                             7/21
  Updating   : binutils-2.25.1-32.base.el7_4.1.x86_64                      8/21
  Installing : kernel-headers-3.10.0-693.11.6.el7.x86_64                   9/21
  Installing : glibc-headers-2.17-196.el7_4.2.x86_64                      10/21
  Installing : glibc-devel-2.17-196.el7_4.2.x86_64                        11/21
  Installing : gcc-4.8.5-16.el7_4.1.x86_64                                12/21
  Updating   : 1:make-3.82-23.el7.x86_64                                  13/21
  Cleanup    : 4:perl-libs-5.16.3-286.el7.x86_64                          14/21
  Cleanup    : 4:perl-5.16.3-286.el7.x86_64                               15/21
  Cleanup    : binutils-2.23.52.0.1-55.el7.x86_64                         16/21
  Cleanup    : 1:make-3.82-21.el7.x86_64                                  17/21
  Cleanup    : libgomp-4.8.5-4.el7.x86_64                                 18/21
  Cleanup    : glibc-2.17-105.el7.x86_64                                  19/21
  Cleanup    : glibc-common-2.17-105.el7.x86_64                           20/21
  Cleanup    : libgcc-4.8.5-4.el7.x86_64                                  21/21
  Verifying  : cpp-4.8.5-16.el7_4.1.x86_64                                 1/21
  Verifying  : glibc-devel-2.17-196.el7_4.2.x86_64                         2/21
  Verifying  : glibc-common-2.17-196.el7_4.2.x86_64                        3/21
  Verifying  : 4:perl-5.16.3-292.el7.x86_64                                4/21
  Verifying  : libgcc-4.8.5-16.el7_4.1.x86_64                              5/21
  Verifying  : libgomp-4.8.5-16.el7_4.1.x86_64                             6/21
  Verifying  : 1:make-3.82-23.el7.x86_64                                   7/21
  Verifying  : glibc-2.17-196.el7_4.2.x86_64                               8/21
  Verifying  : 4:perl-libs-5.16.3-292.el7.x86_64                           9/21
  Verifying  : binutils-2.25.1-32.base.el7_4.1.x86_64                     10/21
  Verifying  : kernel-headers-3.10.0-693.11.6.el7.x86_64                  11/21
  Verifying  : glibc-headers-2.17-196.el7_4.2.x86_64                      12/21
  Verifying  : gcc-4.8.5-16.el7_4.1.x86_64                                13/21
  Verifying  : 4:perl-5.16.3-286.el7.x86_64                               14/21
  Verifying  : libgomp-4.8.5-4.el7.x86_64                                 15/21
  Verifying  : libgcc-4.8.5-4.el7.x86_64                                  16/21
  Verifying  : 1:make-3.82-21.el7.x86_64                                  17/21
  Verifying  : glibc-2.17-105.el7.x86_64                                  18/21
  Verifying  : binutils-2.23.52.0.1-55.el7.x86_64                         19/21
  Verifying  : 4:perl-libs-5.16.3-286.el7.x86_64                          20/21
  Verifying  : glibc-common-2.17-105.el7.x86_64                           21/21

Installed:
  gcc.x86_64 0:4.8.5-16.el7_4.1

Dependency Installed:
  cpp.x86_64 0:4.8.5-16.el7_4.1
  glibc-devel.x86_64 0:2.17-196.el7_4.2
  glibc-headers.x86_64 0:2.17-196.el7_4.2
  kernel-headers.x86_64 0:3.10.0-693.11.6.el7

Updated:
  binutils.x86_64 0:2.25.1-32.base.el7_4.1       make.x86_64 1:3.82-23.el7
  perl.x86_64 4:5.16.3-292.el7

Dependency Updated:
  glibc.x86_64 0:2.17-196.el7_4.2      glibc-common.x86_64 0:2.17-196.el7_4.2
  libgcc.x86_64 0:4.8.5-16.el7_4.1     libgomp.x86_64 0:4.8.5-16.el7_4.1
  perl-libs.x86_64 4:5.16.3-292.el7

Complete!
Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Mounting Virtualbox Guest Additions ISO to: /mnt
mount: /dev/loop0 is write-protected, mounting read-only
Installing Virtualbox Guest Additions 5.1.28 - guest version is 5.1.10
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.1.28 Guest Additions for Linux...........
VirtualBox Guest Additions installer
Removing installed version 5.1.10 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
vboxadd.sh: Starting the VirtualBox Guest Additions.

Could not find the X.Org or XFree86 Window System, skipping.
An error occurred during installation of VirtualBox Guest Additions 5.1.28. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
Redirecting to /bin/systemctl start  vboxadd.service
Redirecting to /bin/systemctl start  vboxadd-service.service
Job for vboxadd-service.service failed because the control process exited with error code. See "systemctl status vboxadd-service.service" and "journalctl -xe" for details.
Unmounting Virtualbox Guest Additions ISO from: /mnt
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
    default: SSH address: 127.0.0.1:2201
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Mounting shared folders...
    default: /root/.aws => /Users/joshuabranham/.aws
STDERR: Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 root_.aws /root/.aws

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1] on salsify-basics-centos-72
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration`

**Comment by cheeseplus** [comment]
Yep, so there are two things going on here:

1) You are using old images, at least for Centos 7.2 (we don't update 7.2 after 7.3 is out)
2) You are using `vagrant-vbguest` which is known to be extremely problematic and defeats the effort we put into shipping images that pair with that tooling

In short, this isn't an issue with the bento images, you need to not use this plugin or use it with different base images.

**Comment by joshphp** [comment]
Okay looks like removing the vagrant-vbguest plugin from my install and using the centos-7.3 image  resolved it.

Thanks so much for your help, really appreciate it.

**Comment by cheeseplus** [comment]
No problem, in the future we may look at having `kitchen-vagrant` disable the plugin entirely in the Vagrantfile - by default it enables if installed so this might be a good way to default it to off but if someone _really_ wants it we could give a switch to do so.
