### ISSUE TITLE
Installation of FreeBSD 11.1 fails with syntax error 'elif'

### ISSUE THREAD

**Issue by cdumke** [chef/bento#983]
The installation triggered with 
`packer build -only virtualbox-iso freebsd-11.1-amd64.json`
runs into the following error
`/tmp/bsdinstall-installscript-aa: 9: Syntax error: "elif" unexpected (expecting "then")`

My host is a Windows 10 Pro with git for windows 2.15.1 with Option `auto CrLf convert"=off`

Steps to reproduce:

1. `git clone` the bento project
2. open `cmd.exe`
3. change into `bento\freebsd`
4. call `packer build` (see above)
5. wait for the installation to boot and run into the error

**Comment by cdumke** [comment]
I was able to install freebsd 11 after I changed the line endings in the file `bento/freebsd/http/freebsd-11/installerconfig` from CRLF to LF (in notepad++).

**Comment by cdumke** [comment]
Currently I'm struggling with my git client to take over the LF line endings

**Comment by cheeseplus** [comment]
I'm not sure this really qualifies as an issue with bento itself, this about configuring git settings http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/

**Comment by cdumke** [comment]
Well, You got a freebsd shell-script file object in the git-database which does contain CRLF line endings.
I configured my git client to do not convert and so stumbled into this bug.
BTW: You already specify different line endings in .gitattributes for different sets of files.

**Comment by rickard-von-essen** [comment]
> Well, You got a freebsd shell-script file object in the git-database which does contain CRLF line endings.

No we don't, it's your computer.

**Comment by cdumke** [comment]
After some research I found this: [https://stackoverflow.com/questions/30978710/override-gitattributes-text-auto-in-windows](https://stackoverflow.com/questions/30978710/override-gitattributes-text-auto-in-windows)

 `* text=auto` in `.gitattributes` file together with `core.autocrlf = false` on Windows leads to CRLR in files not matched by other rules in  `.gitattributes` file.

The solution to this unwanted conversion cause by `* text=auto` on Windows is

1. Create a fresh clone
2. Put a file `attributes` into `.git\info` with the content `installerconfig eol=lf`
3. Delete the file `freebsd\http\freebsd-11\installerconfig` (but do not check in)
4. Reset the file using `git checkout -f master`
5. The file `installerconfig` has LF line endings now.

I think, we can close this issue now :-)

Thx for Your support.
