### ISSUE TITLE
freebsd try

### ISSUE THREAD

**Issue by oceanaut** [chef/bento#989]
Is there a way to locate ISO image on my computer? or any tutorial where I can learn to customize freebsd_xxx.json file? I d like to customize json file to install specific packages.
thnx

**Comment by cheeseplus** [comment]
I'm not entirely clear what you are asking - normally packer will download the ISO for you as specified in the template (json). If you want to add packages then you would look at forking the repo and modifying the scripts that the FreeBSD box uses:

https://github.com/chef/bento/blob/master/freebsd/freebsd-11.1-amd64.json#L195-L202

**Comment by oceanaut** [comment]
what I am asking about is some box that I can create and use locally.I dont want to download box via url.

**Comment by cheeseplus** [comment]
The instructions for using our templates to build your own boxes is here https://github.com/chef/bento#building-boxes

You would clone the repo, install packer (and appropriate hypervisor), make any changes to the templates you like, and build your own box.

**Comment by oceanaut** [comment]
I dont have problem with this. On your local when you type "vagrant box list" you list your local custom vagrant boxes,so instead of URL-based vagrant boxes I want to give the local ones.It is ok now.I just give box name it works.I do not want to download URL all the time, I try to build no-internet vagrant pository like environment

**Comment by cheeseplus** [comment]
Yes you can always add a box locally via `vagrant box add BOXFILE`, it's the same arguments whether it's local or remote. Either way, not really a bento issue and more a vagrant issue but glad you've figured it out.
