### ISSUE TITLE
Debian/Ubuntu require cifs-utils for SMB mounts

### ISSUE THREAD

**Issue by jtreminio** [chef/bento#990]
Looks like cifs-utils was added to CentOS in this PR: https://github.com/chef/bento/pull/960/files

The same is required in Ubuntu and Debian distros for SMB mounts.

It is not installed by default:

    root@ubuntu-14:/home/vagrant# ls /sbin/mount.*
    /sbin/mount.fuse  /sbin/mount.lowntfs-3g  /sbin/mount.nfs  /sbin/mount.nfs4  /sbin/mount.ntfs  /sbin/mount.ntfs-3g

**Comment by cheeseplus** [comment]
Does this need to be added for all hypervisors or _just_ HyperV? 

Looking at the linked issues it seems semi-specific to hyperV. We only add it to CentOS when we know it's HyperV and the templates don't currently support any debian hyper-v boxes so while I can add it _everywhere_ I want to make sure I understand if it's generally helpful to the other providers.

**Comment by cheeseplus** [comment]
#994 takes care of this one.
