### ISSUE TITLE
Public Bento boxes not found

### ISSUE THREAD

**Issue by a4ashadow** [chef/bento#992]
According to the read-me, public boxes can be easily downloaded using "vagrant box add bento/ubuntu-16.04" . A few days ago this has changed and all the public boxes returned "
URL: ["https://atlas.hashicorp.com/bento/centos-7.4"]
Error: The requested URL returned error: 404 Not Found
"
According to the announcement on https://atlas.hashicorp.com/bento , one is instructed to create own boxes.
Will public Bento Boxes be made available again and where?

Thanks for the help

**Comment by rickard-von-essen** [comment]
I think they have moved it, see https://www.hashicorp.com/blog/vagrant-cloud-migration-announcement

Maybe upgrading Vagrant will load them from the right place.

**Comment by cheeseplus** [comment]
This is definitely an old version of Vagrant, the boxes never stopped being available and can be found https://app.vagrantup.com/bento.

**Comment by mattlqx** [comment]
Just ran into this myself. If you have been using a box for a long time (before mid-2017), you will still have the old metadata_url stored in the box directory in ~/.vagrant.d. You'll have to remove all versions of the box and re-add it, like:

```
$ vagrant box remove bento/ubuntu-16.04  --all
$ vagrant box add bento/ubuntu-16.04
```

Or just change the content of `metadata_url` to the new location: `https://vagrantcloud.com/bento/ubuntu-16.04`, etc.
