### ISSUE TITLE
Centos 7 Firmwares

### ISSUE THREAD

**Issue by svpace** [chef/bento#998]
IFAICT none of the firmwares below is available on Centos 7. Perhaps they can be excluded (from exclusion) from the ks.cfg

atmel-firmware
b43-openfwwf
bfa-firmware
ipw2100-firmware
ipw2200-firmware
kernel-firmware
libertas-sd8686-firmware
libertas-sd8787-firmware
libertas-usb8388-firmware
ql2100-firmware
ql2200-firmware
ql23xx-firmware
ql2400-firmware
ql2500-firmware
rt61pci-firmware
rt73usb-firmware
xorg-x11-drv-ati-firmware
zd1211-firmware

Regards

**Comment by cheeseplus** [comment]
If they aren't available then we should definitely remove them from the list. Would you like to try for a PR yourself? If not we can definitely take care of it.

**Comment by svpace** [comment]
Sure thing
