### ISSUE TITLE
VirtualBox Guest Additions 5.2.7 in Linux host + 3D

### ISSUE THREAD

**Issue by ltalirz** [chef/bento#999]
VirtualBox Guest additions shipped with VirtualBox 5.2.6 currently [don't work properly on Linux guests with 3d enabled](https://www.virtualbox.org/wiki/Downloads). As stated on the downloads page, this problem can be solved by upgrading the guest additions to [5.2.7](https://www.virtualbox.org/download/testcase/VBoxGuestAdditions_5.2.7-120528.iso) 

This fix worked together with `bento/ubuntu-16.04 (virtualbox, 201801.02.0)`, but when I combine it with the more recent `bento/ubuntu-16.04 (virtualbox, 201802.02.0)` it stopped working for me -- for example opening the terminal app does not work anymore (it is "invisible")

I'm not at a level to point out what is going on here in detail, just wanted to post this in case someone else falls into the same trap. For me, reverting back to `201801.02.0` solved the problem.

**Comment by cheeseplus** [comment]
While this is good to note there isn't really enough detail to work out what exactly is happening and in general e're not at all caring or targetting 3D support for these boxes - these are all based off server operating systems and explicitly exclude any desktop environments.

**Comment by ltalirz** [comment]
yes, sorry for the lack of details, maybe this isn't the right place to post this.
fine to close.

**Comment by cheeseplus** [comment]
We'll be updating boxes to be built with the latest drivers - I try to do this monthly even without hypervisor updates but I did want to note that's not a use case we attempt to cover for these boxes at this time. You might be interested in checking out a related project, Boxcutter https://github.com/boxcutter/ubuntu which does provide specifically desktop templates/images.

**Comment by ltalirz** [comment]
thanks for the hint, very much appreciated!

**Comment by cheeseplus** [comment]
Going to close this one for now since 5.2.7 (or later) isn't officially released yet and given that desktop environments aren't in our scope there isn't much reason to change the templates at this time. I've renamed the issue to make it easy for future searchers to find and with it noted on the VirtualBox download site I think we're covered.
